### ISSUE TITLE
Lexos API

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#1030]
We've talked about streamlining the back end as an API (`LexosLib`), so we might as well make it an issue. Some advantages are:

- Easier development separating front end with back end
- Lexos methods can be called by other tools
- We could build in methods to call other tools like stylo in R, so that we only need to build the interface

I believe there would be considerable demand for an API in the DH community.

**Comment by mleblanc321** [comment]
well ... @Weiqi97 has interest in this ... (he plans to join us today in the 6/11/2020 zoom mtg)

**Comment by scottkleinman** [comment]
![It's Alive! Alive!](https://media.giphy.com/media/YEL7FJP6ed008/giphy.gif)
