### ISSUE TITLE
Issues With Manage Sorting

### ISSUE THREAD

**Issue by Myles-Trevino** [WheatonCS/Lexos#1033]
The manage sorting seems to have a few issues.

-The column in control of the sorting isn't indicated. It should be highlighted and the sort direction arrow should appear only on the active column rather than all columns.

-Making a change to active documents and then sorting visually resets the change.  

-The initial sorting change of some columns seem to change only the order of certain columns when other columns should be affected by the change.

**Comment by scottkleinman** [comment]
Well, I did say it was basic. I would suggest that any improvements be done in conjunction with the Tokenize table. Although I am happy not to have to deal with the complex DataTable API we were using in Lexos 3.2, making up for the lost functionality is a bit of a bummer.

**Comment by mleblanc321** [comment]
i too noticed myles' points .... but i really like what @scottkleinman has done on Manage ... and (at this time) don't think we also need to "fix" tokenizer;  (tokenizer has been a black hole more than once;  personally, i use tokenizer to download my results ... and really don't mind the table being funky ... i know not a good answer);

i hope we can tweek scott's additions
