### ISSUE TITLE
Having Trouble with MacOS Chrome for pdf Viewer in Hierarchical

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#108]
Sometimes the legends are very long so that some parts of the legends would be cut off. I think using this scrollable window for legends would be a better choice. How do you think about it?

![screenshot from 2014-06-04 17_14_55](https://cloud.githubusercontent.com/assets/4997873/3180147/d84a00d8-ec2d-11e3-96ad-6a675d0276b2.png)

**Comment by scottkleinman** [comment]
I have not heard any user complaints about this. Can we close this issue?

**Comment by mleblanc321** [comment]
austin:  let's not let this slide;  can you test this, on fireFox and chrome on windows, macOS, linux; does it work ok?  (we don't need pretty, but hopefully legends print when requested?)

**Comment by kreddy95** [comment]
is this still relevant??

**Comment by scottkleinman** [comment]
I think this discussion is not relevant to the current implementation. Closing.
