### ISSUE TITLE
Scrubber.py

### ISSUE THREAD

**Issue by bawjensen** [WheatonCS/Lexos#111]
In my process on commenting the different python files, I've been reminded of the fact that scrubber.py is really confusing, and could do with a re-write.

I'll take the blame for the current state of the file. I, however, don't think I'll have the time to rewrite it. I can be available to answer questions as to why things are as they are.

**Comment by chantisnake** [comment]
I am sorry. I don't know that you can only assign one person.

I think I can help on this.

**Comment by chantisnake** [comment]
Okay, now it becomes more confusing with my code!

I do think call replacement handler could use a rewrite. I will do this a free this year's release.
