### ISSUE TITLE
Overcrowded multiclouds

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#113]
In multicloud, the ideal scaling for a set of words in a cloud is a guesstimate. The default generally works, as in this set of topics from a 100-topic topic model of a Classical Chinese corpus.

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/1125917/3203377/443fbff8-ed9b-11e3-9ebb-a6f55975b5a6.png)

But when the model is changed to 500-topics the word counts don't work as well with the default scaling. There is considerable character overlap.

![pastedgraphic-3](https://cloud.githubusercontent.com/assets/1125917/3203381/4b1637da-ed9b-11e3-882d-530f202b796c.png)

My recommendation as of now is to open Lexos in a duplicate tab and examine individual clouds using WordCloud. But it would be nice to insert a form field into MultiCloud to accept user-submitted tuning of the scaling settings.

**Comment by scottkleinman** [comment]
We can't implement this right now, so I've added the In the Margins label to remind us to advise users of the recommended workaround.

**Comment by scottkleinman** [comment]
I've added this issue to our _In the Margins Notes_, so I am removing the "In the Margins" label. The "Enhancement" label still applies, so I am leaving this issue open.

**Comment by Weiqi97** [comment]
@jacksonjreed Maybe we can give users the option to choose how many graphs they want in a row.

**Comment by jacksonjreed** [comment]
I don't totally understand this one--can I get more info on how to reproduce the problem?
- is it only a problem with chinese texts?
- does this only happen with a large number of separate documents (graphs) displaying on the same page?
- does it have something to do with the number of unique words/tokens in a document?

**Comment by scottkleinman** [comment]
This is an old issue from before we removed import of data from MALLET. I suspect, however, that the problem might be the same with words that are scaled in a particular way. It's not the number of documents that matters, but certain frequencies of terms within documents which aren't arranged well by the layout algorithm. Identifying the offending combination of term frequencies might be very difficult. It's worth checking, however, whether the problem is more likely to occur with single glyph writing systems like Chinese. That might suggest a test for adjusting the scaling to create a better fit.

**Comment by cgnobrega** [comment]
I did some testing with this, and in the new UI (version 4.0) this does not seem to be an issue
