### ISSUE TITLE
Keeping word-internal hyphens

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#118]
Following on from issue #116 (word-internal apostrophes), I wonder whether we should make the option to retain hyphens really an option to retain word-internal hyphens? A long time ago someone asked me whether Lexos would handle scanned texts where words have been divided by hyphens at the end of lines. I can't remember what I replied. How *does* Lexos behave in this situation?

**Comment by mleblanc321** [comment]
hmm, do we need preprocessor=None explicitly?

**Comment by mleblanc321** [comment]
see 
David L. Hoover's paper from Digital Humanities 2015 (The Trials of Tokenization); i have a copy where he discusses issues with hyphens at--length :)

**Comment by chantisnake** [comment]
I think this feature is fully working.

I will close this. If there is further question, please reopen.
