### ISSUE TITLE
Refresh button does not keep chosen options

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#127]
Refresh button on Hierarchical Clustering page can keep the chosen Tokenize/Normalize options most of the time, but it does not keep the choices if "Only within words" or "Norm: None" is chosen.

**Comment by JingxianL** [comment]
As I was working on cutter, I found out that the button for letter/chunk for cutting option also has this problem. All the other cutting options will keep but this one. After you klick on preview cut, the chosen option for letter/chunk will then disappear.

**Comment by chantisnake** [comment]
Can't we just look at the request.form to determine whether it is checked. Because caching into session do not work...

**Comment by gryphonwastler** [comment]
I added in the jinja to make these checks.  The info was being stored into session.  however, for the inwords checkbox there was simply no jinja code to check the session period. As for the none radio, we were checking if 'none' was in session but we needed to check for 'None'.  This has be fixed now, I will push the change in a couple minutes.
