### ISSUE TITLE
Appearance Bug on Cut

### ISSUE THREAD

**Issue by lithiah** [WheatonCS/Lexos#131]
When you select letters/chunk or words/chunk etc. the "overlap" and "last chunk size threshold" text labels for the input values remained greyed out despite being active fields.

**Comment by austinrg7** [comment]
Adding some more detail to this issue:

This only happens if you choose letter,lines,words/chunk after already cutting a file using the option chunks/file.

**Comment by austinrg7** [comment]
Issue was due to one line in the iconfonts.css file that was setting the labels to white.  Deleted the line and that fixed the issue.
