### ISSUE TITLE
MultiCloud crashes on Classical Chinese files

### ISSUE THREAD

**Issue by jge94** [WheatonCS/Lexos#136]
When the file names are in Chinese, MultiCloud crashes. 
(And maybe for our long term to do, add the Normalization section to MultiCloud as well? Because now it's still looking for white space instead of through individual characters)

**Comment by mleblanc321** [comment]
scott:  just revisiting this old issue; i'm not sure of the status ...

**Comment by scottkleinman** [comment]
I think I've got the fix, but I haven't pushed it yet. I'm not very familiar with the Normalization procedure (it's mentioned in a few issues, but not in a clear way). I think we can address this once I get to Wheaton.

**Comment by JingxianL** [comment]
I am wondering if this still doesn't work, or have we fix it?

**Comment by scottkleinman** [comment]
This issue still has not been fixed.

**Comment by scottkleinman** [comment]
It works for me now.

**Comment by JingxianL** [comment]
I think the page doesn't crash anymore, but it still is only showing paragraph as words in Chinese. Maybe for later enhencement we could add the normorlize option to show character for none whitespace separeted languages.

**Comment by scottkleinman** [comment]
I noticed this, but I assumed that it was because I had not tokenised by characters. Will that solve the problem?
