### ISSUE TITLE
Stopwords, Lemmas, Consolidations, Special Characters don't work for Chinese characters

### ISSUE THREAD

**Issue by jge94** [WheatonCS/Lexos#137]
If you type in Chinese characters in the boxes, they don't work at all.

**Comment by scottkleinman** [comment]
Has this issue been fixed?

**Comment by mleblanc321** [comment]
jingxian:  please check on this?  if still wrong, what is wrong (and how might we take what we learn and apply that to other places in the software that might balk at the UTF-8 range of characters, for example at input?)

**Comment by JingxianL** [comment]
I just checked on this. I think consolidation is the only one that is working. Stop words for what we have now is only working with whitespace separated languages. That is also true for Lemma. We don't have anything that used in Chinese are special characters, so I don't think that is apply.

**Comment by kreddy95** [comment]
as long as we don't have a chinese parser chinese text cannot work.

Closing this for now.
