### ISSUE TITLE
Rolling Window Layout 

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#138]
Need to fix the tooltip position of 'Search Token' when the option 'Rolling Ratio' is chosen

**Comment by mleblanc321** [comment]
rolling ratio windows should line up (one over the other) to give a visual ratio appearance

**Comment by mleblanc321** [comment]
not a layout issue ... but .. after GetGraph is clicked for a rolling ratio, the page reverts to the (default) rollingAverage

**Comment by akuisara** [comment]
- Rolling ratio options can be kept in session and GUI now
- Input fields of `Search Token` are reformatted, so that denominators and numerators can be seen clearly
- Input fields of `Search Token` are active while mouse hovering over
