### ISSUE TITLE
remove digits

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#143]
hmm, remove digits right now removes:   \d+  which is essentially Arabic numerals
0-9 .... but surely other languages have their own "digits", right?

we could update this to check the metadata on each character, similar to how we check
the Unicode Character Class for punctuation startswith{P} and symbols startswith{S} ... ?

here's how i wrote this part up for "in the margins" as of now:
"
"Remove Digits in Lexos
Selecting this option removes all decimal digits: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9} from the text. Lexos does not presently remove Arabic-Indic digits, Eastern Arabic-Indic digits, Roman numerals, ideographic number zero, or the old italic number one."

leaving this as is for now ... but ... thoughts?  should we be more careful to remove "other digits" ?

**Comment by mleblanc321** [comment]
jesse:  can we close this issue?  (that is, are you convinced we have this working now?)

**Comment by jaronson13** [comment]
Yes, we can close this issue now. I believe it works well.
