### ISSUE TITLE
Upload: select groups

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#151]
It would be useful to be able to "select" uploaded files in groups rather than one at a time for processing.
      Reason (example): I loaded 480 files, which turned out to be too many chunks further downstream in the processing for the system to download for me.  I wanted to go back and select only a third or half of the 480 files to work on at a time.  As far as I can figure out, there is no way to select a span of files.  One has to select each file individually, which is s lengthy process because there is a delay of about 3 seconds in selecting a file.

**Comment by scottkleinman** [comment]
This tool ultimately needs a list view to fit more documents on the screen. Regardless, I think the best solution to selecting groups of documents is by drag select. I am working on a prototype.

**Comment by gryphonwastler** [comment]
I think this issue has been addressed by the new select page functionality, which would mean this issue is ready to close.

**Comment by chantisnake** [comment]
no, group allow to have one passage in 2 group, but not class

**Comment by JingxianL** [comment]
I don't think this is implement in the new select page functionality, I think what Mark means is that it will be nice to have a functionality to set a set of files into a group, and have the option of select all or deselect on this group of file. Which we do not have in our new select page currently.

**Comment by scottkleinman** [comment]
I'm a little confused about what this issue relates to as well. If it's the Select page, I recommend setting the table to display all documents and then selecting groups by holding down the mouse button and dragging over them. This is, of course, assuming that the Select screen works. I'm still trying to fix it.

**Comment by scottkleinman** [comment]
Was the original issue addressed by the new Select page?

**Comment by mleblanc321** [comment]
i will close this issue as do believe we have moved Select beyond this original concern(?);

jingxian, moses:  i believe some of the confusion might be the desire for "groups" in topWords, where a document could be in more than one group (thus is not a classLabel which is unique per document for classification examples);  please review this issue's thread of messages and reissue any new Issue (be specific) which may or may not have fixed your earlier concerns)
