### ISSUE TITLE
Cutter: let user know in advance about upload limits (e.g., <= 4M)

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#154]
I lost a lot of time at one point chunking 480 novels only to discover that I couldn't download the results because they exceeded the "maximum transfer" quantity, though it was unclear from the error report whether quantity meant number of files or megabytes.  I had to redo the job in sections, though I had to guess at how many novels I could process at a time.  Lexos could very usefully let users know in advance about the limitations on maximum number or size of a chunking operation if they want to download the results.

**Comment by scottkleinman** [comment]
I wasn't aware of this limitation, and I can't seem to find it in the code. What was the basis for it?

**Comment by JingxianL** [comment]
The upload limit is 4MB per file, but you could still upload a lot of files that are 4MB. The code for this is in upload.html, "<input type="hidden" id="MAX_FILE_SIZE" name="MAX_FILE_SIZE" value={{ 4 * 1024 * 1024 }} />".

**Comment by JingxianL** [comment]
I added a couple of words on the upload page saying that the max file limit is 4MB after supported file type.

**Comment by jaronson13** [comment]
I added an error message that handles the file size limit.
