### ISSUE TITLE
Install directions

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#156]
I tried to download and install Lexos on my Windows machine at one point.  Miserable failure.  The documentation for installation and running could be hugely improved.  I have low- to mid-level Python package installation experience.  Most folks in the humanities have none.  Lexos needs a step-by-step for installatoin aimed, for example, at the ordinary undergraduate humanities student.

**Comment by chantisnake** [comment]
shell on windows is a so hard to use and has a very steep learning curve. 
I think there is something called py2exe, you can look at.

**Comment by Gryphonwastler** [comment]
Added my three undergraduate humanities student approved install guides, including windows.
