### ISSUE TITLE
The Voronoi Tessellation and K-Mean Visualization Tool

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#157]
http://bl.ocks.org/mbostock/4060366

http://www.naftaliharris.com/blog/visualizing-k-means-clustering/

http://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_digits.html

**Comment by scottkleinman** [comment]
Adding two more links:
* http://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_digits.html (this may have been the model for the current Lexos K-Means clustering tool)
* https://github.com/mbostock/d3/wiki/Voronoi-Geom (The d3 API reference for Voronoi graphs)

**Comment by mleblanc321** [comment]
I'd like Moses to help us all get a handle on the options for our clustering algorithms; presently we are using Silhouette Coefficient, but perhaps a small whiteboard session could help us determine if (a) we still want to include this measure and (b) if any other possible evaluation of "goodness" could be applied;

this article is a good starting point:
http://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation

**Comment by scottkleinman** [comment]
This has been implemented. Closing issue.
