### ISSUE TITLE
Improve clustering evaluation metrics

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#158]
I'd like Moses to help us all get a handle on the options for our clustering algorithms; presently we are using Silhouette Coefficient, but perhaps a small whiteboard session could help us determine if (a) we still want to include this measure and (b) if any other possible evaluation of "goodness" could be applied;

this article is a good starting point:
http://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation

**Comment by scottkleinman** [comment]
Just referencing closed issue #56 here.

**Comment by kreddy95** [comment]
I think Silhouette Score did a good job on this.

Do you need any documentation on this?

**Comment by scottkleinman** [comment]
We could definitely expand this page: [http://scalar.usc.edu/works/lexos/establishing-robust-clusters?path=cluster-analysis](http://scalar.usc.edu/works/lexos/establishing-robust-clusters?path=cluster-analysis).

**Comment by scottkleinman** [comment]
I don't really see much advantage to implementing the other metrics offered by scikit-learn. I agree with Kristina that the Silhouette Coefficient provide a good measure for most purposes. We should keep in mind, however, that our eventual goal is to offer Bootstrap consensus. I think this will be the most intuitive form of evaluating cluster quality for Humanities users.

I think that's enough, however, to change the title of this issue slightly and label it for enhancement.

**Comment by chantisnake** [comment]
I think Josh has worked on this last year. Is his work comprehensive enough to solve this issue?

**Comment by cgnobrega** [comment]
Is this still an issue we need to be concerned about in v. 4.0 @chantisnake ?

**Comment by scottkleinman** [comment]
I kind of liked silhouette scores and found them useful with a proper explanation (which I wrote up for _In the Margins_. Now that we have bootstrap consensus trees, however, there is less urgency to reintroduce them. I would suggest closing this issue and opening a new one labelled enhancement to reintroduce silhouette scores in future versions. But I won't do that myself, as this could use a little more discussion.
