### ISSUE TITLE
FOUT issue on Tokenizer page under prepare section

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#159]
I just added a scrollable div on the Tokenizer page to show the DTM. I used some code for the wordcloud TidyTable written by @scottkleinman However, the Tokenizer page has FOUT issue.

**Comment by scottkleinman** [comment]
It's very fast on my local install, but I see the blip. It may be that the problem doesn't occur in WordCloud because the table is initially hidden. I'll look into it.

**Comment by scottkleinman** [comment]
I've pushed some changes to Tokenizer which seem to help. Let me know how it looks on your end. Rendering the table client-side is ultimately going to be slow, so we may eventually want to add a "loading" icon. Sadly, the Tidy-Table script appears to have post-processing hook but not a pre-processing one.

**Comment by akuisara** [comment]
Thanks Scott, it looks much better than yesterday, the process isn't too slow on my end. I really like the idea of using a "loading" icon.

**Comment by scottkleinman** [comment]
I'm glad it works. I made a few tweaks, but most of the problem was that some of the code was for the JQuery UI dialog. I think the implementation of the "loading" icon relates to issue #152, so I'll close this issue and add it there.
