### ISSUE TITLE
add MaxWords to BubbleViz

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#160]
a really useful function would be adding a "Maximum number of words" option to BubbleViz. The current filter by word length is not as good a way to reduce the number of bubbles. This should be an easy fix.

**Comment by Gryphonwastler** [comment]
Finished and pushed.

**Comment by scottkleinman** [comment]
It doesn't look like this was changed in the UI.

**Comment by scottkleinman** [comment]
Correction, this was implemented as a checkbox toggle--I just completely missed it. I'll give some thought to making the UI a little more obvious before closing this issue. The loading icon needs to be displayed, so I'll try to do that a the same time.

**Comment by scottkleinman** [comment]
The fix for this issue will go out in my next push. The check box now toggles both Maximum Number of Words and Minimum Word Length options, and they are given in that order since the former is more likely to be used.
