### ISSUE TITLE
Lexo can work with Chinese now(I haven't push this change)

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#162]
I haven't push this change yet. I am still afraid that this would mess up the project.

## new dependency:
jieba.  // a Chinese word cutting library (tend to over cut from experiment)
* install method:  ```$pip install jieba ```

## how this work:
in the addfile function in ModelClass.py, I add a Chinese handle part. 
it takes the first character of a file to see if that is chinese.
if it is, then the program use jieba.cut to cut, and then add an empty space in each word.
* ultimately I hope we can have our own library to do that. but this seems to work.

### upload
![screenshot from 2015-05-30 15 40 04](https://cloud.githubusercontent.com/assets/10100995/7899077/e0156a6a-06e3-11e5-96c0-8a0a8cf59ad0.png)
### cut
![screenshot from 2015-05-30 15 43 23](https://cloud.githubusercontent.com/assets/10100995/7899089/0ffc9d0c-06e4-11e5-80c4-ee2749cd6880.png)
### rolling window (with word)
![screenshot from 2015-05-30 15 44 41](https://cloud.githubusercontent.com/assets/10100995/7899093/2aff9686-06e4-11e5-98b9-ec725975908c.png)
### word cloud
![screenshot from 2015-05-30 15 44 53](https://cloud.githubusercontent.com/assets/10100995/7899094/3867ca46-06e4-11e5-84e4-b28ac46fb2ae.png)
### Hierarchical Clustering
![screenshot from 2015-05-30 15 45 20](https://cloud.githubusercontent.com/assets/10100995/7899095/46371208-06e4-11e5-9524-1b732f7a5c27.png)
![screenshot from 2015-05-30 15 45 27](https://cloud.githubusercontent.com/assets/10100995/7899096/48086dde-06e4-11e5-8147-44f296cb9305.png)

**Comment by scottkleinman** [comment]
Good work finding the jieba package. Here are some comments that should eventually form part of another issue. Jieba has some settings, including a choice of dictionaries or customisable dictionaries, that should probably be accessible from the Lexos UI. One of the dictionaries is supposedly better for Classical Chinese. In my experience, Classical Chinese can mostly be tokenised as 1-grams, with a few exceptions (often names). It would be interesting to test whether the jieba dictionary works better than allowing the user to upload a small list of bi- and tri-grams.

With regard to your worries about pushing the change, I have similar concerns about development of the Select screen, but I think I have a solution. Set aside a section of the File Manager and lexos.py for development functions. I have a sample of this, which I will push to GitHub before the end of the weekend. You can have a look and see whether it works for you.

**Comment by mleblanc321** [comment]
moses:

please do not push any code in testing phase;  the only code that
gets pushed should be reviewed by sara first, ok?

note:  when you CUT chinese, you must select BY CHARACTER (not WORD)
since as the cutter looks for whitespace

m



On Sat, May 30, 2015 at 7:55 PM, Cheng Zhang <notifications@github.com>
wrote:

> I haven't push this change yet. I am still afraid that this would mess up
> the project.
> New Dependency:
>
> jieba. // a Chinese word cutting library (tend to over cut from experiment)
> // install method: pip install jieba
> how this work:
>
> in the addfile function in ModelClass.py, I add a Chinese handle part.
> it takes the first character of a file to see if that is chinese.
> if it is, then the program use jieba.cut to cut, and then add an empty
> space in each word.
>
>    - ultimately I hope we can have our own library to do that. but this
>    seems to work.
>
> test image upload
>
> [image: screenshot from 2015-05-30 15 40 04]
> <https://cloud.githubusercontent.com/assets/10100995/7899077/e0156a6a-06e3-11e5-96c0-8a0a8cf59ad0.png>
> cut
>
> [image: screenshot from 2015-05-30 15 43 23]
> <https://cloud.githubusercontent.com/assets/10100995/7899089/0ffc9d0c-06e4-11e5-80c4-ee2749cd6880.png>
> rolling window (with word)
>
> [image: screenshot from 2015-05-30 15 44 41]
> <https://cloud.githubusercontent.com/assets/10100995/7899093/2aff9686-06e4-11e5-98b9-ec725975908c.png>
> word cloud
>
> [image: screenshot from 2015-05-30 15 44 53]
> <https://cloud.githubusercontent.com/assets/10100995/7899094/3867ca46-06e4-11e5-84e4-b28ac46fb2ae.png>
> Hierarchical Clustering
>
> [image: screenshot from 2015-05-30 15 45 20]
> <https://cloud.githubusercontent.com/assets/10100995/7899095/46371208-06e4-11e5-9524-1b732f7a5c27.png>
> [image: screenshot from 2015-05-30 15 45 27]
> <https://cloud.githubusercontent.com/assets/10100995/7899096/48086dde-06e4-11e5-8147-44f296cb9305.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/162>.
>



-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Meneely Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by chantisnake** [comment]
That is exactly why I did not push that code.

-----Original Message-----

**Comment by chantisnake** [comment]
Hi Scott:

Thank you for your advise. I will look deeper into jieba tomorrow probably. 

I have done couple of test, this library cuts fine, mostly in some ambiguous part, jieba tend to cut as much as possible, but there is no wrong cutting from what I see now.

As for Classical Chinese, it is incredibly brief. Plus jieba always cut as many as possible, it is normal that it tokenizes most into one-gram. I will check for other customizable options.

FYI, I just did a test on Dream of the Red Chamber, which is wrote by 2 different person. And get a pretty good but not perfect result.

Best,
Moses

**Comment by chantisnake** [comment]
Hi Prof. Leblanc:

I will not push the code until Sarah told me so. 

And the program add white space to the end of each word if it detects the paragraph is written in Chinese. Therefore, this should work normally with other parts of the program.

Best,
Mose

**Comment by mleblanc321** [comment]
moses:
in analyses last year, chapters 64 and 67 cluster with
the ending chapters (81-120);

i believe in redology (the study of this ancient novel) there is some
scholarship that suggests that the author of the later chapters may
have had some hand in rewriting some of the earlier chapters ??

m

On Sat, May 30, 2015 at 11:22 PM, Cheng Zhang <notifications@github.com>
wrote:

> Hi Scott:
>
> Thank you for your advise. I will look deeper into jieba tomorrow
> probably.
>
> I have done couple of test, this library cuts fine, mostly in some
> ambiguous part, jieba tend to cut as much as possible, but there is no
> wrong cutting from what I see now.
>
> As for Classical Chinese, it is incredibly brief. Plus jieba always cut as
> many as possible, it is normal that it tokenizes most into one-gram. I will
> check for other customizable options.
>
> FYI, I just did a test on Dream of the Red Chamber, which is wrote by 2
> different person. And get a pretty good but not perfect result.
>
> Best,
> Moses
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/162#issuecomment-107098716>.
>



-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Meneely Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by chantisnake** [comment]
I have test several files today. I would say that this solution is fine, but far not perfect.

This library works fine with modern (and contemporary) Chinese, including Bajin(contemporary) and Three Body(modern). There is nearly no mistake with Three Body, but there are some mistake with Bajin, and most mistakes occurs around people's name.

It works so-so with ancient article. There are some mistakes, more than contemporary and modern, and some of them are not minor: they completely twisted the meaning of the passage, and can potentially mess up the analysis. but for a passage around 100 of words I can find approximately 5 error cut.

It does not work at all with ancient poem. There is too many mistake, that I think the result will not be useful at all (fortunately there is some pattern with Chinese ancient poem)

---------------------
About redology, I am really not a literature person. I think probably Drout and Marguerite(a Chinese student works with Drout, but now has come back China) would be much more helpful than I can ever be.

------------------
For the mistake, I think that the only way is let the user to manually fix this.
And Jieba package do offer something like temporarily change the word frequency in the dictionary or temporarily add word to dictionary, and use custom dictionary.

I will continue testing how this works with Chinese, and will give a more detailed report by the end of today.

Best,
Cheng
