### ISSUE TITLE
Similarity Query Crashes

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#164]
Similarity Query crashes when there is only a few chunks active, but not exactly how many. I have tried different input files and got different error messages, including "invalid shape", "failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)" and "decomposition not initialized yet". There is no exception handling before calling the models.LsiModel() function inside the similarity.py file.

**Comment by chantisnake** [comment]
I will take this since Greyword is nearly finished.

**Comment by chantisnake** [comment]
something I found on similarity:
1. this did not use get matrix, it generates it own file, this can be a problem
2. this does not support any kind of normalization which it should(because it did not get matrix)
3. ```Remove words that only appear once (hapax legomena)``` option only test the file that is not an comparison file, this is can be a problem
4. the program crashes when there is only one file selected, adding a protector in the back-end is easy, but I probably need some help when it come to front-end
5. this program works pretty well with my test file. Can you recall what file do you use to test this program and send me a copy of them?

**Comment by chantisnake** [comment]
```failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)```
happens when the non-chosen file only contain word with frequency 1, and you check the option ```Remove words that only appear once (hapax legomena)```, or the non-chosen file has empty file

```decomposition not initialized yet``` happens when there is only one file selected

**Comment by chantisnake** [comment]
https://radimrehurek.com/gensim/tut3.html

all the code follows exactly the tutorial. I think that meanly what causes the error is the remove word check box. If you can try to not check that check box to see if the program crash.

There is something I am really interested in.
Although on the tutorial they claim to use Cosine similarity. I did some test, the result clearly defer form Cosine similarity:
test1: 'la la la la he da'
test2: 'he'
without checking ````Remove words that only appear once (hapax legomena)```` the program return ````1.0````, which should not be. the internal code seems to have some kind of noise reduce method.

I will look into that tomorrow.

FYI, I have done some test that we already know what the result should be. This method always give the most accurate result of all measures.

**Comment by scottkleinman** [comment]
Are you still using the old code as a basis to work from? Try the code at [https://de.dariah.eu/tatom/working_with_text.html#comparing-texts](https://de.dariah.eu/tatom/working_with_text.html#comparing-texts). In my experience, it's much faster, and it may avoid the problem you are encountering.

**Comment by chantisnake** [comment]
Yes! This is exactly Cosine Similarity should be! That is why I am confused.

But, this do not give the same result as the plain old Cosine Similarity, and from my test, this result seems to be more accurate. I will dig into that deeper. 

If we really need Cosine Similarity, this should be an easy fix to just rewrite the code.


I just found that this article seems to be the algorithm support for the code:
http://www.cs.bham.ac.uk/~pxt/IDA/lsa_ind.pdf

**Comment by chantisnake** [comment]
I have figure out the back end problem, but adding a message on the front page can be tricky. I might need some help.

**Comment by chantisnake** [comment]
see https://github.com/WheatonCS/Lexos/issues/173
