### ISSUE TITLE
Some Javascript and CSS libraries are not local

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#166]
From the source code:

```html
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
	<script type="text/javascript" src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
	<script type="text/javascript" src="/static/js/scripts_icons.js?ver=2"></script>
	<script type="text/javascript" src="/static/js/scripts_base.js?ver=2"></script>

	<link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css"/>
```
If someone gets a chance, can they hook up local copies of JQuery, JQueryUI (script and stylesheet), and d3.js? That should speed up page load times.

**Comment by bawjensen** [comment]
Hey, just to chime in:

It's recommended to have CDN versions of all external resources, so we should ideally actually replace all local copies of things like jQuery/d3/etc. with external links. This is because CDNs are hosted on servers much more central, and can load faster. People at Wheaton would see a performance hit, since they would have to go farther than the lexos server to load these scripts, but everyone else would have to go less distance, as the CDN server is almost guaranteed to be closer than lexos.

**Comment by scottkleinman** [comment]
Good point, though I don't know if it applies to d3. I think I may just be noticing load times more because my local Starbucks is filled with UCLA students cramming for finals. I'm also not working on a page that uses d3, so we might want to call that from the individual script files for maximum efficiency. But no big deal for now.

**Comment by scottkleinman** [comment]
I'm re-opening this issue because a user might still want to load local copies of Javascript libraries for a local installation of Lexos, especially if they wish to use when they have no or a slow internet connection. It would be fairly easy to include the scripts in the GitHub repo and create a fallback to them if the CDN files fail to load. But I want to raise an alternative possibility, a configuration.settings option to allow the user to opt to load scripts locally. On its own, this may not be worth it, but setting up a configuration structure for future settings options (e.g. for language localisation) might be worth thinking about. I'll set up a separate issue for that and link it to this one for future reference. In the meantime, I won't close this until we decide if we want to introduce a fallback or a config file or screen.

**Comment by kreddy95** [comment]
This may need some attention now. do we localize all package if people uses local install? and deletes some of them on the server?

what is the decision on this?

**Comment by scottkleinman** [comment]
Do you mean javascript libraries loaded over the internet?

**Comment by scottkleinman** [comment]
A fallback option is the best way of dealing with failed CDN calls, but, in the meantime, we have developed a local mode which makes local versions of Javascript libraries available if the user has no internet connection. That should do for now. See issue #431.
