### ISSUE TITLE
Can we move some of the request.from() in analyze in getMatrix method (int ModelClasses.py)

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#167]
This will make the code a little more tidy in other method, and easy to add function to the getMatrix() method.

**Comment by JingxianL** [comment]
What do you mean by move all the request.from()? Where do you want to move them to?

**Comment by chantisnake** [comment]
all the analysis method need to use the method ````getMatrix()````, and the input of method ````getMatrix()```` are exactly all the parameter listed in the template ````base_analyze.html````

so instead of get all the parameter in ````base_analyze.html```` in individual methods like ````generateKMeans()```` and ````generateDendrogram()```` and then pass them in to ````getMatrix()```` method, why not just get the parameter inside  ````getMatrix()````

````Grey Word```` are getting the checkbox straight from ````base_analyze.html````, and it seems to work fine.

**Comment by chantisnake** [comment]
only ````generateSimilarities()```` do not use get matrix method, and this cause some bug...

if do not support any normalization. We probably need to fix that later. = =

**Comment by akuisara** [comment]
Only a few options can be moved into getMatrix(), we can't move all the request.form(), an example would be `metric_dist`

**Comment by chantisnake** [comment]
sorry I am not clear on that, I mean only the parameter in ````base_analyze.html````

**Comment by chantisnake** [comment]
to be exact:
````useWordTokens````, ````onlyCharGramsWithinWords````, ````ngramSize````, ````useFreq````

**Comment by mleblanc321** [comment]
sara: i'm not sure if this is an "issue";  what is the status of this?

**Comment by chantisnake** [comment]
because there is somewhere in greywords and in topword need some variable to be fixed(cannot get directly from the page).

So we are thinking adding a loadrequest function, and after loadrequest, we can overwrite the variable and then get matrix. this way give the program more flexibility

**Comment by akuisara** [comment]
I think adding a new function to get options can still make the code pretty messy, since we are trying to get options from request.form[] all over the FileManager functions. I think moving some redundant lines into getMatrix() sounds good, but code looks messy in either way.

**Comment by akuisara** [comment]
`getMatrixOptions()` is created to get all the options needed for generating matrices. All these options are saved into FileManager as existingMatrix["userOptions"], which is used to detect if there are any options changes on GUI. Even though users may accidentally choose "Use Existing DTM" but change the options to generate the matrices, new DTM will be created based on new chosen options.
