### ISSUE TITLE
Cloned files

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#170]
If you cut a file into 10 segments, de-activate those segments, and then cut the file into 11 segments, you will get duplicate copies of each segment with the same name (except for the 11th segment). This can get confusing. You could assign a class to each set of segments, but that's a little clunky, and not really what class labels should be used for.

A better approach might be to allow the user to clone the original file, automatically giving it a name like "Copy of X". All scrubbed or cut versions of the clone would then have different names. This would allow you to work with two different versions of a text (e.g. with two different sets of stop words) from a single uploaded file. Does the File Manager currently save a copy of the original uploaded, or is it overwritten once scrubbing is applied?

**Comment by chantisnake** [comment]
I will take a look at it.

**Comment by chantisnake** [comment]
the problem I am encountering now is that if we append something after the file name, after couple of cut, the file name will get intensely messy. any idea on that.

**Comment by scottkleinman** [comment]
There's no way to completely avoid this problem, but it helps if the user can modify the file label. For instance. If you start with "Frankenstein" and make "Copy of Frankenstein", the user can then change that to "Frank2", or whatever they want. The new Select UI that I am working on can handle this on the front end, but I'm not sure how to clone the file on the back end. So, if you can figure out a way to do that, make a note of the procedure, and then we'll try to implement it next week.

Also, I am raising this as a question for the literature research group to see if they have felt the need for this functionality.

**Comment by chantisnake** [comment]
the file on the backend in fact use file label(distinct) and file name together. Unless someone don't know this, and use file name to check for file difference, there will be no problem on the backend
