### ISSUE TITLE
Greyword errors on hierarchical clustering

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#171]
When trying to generate the dendrogram with DAZ or Chinese files, program crashes when `Grey Word`, `by Characters`, and either `Manhattan Distance` or `Euclidean Distance` are chosen. 

`ValueError: math domain error` and `ValueError: Number of labels is 1 but should be more than 2and less than n_samples - 1`

```
File "/Users/apple/Desktop/Lexos/models/ModelClasses.py", line 601, in getMatrix
countMatrix = self.greyword(PropMatrix=countMatrix, CountMatrix=matrix)

File "/Users/apple/Desktop/Lexos/models/ModelClasses.py", line 445, in greyword
Bondary = round(sqrt(log(Total * log(Max) / log(Total + 1) ** 2 + exp(1))))  # calculate the Bondary of each file
```

**Comment by chantisnake** [comment]
I think it is because log get a negative value, probably is because Max is too small, I will try to add a 1 there.

**Comment by chantisnake** [comment]
Greyword now works fine with couple of test. I will do more test and push the code

**Comment by chantisnake** [comment]
This is fixed.
rest of the problem see https://github.com/WheatonCS/Lexos/issues/173
