### ISSUE TITLE
Consider creating a configuration/settings function in Lexos

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#175]
There's no immediate need to have user-defined configurations of Lexos, but in the future this may be worth exploring. We may want to have a specific configuration for local installations (see issue #166) or for language localisation. Something to put on the backburner, but we may want to put hooks in the code to allow future configuration.

**Comment by chantisnake** [comment]
do you mean give the user option to write little script for there configuration?

**Comment by scottkleinman** [comment]
No, it would be a screen (i.e. like "Upload" or "Select") which would give the user a choice to run only with local scripts. But that's for later. In the near term, we could add a fallback function like that described [here](http://www.hanselman.com/blog/CDNsFailButYourScriptsDontHaveToFallbackFromCDNToLocalJQuery.aspx).

**Comment by scottkleinman** [comment]
I'm using this issue to catalogue possible uses for a configuration file and/or UI component:

1. Toggle CDN/local Javascript libraries.
2. Linguistic localisation.
3. Toggle In the Margins (to prevent lag time loading the Scalar API).

I'll add other possible uses here as they occur to me.

**Comment by chantisnake** [comment]
can we load int the margin when user open the in the margin page in stead of loading that together with our web page?

-----Original Message-----

**Comment by scottkleinman** [comment]
That's one of the options I am considering...

**Comment by mleblanc321** [comment]
good list:

Toggle CDN/local Javascript libraries.  [good; for now in repo, how set?]
Linguistic localisation. [ugh, we didn't promise this, right?  but clearly important]
Toggle In the Margins (to prevent lag time loading the Scalar API) [hopefully, this can we "pulled out" by the user when she is in more of a reading mode vs. a "cut code" mode? we may cache "just enough" for first use, then call out when more is requested?]

**Comment by scottkleinman** [comment]
For CDN v. local Javascript libraries, we can obviously comment out the one we don't want. I'll get to work on the fallback option--that way using CDN loading becomes a simple Boolean. We can have a setting in the base template, and, if it evaluates to true, Lexos will attempt to load by CDN before using a local fallback. Then it's a matter of setting the Boolean. *We* can do that in the base code, but for users we can create a config file and load that. Eventually, we can build that possibility into the UI.

We didn't promise linguistic localisation. It's just a long term goal, and a UI settings function would be one way to implement switching languages.

"On demand" loading of the Scalar API code is a possibility. However, the implementation I tried this week is browser caching. The javascript loads once by Ajax the first time the user loads a Lexos screen, then it is cached by the browser. That definitely sped things up. So we can see how that method goes and play with other strategies as the need arises.

**Comment by chantisnake** [comment]
I think this is created?

**Comment by scottkleinman** [comment]
It's rudimentary, but yes. I think we can close this.
