### ISSUE TITLE
Installation guide on Mac OS X

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#176]
When I install anaconda on my Mac, anaconda did not prompt me for changing PATH.

I do not have ````pip```` by default

I have python3 and pip3 installed on my Mac, I think that can be the problem.

**Comment by chantisnake** [comment]
I think the problem might be the Mac Developer Tool automatically install python 2.7.6 for me, which do not include ````pip```` I think we need to include that in the User Guide for those who use lower version of Python2.

Linux also has this problem, luckily Linux has built in package manager.
therefor we only need to:
````sudo apt-get install pip````

**Comment by chantisnake** [comment]
Also if your login shell is not Bash, there will be problems

**Comment by chantisnake** [comment]
there are no:

<pre>
Lexos in now running on your computer! But where is it?  To interact with the program you will need to open your favorite web browser and in the address bar type “localhost:5000
</pre>

on the shell

**Comment by chantisnake** [comment]
@Gryphonwastler 

The last one I want you to confirm, and here is the online version of the install guide:
http://lexodocument.github.io/for%20user/2015/06/07/mac-osx-and-linux-install-guide/

Can you take a look and tell me what's wrong? Thanks

**Comment by akuisara** [comment]
Personally I don't think the background in your screenshots looks consistent with this project. Do you mind changing the opacity of your terminal window or maybe using a plain background instead?

**Comment by JingxianL** [comment]
The other thing is that, I just installed a linux system on my windows laptop, and when I git clone, it says git is not installed. I am not sure if this is only with linux box, not os, since I couldn't remember when I first used git on my mac computer.

**Comment by chantisnake** [comment]
Hi Jinxian,

on Mac, git is installed with Mac developer tool, together with python and vim and so on, but on Linux, you might need to install git by hand, but shell will tell you to use ````sudo apt-get install git```` to install unless you use zsh.

And if the user is using linux, we probably can assume that they know how to install something basic like git.

**Comment by chantisnake** [comment]
Hi Sara:

Sorry I did not thought of that...

Retaking the screenshot means that I have to uninstall all the dependence and reinstall them, and rename screenshot, and then add the screenshot to the webpage. it can be a pain...

Let's talk about that on Monday. If people think that is an issue we will figure out a way to change that.

**Comment by chantisnake** [comment]
Luckily my windows box is broken... They have the same background... LoL...
