### ISSUE TITLE
In Scrub, why is Special Characters open by default.

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#182]
The screen is less confusing if it's closed, so we should probably switch that if there is no reason.

**Comment by mleblanc321** [comment]
yes, i think it should be closed by default;  (as a related request, i've asked that Culling Options also be closed by default in order to simplify the first time visit to the busy tokenize/normalize panel)

**Comment by akuisara** [comment]
Both the special characters option and the culling options are closed now by default.
