### ISSUE TITLE
being consistent with TERMINOLOGY

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#186]
We need to sweep through the UI (and internal documentation) and attempt a more rigorous effort at using consistent terminology.

Lexos-Wide Changes:
Letter => (changed to) Character
Chunk => Segment
File => Document in the places listed below

Prepare
Scrub:
Original
Red Text that says 'No Files are Selected' 
New
Red Text that says 'No Documents are Selected'

Cut:
Original
Letters/Chunk 
New
Characters/Segment

Original
Lines/Chunk 
New
Lines/Segment

Original
Words/Chunk 
New
Words/Segment

Original
Chunks/File 
New
Segments/Document

Original
Chunk Size 
New
Segment Size

Original
Last Chunk Size Threshold 
New
Last Segment Size Threshold

Original
Red text that says 'No Files are Selected'
New
Red text that says 'No Documents are Selected'

Cut Tooltips:
Chunk Size: Last line of tooltip, change file to document

Tokenize:
Data Orientation:
Original
Files as Columns, Words as Rows 
New 
Documents as Columns, Words as Rows

Original
Files as Rows, Words as Columns 
New
Documents as Rows, Words as Columns

Culling Options:
Tooltips for first one is broken. Others need to be rewritten

Analyze:
Clustering:
Hierarchical Clustering:
Original
Perform hierarchical clustering analsis on your files 
New
Perform hierarchical clusterng on your documents

K-Means Clustering:
Original
Perform k-means clustering analysis on your files 
New
Perform k-means clustering analysis on your documents

Similarity Query:
Original
Select Comparison File 
New
Select Comparison Document

Original
Select one file to be the external comparison. All other files shown below will be used to make the model, and will be ranked in order of most to least similar to the comparison file in your results.
New
Select one document to be the external comparison. All other documents shown below will be used to make the model, and will be ranked in order of most to least similar to the comparison document in your results.

Tooltip: 
Original
This option will remove words that only appear once in the set of active files
New
This option will remove words that only appear once in the set of active documents

Displaying String Edits.txt.

**Comment by JingxianL** [comment]
I am not sure about others, but I tried to change letter to character before, and the length wouldn't fit.

**Comment by scottkleinman** [comment]
We have a new document that lays out the changes in a slightly clearer way. We printed out some hard copies yesterday.

I'll have a look at the places where "letter" should become "character" to see what can be done.

**Comment by akuisara** [comment]
I have renamed most terms on GUI, not sure about "Displaying String Edits.txt".

**Comment by mleblanc321** [comment]
"Displaying String Edits.txt"  is a mistake, it shouldn't be there (just ignore)
