### ISSUE TITLE
base error template

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#188]
I am thinking creating a base error template, and all the web page can include that.

basically it will have 2 jinja variable, one is error, another is warning. they are list, that is rendered by python program. If both list is empty, there will be nothing shown, but if there is a warning or error there should be a little icon or something that can represent that it is whether an error or warning.

This will solve the problem that if the culling option accidentally deletes all the word, and some other known error that is not caused by our code. 
And if people trying to do a clustering with raw count, we can render the warning together with the result.

**Comment by chantisnake** [comment]
we can close https://github.com/WheatonCS/Lexos/issues/173 when this is finished

**Comment by mleblanc321** [comment]
this is a good idea;  moses, let's share with the group and then encourage everyone to populate this consistent usage throughout the code ...

**Comment by chantisnake** [comment]
This issue https://github.com/WheatonCS/Lexos/issues/495 covers current issue.
