### ISSUE TITLE
Cut by lines removes all '\n' from text

### ISSUE THREAD

**Issue by gryphonwastler** [WheatonCS/Lexos#192]
The current cut by lines function strips all the new line chars from the text so after the  child lfile object have been created, if you call lfile.numLines() you will always receive a result of one, in addition, when the text gets joined back together, it is joined on '' so it combines the words the end of each line to the first word on the next line which will definitely have an impact on any sort of analysis you try to do.

**Comment by mleblanc321** [comment]
i'm not completely following this ... but i can say that this is tricky;  perhaps we should whiteboard to agree on what we should do?

**Comment by scottkleinman** [comment]
I think what this means is that the main cutting function strips white space, making each segment a single-line string of tokens. Once that takes place, it is no longer possible to cut the resulting segments by line. I'm not sure if the original document is affected (hopefully not).

A rather scary way of dealing with this is if we manage to get non-cut milestones working. Theoretically, we could automatically add line break milestones (which are not counted for statistical purpose) to the documents, commit them to the json index, and then use them to cut by line. I'm not saying that's the best or easiest solution, but it's a possibility.

Why do we want to cut by line? Is it for untagged poetry? For languages written vertically?

**Comment by jaronson13** [comment]
I thought cutByLines() helps build the Lines/Chunk function that is part of the cutter. Isn't it used to cut a segment into however many lines the user desires?

**Comment by gryphonwastler** [comment]
Mark and I fixed this yesterday by finding a splitlines function in the python docs which takes a bool and if its true it keeps the \n chars that it splits on.

**Comment by jaronson13** [comment]
It seems that this does work if you press 'apply cuts', but for previewing it still strips the \n chars and gives you a preview of the concatenated lines. It's probably not a hard fix, and it's not a huge bug either.
