### ISSUE TITLE
let the Silhouette Score Options open by defualt if session is different from defualt

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#193]
if session is different from the default in Silhouette Score Options, let that div open.

default can be found in helper/constant.py :: DEFAULT_HIERARCHICAL_OPTIONS

the value of that option is in session['hierarchyoption']

**Comment by chantisnake** [comment]
same for Advanced K-Means Options

**Comment by akuisara** [comment]
fixed the problem
