### ISSUE TITLE
where should the down load workspace go?

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#194]
I have change the download zip to download workspace, witch is basically zip the whole session folder and the pickled session, but I don't know where on the front end should this function go?

**Comment by scottkleinman** [comment]
That's a good question. We could add it to the options in the "Save" button in the Select menu, but I fear it might not be sufficiently prominent. The only other thing I can think of at the moment is to create a new screen under Manage. This might be a better option because it provides some real estate on the screen to explain what saving a session involves.

**Comment by akuisara** [comment]
I think we can add a download button to each submit div in the templates, so that users can save the workspace on any step

**Comment by austinrg7** [comment]
I think we should include it anytime the user hits a download button.  So if they just cut a file and hit download there would be the folder with all the cut files and a folder with the session so far (maybe with a readme explaining the two folders).

**Comment by akuisara** [comment]
Maybe we can add `Download Workspace` to each page, which can be very similiar to `Download Scrubbed Files` and `Download Cut Files`

**Comment by chantisnake** [comment]
Hi Austin
Workspace is basically a zipfile that contain the whole session folder together with the session. so it is huge, so I don't think that the user should download that every time.

**Comment by chantisnake** [comment]
I am thinking of a button next to the reset, like the in the margin button

**Comment by scottkleinman** [comment]
Moses is thinking of the In the Margins hamburger I demonstrated. There is a very real possibility that the hamburger will not remain the toggle for In the Margins, in which case, that space might be available on every screen.

**Comment by akuisara** [comment]
We have placed the button right next to 'reset'
