### ISSUE TITLE
Re-design of Lexos header title

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#195]
Before release 3.0, we really need to make some changes to the header-title area of the tool. In the past, users have found it confusing (some are not even sure what the tool is called). We should perhaps have a logo (which should include the word "Lexos"). This will have implications for screen real estate which will probably overlap with issue #194.

**Comment by mleblanc321** [comment]
i think i have been blinded by this confusion since i rarely look up there anymore; however, i must say that i really like the way the label changed with each page;  i also like the code-like look of the name, e.g.,
lexo{loader}, lexo{scrubber} etc.  ... would it work to just change the base template to "lexos" rather than "lexo"?  

i too think a small logo would be nice ... but we must be careful;  our look is clean and simple now ... and a logo must not be too loud

**Comment by chantisnake** [comment]
I am not really sure I have understand you correctly.

I think that there is another issue related to this: the event on the header is triggered by mouse over, which is not compatible with touch. I think we should change that.

**Comment by scottkleinman** [comment]
I didn't actually know that there was a mouseover event. Supporting touch may be a challenge. I haven't worried too much about mobile devices since Lexos is really not a tool for the small screen, especially if you can't upload. Things are changing, but I'm not sure we need to completely support touch for the next release.

We might increase the height of the header just a little bit to make for a better logo. I have mixed feelings about the code-like look. I like it, but the whole point of the UI is for users not to have to code. One compromise would be a logo that referenced code: something like {Lexos} (this also gets the full name in there.

I also like the subtitle "An Integrated Workflow". Here are some suggestions. We could move the screen title to the right of it, next to Reset. Or we could have a two line header with the screen title below "{Lexos} An Integrated Workflow" in a smaller font. Or we could make sure that the Legend below the menu consistently indicates a screen title.

**Comment by akuisara** [comment]
I really like the idea of adding a logo. The name inside the braces {} might be confusing, but adding a logo can be helpful. And changing `lexo` to `Lexos` would be an easy fix. 

The mouse over event in the header section is used to display the nested menu while mouse hovering over the `Clustering` label.

**Comment by scottkleinman** [comment]
On the logo, online design tools can provide inspiration. Here's an example.

![logo_sample](https://cloud.githubusercontent.com/assets/1125917/8149077/c531bf70-126c-11e5-96ba-a9fad15bf218.JPG)

**Comment by chantisnake** [comment]
here is my idea of the logo
http://1drv.ms/1G51AST

it looks like some plot on a Cartesian coordinate system, if look closely it is 'Lexos'...

(It should be prettier, but my drawing skill is terrible

**Comment by mleblanc321** [comment]
YALI (Yet Another Logo Idea)
![logo2a](https://cloud.githubusercontent.com/assets/1066011/8150630/b7ffa34c-12be-11e5-8653-e4b7b0a34fc8.jpg)

**Comment by gryphonwastler** [comment]
![lexomicsheader](https://cloud.githubusercontent.com/assets/5599278/8215233/b1f943be-14fc-11e5-920e-56ed12826644.png)

I made one yesterday too. Its a vector files so it will scale to any display size, this is just a png copy.

**Comment by mleblanc321** [comment]
potential;  can you use the same font we are presently using in the header?
i don't think we want OS in a separate color (why highlight OS?  i get why we might
want to highlight "lex")

not to pick (i actually think this has potential) ... but the 0 and 1's background is over-used;
perhaps a rolling-window-like plot of 2 or 3 up-down lines?  or some python source code? (hmmm)

**Comment by gryphonwastler** [comment]
![lexomicsheaderalt1](https://cloud.githubusercontent.com/assets/5599278/8217653/b751dcbc-150c-11e5-8f15-fb04bfa696ab.png)

Made changes based on what you suggested.  I didn't chose to highlight one part of the word over the other, I just picked colors that looked nice.  I grabbed a little chunk of code from /upload in lexos.py and threw it in the background there, It looks nice, but much less identifiable when its squished down to 52px.  I'm not attached to any part of this design in particular. I'll try making some kind of graph plot for the background tonight.

**Comment by gryphonwastler** [comment]
![lexomicsheaderalt2](https://cloud.githubusercontent.com/assets/5599278/8217792/5f57cd90-150d-11e5-99da-32357f066d59.png)

Here's one with lexos all one color.

**Comment by gryphonwastler** [comment]
![screenshot from 2015-06-17 16 28 30](https://cloud.githubusercontent.com/assets/5599278/8217890/e0690eee-150d-11e5-9baf-f19f4099f61e.png)
and here's what it looks like on the actual page.

**Comment by mleblanc321** [comment]
oh good, that helps for review;  i still would like the font to match what we previously had;
Lexos could(should) be lowercase, except for the L (?);  
hmm, the "loader" part can't be in the logo right?  i like the way
we auto load the name of the section we're on;  perhaps the logo could just
stop at Lexos ?  and the {name} could be inserted as with now; this will work ok
if fonts match ... (thanks for working on this)

**Comment by ShiweiJuliaHuang** [comment]
- hi Caleb, what program do you use?

Best,
Shiwei

**Comment by gryphonwastler** [comment]
This header is made out of an svg file, so theoretically, we could hardcode the XML into the base template and use javascript to change the text in-between the {}'s, as well as do what we want with the font and capitalisation.  I don't have the font that we have on lexos available in the program that I used to make this svg.  But I could see if changing the font="" attribute in the xml when it is actually on the webpage would work.  It should?

**Comment by scottkleinman** [comment]
We've done about all the rebranding we can do in the interface for this year. We can start a new issue if we want to do further work in this area.
