### ISSUE TITLE
How Exactly do Lexos handle upload file

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#198]
It seems like the upload is only unloading the file string, which I don't think is compatible with zip archive. I checked request.file after the file is uploaded, and it is always empty. 

But Multicloud can get request.file, and I see the html, there seems to be a line that get this:

 ```
<input type="file" class="multicloud-upload" id="uplodefile" name="optuploadname"/>
```

and also, I try to let the js do not block ````.zip```` and ````.lexos```` file when upload, and fail...

Can someone take a look at this, and fix those 2 problem on the front end?

Thanks

**Comment by gryphonwastler** [comment]
Moses and I worked this out.
