### ISSUE TITLE
Some items in session are rewritten after 'GET' request

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#199]
In lexos.py, when GET requests are made `(request.method == "GET")`, some existing elements would be overwritten. For example, rwadatagenerated is always set to False when page is reloaded `(session['rwadatagenerated'] = False)`, this situation happens to all the routes with such GET request and session storing method. I wonder how much data we want to cache in session.

**Comment by chantisnake** [comment]
I saw that code, and just at the top of my head I don't think that is necessary. We might need to chase that down and optimize that 

(I think at least we can replace them with ````request.form[]````)

**Comment by mleblanc321** [comment]
session['rwadatagenerated'] ??
caleb: what is boolean flag for?  (can you track this down and determine why we were resetting this to False in lexos.py for rwa GET but True in rwa POST? )

**Comment by chantisnake** [comment]
This seems to use in the template to determine whether to display that part.

```
{% endblock %}

{% block results %}
{% if session['rwadatagenerated'] %}
<div id="rwagraphlabel">{{graphTitle}}</div>
<div id="rwagraphdiv" class="hidden">{{ session['rwadatagenerated'] }}</div> 
<label>Download:</label>
<input type="submit" class="bttn bttn-action" id="generateRWmatrix" name="get-RW-plot" value="Graph Data"/>
<input type="submit" class="bttn bttn-action" id="generateRWmatrix" name="get-RW-data" value="CSV Matrix"/>
<div class="bttn bttn-action" id="svg-Chrome" href="#">SVG (Chrome)</div>
<a id="svg-Other" href="#" target="_blank">SVG (other browsers)</a>

<div id="rwagraphdiv" class="infobox">
	<p></p>
</div>
{% endif %}
{% endblock %}
```

**Comment by akuisara** [comment]
Fixed it
