### ISSUE TITLE
select page behaving odd with Chinese files

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#200]
The preview for some of the Chinese files are not showing up, but we could still get them from the context menu. Also when the preview is too long, the selecting of files might get weird (might get a double post, or not select the right file).

**Comment by scottkleinman** [comment]
I'll look into this as soon as I can. Which Chinese files were you using?

Also, can you clarify the second part of the issue? Is the problem in the Extract column of the table? It should clip the preview at 155 characters, but maybe it is treating Chinese differently?

**Comment by austinrg7** [comment]
We uploaded all the files in the modern Chinese folder inside the test suite.  The following have weird/missing previews (end of file names given):

1.  Fog (One char in preview)
2.  Autumn (One char in preview)
3.  Spring (missing)
4.  Wolves (missing)
5.  Opera (missing)
6.  Body (one number in preview)

The second part: Chinese characters are "taller" than English characters.  As such the rows for the Chinese files are wider than the rows for English files (or Chinese files without a preview).  This can cause some weird behavior when using click to select/deselect files.

**Comment by scottkleinman** [comment]
I see the problem. Everyone seemed agreed that the 50px height for the rows was nice, but we didn't test with Chinese. I'll check whether a simple modification of the CSS does the trick. The previews may be a bit more difficult. Right now, they are the text that is passed through Jinja, which I then clip at 155 characters. With any luck, I just need to encode the string. I'm not sure why different texts are behaving differently. I'll see if I can tackle this on the plane tomorrow.

**Comment by austinrg7** [comment]
We ran the same test on the live site and while the preview behavior was the same the click events functioned normally.

**Comment by scottkleinman** [comment]
Using the Jinja truncate filter to drop the last word does not work for Chinese texts. I set it to truncate at exactly 155 characters. This still makes the rows larger than 50px, but they are even. We can consider reducing the number of characters to get the row height closer to 50px if people don't like it. Let me know if you are still encountering issues with selecting and deselecting Chinese texts.

**Comment by JingxianL** [comment]
Moses opened a new issue that is related to this, I think the height for the preview is now fine, so I close this one.
