### ISSUE TITLE
Select All/Deselect All

### ISSUE THREAD

**Issue by austinrg7** [WheatonCS/Lexos#201]
Select all and deselect all only work on the page of the table being viewed.  So if you have 50 segments, but are only displaying 25 in the table, the last 25 will not get the select/deselect applied to them.

**Comment by scottkleinman** [comment]
I didn't think to check that, but it makes sense. Those buttons are pre-set in the DataTables code. I'll change them so that they just call the same functions as the links in the context menu.

**Comment by austinrg7** [comment]
This is a ui issue.  All files get selected/deselected in fileManager, but for example on deselection the rows not on the current page remain green (even though they really are disabled).

**Comment by scottkleinman** [comment]
I've pushed a fix. If it tests all right for you, go ahead and close this issue. The commit history should show you where the changes are if you want to fix the bug on the server.

**Comment by mleblanc321** [comment]
i won't try to make the changes on the server (until i return to the lab);  jingxian and austin: since you first noticed this, can you test to confirm that scott's patch is sufficient?

**Comment by JingxianL** [comment]
I think this is fixed. So I will close this issue.
