### ISSUE TITLE
WorkSpace is significantly larger than the original file

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#204]
we store file content inside a folder and we store them also in filemanager, this is not efficient.

now the upload and download workspace is fully implemented, the file size is always larger than 4MB

**Comment by chantisnake** [comment]
turns out it do not save the file string. I will investigate on why the file is so large

**Comment by scottkleinman** [comment]
We knew this was going to happen. Perhaps we should lift the file size restriction and have the message state that it is best to use files under 4MB over the internet, except for zipped workspace files. We have to change the label anyway.

**Comment by JingxianL** [comment]
I don't think the local progress for loading a over 4mb zip will be really slow. But I am not sure about how the process will be over on the internet.

**Comment by chantisnake** [comment]
This is fixed last year. I don't know why we did not close this...

Workspace also need to be able to upload if we have many large file in the workspace.
