### ISSUE TITLE
Tokenizer questions

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#205]
* Should the default normalisation for generating a matrix in Tokenizer be raw counts? I think that's what people will most likely want to see first.
* Do you have to generate a DTM before you download it? I found that *Pride and Prejudice* froze my browser for quite some time before the table generated. It may be easier to allow the user to download and then open in Excel. Alternatively, we could try to implement one of the [DataTables Scroll functions](https://datatables.net/extensions/scroller/examples).
* Should "Frequency Matrix Options" be "Document-Term Matrix Options"?

**Comment by mleblanc321** [comment]
>default normalisation for generating a matrix in Tokenizer be raw counts
the assumption was that segments would typically be of unlike sizes, therefore, proportions is the better default (especially for teaching new users to be careful on this point); however, i'm open on this one and could go either way;

>do you have to generate a DTM before you download it?
hmmm, i got the Save dialog ... but Lexos (macBook localhost) is still showing a spinner ... (so i guess we have a bug here?)

>Should "Frequency Matrix Options" be "Document-Term Matrix Options"?
yes

**Comment by JingxianL** [comment]
I don't think you have to click the generate button before you do the download. And I fixed the problem with the spinner.

**Comment by akuisara** [comment]
- The normalization section is extended from base_analyze.html, so switching the default to raw counts would change the default value for all the analyze pages.
- I believe the second question should be fixed already
- I have changed the option title on GUI

**Comment by scottkleinman** [comment]
I think we might want to reconsider the default normalisation in Tokenise, just because it generates a table that the user can see. But I understand the technical problem, so this is pretty low priority at the moment.
