### ISSUE TITLE
Usability issues in WordCloud, MultiCloud, and BubblViz

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#206]
The new check box document selection interface integrates nicely with the look of Lexos. But what if the user has 1000 documents and wants to generate a word cloud which includes all of them? What we really need is a select menu that allows you to shift-click to select ranges. We probably need something like [ShiftCheckbox](http://nylen.github.io/shiftcheckbox/) or [finderSelect](http://evulse.github.io/finderSelect/) (which I considered using for the Select screen).

**Comment by gryphonwastler** [comment]
I just worked out how to make a simple select all checkbox on word cloud, which helps (not pushed yet).  I was thinking if instead of select all, if we did toggle all instead this might be (more?) useful? (when you click the button it flips the state of all the checkboxes, so you chose the ones you don't want to analyse out of your 1000 docs, and then hit toggle all)  I'll also try and work on some sort of multiselect function.  Should I wait to do multi select until I put the select box on all of the pages?  Also, should the select all box be inside the scrolling div or above it so its always visible(as long as there are active files)?

**Comment by scottkleinman** [comment]
I think "Select All" and "Deselect All" button will be more intuitive for our users than "Toggle All", even if the latter is more streamlined. But this functionality should be included. I still think it is important to be able to select ranges by shift-clicking.

I'm not sure I can answer the second question until I have a better idea of your implementation. Are you using either of the ShiftCheckbox or finderSelect scripts that I mentioned?

**Comment by gryphonwastler** [comment]
I've been trying to get the shiftCheckbox to work; however, I'm not really sure if I have the JQuery experience to make it work.  I actually had not written any JavaScript ever prior to coming to Lexos and I'm afraid that I just don't understand enough about the jquery object and so I'm not putting things in the right place to make them work.  I can keep working on it, but it will probably get done faster if I handed if off to someone who's actually taken a webdev course, or who has made a project before with JQuery.

**Comment by gryphonwastler** [comment]
The problem I'm running into is that when I'm in the browser, if I hold down the shift key I cannot select a checkbox, regardless of whether or not there is an event listener bound to the checkbox.  This is true on all of the pages in lexos, I'm not really sure what's going on but I'll keep looking.

**Comment by scottkleinman** [comment]
Hmmm... If you can't figure it out, I'll try to have a look at it tomorrow when I do a pull.

**Comment by gryphonwastler** [comment]
I've implemented a drag select lasso which will flip the state of all the checkboxes within the selection range using the .selectable() attribute.  Honestly, this in combination with a select all toggle should be enough?  if someone has 1000 files that they are working with, they aren't going to want to do all of that selecting and deselecting in that tiny box, they should go to the select page and choose the active files they will want to analyse, right?

**Comment by scottkleinman** [comment]
Yes, I think that's right. `selectable()` is what I implemented in the Select menu, so that provides a unified solution across the tools.

**Comment by gryphonwastler** [comment]
I figured out how to tweak it to do both drag and shift click!!  I got it working on word cloud. I'll push so you can see the code and I'll implement it on the rest of the pages by the end of tomorrow.

**Comment by gryphonwastler** [comment]
Finally all done and pushed.

**Comment by ShiweiJuliaHuang** [comment]
If my righthand bar is on the top, multi cloud bar cannot move. I am using Chrome. 

![wordcloud](https://cloud.githubusercontent.com/assets/11905193/8268361/2fc00188-1751-11e5-9c9b-ec1345b20d05.png)
