### ISSUE TITLE
moving to json rather than pickle:  profiling lexos

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#209]
branching off issue #155 ...
i've just finished a preliminary profiling of lexos;  pickle is our enemy!  we must start using json

e.g.,  the time to upload and scrub mobydict.txt was spent almost entirely in pickle.load and pickle.dump :(
(scott mentioned this before; he's right; ...  but now we must make the switch)

see good article on profiling from within flask
http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-debugging-testing-and-profiling

see the good article on using json vs. pickle
http://www.bogotobogo.com/python/python_serialization_pickle_json.php

i don't quite have this working yet ... but here is where i am focusing so far ...

#constants.py

# session.py
import json
import codecs

def loadFileManager():
    managerFilePath = os.path.join(session_folder(), constants.FILEMANAGER_FILENAME)
    #fileManager = pickle.load(open(managerFilePath, 'rb'))
    fileManager = json.load( codecs.open(managerFilePath, encoding="utf-8") )

def saveFileManager(fileManager):
    managerFilePath = os.path.join(session_folder(), constants.FILEMANAGER_FILENAME)
    #pickle.dump(fileManager, open(managerFilePath, 'wb'))
    json.dump(fileManager, open(managerFilePath, 'w'))

**Comment by chantisnake** [comment]
I have worked on pickeling session, so I know where that is.

I will take that.

**Comment by chantisnake** [comment]
json can only dump build in type. we need to convert all of them into dictionary in order to dump.

since python build class using dict, that will not be hard, but loading need some effort.

**Comment by scottkleinman** [comment]
Also, watch out for tuples in the current code--json doesn't accept them. But, as Moses says, you can turn them into dictionaries (or lists, as appropriate).

After what we've accomplished this summer, I was going to let the pickle to json item on the road map rest for a while. But it looks like we should move it back up.

**Comment by mleblanc321** [comment]
yup, pickle to json is now a priority;  we've got to speed this thing up on the load/save ... then we can zoom in on other methods using the flask profiler (which makes good dumps to the debug-console);
again ...
see good article on profiling from within flask
http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-debugging-testing-and-profiling

**Comment by chantisnake** [comment]
well, tuple is not build with dict, so that is a problem.
for filemanager we can ````json.dump(filemanager.__dict__)```` but if there is a variable has tuple, we are pretty much stuck (which I am now.)

I begin thinking that this may not be a good idea.

I think we need to do the stress testing on the DTM loading and saving. I am kind of sure that is what slowing all of them down.

**Comment by chantisnake** [comment]
I have do some testing on loading filemanager.
this when I upload 4 chinese file and do tokenize with all the option as defualt

------
#### with matrix
##### filemanager.p file size:
14.3MB
##### time
take -0.000943899154663 to load fileManager
take -0.00562906265259 to load fileManager
take -1.8527572155 to load fileManager
take -1.17583799362 to load fileManager
take -1.11729598045 to load fileManager

-------

#### with out matrix
##### filemanager.p file size:
12.6 kB
##### time
take -0.00248193740845 to load fileManager
take -0.00253200531006 to load fileManager
take -0.000662803649902 to load fileManager
take -0.000606060028076 to load fileManager
take -0.00286102294922 to load fileManager
take -0.00110101699829 to load fileManager

**Comment by chantisnake** [comment]
### profile
this is the profile when you upload all the Modern Chinese file (this is the most stressful case for matrix)

##### without matrix
load filemanager takes0.00133609771729 seconds
load matrix option takes 4.88758087158e-05 seconds
get matrix takes 2.85950088501 seconds

load filemanager takes0.00164914131165seconds
load matrix option takes5.79357147217e-05seconds
get matrix takes 2.82357096672seconds

load filemanager takes 0.00161290168762 seconds
load matrix option takes 6.29425048828e-05 seconds
get matrix takes 2.89263701439 seconds


---

##### with matrix
//first time
load filemanager takes 0.00540590286255 seconds
load matrix option takes 4.72068786621e-05 seconds
get matrix takes 2.85316205025 seconds
//first time

load filemanager takes 4.81610393524 seconds
load matrix option takes 3.981590271e-05 seconds

load filemanager takes 5.24717020988 seconds
load matrix option takes 4.10079956055e-05 seconds

load filemanager takes 5.27949285507 seconds
load matrix option takes 4.10079956055e-05 seconds

**Comment by chantisnake** [comment]
### Profile 2
this time I upload 5 small Middle English text to simulate the normal usage of the Lexos


##### With Matrix
workspace size: 953 KB

// first time
load filemanager takes 0.00472712516785 seconds
load matrix option takes 0.000114917755127 seconds
get matrix takes 0.141049146652 seconds
save filemanager takes 0.5060338974 seconds
total: 0.651925 second
// first time

load filemanager takes 0.463200807571 seconds
load matrix option takes 4.6968460083e-05 seconds
save filemanager takes 0.450832128525 seconds
total: 0.91408 second

load filemanager takes 0.547954797745 seconds
load matrix option takes 4.60147857666e-05 seconds
get matrix takes 0.127177000046 seconds
save filemanager takes 0.445229053497 seconds
total: 0.91408

load filemanager takes 0.0909790992737 seconds
load matrix option takes 3.91006469727e-05 seconds
get matrix takes 0.11242389679 seconds
save filemanager takes 0.122905015945 seconds
total: 0.213923



---

#### without matrix
workspace size: 208 KB

load filemanager takes 0.00244498252869 seconds
load matrix option takes 4.41074371338e-05 seconds
get matrix takes 0.122187852859 seconds
save filemanager takes 0.00191879272461 seconds
total: 0.126596 seconds

load filemanager takes 0.00055718421936 seconds
load matrix option takes 3.88622283936e-05 seconds
get matrix takes 0.107752084732 seconds
save filemanager takes 0.00065016746521 seconds
total: 0.108998 seconds

load filemanager takes 0.000890016555786 seconds
load matrix option takes 4.19616699219e-05 seconds
get matrix takes 0.114856004715 seconds
save filemanager takes 0.00173497200012 seconds
total: 0.117523 seconds

**Comment by chantisnake** [comment]
the total of ````profile 2 - with matrix```` do not take account of the time to generate matrix

I have no idea what happened on the last time ````profile 2 - with matrix````, and why loading and saving takes so little time.

No matter what, the speed of ````without matrix```` crash the speed of  ````with matrix```` and also the workspace size

I see no reason in leaving ````self.existingMatrix```` in ````FileManager````

**Comment by mleblanc321** [comment]
yesterday in lab moses and i confirmed that
(a) we cannot directly convert our Python objects (FileManage, LexosFile) to JSON
(b) using __dict__ we can force it (but not an elegant solution)

our course of action is the following:
*short term -- we stay with pickle, but we remove the DTM from the filemanager (the profiler confirms that it doesn't take long to make a DTM;  when saving (and re-uploading) a session, we can save the attributes that were used to produce a previous run and use those to recreate the DTM;  not saving the DTM makes good sense for now)

*longer term -- we investigate JSONpickle and/or massaging our Python objects into (all) built-in types so we can convert to JSON
