### ISSUE TITLE
In the Margins Integration

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#210]
In your next pull, you should get In the Margins fully integrated into Lexos. Right now, content is automatically loaded from [Scalar](http://scalar.usc.edu/works/lexos/index) in the left panel, which can be toggled using the hamburger icon next to the Reset button.

I've included some sample "hooks" below the footer. (Don't worry, I'll remove them once everybody sees how it works.) One button opens the [Best Practices page] (http://scalar.usc.edu/works/lexos/best-practices) and the other opens the YouTube video in the [How to Read a Dendrogram page](http://scalar.usc.edu/works/lexos/how-to-read-a-dendrogram).

To insert a hook into Lexos, just add some attributes to the trigger element (I'll use a div for the examples below):

```HTML
<div class="ITMtrigger dialog" data-slug="best-practices">Call an ITM Page</div>
<div class="ITMtrigger video-dialog" data-slug="how-to-read-a-dendrogram">Call an ITM Video</div>
```
So `ITMtrigger dialog` or `ITMtrigger video-dialog` in the class attribute and the Scalar slug (the end of the url) for the desired Scalar page in the data-slug attribute. Obviously, these pages have to exist in the Scalar site.

Each Lexos screen should call a Scalar page, so we need to create them. Until we do, I have put the hook for the ITM panel in base.html by adding `data-slug="{{ itm }}"` to `<span id="titleprefix">`. The `itm` variable is the slug passed from Lexos.py. Eventually, we'll want to add `itm=SLUG` for each screen.

Further down the road, we'll be able to link to ITM from tooltips or even display ITM content in tooltips. But for this we need to follow up on Moses' suggestion of a persistent tooltip that doesn't disappear when you mouseover it. I have a primitive version working, but I didn't push it since I think I can enhance it.

Questions? Comments?

**Comment by gryphonwastler** [comment]
Hey, looks great.  The only thing I've seen so far is a small issue, if the itm page has enough content that it gets a scroll bar, if you open then close in the margins, the scroll bar does not get moved off the page. This is probably a easy adjustment.

**Comment by scottkleinman** [comment]
Apart from issue #233, it seems that the ITM integration works. The scroll bar issue is nothing to worry about since this was not intended to be the final styling of the interface. So I think we can close this issue.
