### ISSUE TITLE
Another select bug

### ISSUE THREAD

**Issue by austinrg7** [WheatonCS/Lexos#211]
If you upload a document then re-upload that document, select changes the second document to copy of + the first document name.  If you then delete the copy of document using delete document on the select page and refresh the page, both the copy of and the original document get deleted.  The ui does not reflect this until the page is refreshed.

**Comment by scottkleinman** [comment]
I'm in the middle of a massive overhaul of the Select page functions, so I'll take that into account.

**Comment by chantisnake** [comment]
are you sure this is the select pages problem? did you track the post request?

**Comment by chantisnake** [comment]
I have see that the post is correct, this is more likely to be a back-end problem than a select problem

**Comment by scottkleinman** [comment]
Yes, I think you are probably right. I'm still working out the front end, but I'll chase this up when I'm done.

**Comment by chantisnake** [comment]
'''
def deleteOneFile(self):
        """
        Deletes every active file by calling the delete method on the LexosFile object before removing it
        from the dictionary.

        Args:
            None.

        Returns:
            None.
        """
        for fileID, lFile in self.files.items():
            lFile.cleanAndDelete()
            del self.files[fileID]  # Delete the entry
'''
this function is called when delete a document
despite it says "delete one", it deletes all, so no matter what you upload, as long as you delete one file, all the file will be deleted
