### ISSUE TITLE
required reading

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#214]
https://wiki.python.org/moin/PythonSpeed/PerformanceTips

**Comment by mleblanc321** [comment]
we made good progress today on speed up ... and learned some good tips about
what not to do with large strings in Python (e.g., when making a huge table);  sara will push new tokenizer code soon (and it is here where we can reference how to handle large strings, such as not using concatenation, append, etc);  again, see the URL referenced above ...

** just a wonderful six hours of work on a saturday afternoon ... **  (thanks software crew)

**Comment by chantisnake** [comment]
I did some reading on efficiency of python, it seems like numpy array operation can be up to 200x faster than the python array, and it has lot more useful functionality than python array. 
For example it can generate a CSV or tsv just in one line. And most scipy function take numpy array naturally.
So, I am thinking probably if lexos is going to be a enterprise oriented power tool, there maybe a lot more optimization we can do on our code.

**Comment by mleblanc321** [comment]
yes, true; however, at this point i am calling a halt to major overhauls (e.g., changes in data structures);
from here until we finish on July 3, we are in stabilized-mode: that is, we fix select, we finish the speed-up obtained on tokenize, we tighten existing tools (and any new functionality and/or changes should be in (future) development);

i am about to create an issue explaining the plan from here until the end of the summer ...

**Comment by mleblanc321** [comment]
just bumping this Issue back on the 2do list (for Summer 2016)

**Comment by chantisnake** [comment]
and where is the 2do list for summer 2016?

**Comment by chantisnake** [comment]
Maybe put this in the same place as my git intro.

**Comment by scottkleinman** [comment]
All links have been moved to the Developer's Guide.
