### ISSUE TITLE
I will change the file structure of Lexos

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#217]
as mentioned in issue  #215, I will change the file structure of Lexos at 6pm today, this process will take approximately less than half an hour. 

---

before 6pm **PLEASE**:
* push all your changes to github (especially back-end)

during this time, **PLEASE DO NOT**:
* push anything to github
* edit any thing in Lexos on your local machine

after this time **PLEASE**:
* pull after you apply any changes in Lexos on your local machine.

otherwise there will be serious merge conflict, and the auto-merge will do weird things and cause bugs.

---

#### Please reply when you have read this issue

I will update this issue and close it when I am finished

**Comment by chantisnake** [comment]
please notice: ** I have changed the time to 6pm **

**Comment by ShiweiJuliaHuang** [comment]
Ok

Best,
Shiwei

**Comment by chantisnake** [comment]
I just finish the local install on my laptop. Do anyone want me to wait until they push?

I will start working in 10 mins.

**Comment by chantisnake** [comment]
After minor testing, I have pushed this version to the master. I will continue to refine the back-end code.

a lot of the code are not following the standard.
