### ISSUE TITLE
Does additional option on scrub has to be hidden

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#218]
I find out that if you do not have any file active and click on the arrow next to additional option,  the whole page will be shifting right and left and couldn't figure out why. I am wondering do we have to have a arrow to hide the additional options? I think it is nice to hide each option and just show the title, but I don't see the point of hiding all the additional options.

**Comment by gryphonwastler** [comment]
I also don't think that we need that arrow there.  It would make more sense if it were closed by default when you come to the page, but those options are too commonly used (especially the special chars option) so it shouldn't be closed by default.

**Comment by akuisara** [comment]
This issue has already been fixed
