### ISSUE TITLE
Scroll on Tokenizer Table

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#219]
I discovered that on the data table for tokenize page, the title row has the bottom border not all one line. the "token" and "raw total"'s border is little bit below the border of the middle cells. 

Also, if you have more than one page of the table, going to next page will have the scroll bar going up and down. I think if the bar could always go to the top of the page when you get to another page would be better.

**Comment by akuisara** [comment]
Fixed the problem, see 933106f
