### ISSUE TITLE
Tokenizer error message blocking menu

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#220]
If you try to generate a matrix table in Tokenizer without any files selected, the error "You must have active documents to proceed!" appears right below the Manage menu and effectively blocks access to that menu so that you cannot navigate to Select. This might just need a change to the CSS z-index, but may I recommend that we move the error message to a JQuery UI dialog?

**Comment by JingxianL** [comment]
I think Sara fixed this problem, may be repull and check if it still happens.

**Comment by scottkleinman** [comment]
No change, I'm afraid. I have discovered that JQuery UI is not working on that page. There's no error calling the library, but the console displays a function not found error whenever I try to call a JQuery UI function.

**Comment by scottkleinman** [comment]
OK, it appears that JQuery was being loaded a second time in tokenize.html. I've put in a preliminary error message in a JQuery UI dialog. It's not particularly pretty, so feel free to change it. But as long as you don't revert to the original code (which I've commented out), this issue is fixed (with the issue of JQuery UI not working the page thrown in as a bonus).
