### ISSUE TITLE
Cosmetic Enhancements to Similarity Query

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#227]
I have switched the rankings table in Similarity Query to TidyTable. This adds some nice styling and the ability to sort the table by column (click on the column headers). I've also displayed the blue loading icon when the user clicks the Get Similarity Rankings button, since it can take a while for the table to render. If everybody likes these changes (I commented out old code, rather than deleting it), I'll close this issue.

**Comment by mleblanc321** [comment]
can we close this?

**Comment by scottkleinman** [comment]
I think we can do this in the context of Bootstrap conversion and implementing faster back end code.
