### ISSUE TITLE
BubbleViz tooltips

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#230]
Getting tooltips to display in the right location relative to their bubbles was always difficult, but it appears that some of the new styling or the new Select checkboxes has thrown them off. We need to take another look.

**Comment by scottkleinman** [comment]
I have a fix for this working, but it requires qTip2. See issue #235. If we adopt qTip2, we can probably also do better tooltips in Word Cloud, Multicloud, and other d3 visualisations.

**Comment by mleblanc321** [comment]
we should try another page with a number of tool tips; once we do a couple we'll have a good feel of if we want to replace all of them (sounds/looks good)

**Comment by scottkleinman** [comment]
I've pushed the changes. If we decide not to go with qTip2 for some reason, we can re-open this issue.
