### ISSUE TITLE
Multicloud has nonintuitive radio buttons

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#231]
The radio button for Select a Document in Multicloud is in a funny location. It seems that the radio buttons are necessary for file management on the back end, but perhaps we can make a visibility toggle between the two options so that the user knows that he or she has a choice (and also does not forget to select a button).

**Comment by akuisara** [comment]
Hey @scottkleinman I have changed those nonintuitive radio buttons on Multicloud page, please let me know if you have any comments. Thanks!

**Comment by scottkleinman** [comment]
It looks like you were using the toggle option, but this is what the page looked like to me on load (I pulled right before testing):
![multicloudcapture](https://cloud.githubusercontent.com/assets/1125917/8459178/486b4b48-1fd0-11e5-8eb9-478b870ef726.JPG)

**Comment by akuisara** [comment]
I think this layout issue can be resolved by hard refresh...

**Comment by scottkleinman** [comment]
You're right. That worked.

So here are some changes. I think the toggle should read "Document Clouds || Topic Clouds", and it should have a tooltip explaining these options. I have just added the tooltip, so please pull again to see what I mean. It will need some styling to get it in the right location.

In addition, it would be clearer if the `multicloud-selection` and `multicloud-upload` fieldsets were shown or hidden based on the state of the toggle.

I also think that the location of the toggle should be moved. See the following illustration:
![multicloudcapture](https://cloud.githubusercontent.com/assets/1125917/8459489/7689e7c6-1fd2-11e5-9698-ed8d3f06867b.JPG)

**Comment by akuisara** [comment]
Just did the changes. How do you like the new style of this page?

**Comment by scottkleinman** [comment]
That looks great. The only problem (very minor) is that clicking the tooltip icon actually triggers the toggle button. But that doesn't need to be fixed immediately. It's even potentially useful.
