### ISSUE TITLE
Browser spend a lot of time connecting to Scalar

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#233]
originally I think that this is because of the browser, so I killed it, restart lexos, even restart my computer, it still takes a long time to connect.

It is still trying to connect, and it has already taken couple of minutes. Can we set a time out value or something? and keep a local copy in this program, if time out, just send the local copy.

@scottkleinman

**Comment by scottkleinman** [comment]
For the last 24 hours I have been experiencing slow download times from Scalar, so I think the problem is on their server. For development, we might want to comment out the call to their API in base.html.

But this is a problem I am worried about more generally. I'll look into calling the API based on an event (such as opening the In the Margins panel), rather than pre-loading it in the page. I don't think we can store a local version because it functions as a proxy to get around cross-domain issues.

**Comment by mleblanc321** [comment]
Not unexpected, we have been agile by being modular ... But also a test
cost, so yes to hiding ITM for now

Greetings from new range in Maine woods
m

On Friday, June 26, 2015, scottkleinman <notifications@github.com> wrote:

> For the last 24 hours I have been experiencing slow download times from
> Scalar, so I think the problem is on their server. For development, we
> might want to comment out the call to their API in base.html.
>
> But this is a problem I am worried about more generally. I'll look into
> calling the API based on an event (such as opening the In the Margins
> panel), rather than pre-loading it in the page. I don't think we can store
> a local version because it functions as a proxy to get around cross-domain
> issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/233#issuecomment-115804068>.
>


-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by scottkleinman** [comment]
We will probably comment out the whole ITM apparatus for the upcoming release since we don't have ITM content yet (although I'm working on it).

Hope you caught lots of fish, Mark.

**Comment by mleblanc321** [comment]
Catching ... Found some wifi in jackman, Maine

On Friday, June 26, 2015, scottkleinman <notifications@github.com> wrote:

> We will probably comment out the whole ITM apparatus for the upcoming
> release since we don't have ITM content yet (although I'm working on it).
>
> Hope you caught lots of fish, Mark.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/233#issuecomment-115808968>.
>


-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by scottkleinman** [comment]
I have determined that it *is* possible to store the Scalar script locally. I've also set it up to load by Ajax when you first come to Lexos and then cache in the browser. The changes will come with my next push.

This will need a second look somewhere down the line when we have more ITM content, but for now I think we can close this issue.

**Comment by mleblanc321** [comment]
we should leave an easter-egg somewhere for ITM demo

**Comment by scottkleinman** [comment]
We could leave the hamburger and have it open some specialised content. But, if we grab it from Scalar, that might give the user access to all our draft material before it's ready, so we have to be able to grab some material without links internal to the ITM site. Should be possible.

**Comment by mleblanc321** [comment]
>so we have to be able to grab some material without links internal to the ITM site. Should be possible

exactly.  (but i'm not sure about hamburger; seems too much like a UI mistake to leave there to do just that);  (just thinking out loud here ...[typing from Maine, just outta the woods])

**Comment by scottkleinman** [comment]
Another possibility is a simple link at the bottom of the page.

**Comment by mleblanc321** [comment]
i'd be fine with that;  it might depend on how much we want to show (foreshadow) as to where ...

**Comment by chantisnake** [comment]
No longer relevant
