### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#234]
* Scub Issue
  * there will be errors if the `Special Characters` on scrub are not appropriately chosen (we probably need to raise a warning, if we know that they are not doing it correctly)

* MultiCloud Issue
  *  the radio button on multicloud is not intuitive 
  * MultiCloud and BubbleViz still proceed if there is no file active or selected, it will give a graph of all the active file.
  * MultiCloud sometimes give an error indicate that the topic file do not exists, I have encounter this several times, but cannot replicate

* Statistic Issue
  * statistic crashes when no document selected
     * [solved]
  * statistic crashes with a `bad request` if there is no file active
     * [solved]

* Similarity Issue
  * similarity crash when only one-file active
     * [solved]
  * similarity crash when one of the file is empty
    * [solved] commit 08ee0592946586733d397dd5ad96cbb3a61d2e94, solution is not pretty at all
  * similarity give a bad request if there is no file active
     * [solved]
  * similarity return unexpected result when using `debugsuit/smallfile_repeat`
    * [solved] change the indentation of `similarity.py`'s last line from a `tab` indent to 4 spaces commit bd2dda01714b36bf0b3cd8a7ff2cd8412623eaaf

* TopWord Issue
  * topwords give unexpected result when there is only one word in the document
    * [solved] because z-test cannot handle the file with only 1 word, and will return 'Insignificant'.
  * topwords test for class crash when there are only 1 class.
     * [solved]

* WorkSpace Issue
  * for 100 `les_misra`, the front-end of the upload do not indicate that the file is uploaded, but the back-end works properly, and if you move to other page, you can proceed normally

* General Issue
  * `KeyError: 'id'` This happens on local machine very often even we don't have 2 lexos open on the same time.
  * spinning icon exists even if error message pop up
     * [solved]
  * jquery error message pop-up are behind of the block `submit`
     * [solved]
  * when there is no file active some page will have `You must have active files to proceed. Please select one or more files on the Select screen.` pop up, with a header `<span id="ui-id-2" class="ui-dialog-title"><span class="ui-icon ui-icon-alert"></span> Error!</span>`(this is what displayed on the webpage)
     * [solved]
    * scrub, tokenizer, top-word only have pop-up 
    * cut, k-mean has the pop-up and the red error message
    * rolling window, word cloud, multicloud, bubbleviz, dendrogram only have red error message
    * similarity has the pop-up and crash with a `bad request`

**Comment by austinrg7** [comment]
"Statistic crashes when no document selected"

Have you tested that recently?  I'm fairly certain I fixed that some time earlier this week.  Unless you are talking about the select part of the statistics page.

**Comment by chantisnake** [comment]
This is the result I test today. 
I am talking about if on `Select a File` section, you deselect all.

**Comment by austinrg7** [comment]
Okay I mostly just  copied that code from the multicloud and wordcloud.  I made some modifications, but if the problem is on the select/deselect all it probably applies to those pages as well.

**Comment by scottkleinman** [comment]
It's apparently just on the Statistics page. It works on the other pages.

**Comment by chantisnake** [comment]
I think just on select page is because that select page require there is one file, on multicloud and bubbleviz, there are no protection on no file selected as well, it is just that the program do not require you have one file to proceed.

**Comment by akuisara** [comment]
in terms of the issue
`when there is no file active some page will have You must have active files to proceed. Please select one or more files on the Select screen. pop up, with a header <span id="ui-id-2" class="ui-dialog-title"><span class="ui-icon ui-icon-alert"></span> Error!</span>(this is what displayed on the webpage) `
The loading icon wouldn't disappear when the pop up is closed

**Comment by scottkleinman** [comment]
I've fixed this. It will go out with my next push.

**Comment by JingxianL** [comment]
I just realize that we have duplicated the error message showing on all most every page with both the dialog box and the flashing errors. Also, on some of the page the loading icon isn't working correctly and some are. I don't think it is an good idea to have the pop up error messages everywhere, also with the loading icon spinning in the back. Also I think Mark doesn't really like the pop up error messages. @mleblanc321 
Also, I am not sure who made any changes in the similarity page on the front end or back end. But now the page only show one file in the table. It was working "properly" last Wednesday.

**Comment by akuisara** [comment]
This is how the dialog looks like on my Linux machine:
 ![screenshot from 2015-06-29 12 00 23](https://cloud.githubusercontent.com/assets/4997873/8412266/b7f80ea4-1e56-11e5-9dde-ed7fd4917d70.png)

**Comment by mleblanc321** [comment]
Hmmm...jingxian, please try to track these ... Thx

On Monday, June 29, 2015, Jingxian Liu <notifications@github.com> wrote:

> I just realize that we have duplicated the error message showing on all
> most every page with both the dialog box and the flashing errors. Also, on
> some of the page the loading icon isn't working correctly and some are. I
> don't think it is an good idea to have the pop up error messages
> everywhere, also with the loading icon spinning in the back. Also I think
> Mark doesn't really like the pop up error messages. @mleblanc321
> <https://github.com/mleblanc321>
> Also, I am not sure who made any changes in the similarity page on the
> front end or back end. But now the page only show one file in the table. It
> was working "properly" last Wednesday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/234#issuecomment-116741932>.
>


-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by scottkleinman** [comment]
On your next pull, the loading icon should disappear when the error message pops up. If you could tell us which pages the error message occurs on, we can fix it more easily.

**Comment by chantisnake** [comment]
this error appear not only on tokinzer page. the pop up seems to be behind the submit div

**Comment by JingxianL** [comment]
Also, I still don't think it is an good idea for an loading icon to be on base.html, it is messing up on a lot of pages, some of them have two icons on the same page, and some of them are not the same size.

**Comment by mleblanc321** [comment]
What is the better location?

On Monday, June 29, 2015, Jingxian Liu <notifications@github.com> wrote:

> Also, I still don't think it is an good idea for an loading icon to be on
> base.html, it is messing up on a lot of pages, some of them have two icons
> on the same page, and some of them are not the same size.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/234#issuecomment-116796069>.
>


-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by scottkleinman** [comment]
Part of the problem is that we have two icons. One is in `<div id="status">` and one is in `<div id="prepare-status">`. There are also a couple of divs for In the Margins components. As long as only one loading icon is invoked by a function, there shouldn't be problem. The idea behind the `<div id="status">` div being in `base.html` is that there is a basic black loading icon of a relatively small size. It is invoked by all the In the Margins components (and is sized to fit in them). It can also be used to fit in smaller divs in the main UI. If we want to change icon to the blue one, I have no objections.

**Comment by chantisnake** [comment]
No longer relevant
