### ISSUE TITLE
Tooltip enhancement

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#235]
Does anybody have any objections to changing the tooltip icons to [Font Awesome](http://fortawesome.github.io/Font-Awesome/) and the tooltips to [qTip2](http://qtip2.com/)?

I have them working in Select (which only has one tooltip). Here's a screenshot.
![selfdestruct](https://cloud.githubusercontent.com/assets/1125917/8389749/da06f69a-1c2b-11e5-9be6-441c7b211bc1.JPG)

As you an see, they are styled to look like the current icons and tooltips, but they stay open until you click somewhere else and they can contain HTML.

Since it would take a while to convert the tooltips on all pages, I don't want to do any more without some feedback.

**Comment by mleblanc321** [comment]
should we port to another page with richer use of tool tips and see how that goes?

**Comment by scottkleinman** [comment]
The Select page doesn't make much use of the tool tips, but I can update it. I'm going to try to update BubbleViz tonight. (As mentioned, it works, but I've left some the CSS and Javascript in the template, so I need to move that stuff before pushing.) Scrub makes heavy use of tool tips, so I could do that page as well, and we can see what people think.

NB. The d3 in the Word Cloud and Multicloud functions is a little harder to work with, which is why we are currently using the browser tool tip. It'll take a little time to figure out how to inject the qTip2 code.

**Comment by scottkleinman** [comment]
There is a problem with the Bubble Viz maximum number of words and minimum word length functions. If you set the values to null, the tool crashes. I'm going to try to fix that before pushing the improved tool tips. If I can't get it done, I'll post it as an issue.

**Comment by scottkleinman** [comment]
The aforementioned problem with null values has been fixed, and I've pushed all the changes.

**Comment by mleblanc321** [comment]
can we close this?

**Comment by scottkleinman** [comment]
Actually, there is an ongoing issue with tooltips. They are _hard_. But I think that the issue problems raised in this issue were fixed, so I'll close this and open a new one for the tooltips.
