### ISSUE TITLE
JQuery query

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#236]
Due to issue #226, I switched JQuery and JQuery UI to the jQuery CDN, using the latest versions of both libraries. Formerly, we were loading fairly antiquated versions from Google. The change did not create any problems for Lexos, so I am going to recommend that we keep the latest versions and update our local copies. This will have the knock-on effect of allowing me to create a fallback option and close issue #166. Any objections?

**Comment by mleblanc321** [comment]
very good;  nice solution, keeps us up2date as best we can at this release ...

**Comment by mleblanc321** [comment]
>recommend that we keep the latest versions and update our local copies
no objections, but i don't quite get exactly what you mean (see above)?

**Comment by scottkleinman** [comment]
A fallback option is a check for whether the library is loading from CDN. If it fails (for instance, if the user does not have an internet connection), Lexos would automatically load the local copy instead of the CDN. In issue #166 I recommended that we do this anyway, regardless of whether we allow the user to configure which copy they load manually. If we create the fallback option, I think #166 can be closed.

**Comment by scottkleinman** [comment]
Transferred to issue #431.
