### ISSUE TITLE
Saving d3 Images

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#237]
I've added a primitive Save as PNG function to BubbleViz. We may want to investigate more robust systems like [https://github.com/agordon/d3export_demo](https://github.com/agordon/d3export_demo), which can also save as PDF.

**Comment by austinrg7** [comment]
Just a small note about this.  I was looking into it when I was working with the Voronoi diagrams and the solutions I was looking at required all the css to be inline.

**Comment by scottkleinman** [comment]
Here's the implementation I used. I loaded `canvg.js` plus associated scripts into viz.html. I then created a canvas element and an image element, both set to `display:none;`.
 
```html
<!-- Canvg Used for Save to PNG -->
<script type="text/javascript" src="http://gabelerner.github.io/canvg/rgbcolor.js"></script> 
<script type="text/javascript" src="http://gabelerner.github.io/canvg/StackBlur.js"></script>
<script type="text/javascript" src="http://gabelerner.github.io/canvg/canvg.js"></script>
<canvas id="svg-canvas" style="display:none;"></canvas>
<img id="svg-img" style="display:none;"/>
```
Then, in `scripts_viz.js`, I set a button trigger, grabbed the HTML container for the SVG, and transferred it to the canvas element. This allows conversion to a PNG url. I then injected that URL into the `src` attribute of my `img` element. Finally, I open a new window containing a clone of the `img` element set to `display: block`. 

```Javascript
// Save to PNG
$("#save").on("click", function(){
    var $container = $('#viz'),
    content = $container.html().trim(), // Canvg requires trimmed content
    canvas = document.getElementById('svg-canvas');

    // Draw svg on canvas
    canvg(canvas, content);

     // Change img from SVG representation to PNG url
    var theImage = canvas.toDataURL('image/png');
    $('#svg-img').attr('src', theImage);

    //Open a new window with the image
    var w = window.open();
    var img = $("#svg-img").clone().css("display", "block");
    var html = $("<div/>");
    html.append("<h3>Use your browser's Save as function to save the image</h3>");
    html.append(img);
    $(w.document.body).html(html);
});
```
Once I got this working, I tried briefly to do this with the Voronoi diagram, but in the time I had available, I was not able to figure out what container to target. Perhaps you can figure it out.

**Comment by mleblanc321** [comment]
austin: do you know this speak?  :)

**Comment by jacksonjreed** [comment]
closing this one--currently we have png and svg download working for both visualizations that use d3
