### ISSUE TITLE
Word cloud generates 400 Bad Request

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#238]
The full message is:

Bad Request
The browser (or proxy) sent a request that this server could not understand.

The Firefox console adds:

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

I'm not sure what's causing this.

**Comment by akuisara** [comment]
I have tried moby_dick.txt, a Chinese file, number_large.txt, and A3.3_Az_T00130.txt. All of these files can cause 400 Bad Request

**Comment by akuisara** [comment]
`generateJSONForD3` function inside `utility.py` should be the reason why Bad Request is caused. There is no 'minlength' in request.form

**Comment by scottkleinman** [comment]
Does this means that the bug is fixed?

**Comment by akuisara** [comment]
Yes
