### ISSUE TITLE
Curious formatting issue in Select

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#239]
Sara noticed that the loading icon was at the bottom of the screen in Select. When I checked, I discovered that the reason was because some empty divs with large css heights. I traced these back to `base_manage.html`. This has the code block

```html
<div id="manage-previews" class="cf">
    <div id="prepare-previews-context">
	{% block previews %}{% endblock %}
    </div>
</div>
```
I'm pretty sure that these were for the old Select page with the large preview blocks. Before I get rid of them, does anyone know of any other templates that extend `base_manage.html`?

**Comment by akuisara** [comment]
Besides Select page, Upload also extends `base_manage.html`

**Comment by scottkleinman** [comment]
In that case, I'll just over-ride the div height in css for now.
