### ISSUE TITLE
Error Message Standardizing

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#240]
We are about to standardize all the error message on the GUI. Mark, Austin and I have talked about the styling of the error message, and we think we decided on not to use the dialog box but the flashing messages. There are two styles of the error message on screen right now. The dialog box error message is not really stable with the title, and the style doesn't fit the page. Also, it sometimes goes under the buttons div on the analysis page. Since the dialog is movable, it is really hard to close the dialog box with the little button. The other thing is that the flashing error messages works for all the pages and are all styled the same way. It would be much easier to standardize and get it to work right in a short time period. 
#234 has the discussion that we had before, so I will reference this here.

**Comment by mleblanc321** [comment]
Scott, are u ok with this?

**Comment by scottkleinman** [comment]
For now, yes. Bootstrap is much better than JQuery UI for error messages. There are some possibilities enabled by qTip2. Look [here](http://qtip2.com/demos). Scroll down to API and Callbacks and look at the first row of dialogs. The jGrowl might be an option.

**Comment by akuisara** [comment]
I have changed the error messages and commented out the jQuery dialog box. I will close this issue now. For later enhancement, feel free to reopen the issue and implement the Bootstrap error messages.
