### ISSUE TITLE
Natural Sorting on the Front End

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#241]
For some time we've had a natural sorting function on the back end. There is now a front end version in case anyone needs it. You can find it at `js/naturalSort.js` folder. To use it on an array, just call `arrayName.sort(naturalSort)`. I was only using it for some debugging, but I thought I'd leave it in the folder in case it is handy in the future.

**Comment by mleblanc321** [comment]
hmm, natural sort:  so z11 sorts after z2, i get it;
where do we call for "natural sort" now?

**Comment by scottkleinman** [comment]
In `general_functions.py` there is a function called `natsort()`. `lexos.py` apparently sets it up for use in a Jinja filter:

```python
app.jinja_env.filters['natsort'] = general_functions.natsort
```
So we really only need front-end natural sorting for post-processing/user interaction. But there is no current requirement for it; it's just there if we need it.

**Comment by scottkleinman** [comment]
There are now various ways to do this. I think we can close this issue.
