### ISSUE TITLE
Tokenizing by characters

### ISSUE THREAD

**Issue by jaronson13** [WheatonCS/Lexos#243]
Blank spaces are seemingly added into the original segment when we select Tokenize>by Characters. 

This makes the total character count appear higher than it really is. 

For example, I uploaded the word 'one' and scrubbed it. When I went to the statistics page and changed the tokenize options to tokenize by character, the resulting total character count was 5 instead of 3. When the countMatrix is printed, it shows that there are two blank space characters.
![countmatrix](https://cloud.githubusercontent.com/assets/7633573/8441528/def52f5a-1f46-11e5-887f-6f3389d3f2d6.png)

**Comment by chantisnake** [comment]
this is solved by adding deleting the 'character within word option'
40fefe9cc7ba06b7a7a08ad6d7f054c244d77f16
