### ISSUE TITLE
Similarity Query Problem

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#244]
First, Similarity Query doesn't work with Chinese at all, it is not generating a table no matter choosing by word or by character. I think Sara is going to take a look to see if it is a problem with decoding/encoding for the tidy table. 
[update] I think the problem that it doesn't show the table at all is because of a decode/encode problem with the Chinese title. If I use a Chinese file with english title, then the table does show up. But the values aren't correct. 
Also, we are thinking about adding the normalize option to Similarity Query. I read in a lot of articles about using tf/idf with similarity query could be more helpful in comparing documents. I will look into this, it might not be a easy change so may be could be a future enhencement .

**Comment by akuisara** [comment]
These Unicode problems below are fixed, Unicode characters shouldn't cause program crash now
- Selected Document Labels: 2cf603c500193468e97e143d253495fb165230e
- TidyTable Unicode problem: 810a761e4da5d385c72e529eef8a4921a637a138

**Comment by akuisara** [comment]
Bugs are fixed, the normalizatoin remains as future work

**Comment by chantisnake** [comment]
I am not even sure normalization option will make any sense, because when I read the tutorial there is no place mention anything about normalization.

**Comment by JingxianL** [comment]
I read it not on the tutorial but on otherwhere saying that tf/idf can now used to create vectors and use this vector to calculate the cosine similarity.

**Comment by JingxianL** [comment]
There are few urls about this topic. 
1. Just some basic and simple explanations
http://www.ir-facility.org/scoring-and-ranking-techniques-tf-idf-term-weighting-and-cosine-similarity
2. Talk about what tdifd has affected on
https://www.elastic.co/guide/en/elasticsearch/guide/current/pluggable-similarites.html
3. This is a ppt, but does have some of the detailed calculations.
http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&ved=0CEwQFjAG&url=http%3A%2F%2Fcecs.wright.edu%2F~tkprasad%2Fcourses%2Fcs707%2FL08VSM-tfidf.ppt&ei=3FOVVfm1BsufNs-9vxg&usg=AFQjCNFsUErC07IB27mHWyzdsB4zlqldNg&bvm=bv.96952980,d.eXY

I will add more to the list if I read some useful ones.

**Comment by scottkleinman** [comment]
Similarity Query has been re-written, and normalisation options have been removed. It also works on Chinese. So I'm guessing that this issue can be closed.
