### ISSUE TITLE
countVectorizer recognize the diacritical mark as word boundary

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#245]
the solution we have for now is just remove all the diacritical mark in the countVectorizer. The problem with this is that the word with diacritical and without will be recognized as the same word, for example `ę` and `e` will be recognized as the same

Future Solution:
* change the regular expression in the countVectorizer, so that the countVectorizer do not recognize the diacritical mark as word boundary
* change scrubber, so that the letter with diacritical will scrubbed as one code point charactor, instead of scurb `&e;` to `\u0065\u0328`, we scrub that to `\u0119`

We will not apply any further change on this issue in this year's release

**Comment by scottkleinman** [comment]
But keep this issue open with bug status so that we don't forget. This is important.

**Comment by mleblanc321** [comment]
but we need to remove
strip_accents='unicode'
from CountVectorizer()

we cannot allow for the loss of all accents ... so for now, diacriticals (at least the &e; (e-tail) will cause a word boundary and thus separate words to be counted when the diacritical appears in the middle of the word

**Comment by kreddy95** [comment]
fixed with the change in countvectorizer regex.

6070dfdb4c1e1f22bd70b9c4594b0830786e523e here is the fix.

**Comment by scottkleinman** [comment]
Good catch. And I really like the "Cheng magic regex".
