### ISSUE TITLE
Rolling Window video button

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#246]
On your next pull, check out the video button in Rolling Window Analysis (top right).

**Comment by chantisnake** [comment]
when I open that video via firefox, it asks me to download

**Comment by chantisnake** [comment]
and it require flash plugin.

**Comment by scottkleinman** [comment]
Is that also true of the Call an ITM video button at the bottom of the screen?

**Comment by akuisara** [comment]
The bottom one works fine, but the top right one on the Rolling Window page also asks me to save the video

**Comment by chantisnake** [comment]
I have installed fresh-player-plugin, everything works fine now.

I think we can assume that everyone has flash.

**Comment by scottkleinman** [comment]
OK, I think I can force it to use HTML 5, but as long as we know that's the problem, we're good.

**Comment by chantisnake** [comment]
I think, we don't need to convert that to be a html5 video, but it is better if it is.

Is converting it to be an html5 video a complicated job?

**Comment by scottkleinman** [comment]
I think it's actually just a matter of changing the URL that we have in Scalar. I've done that. I then de-activated Flash in Firefox, and the video still works for me. Try it yourself.

**Comment by akuisara** [comment]
It works now!

**Comment by scottkleinman** [comment]
I'm going to convert this to a separate issue with instructions for embedding YouTube videos. I had no idea that YouTube used separate URLs for Flash and HTML 5 until this issue on GitHub.
