### ISSUE TITLE
Cut Page Warnings

### ISSUE THREAD

**Issue by austinrg7** [WheatonCS/Lexos#250]
Caleb and I implemented a confirm step on the cut page if the user enters a value that will result in more than 100 segments being created.  Currently this is being implemented using a simple JavaScript confirm.   These confirm messages cannot be styled and look different depending on the user's browser.  In the future we may wish to style these confirm messages to look more like the rest of the website.  One possible solution is the jQuery plugin [boxy](http://onehackoranother.com/projects/jquery/boxy/).

**Comment by scottkleinman** [comment]
Good job. Confirm messages can also currently be implemented with the [qTip2](http://qtip2.com/) plugin, which is already loaded into Lexos. Something like this:

```html
<div class="bttn bttn-minor" style="width:75px;" id="warning">Confirm</div>
```
```javascript
$(function(){
    $("#warning").click(function() {
        message = "<p>This will produce thousands of tiny segments. Do you want to continue?</p><button>Why not?</button><button>No way!</button>";
        $('<div />').qtip({
            content: {
                text: message,
                title: "Warning!"
            },
            position: {
                my: 'center', at: 'center',
                target: $(window)
            },
            show: {
                ready: true,
                modal: {
                    on: true,
                    blur: false
                }
            },
            hide: false,
            style: 'qtip-rounded qtip-shadow lexosConfirmTooltip',
            events: {
                render: function(event, api) {
                    $('button', api.elements.content).click(function(e) {
                        api.hide(e);
                    });
                },
                hide: function(event, api) { api.destroy(); }
            }
        });
    });
});
```
This should work as is, although the css for `lexosConfirmTooltip` will have to be defined.

**Comment by cmccarthy41899** [comment]
Is this still valid in the Bootstrap version? @scottkleinman 

If not, can we close this?

---Moses

**Comment by scottkleinman** [comment]
Right now, Cut is just using the Javascript confirm() method. We should probably switch it to a Bootstrap modal. I'll see if I can do that today, and then we can close this issue.

**Comment by scottkleinman** [comment]
After a closer look, I see that Cut is still using the form submit method rather than submitting values by Ajax. The warning message is tied into this code. So both of these will have to be fixed at once. On Wednesday we might want to do a quick workshop on converting to Ajax, as this is probably true of a number of the other pages.

**Comment by scottkleinman** [comment]
This issue is superseded by #412.
