### ISSUE TITLE
flag in the ground

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#251]
... and so the Summer 2015 coding blitz is over; that was one of the most productive and enjoyable coding sessions i've participated in ... we are a great team ... (stay close to Lexos ;) ... ahem, i'll be in touch)

**Comment by scottkleinman** [comment]
Seconded. This was an incredible group to work with, and the project has advanced far beyond what we expected to achieve in a few short weeks. I really enjoyed working with you all, and, as Mark says, I hope you stay close to Lexos.

**Comment by mleblanc321** [comment]
i'm bored ...
