### ISSUE TITLE
Use Pandas for Rolling Window?

### ISSUE THREAD

**Issue by lithiah** [WheatonCS/Lexos#252]
Might be an idea to use something like pandas for calculating rolling window data. 
see: http://pandas.pydata.org/pandas-docs/stable/computation.html#moving-rolling-statistics-moments

We'd still need to tally the counts ourselves because our input is a text file instead of an array of numbers, but once we have counts we could use panda to get the rolling average. We'd also then be easily able to get more metrics like rolling standard deviation, variance, etc. which could be useful.

**Comment by mleblanc321** [comment]
cool; nice to see a lithia post :)  ... have you seen the updated rolling window?  we've added "milestones" (e.g., chapter marks) and optimized the drawing of the graph by dropping points that fall on a line and hiding circles-drawn-at-each-point ...

**Comment by lithiah** [comment]
I haven't seen the updated rw, I'll have to check it out! Sounds cool!

**Comment by scottkleinman** [comment]
Nice to hear from you, Lithiah. We've been doing a lot more with a document-term matrix from which we could potentially grab the data. We'd have to make RW default to whatever tokenisation options the user has chosen for building the matrix, but it might be possible to see if calling the pandas functions is more efficient for all the individual RW functions we have for each setting. I think there's been some heavy use of RW this summer, so we'll try to get some feedback on what people think they need.

**Comment by lithiah** [comment]
Sounds good Scott!

**Comment by scottkleinman** [comment]
We haven't got there yet with RW, but we're now making use of Pandas in Tokenize. So there's precedent.

**Comment by chantisnake** [comment]
@arialfie759 Please take a look at this.

**Comment by chantisnake** [comment]
Done with the new rolling window.
