### ISSUE TITLE
Getting mathematical notation in In the Margins/Lexos

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#253]
Lexos will print mathematical equations if we load the [Mathjax](https://www.mathjax.org/) library. But it won't convert dynamically loaded *In the Margins* content, which is where would expect this notation to appear.

The Scalar editor, unfortunately, does not seem to be up to representing mathematical notation. The best option I can find seems to be to construct it in something like [iTex2Img](http://www.sciweavers.org/free-online-latex-equation-editor), which creates a link to an image generated on the fly. The image can be placed in Scalar and will appear in Lexos. But this is not ideal since the service may go down.

How do we want to deal with mathematical formulas in Lexos/*In the Margins* documentation?

**Comment by mleblanc321** [comment]
For the most part, I don't the average ITM reader will want a mathematical equation. If we need one (example?) then we could (for the start) just insert an image of the equation?

**Comment by scottkleinman** [comment]
On the whole, I think you're right, given the ITM audience, and this suggests a "no maths" principle. However, I also think that Humanities scholars and students can (and should) be pushed a little, especially when they are faced with methodological terms (what is the *k* in "k-Means"?

Inserting an image is probably the answer, and [iTex2Img](http://www.sciweavers.org/free-online-latex-equation-editor) is a great way to produce them, even if we do not use the generated links. However, in Scalar, the only way to embed images is by using an `<img/>` element in the page's HTML or by creating a separate Scalar media page for the image. Maybe the thought of having a bunch of media files containing only images of mathematical formulae bothers me irrationally.

The prospect of having more than one or two comes from thoughts I am having about different levels of discussion. For example, anyone going to the Topword page would get a relatively untechnical discussion, but the page could be a (or on a) Scalar path which moves on to more technical discussion, should the reader be inclined to follow it. Perhaps these more advanced discussions should link to embedded documents (e.g. PDF or even HTML + Mathjax). Then mathematical notational will not be a problem.

I raised this question only to create food for thought as we are authoring content...

**Comment by scottkleinman** [comment]
I have found a solution. If you start with the mathematical notation formatted in something like a .docx file, you can convert it to html with [Pandoc](http://pandoc.org/index.html), including [Mathjax](https://www.mathjax.org/). The command is

```
pandoc -s FILENAME.docx --mathjax -t html -o FILENAME.html
```
Open the new file, copy the section inside the `<body>` tags, and paste it into the Scalar HTML editor. At the very end, paste the following:

```html
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
```
In the Style section of the Scalar page, add the following CSS:

```css
code{white-space: pre;}
```
It will display correctly in both Scalar and Lexos.

One inconvenience. The Mathjax script adds a bunch of CSS to the text and deletes the call to the script. So, if you edit something in the page and save, everything breaks. It's better to edit the HTML file and then re-paste everything into Scalar.

Still, this avoids having lots of tiny media files containing images of mathematical formulae.
