### ISSUE TITLE
Add more averages to statistics table

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#255]
It's really easy to calculate the average number of distinct and unique words from the information given in the statistics table, but is it worth adding columns with this information to the table just to save the user the trouble?

**Comment by mleblanc321** [comment]
agreed that it would not be that hard;  given the averages, what would the user do with this info?  (are you hoping to detect segments that have large standardDeviations in these categories?)

**Comment by scottkleinman** [comment]
Yes, that seems to be the most likely use. It's a pretty good index of document homogeneity and heterogeneity.

**Comment by chantisnake** [comment]
I believe weiqi is working on this?

Reference this issue when you finish, so that we can close this.

**Comment by Weiqi97** [comment]
I believe that we report average counts for distinct terms/characters on current master branch, and it will be kept in the future stats model.
