### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by lmrhody** [WheatonCS/Lexos#256]
Hi all, 
I was hoping to use Lexos to teach an introduction to text analysis workshop last week. When I was about to have students upload texts to the site with the uploader (http://lexos.wheatoncollege.edu/upload), I got an internal server error.  We haven't been able to upload texts since.  I was just hoping to demo the scrubbing and cutting features. Am I doing something wrong? Any chance that'll be working again soon? 

Thanks!

Lisa Rhody
<img width="428" alt="screen shot 2015-07-19 at 7 19 30 pm" src="https://cloud.githubusercontent.com/assets/1395793/8768361/8612fbd8-2e4b-11e5-899c-edf0d294cea1.png">

**Comment by scottkleinman** [comment]
It's working for me right now. Typically, we get this error when there's a browser caching issue or something like that. Does clicking the reset button or loading [http://lexos.wheatoncollege.edu/reset](http://lexos.wheatoncollege.edu/reset ) directly help?

**Comment by chantisnake** [comment]
I am feeling that this problem is weird. every time I go to lexos, there is internal server error, and reset fixed it. I think there is definitely something wrong on our part.

**Comment by chantisnake** [comment]
I have find the bug. We have an error handle method to init session when there is no session or outdated session, but we did not init the filemanager together with the session. I will push a change later today, to fix this.

**Comment by scottkleinman** [comment]
I've just tried it on two Windows machines without encountering the error. I don't know why this type of error might be platform-specific (if that's the case), but I thought I'd report it, just in case. But I think we're probably going to have to check the server logs.

Lisa, I'm not sure if you are planning for all of your students to use Lexos or whether you were just doing one-person demo, Lexos is not hard to set up locally. There are installation instructions [here](https://github.com/WheatonCS/Lexos/tree/master/0_InstallGuides).

**Comment by scottkleinman** [comment]
Oops! Near simultaneous posting. Thanks for finding the bug, Moses. Mark, how soon can we get Moses' fix to the server?

**Comment by chantisnake** [comment]
sorry I screw up on the last push... I will make all of them back = =

**Comment by chantisnake** [comment]
I have push a fix to this. I don't think there will be any other internal server error caused by cached session.

**Comment by mleblanc321** [comment]
i will do this later this morning (MON, 20th) ...

**Comment by mleblanc321** [comment]
i have pulled moses' edits to the lexos server ...
