### ISSUE TITLE
Tokenize/Count is slow

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#257]
Tested on the novel *Frankenstein*, scrubbed and cut into 10 segments. In Chrome, it is slow but works eventually. In Firefox, the browser hangs. Possibly a DataTables issue?

**Comment by mleblanc321** [comment]
fyi, evan is working hard to catch up on the dataTables code ....

**Comment by scottkleinman** [comment]
We've pretty much sorted out the Tokenize issues, so I'll close this issue.
