### ISSUE TITLE
Display of uploaded filenames is not fixed

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#259]
On Scrubber page, if a user uploads some files inside the additional options area, the filenames showing on screen can be moved around by expanding and hiding certain option. Also some of them overlap with each other as shown below:

![screen shot 2015-09-30 at 11 00 49 pm](https://cloud.githubusercontent.com/assets/4997873/10211988/3f918aa2-67c7-11e5-937f-6702aaae1070.JPG)
![screen shot 2015-09-30 at 11 01 44 pm](https://cloud.githubusercontent.com/assets/4997873/10211989/3f928a9c-67c7-11e5-93e2-bfb119273c22.JPG)

.

**Comment by scottkleinman** [comment]
I suspect this issue affects Multicloud as well, though it may be less apparent because that page is less cluttered. We should probably try a fix for the upload css in the main css file.

**Comment by mleblanc321** [comment]
i noted this awhile ago (thanks for posting sara); however, i couldn't see where we'd make a change;

**Comment by scottkleinman** [comment]
I've pushed a fix but haven't tested in lots of browsers. If people can do some testing, and it looks all right, we can close this issue.

**Comment by mleblanc321** [comment]
MacOS, Chrome v45.02x
if the uploaded filename is long (e.g., DAZ_consolidations.txt) the uploaded filename appears on the next line and overwriting the next label);  note that DAZ_lemma.txt fits in ok for stopwords/consolidations/lemma sections, but longer uploaded names appear on the next line);

so, if i upload DAZ_consolidations.txt for Consolidations, the filename appears on *top* of the (subsequent) "Special Characters" label

**Comment by scottkleinman** [comment]
I had a feeling that fix was too easy. But this gives me something to go on. I'll see what I can do...

**Comment by scottkleinman** [comment]
Grrrr.... I've pushed another fix, but it was not easy. I ended up having to change the layout, placing the file name on the same line as the legend. I hope you like the effect. It's not a perfect solution: file names longer than about 45 characters will still wrap to the next line, but file names that long should be pretty rare. Please test.

**Comment by mleblanc321** [comment]
umm, did you really push a change?

**Comment by scottkleinman** [comment]
Apparently, it didn't work. I've pushed it again.

**Comment by mleblanc321** [comment]
looks good on my mac laptop; i'll check at the office also; good job, scott

**Comment by scottkleinman** [comment]
Great! You might want to pull one more time. I've added clipping for file names greater than 35 characters long to keep long file names on one line.

**Comment by mleblanc321** [comment]
ha! was just headed there; thanks very much scott;

**Comment by mleblanc321** [comment]
i think we can close this issue (?)

**Comment by scottkleinman** [comment]
It's worth testing this in the Bootstrap version with various browsers and screen sizes, but this should be fixed.

**Comment by scottkleinman** [comment]
Upload seems to be working, so I'll close this issue.
