### ISSUE TITLE
Scrubber stopword (and other) lists are not persistent

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#260]
If the user enters or uploads stop words or other lists in the Scrubber forms, the lists are not persistent when the user leaves Scrubber and then returns. This is not strictly necessary if the user has applied the scrubbing, but it's a little confusing if they want to go back and add to their list. The user may not be sure whether he or she needs to re-enter/re-upload the original list.

**Comment by scottkleinman** [comment]
Updating this issue slightly, stop words lists are now cached _if you apply them_. However, the stop words setting is switched to "off" if you leave and return to Scrubber.

**Comment by chantisnake** [comment]
Another caching issue?

Gosh, these guys are fun...

**Comment by scottkleinman** [comment]
It appears that all options are persistent if you preview or apply them. The only exception is the stop words/keepwords/off radio buttons. That should make for an easier fix.

**Comment by scottkleinman** [comment]
Fixed.
