### ISSUE TITLE
<TODO> automate the testing process

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#261]
write a script that will automatically 
1. upload selected text (text in a particular folder, or the whole test suit)
2. run selected tools (the tool that we want to test)
3. returns all the error and crashes, so that the programmers can fix those issues.

**Comment by mleblanc321** [comment]
:)
from the guy taking 8 courses ....;   this is good thinking, moses

**Comment by mleblanc321** [comment]
i should know (but don't) ... are there good tools we might use for this?

**Comment by chantisnake** [comment]
no, we may need to write it our self... I think beautiful soup and request coupled with cookie jar will do the trick, but is just need lot of time to individually implement every request and analysis of html...

**Comment by scottkleinman** [comment]
Yes, it might not be worth the time to code this. It might be better just to have a script in the non-coding sense or a protocol in which we have a set of test data and run it through various set tasks by hand.

**Comment by chantisnake** [comment]
write up a protocol will be a quick and dirty way to do this, but with code this will be much more efficient.

**Comment by mleblanc321** [comment]
for later ...

**Comment by chantisnake** [comment]
closing in favor of #512
