### ISSUE TITLE
pull to server

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#262]
i submit we should pull what we have at github to the server;   i will fetch some recent analytics on the lexos server in terms of external use, but in the meantime, our audience is so small that we need the best feedback on our current state;  

please feel free to chime in ...

**Comment by scottkleinman** [comment]
If we do this, we should probably do it soon, as I'll be doing a Lexos workshop at the end of the month. That will give us time to roll back if something goes wrong.

**Comment by mleblanc321** [comment]
if i can get moses, sara, and caleb together (or just on call), i'd feel ready to just do it; [scott:  ready?]

**Comment by scottkleinman** [comment]
I don't have any other planned updates for this weekend, so go ahead.
