### ISSUE TITLE
Clustering flyout menu needs improvements

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#263]
The hierarchical and K-means clustering fly-out menus look fine on most computers, but they disappear off the screen when using a projector (at least in my lab). We might want to eventually change to a different implementation that does viewport repositioning.

**Comment by mleblanc321** [comment]
i believe this Issue can be closed given the new bootstrap changes?

**Comment by scottkleinman** [comment]
Yes. Bootstrap should fix this issue. Making the browser window very narrow changes the menu to a hamburger icon with a responsive menu. This could possibly use some styling. But we're talking about tablet portrait width here. I'll close this, and it can be re-opened if there's a problem.
