### ISSUE TITLE
Culling: option to select "all files"

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#265]
i just uploaded (using localhost) 82 texts (mostly novels);  all worked really nice (likin' Jingxian's loading taskbar :) .... and i successfully scrubbed and tokenized (MFW=100, Cull=82), yup likin' moses' MFW and Cull options;  but note that last number, Cull="word must be in all files" ... i had to manually look that up;  somehow, we need a GUI choice to select "all files" without the user needing to know how many segments are presently active

**Comment by scottkleinman** [comment]
Does it make sense to re-write the function so that it automatically checks all active files? Without any other indication, I think that's what I'd assume Lexos is doing...

**Comment by chantisnake** [comment]
I didn't quiet get that...

**Comment by mleblanc321** [comment]
scott:  i'm not sure we are talking about the same thing;  when Culling is opened, a text field allows the user to enter an integer M, where M means the word must appear in at least M of the total (N) active segments

**Comment by scottkleinman** [comment]
Oh, I see. The user can select the minimum number of active documents for a a token to appear but cannot choose "token must appear in all active documents" without going to Select, finding the number of active documents, and then entering that number. Does it make sense to make "Token must appear in all active documents" the default setting with a checkbox that reveals the integer input field when unchecked?

If nothing else, this question revealed that the language of the Tokenize function is still based around words and segments, rather than tokens and documents. We should probably fix that at the same time.

**Comment by mleblanc321** [comment]
>"Token must appear in all active documents" the default setting 
no, i don't think so;  that is, in my opinion, too restrictive for a default;  that is, i usually allow segments that do not include some words: zeros are numbers too :)

**Comment by scottkleinman** [comment]
My suggestion, then, would be to use the same interface, but leave the checkbox unchecked by default and toggle the "disabled" property on the integer input field when the box is checked.

**Comment by scottkleinman** [comment]
I know that we have improved things by making the number of active documents available from the icon in the navbar, but I'm still unclear on what further changes need to be made to the interface for culling.

**Comment by mleblanc321** [comment]
>make "Token must appear in all active documents" the default setting with a checkbox that reveals the integer input field when unchecked?"

i think yes (which upon reading the above, may contradict a previous comment i made);

so

CULL >   (closed by default)
if opened,
Cull   (unchecked by default):   
    IF checked, then show
        Must be in **N** segments   (where **N** is # of current ACTIVE documents)

**Comment by scottkleinman** [comment]
OK, this is easy, except for on the Statistics page, where the user can override the maximum value = the number of active documents. That page needs a lot of logic to change the maximum value to the maximum number of documents the user has selected on the page. Also, if the user has all the documents selected, they can still type in a higher number than the number of active documents. We need to trigger an error message when that happens. I'll see if I can get this done tomorrow.

**Comment by scottkleinman** [comment]
Mission accomplished.

**Comment by mleblanc321** [comment]
nice;  (and good catch on the difference on the Stats page ... dang ...)
