### ISSUE TITLE
Stripping hyphens merges words

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#266]
If you remove hyphens when scrubbing (either `-` or `--`), the words on either side will be merged. It would be better to replace the hyphen with a space. I don't think this is something that should be done automatically. Rather, I think we should build in an option to replace a string with a space. Right now, I think all the regular expressions strip spaces, so you can't do something like `-,` in consolidation. An option to add a space in place of a character would be a nice enhancement.

**Comment by mleblanc321** [comment]
we really should handle double hypens -- in a special case; seeing lots of these -- in older texts; this will let us keep (single) hyphens between two words and keep those as one-token, but remove the double hyphens which are often used for an end (or pause) stop.

**Comment by scottkleinman** [comment]
My students and I ran into this problem last semester. A good way to handle it might be to allow regex consolidation of `--` and `—` (Unicode Character 'EM DASH' (U+2014)). That way it is possible to keep both `-` and `--` with their implicit grammatical or semantic content.

**Comment by mleblanc321** [comment]
_cf_ #118

**Comment by cgnobrega** [comment]
moved to #956
