### ISSUE TITLE
handling (MacOS) \r carriage returns

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#267]
we recently accepted 100s of novels from someone ... and all the lines ended in \r (UGH!);  thus, when we scrubbed and tokenized, those were removed and we ended up with the last word on each line getting mashed into the first word on the subsequent line;

i think this might want to be an automatic feature, that is, if we see these \r, we replace them with \n immediately

**Comment by scottkleinman** [comment]
Cf. issue #266.

**Comment by austinrg7** [comment]
Weird Jesse and I added some code to detect this when we realized it was happening this summer.  I went back and checked and found this code:

'''

 if '\r' in fileString[:constants.MIN_NEWLINE_DETECT]:
            fileString = fileString.replace('\r', '')
'''

I went and checked constants and MIN_NEWLINE_DETECT = 1000 characters so it's unlikely that failed.

Does mac use just \r and not \r\n?

**Comment by austinrg7** [comment]
I just looked it up and it does appear that mac does use just \r.  I would suggest something like:

```
if '\r' in fileString[:constants.MIN_NEWLINE_DETECT]:
        if '\n' in fileString [:constants.MIN_NEWLINE_DETECT]:        
                fileString = fileString.replace('\r', '')
        else:
                fileString = fileString.replace('\r', '\n')
```
This will handle both Mac and Windows line endings.

**Comment by scottkleinman** [comment]
It looks like a version of Austin's suggestion was implemented.
