### ISSUE TITLE
TF-IDF producing empty matrices?

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#269]
I just had a query from a user about TF-IDF in the Tokenize screen. When he selected it, he got back a "No data is available" message. When I try it, I get a table in which every cell is 0 is I use Euclidean or Manhattan distance. Norm:None gives me a result. I had noticed this before and assumed that it was the nature of my data, but we might want to check whether something is going on with the Euclidean and Manhattan functions, or at least get an idea of what our expected output should be for the three options. I'm not even sure what Norm:None means. If there is no bug, we should do a quick write up in *In the Margins*.

**Comment by mleblanc321** [comment]
TF-IDF never got a thorough review; for now, i'd say we
should remove it

m



On Fri, Jan 8, 2016 at 5:01 PM, scottkleinman <notifications@github.com>
wrote:

> I just had a query from a user about TF-IDF in the Tokenize screen When he
> selected it, he got back a "No data is available" message When I try it, I
> get a table in which every cell is 0 is I use Euclidean or Manhattan
> distance Norm:None gives me a result I had noticed this before and assumed
> that it was the nature of my data, but we might want to check whether
> something is going on with the Euclidean and Manhattan functions, or at
> least get an idea of what our expected output should be for the three
> options I'm not even sure what Norm:None means If there is no bug, we
> should do a quick write up in *In the Margins*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/269>.
>



-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Professor of Computer Science
Co-Chair, Department of Math & Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by scottkleinman** [comment]
That makes things easier for short-term development, but I think this is a desired functionality, so we should probably not put it off too long.

**Comment by chantisnake** [comment]
Do we need to remove that now?

**Comment by scottkleinman** [comment]
Oh, good catch. I don't know if this has been addressed. The last time I looked at this only the Norm: None setting produced a non-empty matrix.

**Comment by scottkleinman** [comment]
Transferred to issue #437.
