### ISSUE TITLE
"Anomaly found using StdE" in Statistics

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#270]
The Statistics page outputs "Anomaly found using StdE". Most likely, a Humanities user will have to Google this abbreviation, and the results will not be pretty. This should be expanded to "Standard Error Analysis" and should link to an *In the Margins* page. As yet, I haven't found an easy-to-comprehend definition of Standard Error Analysis.

**Comment by chantisnake** [comment]
can we assume that the standard error is?

the anomaly is just 2 standard deviation of the mean

**Comment by scottkleinman** [comment]
The statistics immediately above it give the Median File Size (in bytes?) which might imply to the users that the "StdE" is the standard deviation of the median.

Here's the code:

```python
        for i in range(NumFile):
            FileSizes.update({lFiles[i]: sum(WordLists[i].values())})
        # 1 standard error analysis
        Average_FileSize = sum(FileSizes.values()) / NumFile
        # calculate the StdE
        StdE_FileSize = 0
        for filesize in FileSizes.values():
            StdE_FileSize += (filesize - Average_FileSize) ** 2
        StdE_FileSize /= NumFile
        StdE_FileSize = sqrt(StdE_FileSize)
        # calculate the anomaly
        for file in lFiles:
            if FileSizes[file] > Average_FileSize + 2 * StdE_FileSize:
                FileAnomalyStdE.update({file.name: 'large'})
            elif FileSizes[file] < Average_FileSize - 2 * StdE_FileSize:
                FileAnomalyStdE.update({file.name: 'small'})
```
Am I right in interpreting that Moses' assumption is correct: two standard deviations from the mean?

Also note that the function appears to calculate interquartile range, although nothing showed up for my data set. We'll need to provide an explanation of that as well in *In the Margins*.

**Comment by chantisnake** [comment]
That is my code, the file size is determined by number of word in the file. (although I forget how do we calculate how many word are in a file... probably by summing up the matrix)

**Comment by mleblanc321** [comment]
>two standard deviations from the mean?
yes (both larger than +2stdev and smaller than -2stdev)

so, an "anomaly" is a file that is outside these [-2, +2] stDev bounds, either much smaller or larger

**Comment by scottkleinman** [comment]
I cut out part of the code, but an argument called WordList is submitted to the function. So the output file size is probably number of words. Just a small tweak to the UI is needed to make that clear.

**Comment by chantisnake** [comment]
Yes the file size is just the num of word in the file. Maybe I need to make it more explicit in the comment

**Comment by scottkleinman** [comment]
I have updated the language to clarify the nature of the tests. The rest will have to go in _In the Margins_.

**Comment by mleblanc321** [comment]
yiqing: check out these comments as you review the code for Stats
