### ISSUE TITLE
Can I just delete lexo_document and lexo_dev repository since we are not using it?

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#271]
https://github.com/LexoDocument/lexodocument.github.io
Lexo_document is the repository and the group I created, and want to have the document in this gitpage, but I later realize that we are using scalar for the documentation. Therefore this repo haven't been maintained since then.

https://github.com/WheatonCS/LexosDev
Lexo_dev the repo we created to do development in, and later we realized we can use the dev branch or just release the software in the release tab. This repo is never used after that.

**Comment by scottkleinman** [comment]
I don't see any problem with deleting these repos.

**Comment by mleblanc321** [comment]
LexosDev was very useful for a practice platform last summer; yes, i think this can be deleted; (but i'm hoping cheng will be able to be with us for at least a few days at the start and perhaps he would lead us all, mostly rookies this year coming in :( ... thru a similar exercise?)

RE: LexoDocument -- i just don't want to lose any writing you might have done, cheng;  i can't really tell what is there ... so it looks like, yes, this repo can be removed also

**Comment by chantisnake** [comment]
I have already deleted them.
