### ISSUE TITLE
XML Handling

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#274]
This issue is mostly to get an idea down where I can remember it. Increasingly, we'll want to be able to handle XML files, generally TEI. Scrub seems to be the place to do that, but I think a separate screen to start with is a good idea so as not to complicate the UI. I suggest detecting all tags in the uploaded document and generating a list with check boxes. The user can then turn on or off the tags whose content they wish to retain. The problem we have encountered in the past is where we have something like this:

```xml
<l>This is a line of poetry containing a foreign <foreign><hi rend="italic">word</hi></foreign> that we might or might not want to retain.</l>
```
I think we can allow the user to select greedy or non-greedy pattern matching, or allow them to remove xml elements in stages (i.e. applying some settings, then changing the settings and applying again) to achieve the content they want. This should be relatively easy to implement.

Something for the "to do" list.

**Comment by chantisnake** [comment]
https://docs.python.org/2/library/xml.html#xml-vulnerabilities
Here is some vulnerabilities that this lib is exposed to. I see the two kind of attack that can break this module, this seems like can be handled by a `re.match()`, if it matched certain property just do not let them run on the server edition, and warn them that this document can consume lot of computing power, if they really want to try it, do the local install.

**Comment by scottkleinman** [comment]
I've used etree before; it's great. The entity expansion (and other?) vulnerabilities are worrying. We'll have to investigate security methods more thoroughly. A variety of strategies are described at [https://pypi.python.org/pypi/defusedxml/#defusedxml-elementtree](https://pypi.python.org/pypi/defusedxml/#defusedxml-elementtree).

**Comment by mleblanc321** [comment]
defusedxml 
and
defusedexpat 
libraries apparently address some of these concerns;  i wonder if we are vulnerable when we use regex elsewhere, e.g., RollingWindowAnalysis?

**Comment by scottkleinman** [comment]
It might be a good idea to contact the [TAPAS](http://beta.tapasproject.org/) folk to see how they sanitise uploads.

**Comment by scottkleinman** [comment]
This has been implemented, but the security issue can use some further thought. I'm going to open that up as a new issue.
