### ISSUE TITLE
Change format of lemmatisation and consolidation inputs?

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#276]
The current format we accept for lemmatisation and consolidation patterns in Scrub is a little bit confusing. Might it be better to accept JSON-formatted values? For instance, the following pattern would merge some Old English morphological variants onto a Modern English lemma:

``` json
{
 "king": ["cyning", "kyng", "kynges"],
 "eye": ["eage", "eages", "eagum"]
}
```

And this would consolidate orthographic variants on the form of the item key:

``` json
{
 "þ": ["ð"],
 "and": ["&", "ond"]
}
```

This might be a little clearer for the user, and the JSON string is easy to parse on the back end (we're probably parsing the input into a Python dict that looks the same).

Alternatively, we can accept the input as YAML, which is just as easy to parse in Python. Here's what the two strings would look like:

``` yaml
king: 
 - cyning
 - kyng
 - kynges
eye: 
 - eage
 - eages
 - eagum

þ: 
 - ð
and: 
 - &
 - ond
```

We could also implement a Javascript code highlighter to make it look prettier/clearer in the form element and do some format validation in the browser. I'm not sure what happens in the current version of Lexos if you enter an invalid format.

**Comment by chantisnake** [comment]
JSON and YAML are two very standard way of inputting dictionary. I think that both of them will be super easy to implement.

But one question, isn't this a little unintuitive? the input means ` change '&, ond' into 'and'`, shouldn't `[&, ond]: and` makes more sense and avoids confusion?

Do you think that JSON and YAML are prevalent among English professors, so that there will not be confusion in what this is and what this means?

**Comment by scottkleinman** [comment]
Yes, this question occurred to me. Currently, our syntax does have the advantage of reading left to right (change x into y), and your formulation `[&, ond]: and` is basically a compromise with JSON syntax, reversing the key and value pair. I think, though, that, if we wanted to preserve this order I'd want something like `&, ond -> and`, which is even clearer to a non-coder. Certainly, not many of our users will be familiar with JSON, so it's really a question of whether the bracketing adds clarity. Regardless, the downside is the brackets and quotation marks. That's why I thought YAML might be the way to go since it's much cleaner looking and easier for the average user to produce (but still easy to process on the back end).

There's no rush on this. We could ask our advisory board for their advice.

**Comment by mleblanc321** [comment]
i would think we'd want to separate the two issues:  user input from how we store it internally;  my point is that the user input should be in as easy as possible, but of course unambiguous;  then the code can parse this input into the format we want;  in short, i don't think we want to require users to input JSON or YAML formats

**Comment by chantisnake** [comment]
I think we can add YAML format to the accepted input. That is just a oneliner, I think... Of course, we will also keep the way we accept the document now.

**Comment by scottkleinman** [comment]
Just by way of information, this question was prompted by a lemma list I am compiling for research for a conference paper. The easiest way to compile the list is just to gather all the variant forms under a single lemma like this example:
```
oure: oure, ore, vre, our, ouwer, ouwere, ovre, vrne
out: out, oute, outen, ovt, ovte, owt
oþer: oþer, oþere, oþur, oþure
```
That's basically JSON. If people are likely to be creating lists like this, it makes sense not to make them reverse the order of the lemma and the variants. If we *wanted* to require JSON, we wouldn't have to intimidate people by telling them "use JSON format". We could simply describe it, as we do now. That is, "put quotes around each form, square brackets around the variants, commas between the lemmas, and enclose the whole thing in curly brackets".

Moses' idea is a good one, as it allows for varying levels of comfort. We can check if input is YAML (one line). If it is, we can convert it to JSON (one line). If we end up with valid JSON, we convert it to a Python dict (which is probably what we are feeding to the scrub algorithm). If it's not valid JSON, we can try to parse it according to the old format.

I've now confirmed that inserting an invalid format (e.g. `he->he, him`) produces no error message.

**Comment by chantisnake** [comment]
My only concern about this is that we need to keep the original input format for backward compatibility. At least, we need to give them a tool to convert the original format to JSON or YAML

Also I still thinks the brackets in JSON may be confusing, but we can test it out.

**Comment by cgnobrega** [comment]
formatting issue has been resolved (right?) but still no error when you input an invalid format
