### ISSUE TITLE
Getting support and reporting bugs

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#278]
As mentioned in issue #277, there is no clear way to get support or report bugs for Lexos. Perhaps we should add a link to the GitHub issues page (such links should also be added on the Lexomics and *In the Margins* sites). Or do we not want to send our users to GitHub?

**Comment by chantisnake** [comment]
I think GitHub issues are by design for the general user with nearly no computer skill

**Comment by scottkleinman** [comment]
I agree, although discussion around the submission process for [Programming Historian](http://programminghistorian.org/) revealed that some Humanities users nevertheless find the GitHub platform intimidating. It's probably a good idea to create a link directly to the [New Issue](https://github.com/WheatonCS/Lexos/issues/new) page.

**Comment by chantisnake** [comment]
I agree, also we can create an in the margin to work them though how to create a issue.

**Comment by chantisnake** [comment]
And I suspect most of them don't have GitHub account...

**Comment by scottkleinman** [comment]
An In the Margins article on how to create a GitHub issue is a great idea. A YouTube video like [this](https://www.youtube.com/watch?v=TJlYiMp8FuY), but slightly less aimed at project developers, would be great.

**Comment by chantisnake** [comment]
that would benefits a lot of people if we do that. That video is obviously out of date. I think we need to mainly explain the function of this tool bar

![capture](https://cloud.githubusercontent.com/assets/10100995/15132483/40ccaa9a-1628-11e6-8871-13da4859a225.PNG)

**Comment by mleblanc321** [comment]
at this point, i'm alil' leery of mixing general-user comments with development (github) issues; however, i also agree that _that is_ the place where we want them centralized;  however, the average user will _not_ have a github acct, thus, we need another mechanism;  i suggest we have a LINK from within ITM (in fact, the link should be liberally sprinkled throughout most/all ITM pages) to enter the message in a form and submit it to us (via email link?), that is probably best;   we can then review user input and consider the value of the comment to be included _in_ the ITM text for that particular section

**Comment by scottkleinman** [comment]
We could always set up a separate bug tracker/support repo. You don't actually need a GitHub account to post issues, do you?

Alternatively, we could have a simple Contact Us form. If it's something like a Google form, it can be embedded in an ITM page. (For that matter, it should be possible to submit GitHub issues from a a form in ITM using the GitHub API.)

But what you're suggesting is a review process for transferring the user comment to the ITM text. That makes sense for support requests and is a good way of growing the content. It's less useful for bug trackers. Of course, we could always pipe selected GitHub issues to ITM using the GitHub API, as well. Or is that just going linked-data crazy?

**Comment by mleblanc321** [comment]
let's keep v1 of this simple ...

**Comment by chantisnake** [comment]
I have never seen anyone leave a issue without a GitHub account. 

Although GitHub registration is easy, I suspect there is many people out there that don't want to register...

I don't really like google form, they are as ugly as the web Gmail, and there is no markdown the test displayed will have ugly '>' for quotation and reply.

But there is many advantage in Gmail, for example people all over the world 🗺 (besides china) have google accounts.

**Comment by scottkleinman** [comment]
Yes, I'd say GitHub is a non-starter if you have to have an account. Google forms _are_ ugly and a little bit inflexible, but they're probably sufficient for questions and reporting. We'll just have to re-format if we want to incorporate any material into In the Margins. If we want to get more sophisticated later, there are ways.

**Comment by scottkleinman** [comment]
We never implemented this. Is a contact form available in the Wheaton Wordpress implementation? If so, we could set that up and link to it. If not, a Google form might be the way to go for a quick implementation.

**Comment by mleblanc321** [comment]
i'll ask our web team

**Comment by mleblanc321** [comment]
hmm, using Google Form ...

https://docs.google.com/a/wheatoncollege.edu/forms/d/e/1FAIpQLSddEsRE2PcserYwcjtNpBAMF-YRKVrL4H4LtWDxHeNKoVVxcA/viewform

??

**Comment by scottkleinman** [comment]
I think that's good enough for now. Should we put a "Feedback and Support" link underneath the Twitter button?

**Comment by mleblanc321** [comment]
yes;  (i just started to do this, but i wasn't sure how to make this [link](https://docs.google.com/a/wheatoncollege.edu/forms/d/e/1FAIpQLSddEsRE2PcserYwcjtNpBAMF-YRKVrL4H4LtWDxHeNKoVVxcA/viewform) right-justified under the Twitter button but on same line as the MIT license)

**Comment by scottkleinman** [comment]
I've pushed a simple way of doing it. Feel free to modify it.

**Comment by mleblanc321** [comment]
for now, let's go with this;  at present, i'll get an email when someone submits ...
