### ISSUE TITLE
Convert Form Submissions to Ajax Requests

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#282]
In order to improve the UI, it is preferable to replace form submissions with Ajax requests so that a page refresh is not required. Flask's method of handling Ajax is perhaps a little atypical. You have to send the Ajax request through a route. Here's how you do it. Assume that you want to create a function that does something on the server and returns something to be handled in the page JavaScript. Create a function in the screen template or (better) `scripts_XX.js` file like this:

``` javascript
function myFunction(args) {
    // If args is a list of values, convert it to a json string
    data = JSON.stringify(args);

    // Submit the ajax request
    $.ajax({
        type: "POST",
        url: "/myFunction",
        data: data,
        contentType: 'application/json;charset=UTF-8',
        cache: false,
        success: function(response) {
            // Do something ...
            console.log(response);
        },
        error: function(jqXHR, textStatus, errorThrown){
            $("#error-modal .modal-body").html("Lexos could not perform the requested function.");
            $("#error-modal").modal();
            console.log("bad: " + textStatus + ": " + errorThrown);
        }
    });
}
```

Obviously, you can change the error message to say something more specific about the function.

In `lexos.py` add a route with the same name as the Javascript function (or whatever you pass in Ajax `url` value). The following example assumes you passed a list of file IDs as the `data` value, calls a function to modify each one, saves the results, and then returns a "success" message by Ajax.

``` python
@app.route("/myFunction", methods=["GET", "POST"])
def myFunctionFunction():
    fileManager = managers.utility.loadFileManager()
    for fileID in request.json:
        fileManager.doSomethingToAFile(fileID)
    managers.utility.saveFileManager(fileManager)
    return 'success'
```

That's pretty much it. The functions for the Manage screen are good examples of how the process works. We end up with a large number of routes in `lexos.py`, but it seems worth it to avoid page refreshes on the front end.

Screens already converted to Ajax in the Bootstrap branch:
- Upload
- Manage
- Scrub
- Cut

**Comment by mleblanc321** [comment]
helpful, scott;  this is all new to me ... and will be tricky for the new folks;  i'm hoping i can assign UI to a couple of (good) students;  do you agree that it is best to assign UI to one or two students who can then advise on UI issues to others as they interact with the UI in their particular work?

**Comment by scottkleinman** [comment]
Well, we got partway this summer, but we'll have to leave the rest for future development.

**Comment by chantisnake** [comment]
Okay, ajax has pop up too many times in our issue...
