### ISSUE TITLE
toy repo is done!

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#283]
I have created the toy repo for the new guys to practice `git` commands:
https://github.com/WheatonCS/ToyRepo

In the `readme`, there is all the command that I think is essential to use `git` to collaborate
In the `toy.md` is the file to mess around with.

What do you guys think? Am I planning to teach too many commands?

**Comment by scottkleinman** [comment]
This a great idea. I don't think it's too many commands.

**Comment by mleblanc321** [comment]
[sorry for delay;  very long day traveling to lasVegas];   good job, cheng;  i'll play with this alil;   mostly, we want to provide some examples, e.g., the order of use ... so let me try to play and add a sample use-path

**Comment by mleblanc321** [comment]
ugh, i'm not quite sure when doing a commit how to add my own id/credentials;  that is, when i commit shouldn't i include "mleblanc321" ?  (see changes to readme.md)

**Comment by chantisnake** [comment]
Nuh, I think git does that for you.

I will write up a guide to git in my blog, or inside lexos

**Comment by chantisnake** [comment]
@mleblanc321 if you want to setup ssh identification, this doc is the place to go:
https://help.github.com/articles/generating-an-ssh-key/

**Comment by chantisnake** [comment]
We have crushed this! close this
