### ISSUE TITLE
DataTables area select

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#285]
The new Bootstrap-based Manage tool loses the drag-select function implemented in Lexos 2.5. However, I've just seen that there is a DataTables plugin called [jquery.dataTables.areaselect](https://github.com/ApiO/jquery.dataTables.areaselect) which handles this functionality. We should implement it once we switch over to Lexos-Bootstrap, as it should lead to a smoother experience. It looks pretty easy to integrate.

**Comment by mleblanc321** [comment]
i'm moving Evan onto dataTables;  careyLewis (ENG student in lexomics) also showed me issues with dataTables just not loading when using 2- and 3-grams

**Comment by scottkleinman** [comment]
Oops! I apparently did not insert the updated tokenizer functions when I converted to Bootstrap. I have them in another local installation, and I just successfully did 5-grams. I'll get the functions transferred over to the master repo as soon as I can.

**Comment by scottkleinman** [comment]
Tokenizer should now work properly the next time you pull. Just don't choose the "Documents as Rows, Terms as Columns" option, as that is still on the "to do" list.

There's one important UI change in the new version. The table is generated showing the first ten rows on page load. If you click through the table pages (or choose other options), new content is loaded by Ajax. Getting 5-grams of _Emma_ takes about two seconds on my computer.

There's still a lot of work to be done on Tokenizer, but, if it tests OK for everyone, we should be able to close issue #257.

**Comment by scottkleinman** [comment]
This issue has been implemented.
