### ISSUE TITLE
Type Hinting 

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#287]
I just found out pycharm and python supports type hinting...

THIS IS THE THING I AM SEARCHING FOR SINCE I USES PYTHON

Here is two article on that:
https://www.jetbrains.com/help/pycharm/2016.1/type-hinting-in-pycharm.html
https://www.python.org/dev/peps/pep-0484/

Should we add type hinting in lexos? That will make pycharm more intelligent, and make the code to be more predictable

**Comment by scottkleinman** [comment]
I can't really see enough advantages for our type of project. The syntax is pretty unwieldy and adds an extra layer of complexity for newcomers to our development team or users wishing to modify or understand the code. Just my initial reaction after glancing at the links and a few other websites.

**Comment by chantisnake** [comment]
I would agree on that.

I love strong typed language, so I always hope python can be kind of like that.

I can understand why that would be harder...

**Comment by chantisnake** [comment]
seems like nobody thinks this is a good idea, I am closing this

**Comment by chantisnake** [comment]
I am gonna reopen this.

now that I am spend more time with python, and I have written two project with solid type hinting: 
https://github.com/MarkdownForAcademia/markdown_for_academia
https://github.com/PyerShell/PyerShell

I think type hinting is really a great thing to have.

First, it provides much better intellisense. This make programming much more enjoyable than before.

Second, and more importantly, types prevents many bugs that can happen on both while you are codding and you are refactoring.
I have fixed many bug last year caused by sending the wrong type of argument into the function (for example the function expect a list, but get a string), many of them will throw no errors and gives you very inconsistent behavior. Therefore it is very hard to trace and debug.

Third, in the programming language community, there is a growing believe that types will help people understand how the function works.
Because type is much more concise than documentation, developers can get a good idea of what the function does with first glance of the function, and then looking into the documentation will be so much easier.
If you have been following the new of programming language, there is a pretty popular new language that just focus on types, called [idirs](https://www.idris-lang.org/). It proposed a way called type-driven development: use type to replace some of the test and documentation. (python can never raise to that level because it is too dynamic, but types do reduce bugs.)

**Comment by chantisnake** [comment]
done
