### ISSUE TITLE
chardet fail to recognize some encoding

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#293]
in `Lexos / TestSuite / Scrubber / Digits /` there is an `allDigits.txt`

chardet will give `None` for encoding type(I think gedit is confused by this file too), but sublime text gives the encoding `UTF-8`

then I force chardet to decode this with `UTF-8` everything works.

-----Founded by Christina (I think that is her name...)

**Comment by chantisnake** [comment]
This issue is confirmed to be a chardet issue.

The discussion will be moved to here: https://github.com/WheatonCS/Lexos/issues/306

**Comment by scottkleinman** [comment]
If I understand correctly, chardet is not detecting the encoding of one or more characters in `allDigits.txt`. It might help to test outside of Lexos to see which ones. Maybe we can compensate.

**Comment by scottkleinman** [comment]
This one's tough.

```python
in[]:  str = "𐒠"
       isinstance(str, unicode)

out[]: False
```
But

```python
in[]:  str = "𐒠".decode('utf-8')
       isinstance(str, unicode)

out[]: True
```
I presume you did something like this. It suggests to me that the problem might be in Python (or at least Python 2.7). Anyone with Python 3 installed want to try it?

**Comment by chantisnake** [comment]
I don't think python 3 needs all the decode any more. because all string in python 3 is bytes...

But I am not sure about this.

**Comment by chantisnake** [comment]
yes, in python 3 all the string is automatically Unicode, and there is no Unicode type any more.

There is only bytes and string.

**Comment by chantisnake** [comment]
currently we know that chardet dose not handle `utf-16be`, `utf-16le` very well.

**Comment by chantisnake** [comment]
maybe investigating more about `cchardet` for future

**Comment by jacksonjreed** [comment]
allDigits.txt works now and we haven't run into any more issues since the new fix for this
more testing under different encodings may be necessary but I think it's safe to close this particular issue and open a new one if more specific issues arise
