### ISSUE TITLE
Ampersands are deleted by Scrubber

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#296]
This happens when the ampersand is free-floating (e.g. "this & that") or when the ampersand is not part of a special character rule set (e.g. `&rrot;`). We need to protect ampersands in these two positions. It's possible that this issue has contributed to token-counting errors in some texts.

**Comment by scottkleinman** [comment]
I have introduced a horrible hack to protect ampersands. Here's the code:

```python
text = re.sub("&", "LEXOSAMPERSAND", text)
text = text.translate(remove_punctuation_map)
text = re.sub("LEXOSAMPERSAND", "&", text)
```
It works, but the ampersand should really be removed from the punctuation map. I just can't figure out how.

**Comment by mleblanc321** [comment]
you should be able to just delete the & from the punctuation map with

 del remove_punctuation_map[38]

**Comment by scottkleinman** [comment]
That works. Thanks! I've pushed the fix.
