### ISSUE TITLE
handling TEI

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#297]
## TEI Handling
This should be fairly easy to implement. Here are the steps:

1. Detect tags (we already do this).
2. Display all tags with checkboxes for the user to choose. Options include "remove tag only", "remove tag and all inner content" (greedy matching), "replace tag content with content of attribute".

Because the user can choose which tags to eliminate, and can do so in repeated iterations, it should be possible to filter the content accurately to achieve the desired results.

In addition, structural tags can be converted to Lexos milestone delimiters. This is easy to do with empty elements like `<pb/>` (page break), but it is less straightforward with elements like `<l>Was this the face that launched a thousand ships?</l>` (a poetic line). How we handle these elements will depend on whether we continue to implement milestones as a "cut here" string or whether we adopt a more xml-like approach marking the beginning and end of structural elements.

I would recommend keeping the process described above independent of the scrub pipeline. That is, the scrub pipeline will treat xml files as text files "tags and all", although it should have the option to simply strip all the tags. But the TEI-handling dialog should execute a separate functions, which can be run before scrubbing to fine tune the text to be scrubbed and convert xml markup to milestones.

**Comment by scottkleinman** [comment]
This feature has been implemented.
