### ISSUE TITLE
Simularity Query

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#299]
as i was testing the updated SimQuery tool yesterday (thanks cheng for the update), i noted:

* once Evan updates DataTables on Tokenizer, we'll replace TinyTable currently on simQuery with DataTables

* we should sort the initial output from simQuery not by the default Rank but rather by the score, with smallest match first

**Comment by chantisnake** [comment]
I can do the second one, that is a one-liner

**Comment by chantisnake** [comment]
the second one is done.

**Comment by scottkleinman** [comment]
The first bullet point is also done.
