### ISSUE TITLE
(really) Understanding why one would use a tool and metric

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#300]
as i was testing the updated simQuery tool, i again realized that i personally don't have a good handle on why i would choose (a) a certain tool, e.g., clustering vs. simQuery and (b) one distance and/or linkage method over another;  

** perhaps we can assign Helen and/or another math-minded student to work on the English explanations of the metrics?

**Comment by scottkleinman** [comment]
I think this type of analysis will go in _In the Margins_ and will be an ongoing activity. Parts of the suggestions above have already made it into _ITM_. So I think we can close this issue.
