### ISSUE TITLE
apply scrub and apply cut buttons don't always work

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#302]
doesn't always apply cut or scrub the first time you click...or the second, can take multiple tries

**Comment by evanlaferriere** [comment]
Does it eventually go through? I've noticed that if there's an error going
on the scrubber page it'll throw exceptions in the terminal but say nothing
on the webpage.

**Comment by evanlaferriere** [comment]
If you have the special characters box filled out improperly it will never
apply the cuts nor tell you what is wrong

**Comment by chantisnake** [comment]
@evanlaferriere can you give us the info about how to reproduce this?

**Comment by evanlaferriere** [comment]
In the special characters box just write anything that isn't formatted
properly. When you try to scrub, it will fail, seemingly without reason if
you don't have the running window open

**Comment by evanlaferriere** [comment]
http://imgur.com/zgjNIMF

**Comment by chantisnake** [comment]
This is definitely a error on scrub regex...

let's call some scrub people...

**Comment by chantisnake** [comment]
@evanlaferriere this is very different matter with the original issue.

I will open a issue for that.

**Comment by chantisnake** [comment]
This issue is fixed
