### ISSUE TITLE
chardet maybe unreliable

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#306]
https://github.com/WheatonCS/Lexos/issues/301
https://github.com/WheatonCS/Lexos/issues/293

Those two issues are both problem inside of chardet...

maybe we need to find an alternative.

**Comment by evanlaferriere** [comment]
Both of those were handled better since we made chardet look at the first
5000 instead of 500. Further testing may be required.

**Comment by chantisnake** [comment]
I don't think #293 is solved by `MIN_ENCODING_DETECT = 5000` though.

**Comment by scottkleinman** [comment]
If that's the case, I think we can close this issue and re-open #293.
