### ISSUE TITLE
cut page tool-tip not in the correct place

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#307]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
N/A

### which file did I use
N/A

### what the bug looks like
when you are on cut page the tool tip for `Last Segment Size Threshold: ` is not in the correct place
![screenshot from 2016-05-31 15 45 29](https://cloud.githubusercontent.com/assets/10100995/15688189/ceb9c412-2746-11e6-8345-a457ce2f9e08.png)
 
### what I expect to happen
well, in the correct place...

### how to reproduce it
every time you open cut page 

### workspace file
* change the extension from `.lexos` to `.zip` before uploading it
Unrelated...

**Comment by scottkleinman** [comment]
This has been fixed.
