### ISSUE TITLE
cut by milestone tool tip is not in the correct place

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#308]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
N/A

### which file did I use
N/A

### what the bug looks like
when you resize the cut to make it narrower, the `Last Segment Size Threshold:` tool-tip works(see https://github.com/WheatonCS/Lexos/issues/307), but `Cut by Milestone ` tool tip does not work...
![screenshot from 2016-05-31 15 53 57](https://cloud.githubusercontent.com/assets/10100995/15688411/f8b0d2fa-2747-11e6-943d-44d037d978d1.png)

### what I expect to happen
tooltip should be in the correct position...

### how to reproduce it
resize the Bowers windows narrower until the layout changes for the first time...
then this happens  

### workspace file
* change the extension from `.lexos` to `.zip` before uploading it
Unrelated

**Comment by SocialHulkHogan** [comment]
I fixed this too
