### ISSUE TITLE
scrubbing deletes all new lines

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#309]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
default scrub
### which file did I use
any file
### what the bug looks like
removes all new lines so cut by line doesn't work
### what I expect to happen
new lines should stay in text
### how to reproduce it
click apply scrub and then try cutting line/segment
### workspace file
* change the extension from `.lexos` to `.zip` before uploading it

**Comment by chantisnake** [comment]
I did some testing on this, it seems like `Remove Tags ` option is the one that is messing this thing up.

**Comment by chantisnake** [comment]
this is related to 229 line in `scrubber.py`

```
        text = re.sub('\s+', " ", text)  # Remove extra white space
```

but this is not the only reason.

my test file is like:
```
this 

is 

a 

test 


```
in `test.txt`

**Comment by chantisnake** [comment]
WTF, line 237 is exactly the same as 229

**Comment by chantisnake** [comment]
yes... removing line 237 and 229 everything works fine...

I will go to topwords for now. Scrubber people need to take over this.

**Comment by scottkleinman** [comment]
There is a purpose for these lines, but they're for a function not yet implemented. It's fine to delete them for the moment. I think we can close this issue if the change is pushed.
