### ISSUE TITLE
remove all punctuation options

### ISSUE THREAD

**Issue by Landaluce** [WheatonCS/Lexos#310]
In the scrubber page, when I unchecked remove all punctuation, click preview scrubbing, refresh the website, then when I click on remove all punctuation, the options (keep hyphens, keep word-Internal apostrophes, and keep ampersands) are not displayed.

**Comment by scottkleinman** [comment]
Does this happen only when you are previewing? It may be that the option variables are not being written to the session file.

**Comment by JordanHelpsAlot** [comment]
Still happening as of today. If neither preview nor apply are clicked, leaving or refreshing the page will return the page to default settings. If either are performed, and remove all punctuation is left unchecked, a refresh or page change will permanently remember it was unchecked, locking you out of the three other  punctuation options.

**Comment by JordanHelpsAlot** [comment]
@SocialHulkHogan found a fix for this, changed it so that instead of adding the class "hidden" it now edits the display styling, which is what the checkmark does.
