### ISSUE TITLE
easy Installer

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#311]
make a 'double-clickable' installer for 

 * Windows 
 * Mac
 * Linux

**Comment by chantisnake** [comment]
windows installer is finished

`Updater` should be easy, but the exe to run should be a little harder.

Because it need to trigger python asynchronously...

I am still investigating on that.

Here is the zip for windows installer:
[install.zip](https://github.com/WheatonCS/Lexos/files/296636/install.zip)

unzip this and click `install.exe` would work.

for now, the script has been tested on:
 * windows 10 with powershell 5 and .NET framework 4.0

**Comment by JordanHelpsAlot** [comment]
Cheng... you are the man. Seriously. This is really great and I can't
believe you put it together so quickly. Everything works perfectly on my
station, what do you think is the next step towards making this
"double-clickable"? Also, I'm not sure if this is possible on your end but
the default directory for the install absolutely has to be on the desktop
for the install instructions to still be accurate (unless I missed a step
in your install or something). Also the instruction window that pops up
could mention that the user needs to navigate to the install instructions
of the lexos directory and jump to step 4 to actually run the program. But
again man, great job. No idea how you do it!

Jordan

**Comment by chantisnake** [comment]
This is all the binaries, including the installer, updater, and the runner (runner sounds a little weird to me)

[windows.zip](https://github.com/WheatonCS/Lexos/files/296675/windows.zip)

I will push the source code in a minute.
-----------------------------------------------------------------------------------------------

changing the install location is not tricky, but I guess people tend to delete their stuff on their desktop, but not on `C:\`.
We can talk about this tomorrow.

**Comment by chantisnake** [comment]
SmartScreen filter is blocking my own app... Interesting...

**Comment by evanlaferriere** [comment]
[here are some txts of the console when I installed it on my windows 7 laptop](https://github.com/WheatonCS/Lexos/files/300555/debug.txt)
It doesn't work.

**Comment by chantisnake** [comment]
For now I don't want to support windows 7 any more...

It is too hard to script something this complicated with a powershell and .NET framwork that old... and let it run natively without any extra installation. That is even too hard if we are using python...

All my personal poject only supports latest version of windows 10. 

For now just let windows 7 user to use the install guide... maybe we will support it later.

**Comment by mleblanc321** [comment]
i'm ok with this decision;  so essentially we say:  "auto installer for Windows v10.x only" ... users of Win7/8.x should follow the manual installation guide;  correct?

**Comment by chantisnake** [comment]
Yes, I feel bad that I cannot make an installer for windows 7 or 8.1, but I think this is the best I got, because automating download anaconda is complicated.

**Comment by chantisnake** [comment]
FYI, @JordanHelpsAlot If you want to do anaconda install without any prompt (all the Y/N questions).

do `bash anaconda2.sh -b`

**Comment by chantisnake** [comment]
Here is all the parameter you can pass into the installer:
```
Installs Anaconda2 4.0.0

    -b           run install in batch mode (without manual intervention),
                 it is expected the license terms are agreed upon
    -f           no error if install prefix already exists
    -h           print this help message and exit
    -p PREFIX    install prefix, defaults to $PREFIX
"
```

I found this in Linux script installer.

**Comment by chantisnake** [comment]
TODO: uses a cmd file to call powershell script with `-noprofile` parameter may boost speed

**Comment by chantisnake** [comment]
I have found the way to silently install anaconda...

I will change the windows script soon

**Comment by chantisnake** [comment]
Mac runner need a separated terminal to run.

I will put up a separated issue for that.
