### ISSUE TITLE
Please install missing requirement

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#312]
We are adding a new Python module as a requirement for Lexos. Please go to a command prompt and enter `pip install natsort` to install the package.

**Comment by chantisnake** [comment]
why not do a `requirement.txt`

**Comment by scottkleinman** [comment]
For now, we're just telling everyone to install it manually and updating our instructions. Eventually, a `requirements.txt` file is a good idea. I think it should be integrated into the auto-installers, so that's probably best implemented as part of the auto-installer enhancement process.

**Comment by scottkleinman** [comment]
Everyone on the development team has got `natsort` installed now, so I think I can close this.
