### ISSUE TITLE
implement culling and normalize option on sim query

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#314]
just implement the input on the front end and make a couple of handler on `managers.utility.GenerateSimQuery`(stuff like that)

For now, on the back end, I just set everything to false.

**Comment by scottkleinman** [comment]
In the old Lexos, these options were not present for Similarity Query, so I just used some fancy Javascript to hide them. If we want to these options, I can just delete the Javascript functions. Let me know if that's what you want me to do.

**Comment by chantisnake** [comment]
I think if we are not planning to use fancy stuff like tf-idf, normalize will not make any difference.

**Comment by scottkleinman** [comment]
I'll take care of this as soon as I can.

**Comment by chantisnake** [comment]
This should be no more than 10 lines of code on the back end.

**Comment by scottkleinman** [comment]
Culling options have been restored on the front end.

**Comment by chantisnake** [comment]
I will do the backend then, maybe this afternoon

**Comment by scottkleinman** [comment]
I just did a test with the top 10 MFWs and got a result. Does that mean that this was fixed on the back end?

**Comment by chantisnake** [comment]
I think the backend is done for this, I will look

**Comment by chantisnake** [comment]
I just went through the code and the backend is done.

it is fixed in this commit: https://github.com/WheatonCS/Lexos/commit/b92e2a3b51219fab4517080b58b25b281ab3058b

**Comment by chantisnake** [comment]
I think this is all done. I will close this.
