### ISSUE TITLE
little tip for lexos folder

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#315]
This is a little startup guide Flask:
https://realpython.com/blog/python/introduction-to-flask-part-1-setting-up-a-static-site/

in here it mentioned the `static` and `template` folder, which is two default folders for `Flask`:
> Here, we simply have a single file for our Flask app called app.py and then two folders, “static” and “templates”. The former houses our stylesheets, Javascript files, and images, while the latter is for HTML files.

**Comment by mleblanc321** [comment]
oh, helpful;  thx cheng

**Comment by chantisnake** [comment]
I think that people are getting this.

close this...
