### ISSUE TITLE
Tokenize breaks with xml files

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#316]
Loading Tokenize with an active XML file triggers `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 2: ordinal not in range(128)`. I'm not sure if the tagging is causing the problem or if it is an actual Unicode character in the file I am using. DOE and HTML files don't trigger the error.

We may need to catch errors and provide a message like "Lexos cannot tokenize one or more of your active documents. Please try running them through Scrubber before loading this page."

**Comment by chantisnake** [comment]
I think I have see this some where before...

smells chardety to me

**Comment by chantisnake** [comment]
here is the issue:
https://github.com/WheatonCS/Lexos/issues/301

**Comment by chantisnake** [comment]
debugging this would require the actual file or the workspace file...

**Comment by scottkleinman** [comment]
I have a partial fix. When I get this done, I'll try to catch instances where there is no document. See issue #319.

**Comment by scottkleinman** [comment]
Continuing to track down this problem, I have traced it to `generateCSVMatrixFromAjax()` in `utility.py`. This function calls `filemanager.getMatrix()`, which returns a list of lists called `countMatrix`. If you print it, you can see representations of the Unicode characters that cause Tokenize to crash. I added the following code after `countMatrix` was generated:

```python
for k,v in enumerate(countMatrix[0]):
        countMatrix[0][k] = v.decode('utf-8')
```
When I did this, Tokenizer did not crash. However, the single Unicode character `ȝ` I had in my test file was decoded to `č`.

So it seems like the problem is in how Unicode characters are piped in and out of `filemanager.getMatrix()`.

**Comment by mleblanc321** [comment]
... and this is assuming that the user did *not* use Scrubber, correct?  (i wonder how valid this assumption is ... or should be?)

**Comment by scottkleinman** [comment]
Yes, that's correct. I definitely think we need to allow for this possibility (and, if nothing else, catch the error).

**Comment by mleblanc321** [comment]
we might consider a set of minimal (safe) scrubbing that must always be done at a minimum, otherwise we'll chase situations all over?

**Comment by scottkleinman** [comment]
It's a thought. However, I just loaded an *actual* xml file (rather than the 6-line test file I was using), and with the decoding change I made above it now works and gets the character right. Maybe I just need to test this some more, and, if it continues to work, we can close this issue. *That* would be a relief.

**Comment by scottkleinman** [comment]
The fix works well with Chinese and curly quotes, so I'm going to tentatively say it works and close this issue.
