### ISSUE TITLE
Tokenize crash when there is no document

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#319]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
N/A

### which file did I use
None

### what the bug looks like
Tokenize crash

### what I expect to happen
do not crash

### how to reproduce it
On windows, press reset and go to scrub page, this will crash

### workspace file
* change the extension from `.lexos` to `.zip` before uploading it
not relevant

**Comment by scottkleinman** [comment]
It also crashes when documents have some Unicode characters. I'll try to fix it along with issue #316.

**Comment by scottkleinman** [comment]
Fixed.

**Comment by chantisnake** [comment]
just to log the commit:
https://github.com/WheatonCS/Lexos/commit/e39a751793dbdc6eadb50675965d2cfb1c4011af
