### ISSUE TITLE
Change document name and class does not accept Unicode in Manage

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#320]
### which option did I check
Manage

### which file did I use
Several Chinese files

### what the bug looks like
Ajax returns an error when I try to change the document name or class using Chinese characters. All Unicode characters will presumably return the same error.

**Comment by mleblanc321** [comment]
hmm, we've seen this before, right?  first we knew we had to fix words, then filenames; labels the same thing?

**Comment by scottkleinman** [comment]
It seems that there was an unnecessary decode method in the pipeline. Removing it fixed the problem, and I have pushed the change.
