### ISSUE TITLE
data structure of the workspace download is updated

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#322]
### This is a report about the new data structure of `workspace.lexos`

* recall that `workspace.lexos` is actually a `zip` file

#### why do I need to change this now
because we move the tmp folder on windows, therefore we need to fix `constants.WORKSPACE_UPLOAD_DIR` in order for the upload workspace to work

#### why is the new way better
  * the data structure inside the `zip` file is much more cleaner, see the commit message for f9d93437f32b79891119cbbbb4fb8cdcfe733362
  * we no longer need `constants.WORKSPACE_UPLOAD_DIR` here is why `constants.WORKSPACE_UPLOAD_DIR` is bad:
    1. this looks like a absolute path, in fact it has to be a relative path to work, which is confussing, see [L15](https://github.com/WheatonCS/Lexos/blob/57d95963ded314855fc543e1e03aa466f47ebc16/helpers/constants.py#L15)
    1. this path need to be set independently, because it has to be relative, therefore we cannot use `os.path.join(UPLOAD_FOLDER, WORKSPACE_DIR)` which is annoying because it is related to those two. see comment [L16](https://github.com/WheatonCS/Lexos/blob/57d95963ded314855fc543e1e03aa466f47ebc16/helpers/constants.py#L16)
    1. this is easy to set for Linux and mac, but for windows, this will require the user name of the user(because on windows the temp folder is in `HOME`, and in order to make this relative, we cannot simply use `~`)
  * the old way will not support cross platform work space transfer (if you download a workspace on windows running on localhost, then you cannot upload the workspace on mac localhost), the fix is very ugly, need to first use windows temp dir to find the file then try to use unix temp dir to find the file... which is purely annoying (in fact this will break if you download and upload using two different windows machine, because the temp dir on windows is related to username)

#### the weakness of the new way
* **but the new way will no longer supports old workspace file.**

#### the commits that are related to this change
https://github.com/WheatonCS/Lexos/commit/997e13a6bde3c09f5e909988ac32f74ea522cd20
https://github.com/WheatonCS/Lexos/commit/9032844c417be988cf300368b04ed556c6be2fc0
https://github.com/WheatonCS/Lexos/commit/f9d93437f32b79891119cbbbb4fb8cdcfe733362

**Comment by mleblanc321** [comment]
just excellent work, cheng (again);  thanks very much for the fix and explanation;  (i do not consider it a big deal that the new workspace fix won't support old workspace files;  with the new installers coming, this fix is timely as we will have many more localhost users);

**Comment by chantisnake** [comment]
Seems like everybody know this. I will close this.
