### ISSUE TITLE
Git introduction

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#323]
some people ask me to write up a guide for git.

Because there is too many images, so I put the guide inside of my blog.

http://chantisnake.github.io/2016/06/05/git-installation-and-basic-configuration/
http://chantisnake.github.io/2016/06/05/a-introduction-to-basic-git-concepts/
http://chantisnake.github.io/2016/06/05/how-to-use-git-on-pycharm-and-command-line-1/

This haven't finished, there will be some follow up article when I have time (and want to)...

**Comment by mleblanc321** [comment]
nice;  but we don't want to lose these links;  perhaps a link to these from inside the Install Guide area (somewhere) ??

**Comment by chantisnake** [comment]
yes... Let's think about this...

**Comment by scottkleinman** [comment]
I've added these links to the Developer's Guide.
