### ISSUE TITLE
tons of bug when I was playing around with Dream of the Red Chamber

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#326]
my workspace file:
[workspace (1).zip](https://github.com/WheatonCS/Lexos/files/301425/workspace.1.zip)

the uploaded document is tokenized Dream of Red Chamber

**Comment by chantisnake** [comment]
first, the tokenizor breaks when I checked Raw Count option...
![capture](https://cloud.githubusercontent.com/assets/10100995/15839382/0cb79f72-2c11-11e6-968d-cac90ad2eecb.PNG)

second K-mean is to small to see anything.

Third There are three documents not on the kmeans graph...
![capture](https://cloud.githubusercontent.com/assets/10100995/15839420/3ad17dce-2c11-11e6-83f2-075d1ab05433.PNG)
notice that three of the documents name is hanging down on the graph...

**Comment by chantisnake** [comment]
loading ring on Dendrogram breaks:
![capture](https://cloud.githubusercontent.com/assets/10100995/15839493/a45f890c-2c11-11e6-81dd-0f2343d9b6da.PNG)

and we have huge amount of wasted space down the dendrogram:
![capture](https://cloud.githubusercontent.com/assets/10100995/15839572/ffbda2b6-2c11-11e6-9d38-30e6fdbd969a.PNG)

**Comment by chantisnake** [comment]
also we may need a better version of the Dream of the Red Chamber.
I am pretty sure this is 
![capture](https://cloud.githubusercontent.com/assets/10100995/15839816/b06a3c7c-2c13-11e6-834f-7490ea48c7e7.PNG)
not Chinese

**Comment by Landaluce** [comment]
K-mean is now fixed

**Comment by chantisnake** [comment]
All of them is fixed or moved to different issues.
