### ISSUE TITLE
Active documents coffee always active

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#330]
### which option did I check
I hit reset
### which file did I use
none
### what the bug looks like
the coffee that says you have active documents always says that, even as a lie
### how to reproduce it
hit reset and you will notice that the coffee is still active no matter what you do
### workspace file
[workspace.zip](https://github.com/WheatonCS/Lexos/files/304963/workspace.zip)

**Comment by scottkleinman** [comment]
It's a place holder at the moment. There is no actual detection code. It's on the to do list.

**Comment by evanlaferriere** [comment]
oops
