### ISSUE TITLE
Lexos_Assets repo

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#331]
Since the local install is more and more mature. We need to consider the user who actually downloads from this repo, not just developers.

We are letting the user downloading couple of mega bytes of file from `testSuit` and all kinds of guides, and they are not gonna use them at all.

Can I move them to a separated repo in WheatonCS?

**Comment by SocialHulkHogan** [comment]
I support that Idea.

**Comment by SocialHulkHogan** [comment]
-steven

**Comment by mleblanc321** [comment]
can we hold on that for now;  we really make lots of use of testSuite while debugging ...

**Comment by chantisnake** [comment]
well, it is not removing them, is just make a separated repo that is only for us developer.

**Comment by mleblanc321** [comment]
fair enough;  let's chat about this

**Comment by scottkleinman** [comment]
I've reframed this as issue #452.
