### ISSUE TITLE
Active Documents Counter in Manage

### ISSUE THREAD

**Issue by bbrule** [WheatonCS/Lexos#332]
### which option did I check
Default Manage, after cutting a document and before pressing either select, deselect, or delete on the manage page.

### which file did I use
Multiple files. 

### what the bug looks like
Active Documents counter does not correspond to actual amount of active documents, seems to be attached to the selected files on the first page (if four documents are selected on first page and five on second, only shows four active documents)

### what I expect to happen
The counter to correspond to total amount of active documents. 

### how to reproduce it
Upload file, cut file, enter manage page.

**Comment by SocialHulkHogan** [comment]
I fixed this
