### ISSUE TITLE
Scrub does not cache options

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#335]
It looks like the options being sent to Scrub on the back end are not being cached to the session. If you select options, navigate to another page, and then return, your options are lost.

**Comment by evanlaferriere** [comment]
That only happens if you don't run preview/apply. Do we want to save them if they never hit preview or apply?

**Comment by chantisnake** [comment]
Cannot reproduce this, I think this maybe got fixed.
