### ISSUE TITLE
Active Document Detection

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#336]
This is mainly a notification that an active document detection function has now been implemented for all Lexos tools. The function must be called at the beginning of each Flask route like this:

```python
@app.route("/scrub", methods=["GET", "POST"])
def scrub():
    # Detect the number of active documents.
    numActiveDocs = detectActiveDocs()
```
When the template is rendered, it should pass the variable `numActiveDocs`. For instance:

```python
return render_template('scrub.html', previews=previews, haveTags=tagsPresent, haveDOE=DOEPresent,
haveGutenberg=gutenbergPresent,numActiveDocs=numActiveDocs)
```
If either of these is missing, Lexos will crash.

At the moment, `detectActiveDocs()` is at the top of `lexos.py`. However, it should probably be moved to `file_manager.py`. (This is a "to do" item.) At the top of `lexos.py` there is also a Flask route which calls `detectActiveDocs()`. This is in case we ever need to call it by Ajax.

`detectActiveDocs()` returns the number of active documents, so this number is available in the template if it is needed.

**Comment by chantisnake** [comment]
This has been here long enough, I will close this for now.

Please feel free to reopen it.
