### ISSUE TITLE
move installer into install dir

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#337]
Hi @JordanHelpsAlot I have moved the installer into `install` directory, because my windows installer will need the Url to be in `install`... (see `install.cmd` and `update.cmd`)

But if you think this dir location is ridicules, please reply, this is an easy change in the script.

If you think this is okay, then reply or close this issue.

---
By the way, the `exe` installer is outdated.

**Comment by JordanHelpsAlot** [comment]
Oh I'm sorry Cheng I should have been more careful. Of course wherever you
need that installer to be is where it should go. And thank you for the
heads up you can upload the updated version if you haven't already or send
it to me and I can upload it.

**Comment by chantisnake** [comment]
that is `install.cmd`, if you want to test, you can just download that and double click it. or put the content in CMD, it's just a one linear (the first line simply means do not write and output).

It should be much faster than the original one. I have changed a few things.

**Comment by chantisnake** [comment]
I'm gonna close this. Reopen this if you have further question.
