### ISSUE TITLE
(beating heart) icon on (long) upload

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#338]
[from mikeDrout @Mellon workshop]: One of the computer science profs here suggested that we should have a "heartbeat" during text upload.  He uploaded 150 texts all at once through drag and drop (and it worked), but suggested that a visible "heartbeat" would let users know that the program is uploading the texts.  Seemed like a good idea.  

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
During upload

### what I expect to happen

icon appears during upload;  [hmm, don't we have a twirling/loading icon now?]

### how to reproduce it

upload many files

**Comment by SocialHulkHogan** [comment]
I'm going to be a little late today. Having stomach cramps.

**Comment by scottkleinman** [comment]
This feature was there in the infrastructure. I have activated it.
