### ISSUE TITLE
cutting seg/doc after removing white spaces

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#340]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
remove all white space in scrub, then seg/doc in cut
### which file did I use
any file
### what the bug looks like
stays in one segment no matter how many segments you told it to split into because seg/doc splits an even number of tokens into each of the segments, since there is only one token without white spaces it only ever has one segment
### what I expect to happen
it should split into the selected number of chunks, possibly with even numbers of characters instead of tokens when these options are selected
### how to reproduce it
upload any file, scrub: removing all white spaces, cut: seg/doc
### workspace file
* change the extension from `.lexos` to `.zip` before uploading it

**Comment by JordanHelpsAlot** [comment]
Maybe there could be a warning on the remove white space tooltip? Something like, this will create a document with only one segment, cutting the documents by segment must be done prior to removing all white space?

**Comment by cmccarthy41899** [comment]
From what I understand we are mainly removing white spaces for languages like Chinese where spaces do not signify beginnings and ends of words. Cutting by segment before removing white spaces wouldn't fix this. The segments in these languages would split paragraphs or sentences evenly over the number of segments chosen since they don't have spaces between words.

**Comment by scottkleinman** [comment]
Yes, I think in this case the user would quickly discover that this is not what they want to do and start over.
