### ISSUE TITLE
preview scrubbing when removing whitespace removes new lines between ellispes

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#341]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
preview scrubbing with remove white spaces
### which file did I use
any file
### what the bug looks like
removes new lines between ellipses in preview
text...

...text
becomes
text......text
this is because the text sent through scrubbing for preview is only the section of text you see in the preview window.  so when it is scrubbed to remove white spaces it removes the new lines separating the ellipses as well
### what I expect to happen
the new lines separating the beginning of the text from the end to stay in the preview
### how to reproduce it
upload any file, scrub: remove all white spaces & preview scrubbing
### workspace file
* change the extension from `.lexos` to `.zip` before uploading it

**Comment by scottkleinman** [comment]
If you put the preview text in a Javascript alert, the new lines appear to be there. So this may be a case of Jinja not recognising `\n`. The solution might be [http://flask.pocoo.org/snippets/28/](http://flask.pocoo.org/snippets/28/).

**Comment by chantisnake** [comment]
yes, I think we can do add that to HTML_escape, to change \n to <br>

**Comment by mleblanc321** [comment]
hmm, i tried to change `html_escape()` to change TABs to the "em space, roughly four normal spaces" ... but that didn't work

```
        u'\t': u"&emsp;"
```

**Comment by scottkleinman** [comment]
OK, [http://flask.pocoo.org/snippets/28/](http://flask.pocoo.org/snippets/28/) works, but it needs some modifications as discussed at [http://stackoverflow.com/questions/12523725/why-is-this-jinja-nl2br-filter-escaping-brs-but-not-ps](http://stackoverflow.com/questions/12523725/why-is-this-jinja-nl2br-filter-escaping-brs-but-not-ps).

I have implemented this and added the relevant function to the end of the temporary development functions section in `lexos.py`. However, I think there is probably a better place to put it. I am taking suggestions before I close this issue.

**Comment by mleblanc321** [comment]
ok (but on one read, i can't write the comments that the code begs for on inserts like this); scott, can you sprinkle some # comments in there while it is fresh in your mind?

you guys decide where `nl2br()` should live ...;  aret nl2br()` and `general_functions.natsort` alike in that those are the only jinja2 filters set to our functions?

```
# lexos.py (at bottom)
install_secret_key()
app.debug = not constants.IS_SERVER  # open debugger when we are not on the server
**app.jinja_env.filters['tynl2brpe'] = nl2br**
app.jinja_env.filters['type'] = type
app.jinja_env.filters['str'] = str
app.jinja_env.filters['tuple'] = tuple
app.jinja_env.filters['len'] = len
app.jinja_env.filters['unicode'] = unicode
app.jinja_env.filters['time'] = time.time()
**app.jinja_env.filters['natsort'] = general_functions.natsort**
```

**Comment by scottkleinman** [comment]
Flask does not import global variables in the template. Instead, it is set up to add them to the template's evaluation time context in a way that can be configured. That's what the function decorators are doing. The function itself just wraps the string in `<p>` tags and converts and internal new lines to `<br/>`. It uses the `Markup()` function to temporarily disable Jinja's auto-escaping in the context of the result returned to the template. I've added some comments to this effect.

The function works, even though I added `app.jinja_env.filters['**tynl2brpe**'] = nl2br` instead of `app.jinja_env.filters['**nl2br**'] = nl2br`. So this line is clearly not necessary. But we use it for `general_functions.natsort`, as you point out. So I'm going to try to move the function there and see what happens. If it works, I'll push the new commented code.

**Comment by scottkleinman** [comment]
I couldn't figure out how to transfer the filter over to `general_functions.py`--the decorators seem to add a layer of complexity that's not there for `natsort`. So I just added comments and moved the code block to the "helpful functions" section in `lexos.py`. I think that's good enough for now.
