### ISSUE TITLE
Project Gutenberg warning pop-up missing

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#342]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which file did I use
any Project Gutenberg file
### what the bug looks like
PG pop-up warning doesn't show up upon entering scrub page 
### what I expect to happen
pop-up warning to display when entering scrub page with a project Gutenberg file active
### how to reproduce it
upload any PG file, got to scrub page
### workspace file
* change the extension from `.lexos` to `.zip` before uploading it

**Comment by scottkleinman** [comment]
Fixed.
