### ISSUE TITLE
Tags function removing ALL extra white spaces

### ISSUE THREAD

**Issue by JordanHelpsAlot** [WheatonCS/Lexos#344]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**
Original Issue (described below) was that (we thought) Remove White Spaces was being called when unchecked
------------------------------------------------------------------------------------------------------------------------------------
### which option did I check
No option checked

### which file did I use
Any file with whitespace other than basic word separators
ex) this  is   a    test      of      spacing

### what the bug looks like
ex) this is a test of spacing

### what I expect to happen
ex) this  is   a    test      of      spacing

### how to reproduce it
Upload a file with whitespace and preview scrubbing with no options checked or selected

**Comment by JordanHelpsAlot** [comment]
This issue might actually not be related to the remove white space function. When I commented out the only code that calls the function, the excess white spaces were still removed.

**Comment by JordanHelpsAlot** [comment]
@cmccarthy41899  and I added a conditional to the tag handler function so the excess white spaces are preserved by default again. We did find that the tag handler basically removes all excess white space and replaces it with a single space (even on spaces unrelated to tags). Is this what we want?

**Comment by scottkleinman** [comment]
I'm not sure I understand this issue correctly, but it may be about whether tags are replaced with `" "` or `""`. Consider the following TEI markup:

```xml
This is a <choice>
    <orig>good choice</orig>
    <reg>bad choice</reg>
</choice>.
```
Here we want to remove white spaces so that we end up with something like:

```xml
This is a good choice.
```
However, consider this:
```xml
This is a <choice>
    <orig>good choice</orig>
    <reg>bad choice</reg>
</choice><note>With an asterisk</note>
```
In this case, collapsing spaces might give us

```xml
This is a good choiceWith an asterisk
```
I have a feeling that the appropriate choice of space or no space to replace tags will depend on the individual tag. We should probably add a "Replace tag with space option". Scrubber will subsequently collapse multiple white spaces into one space for tokenisation purposes.

**Comment by chantisnake** [comment]
I don't think Scott's example will actually happen... I think in handle tag, we replace all the tags with white space.

**Comment by scottkleinman** [comment]
At present that's true. My point was that in the future we should give users a choice of whether to remove tags or replace them with a space. I know that when I use the current implementation on my xml files I end up with some merged words.

**Comment by scottkleinman** [comment]
Just following up on Jordan's question from [June 14](https://github.com/WheatonCS/Lexos/issues/344#issuecomment-225916854), I'm pretty sure that we do want to collapse all white spaces to a single space within tag content. Most XML processors will do that anyway, and Lexos certainly will when it tokenises. We don't want spaces _within_ tags collapsed, but that doesn't happen if the user selects "Leave Tag Alone".

So I'm pretty sure the only thing left to worry about it the ability for the user to select whether an element should be removed completely or replaced by a space. But I think that's an enhancement for the future. I think I am going to close this issue and open a new one for that.
