### ISSUE TITLE
Rounding?

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#345]
In stats, the average term frequency is only showing to the tenths place, but not rounded to the nearest tenth. Do we want to do that? Are we doing that anywhere else?

**Comment by scottkleinman** [comment]
I think we do want rounding, but this issue makes me question whether we should round to the nearest hundredth, or possibly thousandth. Users may see such fine distinctions as insignificant, but, if nothing else, it will help rank the documents if they choose to sort the table by average term frequency.

**Comment by evanlaferriere** [comment]
Where is the statistical significance for term frequency?

**Comment by chantisnake** [comment]
I would say, not much...

because the distribution of word count is highly skewed, the average is not that helpful. (Median is even less helpful at this case)

But, if there is a high average term frequency, then we can know that there is something wrong with the passage. There is super high repetition in some or all the word.

---

By the way `statistical significance` has some other meaning... It is confusing.

**Comment by evanlaferriere** [comment]
Is stat significance not the largest unit you round to that is still accurate?

**Comment by scottkleinman** [comment]
Whether deviations in average term frequency are statistically significant will probably vary with the type of texts you are studying, and I suspect that statisticians will say that they never are with the size of the data sets most users are likely to be uploading. So this statistic might only really be usable with the greater freedom of interpretation allowed in the Humanities, or, at least only meaningful in tandem with contextual knowledge from the user's familiarity with the texts.

**Comment by chantisnake** [comment]
I would say that anything below tenths place will not matter that much, but that is just my personal judgement.

**Comment by scottkleinman** [comment]
I think that's right from an interpretive point of view, but, as I mentioned earlier, it will effect the sorting in the UI. Perhaps when implementing the rounding, we should switch it to hundredths, and we'll survey users to see how that goes.

**Comment by scottkleinman** [comment]
The following table gives an idea of why it's useful to round on hudredths. I cut _Pride and Prejudice_ into ten segments and generated the table first with rounding on tenths and then on hundredths. The table column below all provide both statistics but sort by hundredths:

| Document Name          | Average Term Frequency (tenths) | Average Term Frequency (hundredths) |
|------------------------|---------------------------------|-------------------------------------|
| Pride_and_Prejudice_9  | 6.2                             | 6.24                                |
| Pride_and_Prejudice_1  | 6.2                             | 6.17                                |
| Pride_and_Prejudice_8  | 6.2                             | 6.15                                |
| Pride_and_Prejudice_3  | 5.9                             | 5.85                                |
| Pride_and_Prejudice_4  | 5.8                             | 5.77                                |
| Pride_and_Prejudice_7  | 5.8                             | 5.76                                |
| Pride_and_Prejudice_5  | 5.7                             | 5.67                                |
| Pride_and_Prejudice_2  | 5.4                             | 5.36                                |
| Pride_and_Prejudice_6  | 5.3                             | 5.33                                |
| Pride_and_Prejudice_10 | 4.1                             | 4.14                                |

Segments 9, 1, and, as well as 4 and 7 may be sorted in any order if they are rounded by tenths. Rounding by hundredths does not guarantee sorting according to an accurate ranking, but it makes it much more likely without making the numbers unreadable.

I've made the fix, so I'll close this issue pending user feedback.
