### ISSUE TITLE
Some Individual options in cut disappear when remove white spaces has been applied in scrub

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#347]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
remove white spaces in scrub then individual options in cut
### which file did I use
any file
### what the bug looks like
if the file has had the white spaces scrubbed out and you select individual options in cut for that file the only options are characters/segment, lines/segment, and cut by milestone (no size selection)
### what I expect to happen
It should have all of the options that the other ones have
### how to reproduce it
upload any file, scrub removing white spaces, cut go to individual options
### workspace file
* change the extension from `.lexos` to `.zip` before uploading it

**Comment by chantisnake** [comment]
this is interesting, I will take a look at it.

**Comment by cmccarthy41899** [comment]
It seems to only be a problem on Firefox, not Chrome

**Comment by chantisnake** [comment]
That looks like front end = =

I will probably out after the first try...
