### ISSUE TITLE
XML handling needs extensive testing

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#350]
I'm trying to use regex to solve our handle_tags woes, but these statements aren't doing the trick

``` python
if 'xmlhandlingoptions' in session:
            for tag in session['xmlhandlingoptions']:
                action = session['xmlhandlingoptions'][tag]["action"]
                if action == "remove-tag":                # Should only take out the tags
                    text = re.sub("(<.*>)?|(<\/.*>)?", "", text, re.MULTILINE, re.DOTALL)
                if action == "replace-element":         # Should replace the tag
                    attribute = session['xmlhandlingoptions'][tag]["attribute"]
                    text = re.sub("(<.*>.+<\/.*>)?", attribute, text, re.MULTILINE, re.DOTALL)
                if action == "remove-element":         # Should take out the tag+content
                    text = re.sub("(<.*>.+<\/.*>)?", "", text, re.MULTILINE, re.DOTALL)
```

**Comment by chantisnake** [comment]
use 

<p>```</p> python
your code here
<p>```</p>

to get a better display.

**Comment by scottkleinman** [comment]
Did you check these in [https://regex101.com/](https://regex101.com/)? The code itself looks all right to me, assuming that the comments have `#` in front of them in the actual code.

If you can't get the regex working, another possible approach is to use Beautiful Soup.

**Comment by chantisnake** [comment]
Beautiful Soup is a nice idea, it is much more readable than regex...

**Comment by evanlaferriere** [comment]
I'll look into BS because the regex is too greedy.

**Comment by chantisnake** [comment]
The regex looks good to me, but I think instead of `.+` you probably should use `.*`

I am not familiar with the second (`action == "replace-element"`) option, so I cannot give you suggestion on that. The first and the last is correct

**Comment by chantisnake** [comment]
also, can you be more specific on 
> but these statements aren't doing the trick

for example, give us some of the input and output examples

**Comment by evanlaferriere** [comment]
So rn if you handle all tags to remove tag only, it empties that text. Also, preview is wildly unpredictable for describing how xml files will come out 
[Book.xml.txt](https://github.com/WheatonCS/Lexos/files/316744/Book.xml.txt)

**Comment by chantisnake** [comment]
so you are sure that it is these lines problem?

**Comment by chantisnake** [comment]
I will take a look at it

**Comment by scottkleinman** [comment]
I think the pattern you want to use to strip all tags (including their attributes) is

```python
pattern = re.compile(
ur'<(?:[A-Za-z_:][\w:.-]*(?=\s)(?!(?:[^>"\']|"[^"]*"|\'[^\']*\')*?(?<=\s)\s*=)(?!\s*/?>)\s+(?:".*?"|\'.*?\'|[^>]*?)+|/?[A-Za-z_:][\w:.-]*\s*/?)>'
)
```

See line 306 of `scrubber.py`.

**Comment by evanlaferriere** [comment]
That line hurts my head. Is there a verbose copy of it somewhere?

**Comment by scottkleinman** [comment]
See [https://github.com/WheatonCS/Lexos/issues/295](https://github.com/WheatonCS/Lexos/issues/295) for the verbose description.

**Comment by scottkleinman** [comment]
Looking at issue #295 referenced above, I see that we need to handle some space issues. In some cases, tags will need to be replaced with " ", and in others with "". (The problem with ampersands was closed in issue #296.) I think we should just get it working with no space to begin with, and we can add a space option in the UI later. But I thought I'd transfer that issue over here so that we can follow up.

**Comment by evanlaferriere** [comment]
Okay, now remove tags works.

**Comment by scottkleinman** [comment]
Good news. Now I'm worried about replacing elements with the values of their attributes. This may be insanely difficult with regex. This might be easier (using an element and id from the sample xml file):

```python
from lxml import etree
root = etree.XML(text)
elementName = 'book'
attributeName = 'id'
for node in tree.findall('.//'+elementName):         # Loop through the designated elements
    if "id" in node.attrib:                          # Get the attribute value
        attributeValue = node.attrib['id']
        for child in node:                           # Remove all children of the element
            node.remove(child)
        node.text = attributeValue                   # Set the element's content to the attribute value
textString = etree.tostring(root, pretty_print=True) # You can print this to the console to see the result
```
This will leave you with the original element containing the attribute value. Now all you have to do is strip the element tags.

**Comment by evanlaferriere** [comment]
I don't understand what that actually does? I've also changed that data structure to something a little more comprehensible, so what it does might not work.

**Comment by scottkleinman** [comment]
The code actually introduces an xml parser, the [lxml](http://lxml.de/) processing library. It translates the string text file (including xml/html/sgml tags) into a hierarchical structure (a list of lists and dictionaries) which can then be parsed through normal Python algorithms (e.g. `for node in root`) and/or [XPath](http://www.w3schools.com/xsl/xpath_intro.asp) expressions (e.g. `'.//book'` = find all child nodes of the root consisting of the element`<book>`). So, basically, the code parses the text into an XML tree, finds all elements with the user-defined name, and grabs the value of the user-defined attribute. It then deletes all child nodes of the element and makes the attribute value the element's new content. So it would change

```xml
<p type="Greetings">Hello, <hi rend="italic">friend</i></p>
```
into

```xml
<p>Greetings</p>
```

**Comment by evanlaferriere** [comment]
As of this moment, the handle_tags code looks this:
```python
 for tag in session['xmlhandlingoptions']:
                action = session['xmlhandlingoptions'][tag]["action"]
                if action == "remove-tag":
                    pattern = re.compile(u'<(?:'+tag+'(?=\s)(?!(?:[^>"\']|"[^"]*"|\'[^\']*\')*?(?<=\s)\s*=)(?!\s*/?>)\s+(?:".*?"|\'.*?\'|[^>]*?)+|/?'+tag+'\s*/?)>',re.MULTILINE|re.DOTALL)
                    m = re.findall(pattern, text)
                    m = list(set(m))  # unique values take less time
                    for st in m:
                        #st may have regex characters, re.escape(st) will backslash all characters in st
                        text = re.sub(re.escape(st), " ", text,re.UNICODE)

                elif action == "replace-element":
                    attribute = session['xmlhandlingoptions'][tag]["attribute"]
                    pattern = re.compile("<\s*"+tag+".*?>.+?<\/\s*"+tag+".*?>", re.MULTILINE | re.DOTALL)
                    m = re.findall(pattern, text)
                    m = list(set(m))  # unique values take less time
                    for st in m:
                        # st may have regex characters, re.escape(st) will backslash all characters in st
                        text = re.sub(re.escape(st), attribute, text, re.UNICODE)

                elif action == "remove-element":
                    pattern = re.compile("<\s*"+tag+".*?>.+?<\/\s*"+tag+".*?>", re.MULTILINE | re.DOTALL)
                    m = re.findall(pattern, text)
                    m = list(set(m))  # unique values take less time
                    for st in m:
                        # st may have regex characters, re.escape(st) will backslash all characters in st
                        text = re.sub(re.escape(st), " ", text, re.UNICODE)
                else:
                    pass #Leave Tag Alone
```
Since this seems to be working I'm closing this issue

**Comment by mleblanc321** [comment]
so we are still using regex (rather than iterate over the DOM via some parser);  scrubbing is hard;

i re-opened this issue since we need to test, test, test ...

**Comment by scottkleinman** [comment]
I've changed the title of this issue to reflect the current state.

**Comment by scottkleinman** [comment]
I now think this could use a new issue just for testing. Closing this.
