### ISSUE TITLE
Firefox in general

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#353]
Okay so In addition to firefox being super annoying about how they create web pages, I noticed something really disturbing. On Karen's computer, she was using Firefox and I noticed that some graphical problems I fixed were still on here page. I told her to pull but she showed me she was up to date. I pulled up chrome and viewed the element in question (which was the tooltip css) and it was up to date. I deleted her firefox cookies and history and sure enough that solved the problem, but this is bad. If users are using localhost installations of firefox, apparently firefox saves and applies old layouts. Even if they reinstall or pull from github, theres a chance that firefox will block updates to the app. Off topic, this is why firefox is trash. This is related to my other issue too about jinja not working properly in firefox. I don't like the sound of telling people to use chrome because plenty of people think firefox is a good browser. I'm not sure what to do, these issues might be unsolvable.

**Comment by chantisnake** [comment]
did you try `ctrl-r`

**Comment by SocialHulkHogan** [comment]
One idea I had was to not use jinja to mix html files into one page and just have each page have it's own html file. The other problem could be solved by telling people to delete their cookies before doing a pull or reinstall if they use firefox.

**Comment by SocialHulkHogan** [comment]
It was many days behind, would ctrl-r have helped?

**Comment by chantisnake** [comment]
all the browser cache js and css to speed up the webpage.

`ctrl-r` means delete cache, cookies and history is obviously unrelated to this.

**Comment by SocialHulkHogan** [comment]
Also it was only happening on Karen's box. Idk if that's because I don't use firefox. If someone else uses Firefox we could see if they have the problem and if ctrl-r helps

**Comment by SocialHulkHogan** [comment]
also clearing cookies was definitely related to this issue, because it fixed the problem.

**Comment by SocialHulkHogan** [comment]
They shouldn't be permanently caching css. the fact that her computer was restarted multiple times and the css continued to not change is a big problem.

**Comment by chantisnake** [comment]
I wonder what option did you check.

firefox by default will clear history, cache and cookies together.

**Comment by SocialHulkHogan** [comment]
I watched Jordan do it, he cleared browsing history and cookies

**Comment by scottkleinman** [comment]
Browser caching is an ongoing problem which we were not able to resolve last year. This is annoying, but I'm hoping that it will not be an issue for non-developers using the finished project.

**Comment by SocialHulkHogan** [comment]
So should we include a message while it's in the beta that recommends clearing cookies? It bothers me that a member of our own dev group didn't even know she wasn't dealing with the latest code. Not that it was her fault at all, but still.

**Comment by scottkleinman** [comment]
We should all be aware of the problem and regularly clear the cache and reset our session (which also often works). We should also put a note to that effect in _In the Margins_.

This is emerging as not really a Firefox-specific issue, but more of a general browser caching issue, so I am going to re-title it for search purposes. I also think we've got as far as we can get with it, so I'll close it (re-open if there's more to discuss).
