### ISSUE TITLE
Re-direct users to Upload if there is no session

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#354]
Lexos can generate an error if the user goes to a screen before beginning a session. We should probably catch this and re-direct them to Upload to begin the session.

Multicloud might need some different handling because the user may go there directly to upload a MALLET file. In this case, we'll need to create a session somehow.

**Comment by evanlaferriere** [comment]
Really easy solution, put this at the start of any function that has is taking a 'GET' call:
```python 
if not session:
        return upload()
```
This definitely needs a message or something to inform them of what's going on

**Comment by evanlaferriere** [comment]
The only reason it has to be a get call is because upload only renders the page on get, I'm not sure if/how we should work around that

**Comment by scottkleinman** [comment]
If there is no session, then, by definition, there are no active documents. So we could work the redirect into `detectActiveDocs()`, which is called at the beginning of every function that renders a template. If there is no session, we could render a page that says "Active session required. Redirecting to Upload..." and then redirects after a time delay.

**Comment by evanlaferriere** [comment]
I think we should have detectActiveDocs() return reset() if the case of no session.

**Comment by scottkleinman** [comment]
That makes sense, although, done that way, there will be no message for users. Maybe that's OK.

**Comment by chantisnake** [comment]
I think this is trapped by error model.

Closing this. If anyone has any problem, feel free to reopen this.
