### ISSUE TITLE
Handle XML Tags

### ISSUE THREAD

**Issue by kreddy95** [WheatonCS/Lexos#357]
In the Handle XML Tags for the drop-down options under Action there should be a button at the top to be able to change all of the actions to the same one if the user wants to choose an option other than the default one for all of them

**Comment by scottkleinman** [comment]
Good idea, but let's not dwell on these types of circumstances until we have the complete scrubbing done. If the tool is merely a prototype by the end of the month, that's fine. We can then fine tune it later.

**Comment by mleblanc321** [comment]
i think evan just implemented this

**Comment by evanlaferriere** [comment]
yes I did

**Comment by scottkleinman** [comment]
Yes, I saw that, and it appeared to work. I think we can leave this issue closed.
