### ISSUE TITLE
Upload does not upload duplicate files if you don't drag and drop

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#358]
This is a rare circumstance, but, if you try to upload the same file twice using the file browser. The file is not uploaded the second time. The function seems to work properly if (a) you drag and drop the file twice or (b) you leave the Upload tool and return to it.

**Comment by SocialHulkHogan** [comment]
This bug does not occur in firefox. Also the active file counter I made doesn't work on firefox.

**Comment by SocialHulkHogan** [comment]
Just kidding it works in firefox, but the upload bug is still real in chrome

**Comment by SocialHulkHogan** [comment]
Ok so to be clear, this is still an active problem in chrome and I'm not sure what to do.

**Comment by SocialHulkHogan** [comment]
I figured out what this is. upload.js line 210 
fileselect.addEventListener("change", FileSelectHandler, false);
in firefox, change is triggered each time a file is created, modified or deleted on a given storage area. on chrome, it fires for input, select, and textarea elements when a change to the element's value is committed by the user. Basically, change is what we want for firefox and isn't for chrome. I'm not sure what to change it to though.

**Comment by SocialHulkHogan** [comment]
Ok I fixed it by changing $(#fileselect).value to "" after it was don making the object. This way, 'change' fires in chrome.

**Comment by scottkleinman** [comment]
I haven't pulled this, but, from what you describe, it looks it might be unclear why setting it to `""` is used. If that's the case, please make sure to stick a comment in to explain why it's there.

**Comment by SocialHulkHogan** [comment]
I commented it better. It's because in chrome the trigger is when the value property of an element changes. if you don't clear the value after you upload a file, then try to upload the same file, no change will occur so it won't trigger the event.
