### ISSUE TITLE
Drout wants the rolling window pdf download back

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#359]
we gotta put it back. I'm leaving this as a reminder

**Comment by scottkleinman** [comment]
Did we ever have this? Creating PDFs from d3 is technically very difficult. For now, I would recommend one of the SVG options. Take a screen shot, paste it into Word, and then save that as a PDF.

Eventually we'll get around to automatic conversion, it will be a challenge.

**Comment by SocialHulkHogan** [comment]
He said we had this. I'll let him know.

**Comment by SocialHulkHogan** [comment]
So he says it's very important functionality for lay users, and he doesn't think it will be hard. We have a get pdf option for hierarchical clustering, so he wonders why we couldn't just do the same thing here. I told him that new front end functionality was sort of low on the priority list for this summer, but he wants to be 100% sure it's something he couldn't do easily.

**Comment by scottkleinman** [comment]
Dendrograms are generated using matplotlib, which handles the file format. All you have to do (all other things being equal) is change "filename.png" to "filename.pdf", and the correct format is generated. Rolling windows graphs are SVG images generated using d3.js. There is no easy way to do this, and it will probably require importing another dependency. We might look into generating an equivalent with matplotlib for PDF download. However, the user would not be able to manipulate the magnification using the ribbon at the bottom.

**Comment by SocialHulkHogan** [comment]
I see. I'll let him know.

**Comment by gryphonwastler** [comment]
I think we may have linked to another website's tool in order to accomplish
this in the past. You could double check by making a fresh clone of the
commits from last summer.

**Comment by chantisnake** [comment]
Great to see you here Caleb. If you guys want to see last year's code, just checkout masterSummer2015 branch.

you can do 
``` bash
git checkout masterSummer2015
```

**Comment by scottkleinman** [comment]
There doesn't seem to have been anything in last summer's code for a PDF save. I use the awesome [Fireshot](http://getfireshot.com/) for saving screen shots to PDFs. It might be Windows only, but I'm sure there are Mac and Linux equivalents.

**Comment by scottkleinman** [comment]
Generating a PDF from the SVG is beyond our capacity for this summer, so I'll close this issue for now. See further issue #432.
