### ISSUE TITLE
deprecation of sml animations

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#360]
I'm pretty sure all uses of fadeIn and fadeOut in the javascript are going to be removed from chrome and are already gone from firefox. We need to come up with a different way of doing those animations.

**Comment by scottkleinman** [comment]
I think we only use jQuery methods by those names. As far as I know, they aren't deprecated. Do you have a reference?

**Comment by SocialHulkHogan** [comment]
You're right, the issue is within jquery code. I'm sure they'll change it. Also I was mistaken about things not working in firefox, I just messed up making your new div and the folder play nice.
