### ISSUE TITLE
In the Margins opens and closes after loading a page

### ISSUE THREAD

**Issue by Landaluce** [WheatonCS/Lexos#361]
Each time I click on a menu option, in the margins opens and closes

**Comment by scottkleinman** [comment]
Put another way, the _In the Margins_ panel is open by default and is closed on page load. A consequence of this is that it takes a while for the panel to close if the page loads slowly (e.g. if it is fetching a Javascript library). I tried making it close by default, but this broke the script. Brownie points to anyone else who can find a solution.

**Comment by SocialHulkHogan** [comment]
Where should I start looking?

**Comment by scottkleinman** [comment]
`scripts_ITM.js` has the side panel code.

**Comment by SocialHulkHogan** [comment]
i think I fixed it

**Comment by scottkleinman** [comment]
Let us know when you've pushed the fix. Since the bugs only appears when you have a particularly slow internet connection, it'll take some texting over time before we can say whether the fix worked.

**Comment by SocialHulkHogan** [comment]
So I didn't fix this, and I'm not sure how to fix it.

**Comment by Landaluce** [comment]
Hi Scott,

I found a problem with your mauseenter and mouseleave functions, which are
in scripts_kmeans.js lines 138 -156.
The problem is that it does not display the name of the file when you hover
over some filenames in the table. I narrow it down to file that have a "."
in their name:
A3.3_Az_T00130.txt doesn't work, but if I use the same file, but renaming
it A33_Az_T00130.txt works fine

Alvaro

**Comment by scottkleinman** [comment]
Setting it to `display:none;` by default on page load doesn't seem to work (`visibility:hidden;` also failed). What if we tried setting a negative `z-index` and then changing it back when the panel is closed?

**Comment by scottkleinman** [comment]
This appears not to be happening any more. I'll close this issue, and we can re-open it if the problem re-appears.
