### ISSUE TITLE
MUFI 3.0/4.0 Entity replacements working

### ISSUE THREAD

**Issue by kreddy95** [WheatonCS/Lexos#362]
I think the MUFI 3.0 and 4.0 entity replacements seem to be working.  We used the entire dictionary of MUFI 3.0 as a txt file to test this. 
This issue can be closed after more testing from Scott.

**Comment by scottkleinman** [comment]
Can you push your test file so that I can try this out?

**Comment by kreddy95** [comment]
[MUFI_3_DICT.txt](https://github.com/WheatonCS/Lexos/files/326262/MUFI_3_DICT.txt)
[MUFI_4_DICT.txt](https://github.com/WheatonCS/Lexos/files/326263/MUFI_4_DICT.txt)
These are the two files I used to test both 3 and 4 respectively. Jordan made it so the button for 4.0 is us and that seems to be working

**Comment by chantisnake** [comment]
I think we just fixed this. Is this the encoding error?

Can you give us the error message

**Comment by chantisnake** [comment]
I am sorry, I misread this.

**Comment by scottkleinman** [comment]
I have been getting an encoding error in my test version of tokenizer (Flask route `/t`) since my last pull without having changed any of the code that I know of. Could it be related to the encoding error you mentioned, Cheng?

**Comment by chantisnake** [comment]
no, the encoding error is the error we just fixed together. Now it should works.

**Comment by scottkleinman** [comment]
Well, taking out the line that was breaking seems to solve the problem and may make it easier to solve another one. So, now that I know that my encoding problem was unrelated. The only thing that needs to be done before closing this issue is testing mentioned by Kristina above.

**Comment by mleblanc321** [comment]
scott:
do you have example files kristina could use to test?

**Comment by scottkleinman** [comment]
In haste because I'm about to go out for a couple of hours, but try [https://github.com/scottkleinman/aeme/blob/master/bodllaudmisc108/13_Short-texts-on-folio-238.xml](https://github.com/scottkleinman/aeme/blob/master/bodllaudmisc108/13_Short-texts-on-folio-238.xml). You could also take some of the DOE files and change the eth, thorn, and aesc to their MUFI equivalents in an editor.

**Comment by scottkleinman** [comment]
There's no real issue here. Closing.
