### ISSUE TITLE
Tokenizer page display all the same with whatever options checked and crash all the time

### ISSUE THREAD

**Issue by YiqingC** [WheatonCS/Lexos#364]
Tokenizer page just keep loading if tried with some large file like War and Peace and have to kill the page at last. 

Tried really small text file like OnetoTen.txt(can be found in TestSuite->Experiments->Statistics->Stats_Compare), go to tokenizer after upload, no matter choose by Words or by Characters, Proportional Counts or Raw Counts, the table always display the same results.
e.g. 
![screen shot 2016-06-21 at 3 38 45 pm](https://cloud.githubusercontent.com/assets/15393424/16243644/4a3367c6-37c6-11e6-974c-f328decbf0ad.png)

Another problem: when go to other page and come back, the options do not cache.

**Comment by scottkleinman** [comment]
Apologies. I've taken the latest code to another Flask route. If you want to test it, go to `http://127.0.0.1:5000/t`. But note that not all the functionality is active yet. I'll update everyone as soon as I've got everything working.

**Comment by scottkleinman** [comment]
This issue has been fixed.
