### ISSUE TITLE
Display scrubbed MUFI 

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#365]
Since MUFI scrubbing changes entities into Unicode glyphs, the result in the previews will be a lot of squares. We should probably have a way to display the results in a MUFI-compatible font (e.g. Junicode), which will make the characters appear as desired. Possibly this should just be something the user sets in the settings dialog. I think that might make it easier to extend to other encoding standards in the future.

**Comment by scottkleinman** [comment]
This has been handled by issue #397.

**Comment by scottkleinman** [comment]
Sigh. My solution works fine for Scrubber, but the characters won't be displayed in Junicode in other Lexos tools. The only solution is to load Junicode in `style.css`. Since most users won't want the extra baggage, it's really a good idea to develop a setting for enabling MUFI fonts accessible from the Settings dialog.

**Comment by cgnobrega** [comment]
this works in v4.0
