### ISSUE TITLE
Scrub preview triggers error

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#368]
Since my latest pull, I have been getting an error message when I click the Preview Scrubbing button. Apply Scrubbing seems to work.

**Comment by scottkleinman** [comment]
**Update:** Apply Scrubbing seems to be triggering the error as well.

**Comment by SocialHulkHogan** [comment]
Is this still happening?

**Comment by scottkleinman** [comment]
It doesn't seem to be. Let's close this. We can re-open it if the problem occurs again.
