### ISSUE TITLE
Word Cloud PNG not work

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#369]
Please give us some of the following information, 
That will be really helpful to track the bug:

* **if you are proposing an enhancement, please delete all of these**

### which option did I check
PNG download after getting graph on Word Cloud
### which file did I use
any
### what the bug looks like
when you click on PNG it opens word cloud without the graph in a new window
### what I expect to happen
it should open the image in a new tab
### how to reproduce it
see first question
### workspace file
* change the extension from `.lexos` to `.zip` before uploading it

**Comment by scottkleinman** [comment]
It appears that this option didn't work in Lexos 2.5 either. [Jason Davies' version](https://www.jasondavies.com/wordcloud/) no longer has the option, so I suggest we take it out as well. Perhaps the original script is no longer compatible with modern browsers.

**Comment by scottkleinman** [comment]
I have removed the download PNG option.

**Comment by cmccarthy41899** [comment]
We got the PNG working and added it back in
