### ISSUE TITLE
Word Cloud Graph options

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#370]
Please give us some of the following information, 
That will be really helpful to track the bug:
- **if you are proposing an enhancement, please delete all of these**
### which option did I check

get graph
### which file did I use

any
### what the bug looks like

selecting options other than the default only works if you adjust the orientation by dragging the arrows on the protractor 
### what I expect to happen

clicking the button for an option or clicking the button and then clicking get graph should change the graph (selecting get graph returns to defaults)
### how to reproduce it

get graph then try changing options at bottom
### workspace file
- change the extension from `.lexos` to `.zip` before uploading it

**Comment by cmccarthy41899** [comment]
Clicking on the image will also apply new options

**Comment by SocialHulkHogan** [comment]
I think for this we can just rename get graph to load graph, then maybe reload graph after the first click and tell them somewhere that clicking will redraw the same graph if they ever wanted to do that for any reason more sophisticated than "oooh floaty magic words"

**Comment by scottkleinman** [comment]
Eventually, it might be nice to create our own interactive functions, but for version 3.0, I've added a label instructing the user to click on the graph after changing any of the options.

So we can label this issue as a future enhancement.

**Comment by cgnobrega** [comment]
these issues no longer apply in v4.0
