### ISSUE TITLE
On manage page, can not change class label

### ISSUE THREAD

**Issue by YiqingC** [WheatonCS/Lexos#373]
### which option did I check
Edit document class, apply class to selected documents
### what the bug looks like
After type in the class label name, can not save it.
Click on the save button, nothing happens.
### error message if applicable 
A pop up box said "booop"
### how to reproduce it
Upload any files, go to the manage page and add the class label

**Comment by SocialHulkHogan** [comment]
the booop was from some debugging where I just went nuts with booops. I took it out and while the boop message is gone, the bug persists.

**Comment by chantisnake** [comment]
typically debugging stuff should not be commited.

**Comment by SocialHulkHogan** [comment]
I know I made a mistake

**Comment by scottkleinman** [comment]
I've just pushed a change which should fix it. You'll just need to style the element as you intended.

**Comment by scottkleinman** [comment]
Oops! Ignore that last comment from me. It was about a different issue.
