### ISSUE TITLE
Windows installer has changed

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#375]
windows installer(install.cmd) now automatically download the latest release (**including pre-release**) from GitHub.

and for the dev version (the version used for testing for English student)
they can type the following in there powershell:

install:
``` powershell
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/WheatonCS/Lexos/master/install/windows/install.ps1'))
```

to install the latest dev version (download from master branch)

I will update the updater later today.

**Comment by chantisnake** [comment]
I have made some security update on windows installer. I am not sure that user will appreciate it...

here is now what happened when you run `install.cmd`:
![capture2](https://cloud.githubusercontent.com/assets/10100995/16318834/c6860b8c-395e-11e6-8061-d478f6772f2a.PNG)


Before triggering the main script (`install.ps1`), people can see that the publisher of the script to make sure that is distributed by lexos.

Do normal user like that?

**Comment by scottkleinman** [comment]
It's a small assurance, but I think people will be pleased to see it...

**Comment by mleblanc321** [comment]
i think we just concluded that users running Edge will see the extra warning screen, but not others; 

i only want us to err on the side of looking professional with our installers; small footprint

**Comment by scottkleinman** [comment]
Yes, although it took me a moment even to think of what Edge was. When I tried to Google it, the first thing that came up was "bestiary hedgehog".

**Comment by chantisnake** [comment]
windows installer has changed to an exe and it is signed by me now.

![capture](https://cloud.githubusercontent.com/assets/10100995/16350476/dc4df276-3a2c-11e6-8605-2616de017f18.PNG)

**Comment by chantisnake** [comment]
I have added all the description of how to install to the pre-release v3.0.0. I don't think that is the correct place to put it, but I don't really know where to put it.

@JordanHelpsAlot

**Comment by mleblanc321** [comment]
i've assigned jordan to lead us in a sit down to get this organized;  we need directions to lead them to the installer and what they'll see and what they must do after install

**Comment by chantisnake** [comment]
this issue is no longer applicable
