### ISSUE TITLE
How is the preview generated on scrub?

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#376]
I've been chasing it for hours, on/off for several weeks. I eventually find my way to generatePreview() and makePreviewFrom, but neither of those actually seem to be called. Does anyone know where the preview is being made/why it doesn't take out tags on the initial loads (like it's supposed to) but then once you hit the preview it takes them out regardless of how they appear in the actual text?

**Comment by evanlaferriere** [comment]
#339

**Comment by chantisnake** [comment]
preview is generated when you upload, and it is stored in lexosfile object.

**Comment by chantisnake** [comment]
on scrub I think it access it by filemanager -> files -> preview

**Comment by mleblanc321** [comment]
evan:  think reminded me also;  thanks cheng
