### ISSUE TITLE
multicloud with scraper

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#379]
The default scrape url files seem to crash multicloud when there are multiple clouds to render. 
Note that google chrome takes a while, while firefox the script produces an error message because it lags out the browser.

**Comment by scottkleinman** [comment]
On my machine Firefox froze for a few seconds, but it eventually rendered the clouds. This seems to be a general problem with the d3.js drawing. It could be that certain documents are more complicated to tokenise and layout. I tried leaving out the html file, and it was somewhat faster.

**Comment by SocialHulkHogan** [comment]
It's more than that. I'm 100% positive. I've made d3 drawings with thousands of shapes that loaded faster than this.

**Comment by scottkleinman** [comment]
It's been a while since I looked at the code, but it may be doing some tokenising on the client side, which will slow things down. Likewise, doing separate layouts for each cloud.

**Comment by scottkleinman** [comment]
I don't really think this is the problem, but the data set was being written to the DOM twice. I've commented out one, and the tool still works, so that may be of some minor help.

**Comment by scottkleinman** [comment]
I've done a lot of profiling, and it looks like the processing activity is pretty spread out. Speeding up Multicloud generation is probably going to take some dedicated work, and maybe a new implementation. I am going to close this issue and open a new one labelled "enhancement".
