### ISSUE TITLE
empty tool tips

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#380]
* Hierarchical Clustering: Show branch Height in Dendrogram
* K-Means: Silhouette Score Options: Distance Metric
* Topwords: Token Filter: All

**Comment by scottkleinman** [comment]
These may not be empty. There appears to be bugs in the html which are preventing proper rendering.

**Comment by cmccarthy41899** [comment]
tool tips on topwords need text, but the others are good now

**Comment by SocialHulkHogan** [comment]
I think this is done yeah? close?

**Comment by cmccarthy41899** [comment]
Yeah, as far as I know. I think it was when I left.

**Comment by SocialHulkHogan** [comment]
D: I wanted to do it I was seconds too late

**Comment by chantisnake** [comment]
boooya
