### ISSUE TITLE
Legacy code

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#381]
If there's code on the back end that is not being used anymore, should one delete it?

**Comment by scottkleinman** [comment]
Best to ask first, as some of the code may contain valuable snippets.

**Comment by evanlaferriere** [comment]
Manage_old() and select_old() in lexos.py? I have them commented out on my end and it's working

**Comment by scottkleinman** [comment]
Yes, I think they can go. I have local version with those functions archived.

**Comment by mleblanc321** [comment]
thanks for poking all around Evan;  yes, i agree that it should be safe to remove those (commented out) methods
