### ISSUE TITLE
Having trouble adding a session variable

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#385]
I'm trying to add new session variable, and it's not working quite right. Here's what I'm doing:

#### In `constants.py`:
```python
GENERALSETTINGS = ('beta_onbox',)
DEFAULT_GENERALSETTINGS_OPTIONS = {'beta_onbox': "off"}
```
#### In `session_manager.py`:
```python
def cacheGeneralSettings():
    session['generalsettings'][setting] = (setting in request.json[setting])
```
#### In `lexos.py`:
```python
@app.route("/updatesettings", methods=["GET", "POST"])
def updatesettings():
    if request.method == "POST":
        session_manager.cacheGeneralSettings()
```
#### In `upload.html`:
```html
{% if session['generalsettings']['beta_onbox']=="on" %}
    <p>Show some content if the beta_onbox is checked.</p>
{% endif %}
```
All this worked for me until I hit "reset". Now I get the following error from Jinja2: `UndefinedError: 'flask.sessions.SecureCookieSession object' has no attribute 'generalsettings'`.

What am I missing?

**Comment by chantisnake** [comment]
well, first, you did not load the default setting when general setting is not there. I just look at backendprogrammingguide, it seems like I miss that part, but this is not important.

The thing is, if you want to cache a check box option, the value in the dict should be `bool` not (`on` or `off`)
see the line of code on backendprogrammingguide:
``` python
DEFAULT_LALALA_OPTION = {'input1': 'the-default-of-input1', 'input2': 'the-default-of-input2',
'box1': True, 'box2': True, 'box3': True, 'box4': True, 'box5': False, 'box6': False, 'god!-we-really-have-lot-of-boxes': False
,'list1': [], 'file1': '', 'file2': '',
'this-is-the-option-that-I-do-not-want-to-cache': 'lalalahahaha', 'this-is-another-option-that-I-do-not-want-to-cache': False}
```
Notice that all the box is bool
and this:
``` html
<!-- check box -->
<label> box1 <input type="checkbox" name="box1" {{ 'checked' if  session['lalalaoptions']["box1"] }}/> </label>
```

When you cache the settings, you put a bool inside `session['generalsettings']['beta_onbox']` but when you check it on the HTML you are checking whether it is `'on'`. Of course neither `True` or `False` will be equal to `'on'`

That is why your option did not get cached.

**Comment by chantisnake** [comment]
I found the code to load the default, which is in [lexos.py](https://github.com/WheatonCS/Lexos/blob/master/BackendProgrammingGuide.md#1-lexospy)

it is in 
```
Programming workflow -> split request -> 'GET' request -> apply the default setting to the  session 
```

here is a snippet of the code sample in Backend Programming Guide:
```python
# split request ('GET')
if request.method == 'GET':

    # apply default setting to the `session`
    if 'topwordoption' not in session:
        session['topwordoption'] = constants.DEFAULT_TOPWORD_OPTIONS
    if 'analyoption' not in session:
        session['analyoption'] = constants.DEFAULT_ANALYZE_OPTIONS

```

**Comment by scottkleinman** [comment]
Thanks! that partially solves my problem. I had it as a Boolean, then switched to a string but forgot to change the template. Changing both to a Boolean fixed it. However, now my session variable won't save because jQuery is passing "on" as the value of the checkbox. I think I just need to figure out how to get it to pass a Boolean as well.

Note that I also found the `if not in session` code, but I placed it inside `cacheGeneralSettings()` in `session_manager.py`. Does this make a difference?

**Comment by scottkleinman** [comment]
Well, it seems that I do need to put the if clause in `upload()`, but that's OK. Also, the one-liner loop in `cacheGeneralSettings()` didn't work, but we can deal with that when there is more than one option. For now, it works.

I'll describe the purpose of all this in another issue.

**Comment by chantisnake** [comment]
i think your cache function will return a bool.

That is the way to cache box as a bool. We typically don't care about the 'on', we just check whether that box exists on request.form, because if a check box is in request.form then it's value will always be 'on'

as for why do we use a bool instead of 'on', that is because bool is much more easy to write, concise and readable than check if it equals 'on'
