### ISSUE TITLE
Beta mode

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#386]
Lexos now has a setting to turn Beta functions on and off. The settings (cog/gear) icon has a checkbox which toggles Beta mode for the entire session (the default is off). Right now, the only thing affected by it is the web scraper. (The link to web scraper is no longer displayed on the Upload page unless you turn on Beta mode.)

This easiest way to hide tools still in Beta is to wrap the UI elements in a Jinja conditional:

```html
{% if session['generalsettings']['beta_onbox'] %}
    <p>Your tool code here</p>
{% endif %}
``` 

The content not be written to the template unless Beta mode is on.

**Comment by chantisnake** [comment]
I think everybody know about this.

**Comment by mleblanc321** [comment]
i forgot

**Comment by mleblanc321** [comment]
you two are amazing;  thanks for plowing thru so many issues!

**Comment by chantisnake** [comment]
yeah... but we still has more than 100 of them.
