### ISSUE TITLE
Labels on K-Means Voronoi graph don't display Unicode properly

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#387]
I tried some Chinese text and found that, although there is no error, the label text is not encoded properly.

**Comment by chantisnake** [comment]
I will try to investigate on that tomorrow if I have time

**Comment by chantisnake** [comment]
Probably missing a decode('utf-8') or a codec.open(encoding='utf-8')

**Comment by chantisnake** [comment]
Is the error message like 'ascii codec cannot decode byte'?

**Comment by scottkleinman** [comment]
There's no error message. I think the problem is on the front end. Probably there is a missing `decodeURIComponent(escape())` wrapping the label text. Those functions are typically used inside of d3.js.

**Comment by chantisnake** [comment]
okay, I will focus on the backend for now.

**Comment by scottkleinman** [comment]
The missing function was indeed the problem. I've fixed it.

**Comment by mleblanc321** [comment]
umm, what was the missing function?  where?

**Comment by scottkleinman** [comment]
Line 368:

```javascript
$("#point"+x).attr("title", textData[x-1]["title"]);
```
It should have been

```javascript
$("#point"+x).attr("title", decodeURIComponent(escape(textData[x-1]["title"])));
```

**Comment by mleblanc321** [comment]
this issue is a great stackOverflow help, if we show some output using the additional decodeURIComponent

** in fact:  we'd be wise to share some of our (resolved) Issues on StackOverflow?

**Comment by scottkleinman** [comment]
You'd have to ask a question on StackOverflow, and then I'd have to answer it, or something like that. But, in principle, this is a good idea. We should be making a contribution to the greater coding community's knowledge base...

**Comment by mleblanc321** [comment]
yes, just thinking out loud while typing on a beautiful summer day
