### ISSUE TITLE
2do list (last week)

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#389]
cheng came up with this list of tasks to address (as of SUN, June 2, 2016)

1. we, of course, do not handle nested tags when the [tag + content + /tag] pattern is present
2. if punctuation is removed, then we'll remove the / in the end tag
3.in scrub, when preview/apply, the Preview panel, the `<b>` and `<p>` tags are not escaped, thus the text is bold in case of `<b>` tag)
4. if preview in handle_tag(), the text searched is only the (short) preview text; scrubbing for end tags will not work
5. When asking for a Graph in Dendrogram (hierarchical), two windows flash up:  Figure 1 and 2 windows ??
6. Test Save Workspace

**Comment by mleblanc321** [comment]
when we render_template in flask, JINJA will automatically escape the contents of the variables, but now an AJAX call does not?

where does AJAX do the same to render the preview?

**Comment by scottkleinman** [comment]
Normally, the response variable is acted on in a function inside the ajax. This might be as part of the `success`, `complete`, or `done` methods, depending on the specific ajax implementation. Your questions sounds like a Scrub question. Since I have to look at the ajax for Scrub in a moment, I'll give you a more precise answer shortly.

**Comment by scottkleinman** [comment]
Here's a short version of what's in `scripts_scrub.js`:

```javascript
// Detect click on a button
$(".bttnfilelabels").click( function() {
   ...
   doScrubbing();
});

function doScrubbing(action) {
	...
    // Do ajax
    $.ajax({
	  url: '/doScrubbing',
	  type: 'POST',
	  processData: false, // important
	  contentType: false, // important
	  data: formData,
	  error: function (jqXHR, textStatus, errorThrown) {
	  	$("#error-modal-message").html("Lexos could not apply the scrubbing actions.");
		$("#error-modal").modal();
		console.log("bad: " + textStatus + ": " + errorThrown);
	  }
	}).done(function(response) {
		response = JSON.parse(response);
		$("#preview-body").empty();
		$.each(response["data"], function(i, item) {
            ...
			fieldset = $("<fieldset></fieldset>");
			fieldset.append('<legend class="has-tooltip" style="color:#999; width:auto;">'+filename+'</legend>');
			fieldset.append('<div class="filecontents">'+fileContents+'</div>'); //Keep this with no whitespace!
			$("#preview-body").append(fieldset);
		});		
	});
}
```
I'm guessing that any escaping has to go on the `fileContents` variable at the end.

**Comment by chantisnake** [comment]
number 3 is fixed in 4cf245712e7925dbad7a14ffaca2b1988c92c8e5

**Comment by chantisnake** [comment]
number 2 is fixed in dfab417c68b246edb2414b3c2c7e908e01ab4fac

**Comment by chantisnake** [comment]
only bug left is number 4. I have found another issue. I will try to solve that first and come back to number 4

**Comment by evanlaferriere** [comment]
I have also encountered bug 4, but cannot replicate it. Anyone know how?

**Comment by chantisnake** [comment]
All of it is fixed.

**Comment by chantisnake** [comment]
Besides nested tags, that is next year.
