### ISSUE TITLE
CountVectorizer does not all punctuation within a token

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#390]
despite all our good work on scrubbing, the fact remains that our calls to CountTokenizer match tokens (if WORDs is the token type) by
```
\b[\w\'\-]+\b
```

which means it will accept a punctuation character as a word boundary (non-word character), thus "dog," (with comma at end) and "dog" become the same token (even if you user wanted to test use of punctuation as part of style and thus did not remove punctuation)

** cheng suggests we remove the 'Remove Punctuation' check box from the Scrubber page 

** i think we leave it in, but we've got to be more upfront whenever we call CountVectorizer that we are using all non-word characters to be word boundaries;  users may still want to scrub and leave so we leave it in(?);

**Comment by scottkleinman** [comment]
If I understand this correctly, CountVectorizer handles the tokenization, and it's doing its own thing if you don't strip punctuation. Documentation of how CountVectorizer works is the easiest path, but it doesn't do much good for users who want to study punctuation.

But CountVectorizer does allow you to specify the regex pattern, so there may be a way to exclude punctuation marks. Alternatively, we can use its `preprocessor` parameter to wrap punctuation marks as entities prior to tokenisation.

But, yes, users may simply want to strip punctuation without creating a DTM, so we should leave this option in the UI.

**Comment by mleblanc321** [comment]
cheng and i have pushed two changes to GetMatrix() in the CountVectorizer call

words are considered as any consecutive chars that is/are not a whtiespace:    [\S]+

we were also (incorrectly) allowing CountVectorizer to flip all chars to lowercase;  we've fixed it so that CountVectorizer will leave it alone (as set by our user in Scrubber)

**Comment by scottkleinman** [comment]
Huzzah!

**Comment by chantisnake** [comment]
I think this is fixed, so I will close this for now.

If there is any problems, reopen this issue
