### ISSUE TITLE
Some problem I found on the backend code

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#392]
### `lexos.py`

1. In `lexos.py -> cluster` there is intense calculation, move it to processor. and use `filemanager.getmatrix` instead of copy and pasting the `countVerctorizor` code
2. tokienizer code is too long, I am not sure if there is a reason for that

quote from backend programming guide [lexos.py](https://github.com/WheatonCS/Lexos/blob/master/BackendProgrammingGuide.md#1-lexospy)
> * special comment: 
>     - in this file we should only handle data structure transformation, not calculations (calculation is handled in  /processors/* )
>     - if a function doesn't need to get  request  and doesn't need to call  fileManager , this function does not belong in this file.
>     - if a function is doing intense math and calculation, this function does not belong in this file. (calculation is handled in  /processors/* )

### `general_function.py`

1. `xmlHandleingOptions` function should not be there.

First, importing filemanager there is dangerous. `general_function.py` should only import `constants.py`
(besides external library) and `countant.py` should not import any file in this project.

Second, this function should be in `managers/utility.py`:
quotes from Backend Programming Guide [utility.py](https://github.com/WheatonCS/Lexos/blob/master/BackendProgrammingGuide.md#2managersutilitypy)
> Description: there are 3 type of functions in this file:
>  - **the function loads a request remotely, and turns them into the option that the processor can understand**
>     - **for example: getTopWordOption()**
>  - the function that is used to combine all the information together to give a result that can be sent to the front-end 
>    - for example: GenerateZTestTopWord(filemanager)
>  - other functions: 
>    -  saveFileManager() ,  loadFileManager()

---

**Comment by mleblanc321** [comment]
ok, we hear you;  we may need some help to make sure we do this correctly;  i'll have alvaro work on this tomorrow morning

**Comment by evanlaferriere** [comment]
I just moved over xmlHandlingOptions and replaced all the general_function.xmlHandlingOptions with utility.xmlHandlingOptions.. Pushing that

**Comment by chantisnake** [comment]
yes, make sure it is correct because there maybe something missed if you manually moving functions.

in fact pycharm will automatically move functions. just go to the function declaration and press `F6`, input the file you want to move it to, and all the reference will be changed automatically

**Comment by evanlaferriere** [comment]
Great to know! I used ctrl+shift+R to go through every instance of general_function.xmlHandlingOptions and replace it with utility.xmlHandlingOptions

**Comment by chantisnake** [comment]
I think we can close this issue if all the stuff is moved.
