### ISSUE TITLE
question about detectActiveDocs

### ISSUE THREAD

**Issue by YiqingC** [WheatonCS/Lexos#396]
I am Cheng(Moses), I am working on Yiqing's box, for now some of the bug releated to `countVectorizer` panic because of no active documents.

Can we just handle that just in `detectActiveDocs`?

``` python
def detectActiveDocs():
    """ This function (which should probably be moved to file_manager.py) detects 
        the number of active documents and can be called at the beginning of each
        tool.
    """
    if session: 
        fileManager = managers.utility.loadFileManager()
        active = fileManager.getActiveFiles()
        if active:
            return len(active)
        else:
            return redirect(url_for('manage'))
    else:
        return redirect(url_for('nosession'))
```

we can also change this to maybe `redirect_when_error` or stuff

@scottkleinman

**Comment by scottkleinman** [comment]
I am enjoying the idea of CountVectorizer panicking.

Yes, `detectActiveDocs()` can be called from anywhere. You can even call it from an Ajax request by posting to `/detectActiveDocs`. I think this is entirely appropriate.

For `redirect_when_error`, is this a Flask function, or are you just suggesting renaming `nosession` to `redirect_when_error`. I'm OK with that.

Oh, wait, now I see that you have re-written the function to redirect to Manage if there's a session but no active documents. That looks like a good idea. It's possible that the user will have a session with no uploaded documents, but the Manage page will tell them that.

**Comment by YiqingC** [comment]
another question, for word cloud, multicloud, it does not use active document(do they?)

Therefore i don't think that will be nesscary to be called in that functions

**Comment by scottkleinman** [comment]
I only looked at the template for Word Cloud, which does have a `{{ numActiveDocs }}` passed to it. But I may have put it there just to prevent an error. Older tools like Word Cloud may use different variables to detect whether there are active documents, or they may even use Javascript to count items in the DOM. Where possible, we should probably consolidate and use the `{{ numActiveDocs }}` generated by `detectActiveDocs`. That will eliminate redundancies and make the code more consistent.

**Comment by scottkleinman** [comment]
I think we can close this issue now since we are making this variable available on every screen.
