### ISSUE TITLE
Cut crashes without segment size being entered

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#398]
### which option did I check
tokens/segment
### which file did I use
any
### what the bug looks like
if there is nothing entered in the segement size input, the page breaks
### error message if applicable 
ValueError: need more than 1 value to unpack
### how to reproduce it
hit preview/apply cuts, while the segment size box has no value. You need something uploaded

**Comment by evanlaferriere** [comment]
I've been working on this for too long to no avail
Anyone familiar with cutter want to pick this up?

**Comment by scottkleinman** [comment]
I think I inadvertently triggered this myself a few minutes ago, but not to worry. I have spent the last day re-writing Cutter, which I realised had not been converted to Ajax. I'll probably push the changes in the next 15 minutes or so.

**Comment by scottkleinman** [comment]
OK, I have pushed the changes. Please test!

**Comment by YiqingC** [comment]
Tested but still did not do anything.

**Comment by evanlaferriere** [comment]
Yeah, now the page completely doesn't work for me. Neither buttons do anything.

**Comment by scottkleinman** [comment]
OK, I'm getting that as well, but choosing Segments/Document works. That's what I was using to test. Let me know if this option works on your end.

**Comment by evanlaferriere** [comment]
yes, that works. But tokens/segment and chracters/segment don't, and I can't access individual options

**Comment by YiqingC** [comment]
The segments/document doesn't work on mine ...

**Comment by scottkleinman** [comment]
OK, I'm on it.

**Comment by YiqingC** [comment]
And do we have one more button to the right of "apply cuts"? I thought it was a download button...

**Comment by evanlaferriere** [comment]
That only shows up after it has successfully cut

**Comment by YiqingC** [comment]
I tested it again and actually all the four options work now... the only problem is the download button, that one does appear after successfully cut, but then go to a error page

**Comment by evanlaferriere** [comment]
I can't get any but segments/doc to work still :^/

**Comment by evanlaferriere** [comment]
Correction: all options  work but characters/segment, and the individual options

**Comment by scottkleinman** [comment]
Can you layout a bunch of tests you are doing (what files and what numbers you are using for segment size)? that would help me debug.

**Comment by YiqingC** [comment]
I used the first three texts in TestSuite-Cutter-char_seg folder.
Using 1_alpha with segment size 3 to test char/seg
Using 2_numbered with segment size 1 to test token/seg
Using 3_numbered_large with segment size 1 to test line/seg

**Comment by scottkleinman** [comment]
OK, it seems to be working for me in both Chrome and Firefox, but I will continue to test. The download button didn't work because I forgot to assign the file manager variable in the download function. I've pushed the fix, so it should work for you the next time you pull.

**Comment by scottkleinman** [comment]
Most of the functions in Cutter appear to be working for me now, but there are so many combinations to test, that I think that deserves a separate issue. The original title of this issue seems now to be handled. That is, Cutter now gives an error if you leave the segment size blank. So I'm going to close this issue and open a new one for the testing.
