### ISSUE TITLE
A few issues with page that would break

### ISSUE THREAD

**Issue by YiqingC** [WheatonCS/Lexos#399]
1 [Evan fixed] Tokenize page breaks:
- No file uploaded, go to tokenize page, broken said "UnboundLocalError" [Moses: front end trap this]

2 Word Cloud:
- Upload any files, do scrubbing, cut then go to Word Cloud, generates nothing when click on "Get Graph" [Moses: Jquery UI error, sending 'GET']

3 Multicloud:
- (optional) No file uploaded, go to multicloud page, click on "Get Graphs", no error message [Moses: front end trap this]
- If do have file, first generate some graph, then change "Document Clouds" into "Topic Clouds", then click on "Get Graphs" again, broken said "IOError" [Moses: front end trap this]

4 Rolling window:
- No file uploaded, go to rolling window page, click on "Get Graph", go to Bad Request page [Moses: front end trap this]

5 Statistics:
- Upload any files, but unchecked all in the stats page, then click "Generate Statistics", broken said "ValueError" [Moses: front end trap this -- No mallet uploaded]

**Comment by evanlaferriere** [comment]
I just fixed tokenizer, I added a redirect to nosession at the end if it can't load any pages

**Comment by chantisnake** [comment]
I think only mallet file is the only one that left.

**Comment by scottkleinman** [comment]
Task list showing state of the issues above:

- [x] Tokenizer
- [x] Word Cloud
- [x] Rolling Window
- [ ] Statistics
- [x] Multicloud (no files uploaded)
- [ ] Multicloud (switch to topic clouds)

**Comment by chantisnake** [comment]
I think we can add `doc_selector` on every document selector like the the ones in stats and word cloud and many other visualizer page.

and then add a js in `script_base.js` and handle them once for all.

**Comment by scottkleinman** [comment]
Ultimately, that would be a good move, but everything is working now, except for the slightly more complicated situation with Multicloud.

**Comment by scottkleinman** [comment]
Multicloud has now been fixed as best we can. An error occurs if Topic Clouds is selected and no file is uploaded. Obviously, we cannot test whether the file is a valid MALLET file.
