### ISSUE TITLE
Browser caching

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#406]
On both cut and tokenize, I have experienced an issue where the browser hangs onto a cached version of lexos that behaves incorrectly. I have to clear my cache every time I want to use one of those pages. What could be causing this?

**Comment by scottkleinman** [comment]
I'm encountering this with other pages. I have no idea why it is happening.

**Comment by evanlaferriere** [comment]
Which pages?

**Comment by scottkleinman** [comment]
Got it on Word Cloud. I thought I was getting it on BubbleViz, but that may have turned out to be because I was editing the wrong file.

**Comment by scottkleinman** [comment]
No, I'm getting it on BubbleViz too.

**Comment by scottkleinman** [comment]
The most recent advise for browser caching settings that I can find is

```html
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
```
I will update this in `base.html`.

Other possibilities are to try and implement this in Flask:

```python
resp.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
resp.headers["Pragma"] = "no-cache"
resp.headers["Expires"] = "0"
```

Or even on the server in `.htaccess`:

```
<IfModule mod_headers.c>
  Header set Cache-Control "no-cache, no-store, must-revalidate"
  Header set Pragma "no-cache"
  Header set Expires 0
</IfModule>
```

Source: [http://cristian.sulea.net/blog.php?p=2014-01-14-disable-browser-caching-with-meta-html-tags](http://cristian.sulea.net/blog.php?p=2014-01-14-disable-browser-caching-with-meta-html-tags).

NB. I'm not sure if disabling caching is forcing Lexos to load javascript libraries from CDN on each page load. If so, we may want to get rid of this.

**Comment by scottkleinman** [comment]
I have not had any problems with browser caching since I switched us to the html meta tags listed above. If anyone else is still having problems, let me know so that we can decide whether to close this issue.

**Comment by evanlaferriere** [comment]
I haven't had any issues today

**Comment by scottkleinman** [comment]
I'm going to assume it's fixed. I'll change the title to something clearer and close this issue.
