### ISSUE TITLE
multicloud generating graphs when none are selected

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#414]
[utility.py on L867](https://github.com/WheatonCS/Lexos/blob/master/managers/utility.py#L867)

``` python
        for lFile in filemanager.files.values():
            if lFile.active:
                activeFiles.append(lFile)
```

this code is making all of the multicloud pics when there is no selected.

deleting this code fix the problem.

but we really need to see if there any logic behind the this code @scottkleinman because we don't really want to break anything.

**Comment by scottkleinman** [comment]
Taking this out means that you get the same term count per term regardless of how many documents you have selected (BubbleViz might be the best place to test this). So I wonder if this is an issue that needs to be done on the front end.

**Comment by chantisnake** [comment]
I don't think this is fontend though, we have checked the `request.form`, everything is correct.

And I don't really get what you are saying... It is possible to give us some examples?

**Comment by scottkleinman** [comment]
I'm talking about the Select a Document check boxes. When you set the Toggle All (`id="allCheckBoxSelector"`) box to false, all the other ones should be set to false. But it seems like they are not. Therefore their values are getting submitted and show up in `request.form` on the back end.

**Comment by scottkleinman** [comment]
OK, I stuck the following at the top of `bubbleviz.html`:
```javascript
// On document.ready()
$(function() {
    // If the Toggle All button is clicked...
    $("#allCheckBoxSelector").click(function() {
        // ... and its state is checked
        if (!$("#allCheckBoxSelector").is(":checked")) {
        // Set all the other checkboxes to unchecked
	    $(".minifilepreview").prop("checked", false);
        }
    });
});
```
That works. The problem is that there is still a graph if you have generated one previously. We may need to add a line to destroy the previous graph.

**Comment by scottkleinman** [comment]
OK, I am going to push this code for BubbleViz. Let me know if you have any problems. If not, I'll implement it for the other tools.

**Comment by SocialHulkHogan** [comment]
No don't!

**Comment by chantisnake** [comment]
I don't think just minify preview is the best solution though, because the time is consumed when you generate the graph.

Maybe I misunderstand the code?

**Comment by SocialHulkHogan** [comment]
Bubbleviz is fine

**Comment by SocialHulkHogan** [comment]
oh wait, maybe you're right

**Comment by chantisnake** [comment]
I see that your fix, but no...

It is not sended to the backend when we inspect, it is that code on the backend that is getting extracting all the files when no file is selected. if you want to see the whole code block this is [utility.py L860](https://github.com/WheatonCS/Lexos/blob/master/managers/utility.py#L860):

``` python 
chosenFileIDs = [int(x) for x in request.form.getlist('segmentlist')] 

activeFiles = [] 
if chosenFileIDs: 
    for ID in chosenFileIDs: 
        activeFiles.append(filemanager.files[ID]) 
else: 
    for lFile in filemanager.files.values(): 
        if lFile.active: 
            activeFiles.append(lFile)
```

`chosenFileIDs` is actually the file that is selected, the code below is saying if we have some IDs, go add those files to `activeFiles`, if we don't have any, file all the file that is active and put them into `activeFiles`...

I don't really understand the logic of this code.

**Comment by scottkleinman** [comment]
OK, I'll look at it again.
