### ISSUE TITLE
Selecting a text in Manage does not show the active doc icons

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#417]
I don't think this a bug. I just think we forgot to do this.

**Comment by mleblanc321** [comment]
@SocialHulkHogan is this something you think you can add to Manage?

**Comment by scottkleinman** [comment]
Actually, I have it half done already.

**Comment by mleblanc321** [comment]
excellent

**Comment by scottkleinman** [comment]
Fixed and pushed.
