### ISSUE TITLE
If you upload a workspace, it deletes all the currently uploaded files

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#420]
Do we want to do that? I get the rationale for resetting everything to that work space, but I think if someone uploads a workspace with a batch of other files, they probably want all of them, not just the workspace and the files uploaded after it. It's not like we do this with any other type of file.

**Comment by chantisnake** [comment]
adding that is not hard, but it is certainly not so easy that we should do it now.

and what about settings, do we need to merge them too? that is gotten to messy

**Comment by scottkleinman** [comment]
At present, we are safe because the only setting is enabling beta mode. But we should eventually try to adapt the workspace upload/download functions to handle such new features. I think this is worthy of an enhancement label.

**Comment by chantisnake** [comment]
no, the setting we are talking about is all the settings in the session and file manager.

when you upload a file, like dan. and then do all kinds of operation on it. Lexos will cache your settings on each page, like scrub options, and analysis options.

But then you upload a workspace, all the options and file will be overwrited by the options and file in that workspace.

**Comment by scottkleinman** [comment]
Oh, I see what you mean. Your initial assessment that it would be messy to try to merge settings is correct.

**Comment by chantisnake** [comment]
I think we agree uploading workspace should delete current file.
