### ISSUE TITLE
Fix for PDF button in Rolling Windows

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#423]
I'm not going to push this change myself, but I've identified the problem. The button is missing `name="get-RW-pdf"`. Steven, can you fix this?

**Comment by SocialHulkHogan** [comment]
Yeah can't it just be done in html?

**Comment by SocialHulkHogan** [comment]
I just noticed a flaw in the html that could have been behind this as well

**Comment by SocialHulkHogan** [comment]
I added that name to them. It didn't solve the problem unfortunately.

**Comment by SocialHulkHogan** [comment]
should I push this change anyway?

**Comment by scottkleinman** [comment]
How weird. It worked for me. I just pulled your code, so I'll have a look.

**Comment by scottkleinman** [comment]
Oh, you commented out the function in `lexos.py`. Uncommenting it generates an error, so I'll have a look at that.

**Comment by scottkleinman** [comment]
It looks like you might have commented out the function because it calls `utility.generateJSONForD3(dataPoints, legendLabels)`. In `utility.py`, that function has variable names that don't look to me like they match the same parameter expectations: `generateJSONForD3(filemanager, mergedSet)`. I'm not sure why I didn't get an error before I pulled (I didn't actually download the image, so I didn't fully test). Am I right in thinking that we need a different function to write a PNG/PDF?

**Comment by SocialHulkHogan** [comment]
Sorry I'm a little confused. The problem is that I commented out a function in lexos.py? I don't remember doing that. What should I uncomment?

**Comment by scottkleinman** [comment]
Lines `898-905` in `lexos.py`:

```python
        # This first if doesn't seem to be attached to anything
        # if 'get-RW-pdf' in request.form:
        #      # The 'Generate and Download Matrix' button is clicked on rollingwindow.html.
        #
        #      savePath, fileExtension = utility.generateJSONForD3(dataPoints, legendLabels)
        #      fileExtension = ".pdf"
        #
        #      return send_file(savePath, attachment_filename="rollingwindow_matrix" + fileExtension, as_attachment=True)
```
But, since `utility.generateJSONForD3()` doesn't seem to produce a PDF, this is probably all right. I just have no memory of ever producing a PDF from Rolling Windows. Lexos 2.5 also does not have a button to generate a PNG. So it seems that we probably need to write new scripts for both if we want these functions.

**Comment by SocialHulkHogan** [comment]
no that doesn't make sense I've seen that button work. I feel that something is missing from this picture.

**Comment by SocialHulkHogan** [comment]
Well it at least worked for firefox

**Comment by scottkleinman** [comment]
Here's my theory:

```python
fileExtension = ".pdf"
return send_file(savePath, attachment_filename="rollingwindow_matrix" + fileExtension, as_attachment=True)
```
This assumes that there is a file called `rollingwindow_matrix.pdf` in your session folder. Maybe this file is created elsewhere. You can check this by going into your session folder and looking. But, if there's no file available for download, then this code obviously can't work.

The button itself once worked for me as well, but I suspect that it might have been hooked up to one of the CSV-generating functions.

**Comment by SocialHulkHogan** [comment]
session folder? Sorry I can not get my brain up and running today.

**Comment by SocialHulkHogan** [comment]
I'm looking into a way to do this entirely on the front end because i think that will be much easier. That button doesn't need to be a submit button. I need peace and quiet to think about this though and that probably won't happen today.

**Comment by SocialHulkHogan** [comment]
I don't think this button should have the submit type because that results in a re-rendering of the page. It can probably be done with a single javascript function which would be fantastic.

**Comment by scottkleinman** [comment]
See [https://github.com/WheatonCS/Lexos/blob/master/BackendProgrammingGuide.md#-a-general-introduction-to-some-important-things](https://github.com/WheatonCS/Lexos/blob/master/BackendProgrammingGuide.md#-a-general-introduction-to-some-important-things). The session folder is located in `~\AppData\Local\Temp` on Windows (or it may also be in `C:\temp`), but I'm not sure where it is on Max/Linux. When you start a new session in Lexos, a new session folder is created in this location, and all your files are uploaded to it.

**Comment by SocialHulkHogan** [comment]
awesome thanks. The only front end bugs left are the ones heavily connected to the back end so I need to expand my knowledge base to continue making contributions.

**Comment by SocialHulkHogan** [comment]
Which is both annoying and reassuring because it means We have been very thorough thus far.

**Comment by chantisnake** [comment]
on mac and Linux is `/tmp` on windows is `~\AppData\Local\Temp`

**Comment by scottkleinman** [comment]
I've added that in the Backend Programming Guide.

**Comment by chantisnake** [comment]
What a ninja.

**Comment by SocialHulkHogan** [comment]
Im looking at the filemanager and I don't really understand the framework. Why does sS'active' only appear once for example when I had two active documents? I'm not sure if I'm looking at the right thing but I don't see rollingwindow_matrix.pdf anywhere...
[filemanager.txt](https://github.com/WheatonCS/Lexos/files/350371/filemanager.txt)

**Comment by SocialHulkHogan** [comment]
Well anyways, I don't think that the issue is related to something missing from session. The javascript code that was supposed to activate when you clicked the pdf button was missing timing. it was getting called before the button was clickable. Instead, I added the code to the beginning of makerwagraph after the crucial first if statement and the code now fires. The graph isn't being drawn in firefox still but at least its fixed for chrome

**Comment by scottkleinman** [comment]
We can close this. See issue #432.
