### ISSUE TITLE
lexos install guide is outdated

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#426]
the module is not complete.

**Comment by chantisnake** [comment]
also anaconda has updated to 4.1.0

**Comment by mleblanc321** [comment]
>the module is not complete.
i'm not sure what you mean here?  (what module?)

**Comment by chantisnake** [comment]
like genism, we added bs4 and ete2 and stuff, see `requirement.txt` in the root

**Comment by mleblanc321** [comment]
i don't think we need to add bs4, according to [this](http://cecilialiao.com/2014/02/03/wheres-beautifulsoup-in-anacondas-python/) and a check on the conda list:
```
$ conda list
```
_disagreement on that?_

but the other four are needed;  i'll add ete2 to our install directions

**Comment by chantisnake** [comment]
I know BS4 is in anaconda, but there are other modules, and installing BS4 is not a complicated task.

----

I suggest people to run

``` console
$ pip install -r <path to lexos>/requirement.txt
```

That is what we do in the installers

**Comment by chantisnake** [comment]
I think install scripts are excellent way to do command line install. 

On the other hand we can take advantage of package manager. The best one is, of course, `pip`.

But I also think stand-alone application is necessary for people don't want to install python.
Windows has `chocolatey` (built on powershell and dotnet).
macOS has `homebrew` (built on ruby).
Ubuntu has `ppa` (apt-get), and `linuxbrew`(built on ruby).

that way people will be able to install lexos via 
```console
> choco install lexomics
```
or
```console
$ brew install lexomics
```

**Comment by mleblanc321** [comment]
excellent info (i just printed :)

**Comment by scottkleinman** [comment]
Extending this, could we not have a `lexomics.bat`  which would run `choco install lexomics` (and equivalent shell scripts for Mac and Linux), so that the user could just double click an icon? Either way, this would considerably simplify the installation procedure...

**Comment by chantisnake** [comment]
I think we would have both the chocolatey package and the installer (real `msi` installer for windows and `app`, `pkg` installer for mac) not just a `bat` running `choco` or `brew`.

for Linux an think just the `ppa`is fine, I think if packing a `deb` installer should be as easy as having a `ppa`

**Comment by chantisnake** [comment]
Weiqi, you need to communicate with Mark to determine whether we want to update and continuously support the installer.

**Comment by Weiqi97** [comment]
Sorry I don't quite remember but do we now support pip install? If not, does it worth a try? We talked about installers briefly last week, and at the moment we said we probably won't keep maintaining the installers.

**Comment by chantisnake** [comment]
Yes, we do support pip install. The info are in `info.py` and `setup.py`

**Comment by mleblanc321** [comment]
i have removed the links to the auto-installers from the lexomics website;  i don't think we can work on the auto-installers (at least at this point); (we have updated the manually install directions (see wiki))
