### ISSUE TITLE
Tools use special charactor to concatenate list 

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#429]
I don't know why is originally designed like this = =...

Here is what happens when you have `#` in your search patterns:

Here I entered 3 search patterns: `ð`, `þ`, and `test1#test2`
![capture](https://cloud.githubusercontent.com/assets/10100995/16596961/57737d50-42c4-11e6-9f28-c3479079fb4f.PNG)

this problem is complicated, it is related to the data structure design of rolling window...

If any one want to fix this. fix it in their fork or branch, do not change this on master.

**Comment by chantisnake** [comment]
This is Extremely unsafe, another place we found that is using this is similarity query. uses `***`

**Comment by scottkleinman** [comment]
I'm not sure I entirely understand this bug, but Mark and I were just talking about scrubbing with user-submitted regex patterns. It might be worth making the fix in tandem with a general new feature in Scrubber.

**Comment by chantisnake** [comment]
on rwa, when you want to send a list `some_list` to the front end, we send actually `'#'.join(some_list)`, and on the front end, we use split to unpack that list.

**Comment by chantisnake** [comment]
Fixed in the new simquery and RWA.
