### ISSUE TITLE
decoding issue in excel

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#430]
I was just testing tokenize with dan and az, and I realize that the CSV is not displaying correctly in excel:

the word: `aceorfeð` is displayed as `aceorfeÃ°`:
![capture](https://cloud.githubusercontent.com/assets/10100995/16597260/f1fa49ca-42c5-11e6-8c74-3925f9399186.PNG)

but when I use vim(or even notepad) to open it everything works fine:
![capture](https://cloud.githubusercontent.com/assets/10100995/16597302/28378336-42c6-11e6-8d1d-012d892df558.PNG)

I will investigate on these.

**Comment by chantisnake** [comment]
okay, there is a way...
https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0

you can use import from text file and just click next, excel will handle it all for you... it's just if you double click the csv file it does not work...

**Comment by scottkleinman** [comment]
I'm not sure why I've never encountered this problem, but it looks like something we should document in _In the Margins_. I'm adding that label.

**Comment by chantisnake** [comment]
I uses office 2016, and uses edge browser, and uses Dan. Upload and go straight to tokenize and just download csv.

Double click the csv to open with excel.

See if you can reproduce that.

**Comment by scottkleinman** [comment]
I only have Office 2010, so I can't reproduce it. Discussion [here](http://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically) suggests that inserting a BOM character may help earlier versions of Excel to detect UTF-8 encoding. For _In the Margins_, we might want to link to [this YouTube video](https://www.youtube.com/watch?v=GcYt1mJbwk4).

**Comment by chantisnake** [comment]
but BOM may crash other editors though.
I am not really sure how to handle this.

**Comment by scottkleinman** [comment]
Yes, adding the BOM character may help Excel, but it is not worth it. The problem is with Excel. I think simply providing guidance for the workaround in _In the Margins_ is our best bet.

**Comment by scottkleinman** [comment]
Added to _In the Margins Notes_.
