### ISSUE TITLE
Rolling window pdf situation

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#432]
I made a new issue because this is sort of unrelated to the bug where this doesn't draw for firefox. Right now the SVG other browsers (which should be renamed to svg new tab) button works in every browser. It does exactly what our pdf button currently does, which is open the graph in a new tab and they can go to print and save it as a pdf. Why not just get rid of the pdf button entirely for now? Maybe next summer make a button that actually downloads it as a pdf but for now all it is is a version of the svg other browsers button that doesn't work in firefox. It makes no sense to include it on the page.

**Comment by scottkleinman** [comment]
It's possible that I need to pull again to see what you're working with. Right now, I have a "PDF/PNG" button, which opens Rolling Window in a new tab. I certainly have no problem removing the PDF and just making it "PNG", but are we able to produce a PNG? If not, I have no problem with removing that either for now. You could just set the "PDF/PNG" to `display:none;` for the moment, and we'll look at other export options in the future.

**Comment by SocialHulkHogan** [comment]
okay.

**Comment by scottkleinman** [comment]
I have hidden the button for now.

**Comment by scottkleinman** [comment]
I think we can close this issue.

**Comment by scottkleinman** [comment]
For the PNG side of things, see issue #237.
