### ISSUE TITLE
tokenizer not caching all the options

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#433]
if you click the `regenerate table` button, all the option is not cached(including tokenize and analysis options)

we tried to move the two lines on [lexos.py L1757](https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L1757) and L1758 up,

we changed the code from:

``` python
        return render_template('tokenizer.html', draw=1, labels=labels, headers=headerLabels, columns=cols, rows=rows, numRows=recordsTotal, orientation=csvorientation, numActiveDocs=numActiveDocs)

    if request.method == "POST":
        if 'get-csv' in request.form:
            # The 'Download Matrix' button is clicked on tokenizer.html.
            session_manager.cacheAnalysisOption()
            session_manager.cacheCSVOptions()
            savePath, fileExtension = utility.generateCSV(fileManager)
            managers.utility.saveFileManager(fileManager)
```

to:

``` python 
        return render_template('tokenizer.html', draw=1, labels=labels, headers=headerLabels, columns=cols, rows=rows, numRows=recordsTotal, orientation=csvorientation, numActiveDocs=numActiveDocs)

    if request.method == "POST":
        session_manager.cacheAnalysisOption()
        session_manager.cacheCSVOptions()

        if 'get-csv' in request.form:
            # The 'Download Matrix' button is clicked on tokenizer.html.
            savePath, fileExtension = utility.generateCSV(fileManager)
            managers.utility.saveFileManager(fileManager)

```

and the browser gives us a:
```
DataTables warning: table id=example - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

Tested on Edge and Firefox on windows 10. I thought you will be able to fix it @scottkleinman 

all these changes are not pushed to the remote.

**Comment by scottkleinman** [comment]
I probably won't get to this for a day or two, so I'm just writing an initial diagnosis for my memory. The DataTables warning indicates that the Ajax request did not get a valid response, which normally means that the processing broke on the back end. Probably that means that `session_manager.cacheAnalysisOption()` or `session_manager.cacheCSVOptions()` is not receiving one or more of the variables it expects. Python should indicate this in the error console.

**Comment by chantisnake** [comment]
yes! exactly, I know how to fix this... I am too tired today, I will try to fix this later.

**Comment by scottkleinman** [comment]
OK, my first attempt at this didn't go so well. I moved the session caching function calls up as you did, and, in those functions I used and `if...else` clause to choose whether to get the values from `request.form` or `request.json`. Although this produced some horribly reduplicative code, it did successfully cache the values in the session. One thing I noticed is that the tokenisation settings (e.g. most frequent words) then appear in other tools (e.g. statistics). Is this a bug or a feature, I wonder?

Although the session caching worked, I still got the ajax error, so something is still wrong in the response. Annoyingly, I get no error from the caching functions, and the response object printed in the console looks right. Cheng, did you have a better solution?

**Comment by chantisnake** [comment]
I haven't look at this... (I forgot, stupid brain...)

I think is some constant error in the caching... I will try to fix it now.

**Comment by scottkleinman** [comment]
Thanks. If it's any help, I can print a message right before the return statement in `utility.generateCSVMatrixFromAjax()`, but the message does not print if I put it after the call to this function (`dtm = utility.generateCSVMatrixFromAjax(request.json, fileManager, roundDecimal=True)`) in `lexos.py`. Likewise, I can't print the response before it is returned in the tokenizer function in `lexos.py`. But I can't seem to identify where the error is from this.

**Comment by chantisnake** [comment]
I have traced through the code and found a more serious issue:

for now all the caching function only works with `request.form` not `request.json`, so that is more serious than a constant error...

I think we need to change that in the BackendProgrammingGuide.

**Comment by chantisnake** [comment]
Also, when I got back in china, I realize that I really need to use your local mode feature...

How do I turn it on? @scottkleinman

**Comment by scottkleinman** [comment]
As I mentioned above, the caching from `request.json` is not a huge problem. I fixed it (but didn't push the fix, since it was not elegant). The problem seems to be elsewhere.

On local mode, see issue #431.

**Comment by chantisnake** [comment]
Okay, the thing is that some caching needs to support both form and json (a `or` maybe okay)

**Comment by scottkleinman** [comment]
I've pushed my change, so you can have a look at the result.

**Comment by scottkleinman** [comment]
Some belated progress on this. I _was_ getting the Ajax error on page load, but now I'm not, unless I have something like most frequent words set in my session. When I have MFW set to, say, 10 words, I get the top ten words in my response, but the `recordsFiltered` property is still set to the maximum number of words in the DTM. That property is supposed to be used by the search function. So, if you search for "be", you might get ten word beginning with "be", and `recordsFiltered` would be "10". DataTables needs in the Ajax response. Essentially, we're doing the same sort of filtering with most frequent words and other options, but I'm guessing that we're not adjusting the `recordsFiltered`. That may be the problem. I'll follow up on this the next chance I get.

**Comment by scottkleinman** [comment]
OK, it now seems like most frequent words was not applied (I had to try a number other than 10 to see this). I managed to trace the problem to `file_manager.mostFrequentWord()`, which was still looking for `request.form`. I changed

```python
LowerRankBound = int(request.form['mfwnumber'])
```
to

```python
if request.json:
    LowerRankBound = int(request.json['mfwnumber'])
else:
    LowerRankBound = int(request.form['mfwnumber'])            
```
As I mentioned, this is not necessarily the most elegant solution, but I'll push it as soon as I get rid of all my debugging print statements.

We may have to dig around some other examples of functions which expect `request.form`.

**Comment by scottkleinman** [comment]
Everything mentioned in this issue seems to be fixed by adding `if...else` clauses to test for `request.json`. So I'll go ahead and push those fixes and close this issue. There are still two unrelated problems in Tokenize, but I'll open new issues for those.
