### ISSUE TITLE
migrating to python 3

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#434]
I am thinking of maybe sometime around next year, we should try to migrate lexos to python3.

Since python2 official supports ends on 2020, (see [PEP373](https://www.python.org/dev/peps/pep-0373/#id2)), That means python 2 only have less than 4 years left (that means only 3 lexos teams).

I think we may need to keep up to date.

**Comment by scottkleinman** [comment]
Yes, this has been on my mind as well. Once we get Lexos 3 released, we might want to make a fork and gradually check function by function for compatibility. No doubt the character encoding functions will go haywire...

**Comment by chantisnake** [comment]
Ha, I see you have find my spelling mistake. Sometime I forget you are a English prof. (Kidding, of course)

Well, if we want to work on these together, isn't a branch more appropriate?

**Comment by scottkleinman** [comment]
Yes, branch is what I meant. I just changed the title to facilitate searching. : -)

**Comment by scottkleinman** [comment]
[autopep8](https://pypi.python.org/pypi/autopep8/) may be a good first step for migrating to Python 3.

**Comment by chantisnake** [comment]
this is included in pycharm. I just need to reformat the whole project, only thing pycharm is missing is changing the naming from `likeThis` to `like_this`

**Comment by chantisnake** [comment]
on a more serious subject, when will we release 3.0?

**Comment by scottkleinman** [comment]
Good news that we can just do it through PyCharm.

As for the release of 3.0, the announcement went out on Twitter yesterday. It's official.

**Comment by chantisnake** [comment]
ha, that is great, I will remove the pre-release tag

**Comment by chantisnake** [comment]
uh, I just realize, I cannot download the assets of the release,

can you copy all the info and delete current release and tag, and then recreate a v3.0 tag and a summer 2016 release?

**Comment by scottkleinman** [comment]
So we don't make any conflicting changes, can you comment on [https://github.com/WheatonCS/Lexos/issues/258#issuecomment-246117438](https://github.com/WheatonCS/Lexos/issues/258#issuecomment-246117438) before I do any of the above.

**Comment by chantisnake** [comment]
migration is basically finished, I go through everything with `Dan` and all of them gets good result!

**Comment by chantisnake** [comment]
done in current master
