### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#435]
Not sure what triggers this, but sometimes on first firing up the app you see this 
![lexos](https://cloud.githubusercontent.com/assets/3508076/16771142/709ef4f4-481d-11e6-871b-ec571ce941c7.png) 

I'm looking into this today

**Comment by scottkleinman** [comment]
I got this error after not having Lexos fired up for a couple of days. But it went away as soon as I did anything, and I haven't been able to reproduce it since.

**Comment by chantisnake** [comment]
it seems like flask debugger...

because typically debugger is resource consuming, some software (like visual studio code) turns it off when you have long time of inactive.

**Comment by scottkleinman** [comment]
I'm going to go with this explanation. Let's assume that we turn debugger off for the release version. We can reopen this issue if the problem comes back.
