### ISSUE TITLE
Rolling Window Error Handling Logic

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#436]
In Rolling Windows, the default search pattern is set to strings and the default window type is set to count of characters. If you change the search pattern to words/tokens, you receive an error message saying that you need to use words/tokens as your window type, and Lexos changes it for you. That's good in principle, but it means that you will always get the error whenever you try to use words/tokens as your search pattern. The error is triggered before you get a chance to change the window type for yourself. Perhaps we should remove this attempt to anticipate user error here and do the check on submit. Thoughts?

**Comment by chantisnake** [comment]
hum... I am a little annoyed by this as well...

but simply changing the option without any notice is confusing...

maybe just display a little message on the window type option... also, if the user change search pattern to words/tokens, can't we just disable the string windows type?

**Comment by scottkleinman** [comment]
I think this is a pretty easy fix along the lines you suggest. I'm working on Cutter error handling at the moment, but this was next on my list.

**Comment by scottkleinman** [comment]
I think I've given the validation a more logical structure and will close this. We can re-open it if anyone has problems.
