### ISSUE TITLE
Weighted Counts in Tokenize don't all work 

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#437]
In the Weighted Counts (TF-IDF) options, only Norm:None works (not Euclidean and Manhattan Distance). This is an issue in Lexos 2.5, as well. I don't really understand what Norm:None means (and how it is different from not using weighting), so I'm unwilling to attempt a fix. We should decide what we want to offer for these options.

**Comment by scottkleinman** [comment]
This is a near duplicate of issue #269. Closing that one. The consensus there was to remove Euclidean and Manhattan distances. However, I am still not sure what Norm:None means.

**Comment by mleblanc321** [comment]
in base_analyze.html, i've removed the TF-IDF options from the UI;  we have issues with this code but no time to work on it now, plus i know of no one actually using or requesting this option

**Comment by scottkleinman** [comment]
Is Norm:None still in there? I would use TF-IDF if I could figure out what exactly Norm:None is doing.

**Comment by scottkleinman** [comment]
I think we should re-implement TF-IDF soon but start fresh. I'm going to close this issue and start a new one.
