### ISSUE TITLE
Scrubber hyphen and consolidation enhancements

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#438]
Forked from issue #348, a much needed enhancement for Scrubber would be the ability to choose to replace hyphens with a space, as well as to delete them. This could be part of a general enhancement of the Consolidation function that would allow you to consolidate, say, "black bird" and "blackbird". This would help with a lot of scrubbing edge cases.

**Comment by chantisnake** [comment]
This is not hard to implement on the backend.

**Comment by cgnobrega** [comment]
moved to #956
