### ISSUE TITLE
Cached culling options, bug or feature?

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#440]
When you set the culling options in Tokenizer, Statistics, Similarity Query, Clustering, or TopWord, the options are cached, so the settings will persist in the other tools. The user may not be aware of this, especially if the Culling dropdown panel is closed when the page is loaded. This could lead to some potential bad mistakes when, say, users attempt to cluster the entire DTM and accidentally cluster only the 10 most frequent words. What is the best way of dealing with this issue?

**Comment by chantisnake** [comment]
This is a feature.

**Comment by scottkleinman** [comment]
There's still a potential for confusion. I'm labelling it for documentation in _In the Margins_.

**Comment by chantisnake** [comment]
okay, we made that it, so that user can experiment there MFW or stuff in tokenize or stats and then move on to dendrogram with their desired settings

**Comment by scottkleinman** [comment]
I have now added this to the _In the Margins_ documentation notes, so we can close this issue.
