### ISSUE TITLE
Tokenizer download buttons have UTF-8 encoding errors when the table is transposed

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#442]
They work fine with the default Documents as Columns, Terms as Rows setting.

**Comment by scottkleinman** [comment]
Well, I'm stumped on this one. There appears to be two offending lines in `utility.py`. First, [line 174](https://github.com/WheatonCS/Lexos/blob/master/managers/utility.py#L174):

```python
countMatrix[0] = [u'"' + file_name + u'"' for file_name in countMatrix[0]]
```
This just wraps the filenames in quotes, which isn't necessary to proceed to the next error. So I just commented it out for the moment. The second line is [line 193](https://github.com/WheatonCS/Lexos/blob/master/managers/utility.py#L193):

```python
rowStr = delimiter.join([unicode(item) for item in row])
```
This just creates a comma/tab-separated string of the items in each row. But no matter what I do to the `item` variable, I always get a `UnicodeDecodeError`.

Expressions of bafflement...

**Comment by chantisnake** [comment]
First one is actually necessary, it escapes the commas.

I am guessing you forget to decode filename when you transpose the matrix.

**Comment by scottkleinman** [comment]
I'll try this...

**Comment by scottkleinman** [comment]
Yes, that was the problem. I pushed the fix.
