### ISSUE TITLE
Browser freezes when transposing tables in Tokenizer

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#443]
When you attempt to transpose a table in Tokenizer, there is a browser freeze of a few seconds before the processing icon appears to tell you that there is something happening. The lag is substantially worse going from Documents as Rows to Documents as Columns. The likely culprit is how long it takes to destroy all the data, but it's hard to tell what is going on. I haven't tested whether the lag is intolerable with larger data sets or if it is substantially better or worse in Chrome than in Firefox.

**Comment by chantisnake** [comment]
I think we need a little profiling on this one.

**Comment by scottkleinman** [comment]
Including all the files in the TestSuite large files folder does indeed crash the browser, both Firefox and Chrome. We may be up against a problem in the way DataTables works with HTML tables. With the Documents as columns orientation, it is able to paginate the thousands of possible rows of terms, writing only a few at a time to the DOM. But, with the table transposed, all those terms are now columns and have to be stored in the DOM. That places a burden on the browser...

**Comment by scottkleinman** [comment]
An additional thought. The fixed column and fixed header plugins may be causing problems. In an earlier version of DataTables the fixed header plugin definitely affected tables with large numbers of columns. I'll check this.

**Comment by scottkleinman** [comment]
OK, I turned off the column readjustments and the sorting after initialisation. The browser still freezes, but it unfreezes after about five minutes, and I get a table. When I try to switch the orientation back the browser unfreezes after about three minutes.

I may have to give this a little thought. At the very least, we should be able to detect the number of column and trigger a warning if the table is large enough to cause these problems.

**Comment by scottkleinman** [comment]
I did what profiling I could, but it just seems that DataTables is memory intensive in a way that can't be avoided, particularly with large numbers of columns. So I've introduced a new feature. Tokenizer detects large tables, currently set at 1000 term rows or 1000 document columns. When such a large table is detected, a modal pops up warning that this may cause the browser to freeze or crash. It recommends downloading the table and opening it in a spreadsheet. The user is then given a choice of downloading a CSV, downloading TSV, continuing (and taking their chances), or cancelling. It seems to work.

Note that the choice of 1000 as the threshold is somewhat arbitrary. I am leaving this issue open until we can test and find a sweet spot.

**Comment by chantisnake** [comment]
well, 1000 word is not abnormal... in fact I think less than 1000 words in a passage will be abnormal.

is it possible that you can use the get first 10 term row and then transpose it? so that it will not crash.
and give them the page number on the bottom.

Just like the current layout, but transposed.

**Comment by scottkleinman** [comment]
Yes, I think well above 1000 words will be normal, but I'm not sure how far above. But we can test that.

Currently, when we get a transposed table, we are getting the first ten rows to initialise the table and then drawing the full paginated table by ajax. The procedure is not exactly efficient, but it's not slow. I profile a big table, and the `getTenRows()` function along with getting and transposing the matrix only took about 20 seconds. It was the drawing of the full table that seemed to be where things got stuck.

In any event, the system is workable for now. We can try and optimise for Lexos 3.5.

**Comment by mleblanc321** [comment]
can we close this issue?

**Comment by scottkleinman** [comment]
I think the discussion veered from the issue title, but the bug (or at least the same symptom) is still there. So not ready to close this yet. I think I have fix; I just haven't had a chance to implement it yet.

**Comment by jacksonjreed** [comment]
this seems to be fixed with the tokenizer rewrite
