### ISSUE TITLE
Scrub Tags needs extensive testing

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#446]
It seems to work pretty well, but we should put it to the test.

**Comment by mleblanc321** [comment]
i just found a subtle bug in scrubber:  `remove_punctuation_map()` alters the text (both for internal apos and hyphens), thus it must also be returned (updated) in `scrubber.scrub()`

```
   # -- 4. punctuation (hyphens, apostrophes, ampersands) -------------------------
    if punct:
        # remove_punctuation_map alters the text (both for apos and hyphens), thus it must also be returned (updated)
        text, remove_punctuation_map = get_remove_punctuation_map(text, apos, hyphen, amper, previewing)
```

.... but hmmmmmmmmm, not i'm wondering it this breaks cheng's code that leaves tags alone .... (??)

**Comment by mleblanc321** [comment]
it appears that my fix is ok and didn't break our "leave tags alone" handling;  so, this open issue helped us clear up a bug in scrubbing (apos and hyphens)

**Comment by mleblanc321** [comment]
i'm trying to get a handle on scrubber;  the order of application is not the same as the order in the code; here is my best understanding to date of the actual order of application of scrubbing:

0. Gutenberg boiler plate is (attempted to be) removed, if any
1. if lowercase is ON, we force consolidated, special-char, lemma, and stop-keep words (both from uploaded files and those entered manually) to lowercase (so the 'Make Lowercase' option is applied to all other options);  however, the TEXT is not yet lowercased (see below) but is applied later
2. Special Characters (the TEXT is altered at this point) [note: any special characters inside tags _will_ be modified]
3. Scrub tags (the TEXT is altered at this point) according to the options selected in the tag modal, tags may be left as is, removed, removed along with all contents (from <tag> to end </tag>), or the tag can be removed and its contents replaced with a user-entered value.
4. Remove All Punctuation (if ON): a map is made of all Unicode punctuation characters (unicode metadata categories of 'P' and 'S' for symbol); the text is not altered at this point (only a "delete-map" is built to be applied later; see below)
  1. Keep Hyphens (if ON): a number of "types" of hyphens and dashes are converted to one standard type of hyphen, thus the TEXT is (slightly) altered at this point with the replacement to the standard hyphen and the standard hyphen is removed from the "delete-map" (meaning that the hyphens will remain in the text).
  2. Keep Word-Internal Apostrophes (if ON): the text is altered (using regex) by removing (a standard) apostrophe if it appears at the front of a token (_'bout_) and at the very end of a token, e.g., plural possessive (_students'_). Also, if an apostrophe is surrounded by non-word characters (e.g., a run of apostrophes in the middle of a word:  _foo''''bar_, all but one will be removed; this case is unlikely at best). So single-possessives (_Scott's_) and contractions (_can't_) remain in the text, but all others are removed. The apostrophe is then removed from the "delete-map", but again, note that the overall text is not altered at this point (see below).
  3. Keep Ampersands (if ON):  as with hyphens, a number of "types" of ampersands are converted to one standard type of ampersand, thus the TEXT is (slightly) altered at this point with the replacement to the standard ampersand and the standard ampersand is removed from the "delete-map" (meaning that the ampersands will remain in the text).

**Comment by mleblanc321** [comment]
at this point, i say CHECK;  scrubber needs refactoring (but not now);  the functionality seemed solid (and our "features" we'll have to try and write-up for ITM).  Closing this issue ...
