### ISSUE TITLE
Cut by milestone checkbox is broken in Cutter Individual Options

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#448]
It looks like there may be some general layout issues in the individual options form, as well as the Javascript applied in response to user interactions.

**Comment by scottkleinman** [comment]
I've figured out the fix for the Javascript side of this issue, and it seems worth documenting. The elements in question are created after `document.ready()` is invoked, so events triggered by them won't work inside `document.ready()`. Instead of the typical

```javascript
$(".indivMS").click( function() { ... });
```

You need to use

```javascript
$(document).on("click", ".indivMS", function(event) { ... });
```

**Comment by scottkleinman** [comment]
I've pushed a fix which should improve the layout.

**Comment by chantisnake** [comment]
cong
