### ISSUE TITLE
Scrubber functions don't completely handle markup tags

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#449]
This issue is transferred from #378.

Any easy way to demonstrate this is to upload the GenesisAB .sgml file and try to scrub with with the default settings and without stripping tags. Some punctuation and digits will be removed, and some text changed to lower case--but not all.

We need to explore whether we can improve our regex or whether we need to move to an xml parser to handle this scenario.

**Comment by mleblanc321** [comment]
grrr ... and tags in all caps <TITLE> are not removed ???

**Comment by chantisnake** [comment]
do you mean all text in tags are not handled?

I can fix that, if you guys want...

But is that what we want to do? if they really want to handle tags, shouldn't they just handle tag?

**Comment by scottkleinman** [comment]
I'm working on this now, so please wait for an update.

**Comment by scottkleinman** [comment]
I've just pushed some changes. _Almost_ everything seems to be working. Tags with capital letters and in all caps are scrubbed. The only exception is the root element. In other words, I have a file like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI [
<!ENTITY bar "&#x0305;">
<!ENTITY caret "&#x2227;">
]>
<TEI xml:id="myID" xmlns="http://www.tei-c.org/ns/1.0">
    <TEIHEADER><p>Blankety</p></TEIHEADER>
    <myFacsimile><p>Blank</p></myFacsimile>
    <text><p>Blank</p></text>
</TEI>
``` 
Using the default scrubbing options and "Remove Tag Only", you end up with `<TEI xml:id="myID" xmlns="http://www.tei-c.org/ns/1.0"> blankety blank blank </TEI>`.

I'll investigate why the root element is not being scrubbed.

**Comment by scottkleinman** [comment]
Ah, it's because the root element was not in the list of tags detected. I've pushed a fix. With any luck everything should be working. Please test. If you are using the xml document above, you should end up with `blankety blank blank`.

**Comment by scottkleinman** [comment]
I'm going to tentatively close this issue.
