### ISSUE TITLE
Speed up Multiclouds

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#450]
Generating Multiclouds is slow and often freezes the browser. For future version of Lexos we should assign someone to explore whether a faster implementation is possible.

**Comment by scottkleinman** [comment]
Converting Multicloud to Ajax helps since there is no need to reload the entire page, but it doesn't prevent the browser from freezing. The only way to avoid this seems to be pre-rendering the SVG.

**Comment by chantisnake** [comment]
Any webgl options for details?

**Comment by scottkleinman** [comment]
It's possible to use them together (see [https://bl.ocks.org/vicapow/7f14a531dec565ca0884](https://bl.ocks.org/vicapow/7f14a531dec565ca0884)), but beyond my expertise.

**Comment by cgnobrega** [comment]
this has been fixed in v4.0
