### ISSUE TITLE
Re-organize repo before Lexos 3.0 release

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#452]
This issue is transferred from #331.

Since the GitHub repo contains a variety of development and release files, it might be a good idea to do some gentle re-organisation prior to the next release.

**Comment by chantisnake** [comment]
yes... and someone should really delete that alice.txt in the root...

**Comment by mleblanc321** [comment]
well, at least Alice.txt is gone ...

**Comment by chantisnake** [comment]
I think this issue is no longer relevant.
