### ISSUE TITLE
Double check all requirements before release 3.0

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#455]
Create an up-to-date list of requirements for the install guidelines and for use on the server installation.

Perhaps also create a server install guide.

**Comment by chantisnake** [comment]
I cannot download the windows installer any more... 
Could someone please help me test that...

**Comment by mleblanc321** [comment]
>I cannot download the windows installer any more

what do you mean?  from the [lexomics website](http://wheatoncollege.edu/lexomics/lexos-installers/)?

**Comment by chantisnake** [comment]
installer is hosted on GitHub release (which is hosted on amazon's cloud service called AWS)

and china blocked AWS.

**Comment by chantisnake** [comment]
This issue is probably no longer relevant
