### ISSUE TITLE
Enable the user to select how to replace markup elements

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#457]
It would be useful to allow the user to decide whether to remove an XML/SGML/HTML element completely from the text string or to replace it with a single space. For background, see the discussion in issue #344.

**Comment by chantisnake** [comment]
this is not hard for backend.

**Comment by scottkleinman** [comment]
Also not too hard on the front end. This could be a last-minute bump to "For Version 3.0" status. But I won't do that just yet.

**Comment by chantisnake** [comment]
Although this is easy, I am not sure we will implement that on the last minute.

I think we should focus on the bug for 3.0.

**Comment by scottkleinman** [comment]
Here's a slightly fuller explanation of what we need to do:

In the `Strip Tag` actions, the following options should not replace the text with a space:

- `Remove Tag Only`
- `Replace Element and All Its Contents`

The menu should additional have two additional options:

- `Replace Tag with Space`
- `Replace Element and Its Contents with Space`

Also, we should make sure that patterns like `<pb n="1"/>` are matched by the `Remove Tag Only` and `Replace Tag with Space` options.

**Comment by cgnobrega** [comment]
For each tag v4.0 has 
- remove
- remove all
- replace (w/ dialogue to choose replacement)
- none
