### ISSUE TITLE
Multicloud gives a Bad Request Error in Chrome

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#459]
It works fine in Firefox, and there's no error in either the front end or back end consoles. I'm hoping it's a browser caching issue. But I thought I would report it in case it doesn't go away...

**Comment by chantisnake** [comment]
bad request typically means keyerror in session.

My recommendation is to check the request parameter and conform with the backend.

My intuition is that this may be related to Mallet file upload

**Comment by scottkleinman** [comment]
Typically, a key error would break Firefox as well, and Python usually tells you where the error is. No luck this time. But it should be possible to trace that. I did some work on the Multicloud UI yesterday, but I am not sure whether the problem existed earlier and nobody noticed...

**Comment by scottkleinman** [comment]
Chrome and Firefox had different interpretations of the Javascript to submit the form. I've pushed a fix.

**Comment by chantisnake** [comment]
bad request will not raise a key error, because session is not a pyhthon dict, it is a `secure cookie` type, therefore the exception will not be raised.
