### ISSUE TITLE
Active Documents broken (on new? startup)

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#461]
i just pulled on my Mac laptop (Sat, July 23, 11:00am, EST) and the value for the active documents is broken:

When i checked it (with no files uploaded) i got:
![image](https://cloud.githubusercontent.com/assets/1066011/17078691/a61ff56c-50c7-11e6-9aee-4da9deb4e057.png)

and then when i uploaded one file i got:
![image](https://cloud.githubusercontent.com/assets/1066011/17078694/b4eb3674-50c7-11e6-9b5f-a3c1473b4433.png)

**Comment by scottkleinman** [comment]
This looks like issue #435.

**Comment by mleblanc321** [comment]
perhaps we can check before print to see if it contains a valid value?  if not, make "" no string to print?

**Comment by scottkleinman** [comment]
We should be returning `0` if there are no active documents; otherwise, we return the length. I've added an extra check in Jinja:

```python
{% if numActiveDocs is not defined %}
{% set numActiveDocs = 0 %}
{% endif %}
```
This is, of course, assuming that the error will be caught by `is not defined`. I'll close this issue, and we can re-open it if the error recurs.

**Comment by mleblanc321** [comment]
not same error ... but in the spirit, i just happened to CUT and noticed that after Apply Scrubbing, the active document tally is not updated (?)

**Comment by scottkleinman** [comment]
I'm guessing that the issue there is that we switched cut to an ajax function, which means that we need to add the ajax call to `getActiveDocuments()` to the implementation. Good catch!

**Comment by scottkleinman** [comment]
Well, I was able to get the information from the response to the original ajax function, so I fixed it entirely on the client side. I've pushed the fix.
