### ISSUE TITLE
Tokenizer is missing Row Total column

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#462]
In version 2.5 the left and rightmost columns were fixed, and the rightmost column was a total of the row values. This is missing in version 3.0. Looks like an oversight.

**Comment by mleblanc321** [comment]
dang, good catch;  sum of rows (probably) important, since we base MostFreqWord (MFW) based on those sums (right?);   perhaps @chantisnake could take a peek? :)

**Comment by scottkleinman** [comment]
There are front end and back end pieces to this puzzle. I have enabled left and right fixed columns on the front end, although, at the moment I'm having trouble getting the right column to look right. Still working on that.

On the back end, a total needs to be added in one of the matrix generating functions. For now, I have added cells by hand with the total "327", just so that I can see the result on the front end.

**Comment by mleblanc321** [comment]
and i am wondering if  @chantisnake on backend might be able to consider?

**Comment by chantisnake** [comment]
adding a column on the backend is not hard.

The problem is we are not displaying the whole table, that means the sum may be on the last page, which is confusing. I don't know how you guys want to deal with this problem.

**Comment by mleblanc321** [comment]
oh, i thought we were able to fix (always show) the right-most column?

**Comment by mleblanc321** [comment]
dang ... tokenizer is not responding (as of MON, 10:30am EST) ... and manage (deselect, select: nope) not working

**Comment by scottkleinman** [comment]
Just got up. I'm checking...

-S

On 25 July 2016 at 07:33, Mark D. LeBlanc <notifications@github.com> wrote:

> dang ... tokenizer is not responding (as of MON, 10:30am EST) ... and
> manage (deselect, select: nope) not working
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WheatonCS_Lexos_issues_462-23issuecomment-2D234970592&d=CwMCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=fkkkcAta9tNbJT0GbA-b8fBT5Vx0day25Z1KcBOKxKQ&m=PhCKPkgCs702_uN5tqcaJbovHdDZHjDKu5zdJxfuXaY&s=qu7Ivl0k1Dz5iChL_Fp9EpQjQ0sW3R6FYRq39_YyEUE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABEuHYqtue2UTopfpyRnv6L0ZktAW99Kks5qZMklgaJpZM4JTYfC&d=CwMCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=fkkkcAta9tNbJT0GbA-b8fBT5Vx0day25Z1KcBOKxKQ&m=PhCKPkgCs702_uN5tqcaJbovHdDZHjDKu5zdJxfuXaY&s=qTeXXlDgzmFxNpf7UPTVHp2HTqVm9AHnPFpiH9stLBk&e=>
> .
>



-- 
Scott Kleinman
Professor of English
Director, Center for the Digital Humanities
California State University, Northridge

**Comment by scottkleinman** [comment]
Yes, the rightmost column can be fixed, although I'm presently finding that it is placed about fifteen pixels too far to the left when you have about ten or more documents.

@chantisnake, we need to add up the values of all the cells in each row, if that wasn't clear. This total will be displayed in the final column for each row that is displayed on the screen. The way DataTables works means that it is easiest if we can add this total as a new column in the matrix before we begin processing the matrix to return the data to the template.

**Comment by mleblanc321** [comment]
tokenizer doesn't seem to be responding to Regenerate Table (blue) button;  (but data is resonding, e.g., to MFW=5 in downloaded .csv file) ??

**Comment by scottkleinman** [comment]
This appears to be related to the fixed column issue. I'll see what I can do.

**Comment by scottkleinman** [comment]
I'm not sure where I introduced an error, but I've rolled back the code, so it should work on your next pull.

**Comment by mleblanc321** [comment]
ok, better ... but we've lost your column of SUMs (327s) ...

**Comment by scottkleinman** [comment]
Yes, I think I missed a place to inject that, and that caused the problem. But I'm not 100% sure. Better to leave it out since the implementation of the actual sums will be done differently.

Meanwhile, we have a more important issue. It appears that fixed columns are not compatible with fixed headers (see the [compatibility chart](https://datatables.net/download/compatibility)). I think they were partially compatible in the last version of DataTables, and I managed to fake it with some clever css; or else I never tested enough documents to notice there was a problem. In any event, I'm not sure I can find a workaround with the current version. I'm going to test turning off the fixed header to see if we really need it.

**Comment by mleblanc321** [comment]
you are DataTable god ... hmmm

wait, why do we want SUM ?   it doesn't make sense for proportions does it?

**Comment by scottkleinman** [comment]
Well, if you cut _Pride and Prejudice_ into two segments, and the term "a" has the proportions 0.0217 for segment 1 and 0.0174 for segment 4, does that mean that the proportion of terms in _Pride and Prejudice_ that are "a" is 0.0391?

**Comment by mleblanc321** [comment]
yes, but if you have 5 documents and each has 0.5 proportion for "the", then the sum is 2.0 (?)

**Comment by scottkleinman** [comment]
Ah, I see. The sum has to be changed to an average or the proportion of the corpus as a whole. We could probably change the column title and the calculation depending on whether the table is set to proportional or raw counts.

**Comment by mleblanc321** [comment]
wait, i think we always want AVERAGE for the last column, no?

**Comment by scottkleinman** [comment]
Average and sum make sense for raw counts. I'm not sure sums make sense for proportional counts. Theoretically, we could show and hide columns, but that adds a new layer of DataTables complexity...

**Comment by mleblanc321** [comment]
i think any sorting of the last column needs to be a measure of central tendency (should always be AVERAGE)

>Average and sum make sense for raw counts
IF Documents as COLUMNS

sum isn't helpful if Documents as ROWs (sum of proportions will always be 1.0; sum of raw counts just sorts by the document with the most words:  neither is really helpful imho)

**Comment by scottkleinman** [comment]
Users will want accessible raw counts for each term in their corpus and will want raw counts for the total number of terms in each document.

1. Total number of each term in the corpus: Users can get this from Word Cloud, but do we want to force them to go there?
2. Total number of terms in the corpus: Users can go to Statistics, but do we want to force them to go there?

Statistics also gives the average term frequency. For five documents where the proportion of the term "the" is 0.5, the average term frequency is given as 2.0.

Damn! I wish we had given this more thought earlier.

**Comment by chantisnake** [comment]
do we really want to add functionality at this point?

I think releasing 3.0 should be the number 1 priority. Then we migrate to python3. And then let's talk about new or miss functionalities. 

That is my plan.

**Comment by scottkleinman** [comment]
Well, this isn't exactly "new functionality". Lexos 2.5 already gives the sum of the row values, but it somehow fell out of the revision of Tokenizer for Lexos 3.0. What _is_ new is our considering whether we actually want it there (i.e. Is it useful for our users?).

**Comment by mleblanc321** [comment]
if we don't provide an ending column (with AVG, if anything is my recommendation), the user will have to sort by some specific document (not ideal)

i think we should put the AVG column back in ( @chantisnake can you do this on the backend ?)

**Comment by scottkleinman** [comment]
It is also possible to get this information on the front end. I'll investigate that approach.

**Comment by scottkleinman** [comment]
This is not as easy as it first seemed, but I thin back end is definitely better than front end. I've pushed some changes using pandas that add a "Total" column containing the sum of each row. This is only if the table is set to Documents as Columns, Terms as Rows. For a transposed table, we need to add another row at the end.

I tried using pandas' `mean()` function to get the average instead of the sum, but it doesn't like something in the input data and returns `NaN`. If anyone wants to take a look, maybe you can figure it out before I do.

**Comment by mleblanc321** [comment]
i played, but didn't get it (now must move to a mtg with prez et al);

i'm hopeful (!) that cheng might be able to pull this out of his hat? :)

**Comment by chantisnake** [comment]
okay, want you guys need is just adds up the count for each paragraph (get the frequency of a word in the corpus)

That is okay to do.

But this is complicated for 2 reasons:

   1. when people uses prop instead of raw counts, we need to handle that, and that may need to change the logic of the backend.
    2. what if they have 80 documents? should we display a matrix with 80 columns?

I think let's just leave it for next version (not necessarily next year). notice the more change we make, the harder it is to migrate to python3.

If you guys really want this done. I think I can make it happen, but it is not necessarily beautiful.

**Comment by scottkleinman** [comment]
In my latest commit, I've got partway there. A column is added with the total for each row. The challenge is to change that to an average. I can't seem to get that working. We do display 80 columns, but you can scroll horizontally. DataTables has the ability to show and hide columns, so we can probably add that as a feature.

Unfortunately, I think this is an essential feature--at least showing word counts when Tokenizer is set to use raw counts. Users will want this. And, as Mark points out, averages is more useful, and our users may not know it instinctively.

I don't think we need an elegant solution now, just something that will get it done. My solution starting in [line 952](https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L952) of `lexos.py` is not exactly elegant, but at least it takes relatively few lines of code. Have a look.

**Comment by chantisnake** [comment]
Okay, I will get this working when I have time.

I am currently studying GRE. I can make this work in a week, probably.

But, I cannot guarantee that it will work with tf-idf.

**Comment by scottkleinman** [comment]
Our DTM does not look like the ideal pandas DataFrame. When you convert it (`df = pd.DataFrame(dtm)`), you get this structure:

```python
          0       1       2
0                Az     Dan
1     term1       3       9
2     term2      32      24
3     term3      27       3
```

The following code will get you the sum and the average for each row and stick it in a new column.

```python
sums = ["Total"]
averages = ["Average"]
length = len(df.columns)+1
for i in range(0, length):
    if i > 0:
        sums.append(df.iloc[i][1:].sum())
        averages.append(df.iloc[i][1:].mean())
df = pd.concat([df, pd.DataFrame(sums, columns=['Total'])], axis=1)
df = pd.concat([df, pd.DataFrame(averages, columns=['Average'])], axis=1)
                        
print(df)
```
You end up with

```python
       0       1       2   Total  Average
0             Az     Dan   Total  Average
1  term1  0.0009  0.0009  0.0018   0.0009
2  term2      32      24      56       28
3  term3      27       3      30       15
```

I haven't tried to put this in Lexos yet, but since the DTM is returned to `lexos.py` from `utility.generateCSVMatrixFromAjax()`, the data should be whatever form the user has selected: raw counts, proportional counts, or TD-IDF.

From there, it's just a matter of converting the pandas DataFrame to a matrix (list of lists), which is a one-liner. I'll try it in Lexos tomorrow. If it works, we just need to check whether there's a more efficient way to code it.

**Comment by scottkleinman** [comment]
OK, I can confirm that the code above works, although it displays some curious data before getting the correct data from the POST request. I'll push my version to GitHub for you to pull and have a look.

One thing you'll notice is that we need to add some serious rounding to the numbers. But that can be done to the data after it leaves the pandas DataFrame format.

**Comment by mleblanc321** [comment]
quick peek:
*  dang, we've lost select in Manage again?   see Manage, Select Documents to Alter/Analyze: can't select individual or all or deselect (?)

* hmmm we lost the sort options on the columns

* hmm, the variable end ... ?

**Comment by chantisnake** [comment]
If we decide to use panda data frame, then I think I may need a little time to read the document.

what if we just use the `sum()` function for now? I guess that will not slow down the process by a lot.

**Comment by mleblanc321** [comment]
agreed, functionality is needed first

**Comment by mleblanc321** [comment]
Regenerate Table (blue button) is not working;  never in POST section of def tokenizer()   in lexos.py ?

**Comment by scottkleinman** [comment]
Try pulling again.

On 29 July 2016 at 07:59, Mark D. LeBlanc <notifications@github.com> wrote:

> Regenerate Table (blue button) is not working; never in POST section of
> def tokenizer() in lexos.py
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__lexos.py&d=CwQCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=fkkkcAta9tNbJT0GbA-b8fBT5Vx0day25Z1KcBOKxKQ&m=JT_5Smug7jZY_LVBWSkALM_URLYr-X48OGAD3sDg8WQ&s=5fxOZtnbIkK9BwK4hkgE0XwZFyV0DyiBi4D4840IqrQ&e=>
> ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WheatonCS_Lexos_issues_462-23issuecomment-2D236203950&d=CwMCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=fkkkcAta9tNbJT0GbA-b8fBT5Vx0day25Z1KcBOKxKQ&m=JT_5Smug7jZY_LVBWSkALM_URLYr-X48OGAD3sDg8WQ&s=p1-Bos70j-VhgdE70ffVkge71ZikU1wtUsx0iRUwio8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABEuHRx8b098Kwpnf3QPkwyrWBfDVyflks5qahVegaJpZM4JTYfC&d=CwMCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=fkkkcAta9tNbJT0GbA-b8fBT5Vx0day25Z1KcBOKxKQ&m=JT_5Smug7jZY_LVBWSkALM_URLYr-X48OGAD3sDg8WQ&s=US6yXSx06gy8NWmkHKL0VN2h5tyTchH1ZIjMFDp5XOs&e=>
> .
>



-- 
Scott Kleinman
Professor of English
Director, Center for the Digital Humanities
California State University, Northridge

**Comment by mleblanc321** [comment]
ok ... i think i'm back to a testing state

-- we lose the AVG column on POST ?

**Comment by scottkleinman** [comment]
I just fixed that. Try pulling again.

On 29 July 2016 at 08:22, Mark D. LeBlanc <notifications@github.com> wrote:

> ok ... i think i'm back to a testing state
>
> -- we lose the AVG column on POST ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WheatonCS_Lexos_issues_462-23issuecomment-2D236210107&d=CwMCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=fkkkcAta9tNbJT0GbA-b8fBT5Vx0day25Z1KcBOKxKQ&m=WMc_mVo4UNmuk2E-2QwWCiuRUmGUhfSAoeg3CmYzAvw&s=otEtAy2P6h9qVnhstwC_aGNoHsiX3guO6s6U1fuWlOY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABEuHTdRDDqbW2YVQsHel6q79hArr7jzks5qahq1gaJpZM4JTYfC&d=CwMCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=fkkkcAta9tNbJT0GbA-b8fBT5Vx0day25Z1KcBOKxKQ&m=WMc_mVo4UNmuk2E-2QwWCiuRUmGUhfSAoeg3CmYzAvw&s=8U4HDdBqmOwcZg1NkzZd7DuXd15mBRRxssNm2BJ1P9E&e=>
> .
>



-- 
Scott Kleinman
Professor of English
Director, Center for the Digital Humanities
California State University, Northridge

**Comment by scottkleinman** [comment]
We're using pandas in a very limited and probably not very efficient way at the moment. But at least it's functional.

It's definitely worth scanning the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/10min.html) when you have a spare moment, just to see its potential.

**Comment by mleblanc321** [comment]
so the Total and Average columns (when using 'Documents as Columns') seem to be working;  nice to have them there (for sorting);  nice job

**Comment by scottkleinman** [comment]
There's still quite a bit of work to be done. Here are some questions and tasks:

1. Should we display columns for totals **and** averages columns?
2. Are you seeing the first ten rows flash with weird data (including "nan") before it gets overwritten? I have the beginnings of a fix for this if it's annoying.
3. We need to create a new row for totals and averages in transposed tables.
4. Are we OK leaving these at the end of the table without a fixed column? Fixed columns and fixed headers will hopefully be compatible in the next version of DataTables, but they're not at the moment.
5. Is the current implementation making the process of generating the table noticeably slower than if we did not produce the extra columns?

**Comment by chantisnake** [comment]
I am afraid I cannot contribute any more. My surface book is broken (so is my MacBook), and I have to fix it in the US...

For now I am contacting my friend to help me fix it...

It is gonna take at least a month to get it done...

**Comment by scottkleinman** [comment]
Oh that's horrible! I hope you can get something to work on in the intervening time. We'll still be here when you get up and running again.

**Comment by mleblanc321** [comment]
dang ...

**Comment by cgnobrega** [comment]
Weiqi did a tokenizer re-write for these issues, and in v4.0 there are row counts/page counts, and we decided against fixed columns
