### ISSUE TITLE
Document selector appearance

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#463]
I've discovered that the document selector check boxes are implemented slightly differently in Word Cloud, Multicloud, and Statistics. Before I create one implementation, I'd like to know which one has the most attractive appearance. Please pull the latest code and let me know your views.

**Comment by mleblanc321** [comment]
umm, my UI (Mac 10.11.5, Chrome 51.0) has no response on menu UI items (Manage responded/worked;  but not Prepare/Analyze/Viz ??

**Comment by scottkleinman** [comment]
Damn! I may have deleted something essential. Change `bootstrap-override.css` to `bootstrap.css` in `base.html` and let me know if the functionality returns. I'll be out for about two hours but will then check further...

**Comment by mleblanc321** [comment]
umm, where is bootstrap-override.css ??

**Comment by scottkleinman** [comment]
[https://github.com/WheatonCS/Lexos/tree/master/static/css](https://github.com/WheatonCS/Lexos/tree/master/static/css)

**Comment by mleblanc321** [comment]
i am not finding:  bootstrap-override.css

**Comment by scottkleinman** [comment]
For some reason, I never pushed the new `base.html`. Pull the code again, and it should call `base-override.css`. Then we'll see if you're still having display problems.

**Comment by mleblanc321** [comment]
yay, i can see scrubber again (i missed it) [thx]

**Comment by scottkleinman** [comment]
Phew! So, back to the original issue, which document selector appearance looks best?

**Comment by mleblanc321** [comment]
Word Cloud, Multicloud, and Statistics
and Sim-Query

i like Statistics:  check/uncheck, especially the indentation of choices below

**Comment by scottkleinman** [comment]
Great! I'll use that one.

**Comment by scottkleinman** [comment]
Well, this revealed another problem with the document selector. The document names were not being sorted. I fixed that along with the appearance and have pushed the changes.

**Comment by mleblanc321** [comment]
nicely done (again), scott
