### ISSUE TITLE
d3.js is not the latest version

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#464]
I discovered this by accident when Rolling Windows broke in local mode. It turns out that we are loading d3.js version 3.5.5. If you try version 4.0, everything breaks. For the time being, I placed version 3.5.5 in `static/lib/d3`, but we'll have to address this eventually.

**Comment by chantisnake** [comment]
This issue is no longer relevant since we are using plotly as the new render engine for rolling window.

I can be wrong. If I am, feel free to reopen this issue.

**Comment by scottkleinman** [comment]
The word cloud and bubbleviz tools use d3 without plotly, so we will still need to investigate.

**Comment by chantisnake** [comment]
okay... so the new version also breaks them... the new version is troublesome...

**Comment by chantisnake** [comment]
I don't know if we can get to that this year.

**Comment by scottkleinman** [comment]
Yes, it's a tricky one. As long as everything works, we can de-prioritise it. But issue #450 has some priority, and we may have to investigate them in tandem.
