### ISSUE TITLE
Dendrogram with two leaves triggers an error

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#465]
If you try to generate a dendrogram with two leaves, you get `TypeError: inconsistentMax is undefined` in the console. You still get a dendrogram, but the error then trips up other minor Javascript UI functions on the page. This should be fixed eventually, but we can probably let it go for Version 3.0.

**Comment by mleblanc321** [comment]
hmmm

**Comment by scottkleinman** [comment]
I am not encountering this error any more. However, the UX is less than ideal. Right now, the **Number of Leaves** field has HTML 5 form validation. If you try to enter "1", the field turns red and Lexos won't let you submit. If you enter "2", it works.

So I think we can consider this issue closed. That said, I'm not entirely satisfied with the UX of manipulating number of leaves, but I'll open a new issue for that.
