### ISSUE TITLE
cut doesn't preserve CLASS labels

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#466]
i uploaded DAN and AZ
then before cutting, i assigned DAN and AZ as Class Labels
then cut
but new segments didn't retain Class labels:  but they should inherit parents class labels, right?

**Comment by scottkleinman** [comment]
Well, we probably re-used old code from before class labels could be set.

It makes sense to me have child documents inherit their parents' labels. My only counter-argument is that, if the user _doesn't_ want that to happen, they may then have to end up removing all the class labels on the children. But Manage provides the ability to do that change as a batch. I just did it, and it wasn't that big a deal.

So I'll look into updating the class labels in Cutter tomorrow if anyone in a more advanced time zone doesn't get to it first.

**Comment by chantisnake** [comment]
I think this is an easy fix

**Comment by chantisnake** [comment]
fixed in commit 78de433
