### ISSUE TITLE
The order of column headers in Tokenizer is not always consistent

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#467]
This can lead to some interesting results.

![lexosbug](https://cloud.githubusercontent.com/assets/1125917/17122475/8e72e882-5290-11e6-9c89-c9efd1b1c2ca.PNG)

I was a little shocked to see a nautical term so prominent in _Pride and Prejudice_ but non-existent in _Moby Dick_! The problem does not seem to be in the data. It's just that the headers get ordered differently (possibly because they are coming out of a dictionary?). I'll check into this tomorrow.

**Comment by chantisnake** [comment]
From your narrative this sounds like a bug...

I don't think this is related to dictionary.

Also how should I reproduce the result above?

**Comment by scottkleinman** [comment]
Load the files in `TestSuite/Experiments/LargeFiles`. Scrub them with the defaults. Then load Tokenizer. Note the order of the column labels. Then click the Regenerate Table button (with or without changing the options). You'll see the column label order change.

**Comment by scottkleinman** [comment]
I should add that looking at the word "abaft" is useful because it is a nautical term that only occurs in _Moby Dick_.

**Comment by chantisnake** [comment]
I think the default is proportional count, there why is there number larger than 1

**Comment by scottkleinman** [comment]
Oh, I might have generated that table using TF-IDF.

**Comment by scottkleinman** [comment]
It seems like regenerating the table causes the columns to re-order based on the highest number in the first row.

**Comment by scottkleinman** [comment]
I am no longer able to reproduce this issue. It may have been browser caching of a bug caused by my experimenting with fixed columns. I'm going to keep this issue open for a while just in case.

There is another issue related to column ordering. As mentioned above, the matrix values are given in the order that files were added to the file manager. Assuming document labels keep this order, the table will not be sorted alphabetically. In other words, if you upload _War and Peace_ followed by _Pride and Prejudice_, they will appear in that order. If you cut _War and Peace_ into segments, the segments will then appear after _Pride and Prejudice_. This probably needs to be dealt with pretty deeply on the back end. Maybe we should leave it for Lexos 3.5?

**Comment by scottkleinman** [comment]
I think the original issue has gone away, so I'll close this.
