### ISSUE TITLE
deletes all the install guide, and move it else where

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#468]
I am just bothered by PDFs and DOCXs in the repo.

Typically the install guide should be in the wiki's tab.

**Comment by scottkleinman** [comment]
I think the are two separate issues here. The wiki requires a little extra effort to edit locally. It can be done by cloning the wiki: [https://help.github.com/articles/adding-and-editing-wiki-pages-locally/](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/).

The other issue is the use of the GitHub repo as a document repository. I'm uncomfortable with this too, but I prefer it to using Wordpress (if that is even possible on the Wheaton installation). An alternative is Scalar. The main thing is to make sure we have a system for keeping all the documents in sync.

**Comment by chantisnake** [comment]
wordpress is great, and scalar is a good tools too.

Both of them are better than pdf and docx in the repo.

We might need to consider how to write once and publish on all 3 places.

That is a nice project to work on for myself.

**Comment by chantisnake** [comment]
closing this in favor of #489
