### ISSUE TITLE
Document label ordering in Tokenizer

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#470]
Transferred from issue #467:

In Tokenizer, the matrix values are given in the order that files were added to the file manager. Assuming document labels keep this order, the table will not be sorted alphabetically. In other words, if you upload War and Peace followed by Pride and Prejudice, they will appear in that order. If you cut War and Peace into segments, the segments will then appear after Pride and Prejudice. This probably needs to be dealt with pretty deeply on the back end. Maybe we should leave it for Lexos 3.5?

**Comment by mleblanc321** [comment]
>leave it for Lexos 3.5
dang; yes post 3.0 release

**Comment by chantisnake** [comment]
This is a bug though... We don't want our stable version to produce any result that is simply not true.

**Comment by scottkleinman** [comment]
As far as I can tell, the column labels and column data do actually match. So mainly it is a matter of presenting the columns in an order that will make sense to users, rather than forcing them to download the table and re-order the columns in Excel.

**Comment by chantisnake** [comment]
okay, that is for next version

**Comment by scottkleinman** [comment]
I've had a second look at this. In principle, it should be pretty easy to sort the columns in the pandas data frame. In practice, we'll need natural sorting. Right now, our data frame is constructed with numeric indices for each column, rather that string labels. So it's impossible to do alphabetical sorting without getting the intended sequence and then matching it to each column index number. It doesn't seem worth it. A better approach is to change how we construct the data table so that the header labels are the column indices. But that reinforces the conclusion that this is a task for Lexos 3.5.

**Comment by cgnobrega** [comment]
see #960
