### ISSUE TITLE
File names in downloaded files

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#475]
I just grabbed the _Rāmāyaṇa_ using the web scraper and changed the document names to things like `Araṇyakāṇḍa`. I then downloaded the files from Lexos to my computer. Windows did not object to the Unicode in the file name, but the files did not have the `.txt` extension. I had to add them by hand. Since file names are generated from document names, which can be changed, it might be good to do a check for the extension and add it if it does not exist. But I've labelled this a question in case anyone has other thoughts about this issue.

**Comment by chantisnake** [comment]
so, both the filename and extension are wrong on windows?

**Comment by scottkleinman** [comment]
The extension isn't wrong; there just isn't one. The filename itself is probably right, given the workflow I used. Since I used web scraper, the document name (in the current version) was automatically given as "url0", which is meaningless. I changed it to "Araṇyakāṇḍa", and that is definitely preferable for the name of the downloaded file. But, if I had started by uploading a file called `Araṇyakāṇḍa.txt`, we _could_ choose to use that as the name of the download file, even if I change the document name. In terms of the columns in Manage, that would be using the value in the Original Source Column, rather than the Document Name column. But I _think_ the user is more likely to want their downloaded file to have whatever name they have given the document in the Document Name column.

**Comment by chantisnake** [comment]
okay, this is caused by web scraper, let's just mark that function as beta.

This can be changed once 3.0 is released, if you just want to add a 'txt'

**Comment by scottkleinman** [comment]
It's not actually caused by web scraper. If you upload a file called `filename.txt`, change the Document Name in Manager to `newname`, and download the files, the file will be called `newname`, not `newname.txt`. This seems to be important enough to fix before the release of 3.0, so I'm upgrading this issue to a bug. It needs to be changed in the download functions for Scrub and Cut, but it should be ab easy fix.

**Comment by scottkleinman** [comment]
Luckily, both Scrub and Cut use the same function. I've added a check for an extension, and now the downloaded file will always have one.

**Comment by chantisnake** [comment]
I think a better way would be add a extension in web scraper

**Comment by scottkleinman** [comment]
That wouldn't catch instances where you upload a file and then change the name without using web scraper, whereas my fix covers everything.

However, right now, web scraper simply names every document `url0`, `url1`, etc., which is not ideal. Eventually, we'll want to change that system to something more intelligent. At the moment, the only thing web scraper has to use is the full url, and I didn't think that was a particularly good idea. Maybe the future input should be something like `name: url` so that Lexos can use the user's desired name for the eventual document and file names.
