### ISSUE TITLE
optimizing tokenization

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#476]
as of SUN, Aug. 13, 2016
tokenizer for the 4 large novels in Experiments/LargeFiles/
takes about 30+ seconds (when scrubbed)

i shaved about 5-10 seconds off with some (fairly trivial) optimizations, but this Issue is to highlight that there are likely more savings to be found in here

**Comment by chantisnake** [comment]
Hum... I think we can do some optimization on concatenating list.

**Comment by mleblanc321** [comment]
right;  but, tokenizer is fragile (that is, it is hard for someone, other than Scott, to make changes without breaking something (else)) ... so for now, i think we'll leave as is for v3.0 (and hopefully, it'll hold up)

**Comment by scottkleinman** [comment]
Theoretically, nothing should break if the back end returns the same values to the front end, so it's worth experimenting. But Mark is right. We've got _something_ working on localhost and the server at the moment, so we should probably try to implement any changes quietly as part of 3.1, and maybe in tandem with a server upgrade strategy. I think we want to make sure we're running the latest versions of numpy, pandas, scipy, and scikit-learn.

**Comment by jacksonjreed** [comment]
think this is fixed by tokenizer rewrite--I used the same files and it took ~6 seconds.
