### ISSUE TITLE
Silhouette score options are unclear

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#478]
Can anyone explain the silhouette score options? The criterion (maxclust, distance, inconsistent, monocrit) and threshold labels will be meaningless to most users, and looking at the [code](https://github.com/WheatonCS/Lexos/blob/master/processors/analyze/dendrogrammer.py#L91) didn't help me much.

**Comment by chantisnake** [comment]
I can only explain some of them... and I haven't done any further investigation for almost 2 years.

I will see what I can do with this.

**Comment by scottkleinman** [comment]
I now understand what the options mean, except for `monocrit`, but the implementation is really convoluted, and I don't feel really confident about it. The biggest problem is when you generate a dendrogram, leave `/cluster`, and then return. We don't cache any of the information returned by the function that generates the dendrogram, so we lose the silhouette score (and possibly the options). I think we might want to work on re-factoring the implementation. (Note: silhouette scores for k-means are  different implementation that works fine.)

I have hidden the silhouette score options fieldset with `display:none`, and hidden the button by commenting it out. So you'll need to unhide those if you want to play with the options. The biggest question is how a user would choose (or if a user could choose) a threshold other than (the maximum number of possible clusters, i.e. `maxclust`) before they have generated a dendrogram.

Anyway, for now, we can keep it hidden in the v 3.0.

**Comment by scottkleinman** [comment]
OK, I've re-enabled `maxclust`, which is probably the most intuitive criterion for humanities people. Basically, the user only has a choice for the threshold (re-labelled "maximum number of clusters"). I didn't get rid of anything. All the other options are just commented out.

**Comment by chantisnake** [comment]
that makes sense

**Comment by scottkleinman** [comment]
I've tried to put a layman's explanation up at [http://scalar.usc.edu/works/lexos/silhouette-scores](http://scalar.usc.edu/works/lexos/silhouette-scores). But I didn't cover the `distance` and `monocrit` settings.

**Comment by chantisnake** [comment]
I think silhouette score are getting removed.

Do we still need this function?
