### ISSUE TITLE
Documenting Release 3.0

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#481]
This is really just merging off-topic discussion in issue #258 and [https://github.com/WheatonCS/Lexos/issues/434#issuecomment-246117575](https://github.com/WheatonCS/Lexos/issues/434#issuecomment-246117575).

Right now, the [release](https://github.com/WheatonCS/Lexos/releases/tag/v3.0) has the binary installers attached, as well as zipped in the download. Do we want to do that? Also, the development documents are included in the release, which I am still not keen on.

Can we sort this out before finalising on Zenodo?

**Comment by chantisnake** [comment]
Yes, binary downloads are what releases are for.

**Comment by scottkleinman** [comment]
I think we can close this issue.
