### ISSUE TITLE
Implement webpack

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#485]
The [`webassets`](https://webassets.readthedocs.io/en/latest/) library might gain us some performance improvements and seems to be generally a good idea. It's worth investigating.

[Flask-Assets](https://flask-assets.readthedocs.io/en/latest/) is an integration for Flask.

**Comment by scottkleinman** [comment]
Due to a bug in [webassets](https://github.com/miracle2k/webassets/issues/291), it appears that implementation might hinder development. See also discussion [https://github.com/WheatonCS/Lexos/pull/640](https://github.com/WheatonCS/Lexos/pull/640) (I'm not sure if the link will break if the branch is deleted).

As an alternative, we might consider minifying and budnling our Javascript and CSS manually with an aim towards reducing the number of http requests and simplifying the code the the template files.

**Comment by chantisnake** [comment]
Webassets is no longer under active development. I suggest to use webpack instead.

**Comment by scottkleinman** [comment]
I think this still might be a good idea, albeit with a change to webpack; however, it might introduce an unnecessary level of complexity for this summer's work. I am going to change the title to "webpack" and move the issue a little further down on the road map.

**Comment by Myles-Trevino** [comment]
Currently Lexos is very minimal on loaded resources and the main bottleneck for performance is backend processing, so webpack would not provide much benefit.
