### ISSUE TITLE
Embedded "In the Margins" links are Scalar-internal

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#487]
The embedded "In the Margins" texts has links with relative urls from within the Scalar site. In Lexos, when the user clicks a link, the http request is thus sent to `http://lexos.wheatoncollege.edu/ITM SLUG`. We need to programmatically add `http://scalar.usc.edu/works/lexos/` to the the slug achieved from the Scalar API. In the process, we should probably also add `target="_blank"`.

**Comment by cgnobrega** [comment]
we have left scalar in v4.0
