### ISSUE TITLE
Let's slow down a bit this year

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#488]
I personally think this project has gone a little out of hand.

The root directory contains 14 folders, and the `lexos.py` contains 2000 lines of code, and nearly no comment at all, and there is not lots of comment on the front end either.

maybe this year we can slow down on the development of the new features and make the code cleaner more readable and add more comment.

I also think it is necessary, now that our project is this big, we need have some review before people pushing code to `master` branch.

what do you guys think?

**Comment by scottkleinman** [comment]
Mark and I have had this conversation and are currently applying for grant funding for code refactoring (and conversion to Python 3). In any event, we must start code cleanup before we begin the next release. Thorough commenting and review prior to committing to `master` is a good idea.

**Comment by chantisnake** [comment]
Here is a great video introducing pull request, that is generally serves the purpose of reviewing code before it reaches `master`: https://www.youtube.com/watch?time_continue=249&v=d5wpJ5VimSU

It is a good practice to create a branch for whatever new feature that you are trying to implement, and then create the pull request when the feature is finished (you can use `rebase` to make sure your branch is up to date with the `master`)

This is more complicated than our current work flow, so I will leave you guys to decide whether to adopt this workflow.

**Comment by chantisnake** [comment]
We are currently doing this.
