### ISSUE TITLE
rewrite a windows installer and windows local app

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#490]
rewrite the windows installer using NSIS (so that people can click 'next').
rewrite the windows app using WPF WebView component instead of just popping up a browser window.

**Comment by chantisnake** [comment]
This change will happen in branch `decent-windows` after I nearly finished with the python3 migration

**Comment by chantisnake** [comment]
work has started, based on version py3 branch

**Comment by chantisnake** [comment]
Here is just a show off of the status of current work:

![lexosdemo](https://cloud.githubusercontent.com/assets/10100995/22128699/d43f41c2-de99-11e6-944e-6b13301cf389.gif)

Cool, isn't it?

the development is in https://github.com/chantisnake/LexosWindows
I can later transfer this repo to wheatonCS after I finished all the work

**Comment by scottkleinman** [comment]
Unfortunately, GitHub has no button to "like" this. It looks great! Well done!

**Comment by chantisnake** [comment]
sure it has! 

![capture](https://cloud.githubusercontent.com/assets/10100995/22128898/dd1a930e-de9a-11e6-9299-74a56021282c.PNG)

**Comment by scottkleinman** [comment]
It looks like the code in your repo needs to be compiled. Are you using [NSIS](http://nsis.sourceforge.net/Main_Page) to do this?

**Comment by chantisnake** [comment]
yes, I uses msbuild for the app and makensis (nsis compiler) for the installer, I will draft a build script today, because the installer is nearly finished.

**Comment by chantisnake** [comment]
I have nearly finished with the installer and the exe. The build script will be out tonight (London time).

**Comment by chantisnake** [comment]
the project has took off, therefore I will close this issue.
