### ISSUE TITLE
404 of /doMulticloud page

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#492]
the script on Multicloud page try to POST /doMulticloud, but such function is not defined in `lexos.py`

@scottkleinman you might know something about this bug?

**Comment by scottkleinman** [comment]
Yes, I was trying to fix a bug reported by a user but got interrupted before I finished. This might have been an accidental commit. I'll try to figure out how far back we need to revert over the weekend.

**Comment by chantisnake** [comment]
this is fine. I believe this is an easy fix, you can do it in seconds. I just leave this issue here, so that we both do not forget

**Comment by scottkleinman** [comment]
This should be fixed now. In addition to switching the form submission to Ajax, I have switched the construction of an array used by the d3 to the server, and it gets returned along with the main data set. I'm not really sure if this improves performance, so I left the former Javascript function in just in case we want to compare in the future. Sending more data in the ajax response presumably subjects it to the whims of internet speeds.

In any event, the `doMulticloud` route is now ins `lexos.py`, so I can close this issue.

**Comment by chantisnake** [comment]
Good job
