### ISSUE TITLE
fully migrate to ajax

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#494]
I don't think there is objection to this...

**Comment by scottkleinman** [comment]
I _think_ only TopWords is still not converted to Ajax.

**Comment by chantisnake** [comment]
topwords should be easy @weiqi

**Comment by Weiqi97** [comment]
#760 Changed topword to Ajax call. Once it is merged, I will close this issue.

**Comment by Weiqi97** [comment]
Done
