### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#495]
This is what we should really done before our project gets even bigger (because it will gets harder.)

The backend can be easily added with decorator, I didn't find a great way to great way to automatically identify error sent from the back end and render error template...

**Comment by scottkleinman** [comment]
The Ajax functions all have a built-in error message which could be tweaked to display an error passed from the back end. Assuming the error occurs when the page is rendered, I might have some code from another project that handles this. I'll look into it when I get a chance.

**Comment by chantisnake** [comment]
basically what I can do is to make all the function in `lexos.py` to do this:
```python
def lexos_page():
    try:
        do_important_stuff()
        return result_via_ajax
   except
        return '{"error_message": "error message", "error_type": "errorType"}'
```

**Comment by scottkleinman** [comment]
This is really easy to handle on the front end.

```javascript
if (response["error_type"]) {
  var message = response["error_type"] + "<br>" +  response["error_message"];
  $("#error-modal .modal-body").html(message);
  $("error-modal").modal();
}
else {
  /* Do something with the response... */
} 
```
And I'd probably call a function to show the error in the `if` clause to avoid some code duplication.

**Comment by chantisnake** [comment]
Then let's do this this year!

**Comment by chantisnake** [comment]
One thing to notice, we are not necessarily handling everything through ajax. How do you propose we handle all the render_templates? Render an error template or tweak it to let it work with ajax?

**Comment by scottkleinman** [comment]
One method is to use [message flashing](http://flask.pocoo.org/docs/0.12/patterns/flashing/). Another is [custom error pages](http://flask.pocoo.org/docs/0.12/patterns/errorpages/). We'll have to explore what works best.

**Comment by chantisnake** [comment]
backend is done for this, need more time for the ajax.

We need to discuss use ajax or use message flashing to implement this.

**Comment by scottkleinman** [comment]
We just need to convert one Ajax function, and then I can use that as a model to re-do the other options. I've thought about Flask message flashing, but at this stage let's stick to the Bootstrap modals for error messages since that is how they are implemented throughout most of the UI.

**Comment by chantisnake** [comment]
We will begin the javascript refactoring next semester. At that point we will change all the ajax function

**Comment by chantisnake** [comment]
I think this maybe are done?
