### ISSUE TITLE
Refactoring Javascript

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#496]
the front end is not getting the love it deserves, I think it is the time we systematically refactor and document the front end code.

Here is some of the standard I find:
- for documentation, there is JSDocs standard: http://usejsdoc.org/about-getting-started.html
- for code, there is JSStandard Style: http://standardjs.com/

**Comment by chantisnake** [comment]
What is your thought on that? @scottkleinman , since you are the main contributor on the front end.

**Comment by scottkleinman** [comment]
I will experiment with these on another, smaller project. In principle, I agree that we need to clean up the Javascript following much more standardised parameters.

**Comment by chantisnake** [comment]
Related to https://github.com/WheatonCS/Lexos/issues/705 https://github.com/WheatonCS/Lexos/issues/681https://github.com/WheatonCS/Lexos/issues/661

These issues describes this problem comprehensively. I am closing this.
