### ISSUE TITLE
using CI to check for...

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#497]
- basic build errors
- PEP 8 and front end coding style standards
- unremoved merge conflict

**Comment by chantisnake** [comment]
I still have a hard time deciding which CI to use. 

I am most familiar with [appveyor](https://www.appveyor.com/) but [travis](https://travis-ci.org/) is the one that supports Linux (also macOS)

 I guess if we want to support all three system we should use all of them.

**Comment by scottkleinman** [comment]
I haven't used CI before and am having trouble understanding how it fits into the workflow. Can you elaborate?

**Comment by chantisnake** [comment]
CI basically is just doing something (build, test, or anything you want) when ever there is a commit.

Therefore you don't really need to do anything besides the initial setup, it will automatically test with every new commit, and tell you whether there is error.

In this case, we let it test for PEP8 and JS standards (there are commandline utility to do that) and it will tell us if each commit (and pull request) go through with the test.

**Comment by chantisnake** [comment]
and after adding that we can see a little check when the CI test is successful, like this:
![capture](https://cloud.githubusercontent.com/assets/10100995/22158038/3ad0bbf8-df32-11e6-8666-ab5c52af03b6.PNG)

there is also status indication for pull requests:
![capture1](https://cloud.githubusercontent.com/assets/10100995/22158045/4e5b2ffa-df32-11e6-978a-a9f4006ea1bf.PNG)

**Comment by scottkleinman** [comment]
Sounds doable.

**Comment by chantisnake** [comment]
fixed in #538
