### ISSUE TITLE
Long-Term ToDo

### ISSUE THREAD

**Issue by bawjensen** [WheatonCS/Lexos#50]
I will move all long-term to do issues into this issue, to prevent clutter. Issues that stick around should be issues that we can fix and check off the list, those that can't/won't/we're putting on the back burner should be moved into this list.

Alternate dendrogram plotting (#4)
Scrubbing accents (#7)
Citations (#12)
Installation instructions (#23)
setup.py installer (#24)
Continuous Integration (#25)
Unit Tests (#26)
Info Pages (#51)
Formatted Files Input (#61)
Standardize file sub-selection for analyze/visualize (#69)
Separating HTML and Python variables (#79)
Scrubber.py (#111)

**Comment by scottkleinman** [comment]
Since issue #111 is still open and all the others closed, I think we can close this issue.

**Comment by bawjensen** [comment]
This was intended as a continual list of all things that are desired, but cannot be done right now. So it doesn't make quite sense to close this issue, as any future features that cannot be accomplished right away should be added to this list.

That is, unless there is a new, better place to keep track of such features. Then by all means replace this with that.

**Comment by bawjensen** [comment]
I just realized that this cannot function as I envisioned, seeing as only I can edit the original post. Possibly a replacement post, under Mark's name, should be created and maintained?

**Comment by scottkleinman** [comment]
Bryan, we've started using a Google doc as a road map. Let me know if you want access, and I'll send it to you.

**Comment by bawjensen** [comment]
No worries, I don't need access. I like the idea of a better platform as a roadmap.
