### ISSUE TITLE
Moving to HTTPS

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#500]
There is certainly a trend to HTTPS.

1. Google has blog posts indicate that they eventually alert the user when they are on an HTTP site: https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html

>In following releases, we will continue to extend HTTP warnings, for example, by labelling HTTP pages as “not secure” in Incognito mode, where users may have higher expectations of privacy. Eventually, we plan to label all HTTP pages as non-secure, and change the HTTP security indicator to the red triangle that we use for broken HTTPS.

2. firefox also announced their intention to remove HTTP from the web: https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/

3. and apple has already require all the app in the app store to use HTTPS instead of HTTP: http://www.techrepublic.com/article/wwdc-2016-apple-to-require-https-encryption-on-all-ios-apps-by-2017/

----
Here is some material on HTTPS:

- this is a code snippet to use SSL in flask: http://flask.pocoo.org/snippets/111/
- this is a plugin in flask that can easily establish SSL: https://github.com/kennethreitz/flask-sslify
- this is a google talking about HTTPS on their dev con: https://www.youtube.com/watch?v=e6DUrH56g14
- couple of suggestion to test ssl on localhost: http://stackoverflow.com/questions/4221874/how-do-i-allow-https-for-apache-on-localhost

**Comment by scottkleinman** [comment]
I thought we had some discussion of this in e-mail a few months back, but I can't recover the thread. If https can be served directly in Flask, that's much easier than doing it in Apache. But we should ask Caleb if he can do this in the setup of the new server before we start trying to do anything with Lexos, since setting it up with SSL should be par for the course these days.

**Comment by Myles-Trevino** [comment]
This is more of a server configuration problem than a problem with Lexos.
