### ISSUE TITLE
Handling changes in the number of leaves in dendrograms

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#503]
By default, the **Number of Leaves** field contains the number of active documents. However, if you de-activate a document and return to `/cluster`, the previous number is loaded from the session variable. Again, HTML 5 prevents your from submitting this invalid number, but you do have to manually reduce it. Likewise, if you increase the number of active documents, you get the number you used to generate a dendrogram previously. In this case, the number is valid, so you don't get a warning. For example, if you generate a dendrogram of 5 documents, the number of leaves will be 5. If you then add a document, and generate another dendrogram, it will have 5 leaves, unless you adjust it.

The best user experience might be if we did not cache the session variable and always used the number of active documents unless the user changes it. The problem with that is that a user returning to `/cluster` gets a display of the last dendrogram generated, which means that there may be a discrepancy between the number of leaves in the dendrogram they see and the value in the form. I want to think about how this should be handled, but comments are welcome.

**Comment by scottkleinman** [comment]
Some more thoughts about this one. The number of leaves is not displayed by the **Show Legends** option, but the Scrubbing and Cutting options are. I think this aspect of the UI needs to be re-thought. Potentially, all graphs should have a **Show Metadata** option, and a dialog would allow the user to select which metadata to include with the graph. Options set in the **Prepare** menu would be available in all tools, whilst options in the hierarchical clustering tool, for instance, would only be available when that tool is active. As this would be applied across the suite, I think it is left to a later stage of development, probably to after we transition the workspace from pickle to JSON.

**Comment by chantisnake** [comment]
Is this still relevant in the new dendrogram?

**Comment by scottkleinman** [comment]
I encountered it a couple of weeks ago, but I was using lexos, not lexos3, on the server. I'm not sure if there have been more recent updates that address the issue.

**Comment by mleblanc321** [comment]
i think this bug is still there;  (i encounter it when doing demo's, regularly getting "burned" ...)

**Comment by cgnobrega** [comment]
Number of leaves is no longer an option
