### ISSUE TITLE
Status of Lexos auto-installers

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#504]
We have some Lexos workshops coming up soon, so I thought it would be a good time to ascertain the status of our auto-installers. My understanding is that we offer two auto-installers, Windows 10 and OS X, which install both Python and Lexos 3.0. What is the current reliability of these installers?

In addition @chantisnake has developed a new Windows installer which uses the Python 3 branch of Lexos 3.0. I have a couple of questions about this installer:

1. Is it also limited to Windows 10?
2. Is it easy to make a version that uses the master branch (i.e. Python 2.7)?

This information will be useful for planning the workshop agendas.

**Comment by chantisnake** [comment]
I will need sometime to fix up the auto installer to make sure it works, it got messed up during [this commit](https://github.com/WheatonCS/Lexos/commit/b299c3dca497dd57d70eb3dac8d377a65d6f5e34).

Because our new [awesome installer](https://github.com/chantisnake/LexosWindows) doesn't depend on that file name, therefore I haven't fix the old installer.

For you question:
It only works on windows 10 (more specifically powershell 5, which come with Windows 10 but can be installed on windows 8, not sure about windows 7).
It automatically install the master branch.

**Comment by chantisnake** [comment]
Can you tell me about when the workshop happens? I need to determine when I fix those installers.

**Comment by scottkleinman** [comment]
I think the first one is 23 February.

**Comment by chantisnake** [comment]
I misunderstood your question about current installer.

The current installer has only been tested on Windows 10, it should work on windows 8. I don't know about windows 7, because I have never used windows 7...

The current installer can be easily tweaked to install the master, but I haven't tried it, so I cannot guarantee you anything.

**Comment by chantisnake** [comment]
Okay, I will give you three working installer by that time:
- the old command line installer
- the new installer works with python3 on 64 bits machine
- the new installer works with python2 on 64 bits machine

Do you need 32 bits installer as well?

**Comment by scottkleinman** [comment]
Thanks! I don't think we need a 32 bit installer at this stage.

**Comment by scottkleinman** [comment]
As a side question, should the auto-installers install in local mode by default? I'm on the fence on this one.

**Comment by chantisnake** [comment]
yes, but I haven't implement that yet.

**Comment by chantisnake** [comment]
the old installer is fixed. download it [here](https://github.com/WheatonCS/Lexos/releases/download/v3.0/lexos_installer.exe)

This installer targets the latest version of Anaconda and the master branch of the lexos.
This is just a simple powershell script, so the interface is quiet ugly. but it is usable.

there are couple of command line parameter:
- `noAnaconda`, use it in this way: `.\lexos_installer.exe -noAnaconda` this parameter will skip the installation of anaconda
- `y` or `noconfirm`, use it in this way: `.\lexos_installer.exe -noconfirm` this will make ignore all the error in the installer and just silently continue.

the update script still has some error, I will look into that

**Comment by chantisnake** [comment]
the new installer come with python3 can be found here: https://github.com/chantisnake/LexosWindows/releases/tag/v3.0.0.0

**Comment by chantisnake** [comment]
the legacy installer is out: https://github.com/chantisnake/LexosWindows/releases/download/v3.1.0.0.legacy/LexosInstaller_3.1.0.0_x64.exe

This uses master and anaconda2, probably compatible with the new 4.3.0 release of anaconda, but haven't tested.

**Comment by scottkleinman** [comment]
I gave this a shot and it worked--at least with the Anaconda install checked. [Side note: I only tested this on a Windows 10 machine.]

I didn't really appreciate from your demo that this is a Windows app. It's a little flickery, and, I think, given a choice, I'd use a traditional installation on my own machine. But for most users who are uncomfortable with installing and running Python themselves, this installer will be a real asset. Plus, you get the nice Lexos launch icon! Great job!

Can you write up the procedure for compiling the code into the `.exe` so that we're not reliant on you if we need to make changes in the future? No rush, but this should be done once you migrate a version to the WheatonCS account.

**Comment by chantisnake** [comment]
It is certainly on the roadmap together with detailed description of both the installer and the executable.

I don't quite understand your comment about "windows app", can you tell me more about that?

**Comment by scottkleinman** [comment]
If I search for Lexos on my desktop, Windows calls it a "Desktop app". When I launch it, I get a window, the top of which looks like this:

![capture](https://cloud.githubusercontent.com/assets/1125917/22608555/4130acc0-ea12-11e6-8b99-910c6b8530f6.JPG)

You'll notice two things:

1. It doesn't have the standard browser menu at the top and you can't do things like open up a new tab. If it is a standard browser, I'm not sure which one it is.
2. There is an arrow icon at the top left (and a column beneath it) that is not part of Lexos. Mousing over it reveals the title "go back to the previous page", although clicking it doesn't actually do anything.

So what I meant by "Windows app" was just that there are differences from what you see if you run Lexos from the command line and then go to localhost in Firefox or Chrome.

**Comment by chantisnake** [comment]
Yes, here is why I did this:

1. Open up a browser is much easier than writing a wrapper for the Lexos app, but from what I know, some people are uncomfortable working in a browser, therefore I made it more look like a native app.

2. That button does work, is just you haven't navigate to any page yet, if you go to another page, and then click the button it will go back.

**Comment by scottkleinman** [comment]
OK, that explains things. And it's good to know what can be changed. We can do some user experience testing over the summer to see whether users prefer the stripped down interface.

**Comment by chantisnake** [comment]
although there is still work on the new installer, but I think this issue should be closed.

**Comment by scottkleinman** [comment]
Actually, we shouldn't close this just yet, as I still have questions about the installers:

1. Does the new Windows installer work on Windows 8.1? Unfortunately, I am unable to test this, as I don't want to risk changes to the Anaconda installation on my machine. But it would be nice to be able to tell 99% of Windows users just to use the auto-installer.
2. Does the Mac installer work? I notice also that it is a `.tar.gz` file. One that is downloaded, will Mac users know what to do with it?

**Comment by chantisnake** [comment]
I think the discussion can move to installer repo.

**Comment by chantisnake** [comment]
probably outdated.
