### ISSUE TITLE
never deletets session when running in local mode

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#505]
I think when `IS_SERVER` confinguration equals false, we will do the following:
- move the `upload_folder` from temp to a data folder
  - on Mac, that is `$HOME/Library/Application Support/Lexos`
  - on Windows, that is `$HOME\AppData\Local\Lexos`
  - on Linux, that is `$HOME/.Lexos` (there is also `$HOME/.config/Lexos`, `/usr/lib/libraries/Lexos`  but I don't think this is the way to go, `.config` is for settings, and the `libraries` is used for documentations), it is a mess.
- do not randomly generate the session id, uses a fix session id. (we may want to discuss the security of the file name.)

**Comment by scottkleinman** [comment]
I can't reproduce this. For me, clicking reset does delete the session folder (and replaces it with a new (empty) session folder. If I stop the app and restart it, I get the same thing. Is reset not working for you?

**Comment by chantisnake** [comment]
No, this is an enhancement. I prepare to add the description a little later.

This basically try to keep user's session forever on local mode unless they click reset.

**Comment by scottkleinman** [comment]
OK. Glad it's not a bug.

**Comment by Myles-Trevino** [comment]
The session is already maintained between local server restarts.
