### ISSUE TITLE
DataTables table update issues in Manage

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#507]
When you apply a class to selected documents that are distributed amongst multiple table pages, only the currently displayed page is updated on the front end (the back end is updated successfully). In order to see the correct class label on another page, you have to refresh the browser. In order to deal with this situation, I've introduced a hack to detect whether row IDs not in the DOM are included in the list of labels to change; if they are, the window is reloaded automatically. It works, and it's not too obtrusive, but I'd really like to do it without the browser refresh. I'm hoping that some solution will be posted on the DataTables forum, but, in the meantime, the hack is good enough.

Another DataTables-related issue for the future is when a new row is create because you have merged two documents. For instance, if you select `Pride_and_Prejudice1` and `Pride_and_Prejudice2` to produce `merged_Pride_and_Prejudice`, the table should be alphabetically sorted automatically to list the new file first. I haven't found out exactly how to do this yet. In the meantime, having it at the end is not too annoying. However, if you are not on the last page of the table, you won't see the new row appear.

I'll try to return to these bugs from time to time to see if a solution emerges.

**Comment by cgnobrega** [comment]
see #960
