### ISSUE TITLE
new file structure proposal

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#508]
Our lexos.py has become 2000's lines long and consists of tones and tones function that can be grouped.

I suggest to rethink our lexos structure, there is the one I propose:
```
------ root
  +----- readme.md
  +----- lexos.py
  +----- test.py
  +----- config.cfg 
  +----- requirement.txt 
  +----- LICENSE 
  +----- .gitignore 
  +----- .gitattributes 
  +----- install/
  +----- lexos/
    +--- deprecated/
    +--- debug/
    +--- helpers/ 
    +--- managers/ 
    +--- models/
        +--- topword_models/
        +--- cut_models/
        +--- statistic_models/
        +--- and more...
    +--- interface/   
  +---- gui/
  +---- test/
    +--- test_suite/
    +--- unit_test/
```

----
in the new `interface` folder will contain folder like `file_manager_interface.py`  that will contain functions like `getTenRows` and `topword_interface.py` that will have function like `download_topwords`, `get_topword_page` and `display_topword` function.

also, because we are migrating to ajax, we can split some of the function, and stop using so many `if else` in our functions, that will make our code a lot cleaner

----
and in `lexos.py`, there only should be 
```python
import <all the interface>

install_secret_key()
app.debug = not constants.IS_SERVER  # open debugger when we are not on the server
app.jinja_env.filters['type'] = type
app.jinja_env.filters['str'] = str
app.jinja_env.filters['tuple'] = tuple
app.jinja_env.filters['len'] = len
app.jinja_env.filters['unicode'] = unicode
app.jinja_env.filters['time'] = time.time()
app.jinja_env.filters['natsort'] = general_functions.natsort

# app.config['PROFILE'] = True
# app.wsgi_app = ProfilerMiddleware(app.wsgi_app, restrictions = [300])

if __name__ == '__main__':
    app.run()
```

----

What do you guys think?

**Comment by scottkleinman** [comment]
Your basic point is correct. In terms of the solution, I want to take a serious look at [Flask Blueprints](http://flask.pocoo.org/docs/0.12/blueprints/). It's on the [roadmap for v3.6](https://github.com/WheatonCS/Lexos/blob/master/roadmap.md#v36-begin-major-refactoring).

For the point you make about Ajax, I agree. As part of the transition to Ajax, I just decided to leave tons of small routes for Ajax calls in `lexos.py`, but they can eventually be removed to other files to clean up the clutter.

The result of this refactoring should leave us fairly close to the idealised `lexos.py` that you describe.

**Comment by chantisnake** [comment]
I think we also need to merge the installer into the Lexos main repo. This is easier to maintain.

**Comment by mleblanc321** [comment]
very reasonable proposal;  i've read only once quickly;  i trust you guys, but i've also done this a number of times, so i'll try to stay in the loop with more study;

**Comment by chantisnake** [comment]
I have made the following changes:
- change the `src` folder to `lexos` folder for easier module creation
- add `setup.py` to make lexos a module on pypi
- add `gui` folder to for the local install lexos frontend (see the discussion in https://github.com/WheatonCS/Lexos/issues/517)
- add `freezer.py` to freeze lexos and gui
- I want to merge the `processor` and the `managers/utility.py` into models folder, this will enable us to keep each function in reasonable size.

**Comment by scottkleinman** [comment]
We're now using Flask Blueprints for modularisation, but I'm not sure whether the cleanup of the Ajax queries mentioned above have been addressed. Once that's done, we can close this issue.

**Comment by chantisnake** [comment]
This structure is too outdated
