### ISSUE TITLE
use command line parameter to control debugger

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#510]
I don't really see the point of having a debugger for now, all the error can display on the console. I don't really need to see it on the web page.

**Comment by scottkleinman** [comment]
Does issue #495 relate to this?

**Comment by chantisnake** [comment]
no, Lexos debugger simply display errors on the web page during development. It has nothing to do with error handling.

**Comment by chantisnake** [comment]
I just realize turning on and off flask debugger can be achieved via command line option:

```console 
python lexos.py --debug True
```

this can be easily done by google's brilliant new framework [fire](https://github.com/google/python-fire)
