### ISSUE TITLE
uses submodule to manage the libs

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#511]
in `Lexos/static/lib` there are lots of packages.

I personally think they are not properly managed, since we need to update it manually.

git provide a method to manage libraries: [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules):

> It often happens that while working on one project, you need to use another project from within it. Perhaps it’s a library that a third party developed or that you’re developing separately and using in multiple parent projects. A common issue arises in these scenarios: you want to be able to treat the two projects as separate yet still be able to use one from within the other.

see the full description here: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by scottkleinman** [comment]
The description of git submodules is a little unclear to me. There may not be sufficient need to add an extra layer of complexity to the static Javascript libraries. But, I think that, if we consider it, we should do so as part of the implementatin of Webassets; see issue #485.

**Comment by chantisnake** [comment]
yes, I noticed that issue, this is what makes me think of this.

Actually submodule isn't complicated at all. (It's just the documentation is complicated)

it is basically just clone the lib repo into the Lexos repo; git will keep track of it, but it will not be committed to GitHub. 

You can restore all of them using 
```
git clone https://github.com/WheatonCS/Lexos 
git submodule init
git submodule update
```
or just
```
git clone https://github.com/WheatonCS/Lexos --recursive
```

This is kind of like:
```
pip install -r requirement.txt
```

---
the advantage of having a submodule is that you can manage the version of the libs using git

for example, this issue #464

you can fix that by 
```bash
# go to lib dir
cd ./static/lib/d3
# add the submodule
git add submodule https://github.com/d3/d3 
# checkout the branch to tag
git checkout v3.5.5

# plain old add commit push
git add -A
git commit -m 'add d3 module v3.5.5'
git push
```
just like that.

If you want to upgrade the d3 module to v4.5.0 just
```bash
# go to lib dir
cd ./static/lib/d3
# update the code from master
git pull origin master
# checkout the branch to tag
git check out v4.5.0

# plain old add commit push
git add -A
git commit -m 'update d3 module to latest'
git push
```

**Comment by chantisnake** [comment]
if you don't like submodules, we can try [npm](https://www.npmjs.com/), a package manger for nodejs, but also works for java script.

You can use 'package.json' to specify both the dependency and versions.
https://docs.npmjs.com/getting-started/using-a-package.json#specifying-packages

**Comment by chantisnake** [comment]
using npm now
