### ISSUE TITLE
unit test for lexos

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#512]
Unit test is to test every functionality inside of a program all in once with specific test case (in our case the json response given by ajax).

Unit tests integrates nicely with CI system, once we have our test setup we can easily use CI to see if a commit or pull request break our test with out us doing anything.

the test result will show up on pull requests, commits and the badges:
see this issue: https://github.com/WheatonCS/Lexos/issues/497

---
here is some material on unit testing on flask:
- This is a tutorial for the old school flask default test: http://flask.pocoo.org/docs/0.12/testing/
- This is a documentation for a flask testing module specifically designed for `ajax` and `json` responses: https://pythonhosted.org/Flask-Testing/

**Comment by chantisnake** [comment]
I propose a new repo named `lexos_test` with the following file structure.

``` 
lexos_test
+--- files/                   (all the file that need to be tested currently our test suite)
+--- scripts/               (the scripts to generate test file)
+--- unit_test/            (all the unit test function)
+--- test.py                (the main file, that import all the file from 'unit_test/' and run all of them)
```

**Comment by chantisnake** [comment]
a counter argument to a new repo is that there is more to maintain, and all the submodule `Lexos` is really inefficient, and a pain to manage.

I suppose we can write script for every element in the workflow, but it is just not elegent.

Actually my main concern is about `checkout` and `clone`, because it has gotten really slow recently.
Although Microsoft is working on a new GVFS (git virtual file system) that significant reduce the time to run `git` command. https://github.com/Microsoft/GVFS
It is still in preview, let's hope they make progress with that and they make it available on Linux

**Comment by scottkleinman** [comment]
In principle, this seems like a good idea. But I'm a little confused about how we set up the test case(s). If that's complicated, it might just be better to try out new features manually on an ad hoc basis.

Additionally, I received an e-mail notification for this issue which proposed a new repo and then provided a counter-argument against that. I'm not sure if these were earlier drafts which have been revised, but they did raise flags for me about how the unit tests would be maintained.

But it sounds like, if we go ahead with this idea, it should be set up before we set up CI.

**Comment by chantisnake** [comment]
yes, I just realize that new repo is not a great idea. It is simply to much to manage.

**Comment by chantisnake** [comment]
well, this CI can do other things besides unit test. (like I said, CI is simply running some code after every commit and pull request)

Therefore CI can check your code style and comment style and whatever you want to check.

And also setting up unit test requires lots of work (I would argue it is worth it), therefore I want to set up the CI before hand just to check for simple code style. After we finished with the unit test, we can add the unit test to CI.

**Comment by scottkleinman** [comment]
OK. That logic makes sense. It does seem like unit-testing for Lexos might be a lot of work. So CI first. I'm just thinking of where to put all this on the roadmap.

**Comment by chantisnake** [comment]
implemented!
