### ISSUE TITLE
adopting Semantic Versioning 2.0.0

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#513]
Semantic Versioning is a version guide line that is very commonly used:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

get more information here: http://semver.org/

---
I suggest we use the fommat: MAJOR.MINOR.PATCH.AnacondaVersion

for example, current version will be `3.1.0.430`

**Comment by scottkleinman** [comment]
We're on track to do this. The main thing is to try to keep it consistent. I'll try to adjust the roadmap, and we'll see how it goes. For now, I think we're at `3.1.0`, or `3.1` for short. Lexos isn't dependent on Anaconda, so the additional label isn't necessary, except when the auto-installer downloads it. We can add the label for that use case. In the mean time, I'll label this issue open as a reference before eventually moving it into the developer docs.

**Comment by chantisnake** [comment]
you make a good point, the last one should only be on the installer release, not the Lexos release.

**Comment by jacksonjreed** [comment]
@mleblanc321 perhaps consider this in labelling the new version and then close
