### ISSUE TITLE
make the windows app wrapper cross patfrom

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#517]
Building off #490 

Currently the app is developed using WPF. In order to make the app cross platform I am planning to migrate it into Xamrain or mono, whatever works.

The installer obviously cannot be cross platform, but Linux and Mac packaging probably is easier than NSIS. (everything is easier than NSIS.)

**Comment by scottkleinman** [comment]
[PyInstaller](http://www.pyinstaller.org/) might also be worth considering--a purely Python solution.

**Comment by chantisnake** [comment]
@scottkleinman, as far as I know PyInstaller only create an executable for python script. 

It creates no gui and no installer. Not to mention it is currently broken under python 3.6 (latest python and anaconda release)

I am thinking of writing gui with python, but all the gui library seems kind of lag behind, I cannot find a python frame work that handles threading and hidpi as well as C# and WPF

**Comment by scottkleinman** [comment]
That's too bad. From a Python point of view, I think it is the project that is most up-to-date. Oh well.

**Comment by chantisnake** [comment]
For now I decided to try pyQt and asyncio to create cross platform GUI with pure python.

Let's just see how that works.
