### ISSUE TITLE
Uses Gitter for Question and Other Minor Communication

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#518]
Currently we uses issues for questions and minor issues. This is somewhat a waste of the issues. 
Especially at the start of the project, when everybody has lots of questions.

I think we can use [Gitter](gitter.im/) as the IM for communication for these minor things.

I recommended gitter for the following reason:
- No sign up required, you can directly access it via GitHub account
- You can create public chat, where it is nice to do customer service.
- It can push CI build result, therefore you can see how your branch is doing without going to the CI web page.
- Support GitHub flavored markdown.
- Truly cross platform, has app for Linux, Mac, Windows, Android, iOS, Windows Universal Platform, and web.
- Fancy Badges! Everybody loves Badges! ![capture](https://cloud.githubusercontent.com/assets/10100995/23264896/d1c0245a-f9da-11e6-955d-a48d2d6d7617.PNG) (capture from [Nlog](https://github.com/NLog/NLog))
- Most open source project uses them, to list a couple:
  - [Nlog](https://github.com/NLog/NLog)
  - [NeoVim](https://github.com/neovim/neovim)
  - [materialize](https://github.com/Dogfalo/materialize)
  - see more [here](https://gitter.im/home/explore)

**Comment by scottkleinman** [comment]
We _do_ actually have an underused Slack channel ([https://lexomics.slack.com](https://lexomics.slack.com)). Of course, unlike Slack, Gitter's features are prefaced with word like "unlimited", and Gitter chats accept Markdown...

**Comment by chantisnake** [comment]
Yes, Slack is also my first thought.

But I tested both slack and gitter on some of my other projects, I decided that gitter is more easy to setup, easy to use and contains a lot more integration feature than slack.

**Comment by scottkleinman** [comment]
That's interesting. It's quite a feat to develop something that's easier to set up than Slack. I'm also using [Ryver](https://ryver.com/) on other projects, but I don't think its advantages are appropriate to this kind of project. Once we get through this month's workshops, we can consider switching to Gitter.

**Comment by chantisnake** [comment]
The major advantage of gitter is that it is developed for github, therefore it is basically effortless to integrate.

One of the disadvantage of gitter is that it doesn't have a as good bot framework as slack. I still have a little problem for displaying build status of appveyor.

I will try to figure something out.

**Comment by scottkleinman** [comment]
Just FYI, our current Slack account is already integrated with GitHub. I might need to send you an invite to take a look.

**Comment by chantisnake** [comment]
It seems like we are doing well with slack, therefore forget gitter
