### ISSUE TITLE
Chinese character tokenisation doesn't work in visualisation tools

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#519]
Based on the _Dream of the Red Chamber_ files in `TestSuite`. Tokenising the documents by character 1-grams works in Tokenizer, and the correct characters appear in TopWords. But the untokenised text appears in Word Cloud, BubbleViz, and Multicloud (it works in Rolling Windows). I'm guessing we've got an incorrect function call somewhere (probably created in the Ajax conversion&mdash;my bad).

**Comment by scottkleinman** [comment]
Following up on this, the problem doesn't seem to be Ajax after all. It looks like we never hooked up the Advanced options. From what I can tell, the problem is in `lexos_file.py`, [line 496](https://github.com/WheatonCS/Lexos/blob/master/managers/lexos_file.py#L496), which grabs the contents of the file and calls `split()`. That's not going to cut it (so to speak). We need to run the text through a tokenising function. I'm not sure how we missed this...

**Comment by chantisnake** [comment]
LOL, Probably that is the only place to use the word count. Other functionality grabs word (token) count from the DTM.

I think this `getWordCounts` method of `lexos_file` makes sense, nevertheless it is called "get **word** count", not "get **token** count".

---
I am not an expert in visualize tools, I think you can use DTM instead of this `getWordCounts` method.

**Comment by scottkleinman** [comment]
Yes, that's exactly what I did. WordCloud is fixed (but not yet pushed to GitHub). I'm working on the others. Using the DTM is so much cleaner. But all this code was written before we adopted `CountVectorizer()`.

**Comment by chantisnake** [comment]
I think we need to clean these old functions that uses "non-lexos-standard" data structure this year.

(And we need to discuss what ` "lexos-standard" data structure ` is...)

**Comment by scottkleinman** [comment]
Yes, that will make development (and fixing bugs) _much_ easier.

**Comment by scottkleinman** [comment]
OK, I have finished this fix.

There is a small problem remaining in BubbleViz. If the user selects a maximum of 20 terms, the 20 most frequent terms are displayed. But if term 21 has the same frequency as term 20, either one may be cut off, depending on the spellings of the terms. This is because the terms are sorted by counts, then terms in a pandas dataframe using the pandas sorting algorithm, rather than the natsort algorithm. Most of the time, this won't make a difference, but to absolutely guarantee the expected results, we need to implement natsort on the dataframe. This is not trivial. I note the nature of the problem in BubbleViz here, but it may be something we need to implement for other tools. So I'll open a new issue for that and refer it to the description here.

However, the original bug that prompted this issue is fixed, so I'm closing the issue.
