### ISSUE TITLE
Discussion About GPLv3 license

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#524]
## Objective
There is a great lib https://github.com/cligs/pyzeta we are investigating, but this lib uses GPLv3, which means we need to change our license to GPLv3 (or later) to use that library.

### GPL Is an Virus And It Is Evil

There are many article discussing this topic.

https://www.google.co.uk/#q=is+gpl+evil&*

Here is some point that raises in those article:
- GPL is viral and parasitic by design.
- Industrial company rarely release their code under GPL, because all the derivative cannot be close sourced.
- GPL is non-essential any more. If people want the code to be closed sourced, they can nearly always find another library with similar functionality that does not uses GPL. Therefore GPL is not fooling anyone now, it just forbid your code from being used.
- GPL damages the open-source environment; because of the previous reasons, software developed by industries takes detour because they cannot use GPL code (to be honest, huge corporation usually release the best open source software, like atom, vscode, android, firefox, webkit, clang etc).
- Open source cannot necessarily protect the user: there used to be [back door in C compiler](https://www.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf); and android is probably the easiest to be hacked, among all the mobile OS.
- GPL not only prevents people from publishing  closed source software, but also prevents people to use any other license (This one is actually from me...)

### GPL Will Bring Us More Open Source Software.

GNU's ideology is based on the following axiom:
> Knowing the software is a fundamental right for the software user.

There is famous quote by Richard Stallman:
> Keep control of your computing, so it doesn't control you!

You can find all the article related to philosophy:
https://www.gnu.org/philosophy/philosophy.html

There is one that I think is best to summarize the accomplishment of GPL and why to use GPL:
https://www.gnu.org/philosophy/pragmatic.html

## So How Is GPL Doing?

Hum, it is not that good, because basically they cannot be used in industrial software.
There is practically no software released by any corporation that GPL.

But, GPL and LGPL is quite popular for academic software (LGPL allows you to use other license when you use LGPL code as a lib):
- The package `Gensim` that we are using uses LGPL.
- The famous proof assistant `Coq` uses LGPL license.
- The most famous emacs proof assistant framework [`ProofGeneral`](https://proofgeneral.github.io/) is release under GPL
- Both two famous academic markdown module uses GPL: [scholarlymarkdown](https://github.com/timtylin/scholdoc), and [academicmarkdown](https://github.com/smathot/academicmarkdown).

## What Happens When We Adopts GPL

Practically speaking... Nothing.

- When lib uses GPL, program needs to use GPL. But, lexos is not a library (yet). 
- Modified work needs to uses GPL. But we don't have any derived work as far as I know.
- Data sends in the software is not bonded by software license. (This means people's text is not affected by Lexos license)
- API usage is not bonded software license. (This means if people uses Lexos api to build app, they can use whatever license for their app.)

# TIME TO VOTE.

**Comment by chantisnake** [comment]
My personal repo are typically licensed under GPLv3, and all the people I know (typically my friends don't really care about industrial software) uses GPL too:
[Loli](https://github.com/LoLi-Lang/LoLi) is a lisp dialect. It uses GPLv3.
[Lice](https://github.com/ice1000/lice) is another lisp dialect that runs on JVM. It is also licensed under GPLv3.
[category theroy](https://github.com/MarisaKirisame/Category_Theory) and [CoqUtil](https://github.com/MarisaKirisame/CoqUtil) are two coq libraries, that is licensed under LGPLv3
[first order logic prover](https://github.com/MarisaKirisame/first_order_logic_prover) is a theorem proofer library implemented in C++. This is licensed under GPL.

Although I am kind of reluctant to turn such a big project like lexos into GPL, because there have been so many people working on this; I would vote to change our license to GPL if we really need pyzeta.
for the following reason:
- Lexos is made for learning, nobody is going to build industrial software out of this.
- Lexos is not only for the English student to experience text mining, but it is also an example for entry level programmer to build easy to use web app and basic machine learning app. Therefore, it is important to make sure that entry level developer can access our code and our derivative app's code.

**Comment by scottkleinman** [comment]
I'm not really a fan of GPL; it's incredibly complicated compared to MIT. @chantisnake's logic (for and against) is good.

But I'm not convinced that we really need `pyzeta` integrated into Lexos. `pyzeta` is more of an app than a library, and it comes with its own dependencies (`treetagger` and `pygal`). Burrows'/Craig's Zeta is underlying measure of distinctiveness or keyness&mdash;similar in use to what we do in Topwords. Zeta may be a better measure of distinctiveness, but I'm not sure that's a reason to integrate the entire `pyzeta` script with its scrubbing and visualisation functions. These functions actually do have some merits that would be worth looking at separately. By allowing part of speech tagging (and thus filtering), `pyzeta` does provide a scrubbing function that we don't. Also, it outputs both the entire matrix of Zeta scores _and_ visualisations, which may provide a more useful and easier to interpret tool than the tables based output of Topwords. It would certainly be worth developing these functions for the whole of Lexos and not limiting them to an integrated `pyzeta` feature.

I think a better approach would be to _host_ an installation of `pyzeta` on the Lexomics server with a light wrapper to walk Lexos data into `pyzeta`. For users with local installations, we could provide instructions for (optionally) setting up the two tools to work together. This would avoid both extra dependencies and the issue of changing the licence.

**Comment by chantisnake** [comment]
I have to go with Scott on this one. Although I haven't read the source code of pyzeta, I am really not sure integrating pyzeta is that urgent a task.

**Comment by chantisnake** [comment]
I think there is no objection that we do not need to switch to GPLv3 for now.

I will close this issue. Feel free to reopen when we need to rediscuss this issue.
