### ISSUE TITLE
Stop Words/Keep Words is slow/hangs with long lists

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#525]
When scrubbing large amounts of text with long stop word/keep word lists, Lexos takes a long time or even hangs (with no error in the Python console). This can be tested using the long positive and negative sentiment words lists [here](http://www.unc.edu/~ncaren/haphazard/positive.txt
) and [here](http://www.unc.edu/~ncaren/haphazard/negative.txt). It works with _Pride and Prejudice_ but not with all four novels in the `LargeFiles` folder in the test suite.

This is something of an edge case since most of the time stop word/keep word lists will be shorter (the negative list above is almost 4000 words). But being able to strip/keep long words like this allows users to perform a kind of simple sentiment analysis, which would be pretty nifty. So it might be worth taking a look to see if anything can be optimised. It's possible that this could be done in conjunction with issue #298.

**Comment by cgnobrega** [comment]
This does not appear to be an issue in v4.0. I tested with the LargeFiles docs, and the mentioned stop/keep lists, as well as other scrub methods. The slowness is to be expected with large files but it never hung.
