### ISSUE TITLE
another good tool

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#528]
https://pypi.python.org/pypi/flask-apidoc/

this add support flask support for [apiDoc](http://apidocjs.com/)

we can use this to generate some of our docs, makes the documentation easier

**Comment by scottkleinman** [comment]
I've tried out quite a few documentation generators and generally found them more trouble than they're worth. Some of them (and I think apiDoc may be one) are really designed for APIs consisting primarily of HTTP requests. Maybe I'm being a little too sceptical, but I've wasted a lot of the last week trying to get various documentation generators to produce something usable. So maybe a small test would be worth it before committing.

**Comment by chantisnake** [comment]
I haven't tried this, just came across this tool and thought this maybe helpful.

never the less, I believe this can, at least, be a good guide for our documentation on the APIs

**Comment by scottkleinman** [comment]
You mentioned some other good models in issue #496. It's a great idea to use these for code-internal documentation. And that makes writing straightforward Markdown/HTML guides a lot easier.

**Comment by akuisara** [comment]
Not sure if you have tried Swagger, but I heard a lot of companies using it.

**Comment by scottkleinman** [comment]
Swagger is fabulous, but it's the another one of these documentation systems meant primarily for APIs. I've tried, but I haven't been able to use it successfully for a different kind application.

**Comment by chantisnake** [comment]
I just did a quick bing on swagger. 

There are also swagger support for both pycharm and flask.
https://github.com/gangverk/flask-swagger
https://github.com/zalando/intellij-swagger

**Comment by akuisara** [comment]
@chantisnake Pretty good, thanks! :) Hope everything is well with you and the lexos team!

**Comment by Myles-Trevino** [comment]
On-page documentation has been redone in 4.0.
