### ISSUE TITLE
move to a modern frontend framework

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#529]
maybe react with JavaScript or typescript? 

Just something to think about, probably not in the near future.

**Comment by chantisnake** [comment]
Also, I have been given to understand that react is the only “truly cross platform” framework so far.

I thought it will make our GUI runs more smoothly on desktop platform.

That maybe will also enables us to dev cross platform mobile app for people want to do light computing on their phone (I am not sure this is useful, it is just somewhat exciting to think about).

**Comment by scottkleinman** [comment]
I've thought about this from time to time, and I would probably do it if we were starting from scratch. But I've taken a look at these frameworks, and their learning curves are not insignificant. Adapting the entire UI might be quite a task. It would probably be best taken on if and when we get a new round of funding.

That said, we might look at [Vue.js](http://vuejs.org/), which is supposed to be "incrementally adoptable"...

**Comment by chantisnake** [comment]
I think there are more and more conflict has arises  from the advancement of Lexos and the inexperienced developers. 
Given that most of the students are new students.

I think this is a topic really worth discussing.

**Comment by Myles-Trevino** [comment]
We decided to rewrite the frontend in plain JS and jQuery as it is clean and effective when used with modern standards and is simpler for developers without framework knowledge to start contributing.
