### ISSUE TITLE
No default tokenisation options in session

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#531]
The title is my theory about what is happening, but I haven't investigated. Here's the problem. If you upload documents and then go to Word Cloud or Bubbleviz, you get `KeyError: 'analyoption'`. If you first go to Tokenize and generate the token table, then Word Cloud and Bubbleviz will work. So it looks like we need to check whether there are default settings in `constants.py` or whether our templates can supply the defaults.

I'm not sure why we didn't catch this sooner, as most of the time we don't run Tokenizer. My only theory is that tools like Clustering also submit tokenisation settings from the Advanced Options configs.

This bug does not affect v3.0, so we should be able to trace the bit of code that went missing.

**Comment by chantisnake** [comment]
1. this is why we need unit test.

2. can you tell me precisely in which file and what line did this error occur? I will take a look. (or it is in javascript?)
I am thinking this is that our program calls `session[''analyoption'']` at some point

**Comment by scottkleinman** [comment]
The error comes in [line 574 of `lexos.py`](https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L574) (Word Cloud). At a guess, I would say that it is also triggered by [line 674](https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L674) (Multiloud) and [line 779](https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L779) (BubbleViz). It appears that we need these lines to be preceded by

```python
if 'analyoption' not in session:
    session['analyoption'] = constants.DEFAULT_ANALYZE_OPTIONS
```
This fixes the problem, and I will push the fix shortly.

**Comment by chantisnake** [comment]
Isn't this a little weird? we use `analyoption` in visualize, but they cannot set `analyoption` in visualize.
All the other tools can set `analyoption` (like tokenize, dendrogram). 

Do you think we need to add `analyze template` to visualize section?

**Comment by scottkleinman** [comment]
The basic issue you point out makes sense, but it is too early here and I have had too little coffee to give a confident answer at this time. I'm going to open that as a new issue in a few minutes, as it is a UX question that is essentially different from this bug.
