### ISSUE TITLE
Beta function setting is not saved to the session

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#532]
Selecting and saving Beta functions has no effect (hence no access to the web scraper). This does not affect v3.0, so it should be possible to trace the missing code.

**Comment by scottkleinman** [comment]
Well, this one has me stumped. Checking the "Use Beta functions" box calls `updatesettings()`, which caches the Boolean `True` to the session [here](https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L1992). (Printing the session variable confirms that the caching function works.) The ajax request that calls the function then returns successful and reloads the page. But when the page is reloaded, the session variable is `False`. According the Python console, [`session_manager.fix()`](https://github.com/WheatonCS/Lexos/blob/master/managers/session_manager.py#L82) is being called when the page is reloaded, but I can't see anything there that would reset the session variable.

**Comment by chantisnake** [comment]
I will take a look at it after tomorrow.

(Please remind me. I might suffer from a memory lost when taking Econmetrics exam)

**Comment by scottkleinman** [comment]
I have fixed this bug. For some reason, [`session_manager.cacheGeneralSettings()`](https://github.com/WheatonCS/Lexos/blob/master/managers/session_manager.py#L416) required `session.modified = True`. I'm still not clear on the logic of when we need to tell Flask explicitly when the session is modified, but the fix seems to work.
