### ISSUE TITLE
provide pre-built stopwords list

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#535]
while working with a client, she wanted a pre-established stopword list;  we went out and found one, but we might consider offering an option to upload a list we like and could offer to users?

**Comment by scottkleinman** [comment]
Using pre-built stoplists is a potential form of black-boxification, so we'd want to make a point of that in ITM. Generally, Googling stoplists for modern languages will get you a starting point, but there is also a set of [stoplists for ancient languages compiled by the Classical Language Toolkit (CLTK) project](https://github.com/cltk/cltk/tree/master/cltk/stop). At the very least, we could link to these in ITM, even if we did not provide a menu option like our special character rule sets.

**Comment by jacksonjreed** [comment]
closing this one, move discussion to duplicate #856
