### ISSUE TITLE
statistics breaks on microsft edge browser

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#539]
When you clicks on submit on statistics page, somehow it submits the form twice, first time with data, the next time without data. 

This is not a high priority bug, but this is a constant reminder that we do need to make our javascripts better

**Comment by scottkleinman** [comment]
We don't officially support IE/Edge, but this is a weird error. It looks Statistics is one of the pages that does not yet submit by Ajax. So it's worth checking what happens in the Python console. If I have time, I'll take a look.

**Comment by scottkleinman** [comment]
[This line](https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L337) is returning something that is causing the error in Edge (it's fine in Firefox and Chrome). At this point, I'm not sure why.

**Comment by chantisnake** [comment]
Are you sure? I have tested this multiple times, I am pretty sure the backend will not cause the webpage to submit the form twice.

I still thinks this might be a javascript problem, which makes more sense, because Edge (Chakra), and other browser interprets javascripts differently, but they all use the exact and same backend.

**Comment by scottkleinman** [comment]
There is definitely no Ajax request; it's a normal Flask submission. If I comment out the line mentioned above and don't pass the variables it generates to the template. I don't get an error. When I run the code as is, I get a socket error processing the POST request. I don't see how there is any opportunity for Javascript to run. But I'll take a closer look.

**Comment by chantisnake** [comment]
interesting, in my case I did not get a backend error, but only see that the form get submitted twice, because the second time don't have any data, therefore causing a bad request to raise to frontend

**Comment by scottkleinman** [comment]
I commented out some of the validation Javascript and tried running it, but Edge has cached the uncommented version and refuses to let me clear the cache. So it's impossible for me to check. But I think I know why you might be getting two submissions. The form is submitted by Javascript and the submit button is a submit type. I'll check if changing that makes any difference.

**Comment by chantisnake** [comment]
I also have the same feeling. Unfortunately I don't know much about front end. 

What would lexos do without you.

**Comment by scottkleinman** [comment]
I finally managed to defeat Edge's cache, but it appears that that was not the problem. Still checking...

**Comment by scottkleinman** [comment]
OK, that was a wild goose chase. Apparently, `filemanager.getMatrixOptions()` needed to be updated to accept `request.json`. But now I get an error at [line 248](https://github.com/WheatonCS/Lexos/blob/master/managers/utility.py#L248
):

```python
    i = 0
    for lFile in filemanager.files.values():
        if lFile.active:
            if request.form["file_" + str(lFile.id)] == lFile.label:
                Files[i].label = lFile.label
            else:
                newLabel = request.form["file_" + str(lFile.id)]
                Files[i].label = newLabel
    i += 1
```

It doesn't seem to get past `id` 0. Only one file seems to be active at this point, probably because of the disabling at [line 228](https://github.com/WheatonCS/Lexos/blob/master/managers/utility.py#L228). But I'm not sure what exactly is happening in that line.

**Comment by chantisnake** [comment]
I would personally recommend that you work in `PEP8` or `huge_refactor` branch.

That way we can avoid some nasty merge...

I am currently busy learning Haskell. I believe I will be able to be back into lexos in less than a week.

Best,
Cheng

**Comment by Myles-Trevino** [comment]
The statistics frontend has been redone in 4.0, making this obsolete.
