### ISSUE TITLE
Mac installation instructions refer to Windows

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#540]
Mac installation instructions for Anaconda contain the instructions:

> Note: The installation location is not important; however, make sure that you leave the option to Update the PATH variable checked. This will ensure that **Windows** knows that you want to use the Anaconda distribution of Python when you launch Lexos. This is especially important if you already have a different version of Python installed.

I'm not sure if the instruction about paths applies to the Mac version, so I don't want to fix it without checking with somebody.

**Comment by chantisnake** [comment]
I am pretty sure these instruction will be deprecated pretty soon. 

I am looking into the method to pack lexos into a normal app. that way, we will no longer dependents on Anaconda.

**Comment by scottkleinman** [comment]
I have fixed the text in the Wiki.
