### ISSUE TITLE
Expand dendrogram output

### ISSUE THREAD

**Issue by tarmstro** [WheatonCS/Lexos#56]
I'd like to expand on the text/descriptive output of the dendrogram to include [cluster performance evaluations](http://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation). Dendrogram to start, but then potentially other methods. This is in addition to the _legend_ output include in the figure. We may want to rethink where and in what format this meta information is shared.

**Comment by scottkleinman** [comment]
Much of this discussion has been implemented. Tom's original link to cluster performance evaluations has been transferred to the Lexos road map document. So I think we can close this issue.
