### ISSUE TITLE
different topology for GenesisAB on v3.1.x  vs.  v3.0 (public server)

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#586]
dang;  the README directions for reproducing the GenAB experiment (in testSuite/experiments/AngloSaxon), when followed, produce a different topology than on the (public) v3.0 server;  (segments 2,3,4) stay together, which is GenB, so that's good, but other clades are (slightly) different (e.g., segment 5 moving to another clade).

hmm, what changed with v3.1 that might cause this?

**Comment by scottkleinman** [comment]
There is also a discrepancy in the DAZ experiment. But the difference is between the Test Suite PDF and v3.0. So whatever happened took place before the v3.0 release.

**Comment by scottkleinman** [comment]
Make sure that you click the strip tags check box I got the same topologies for the DAZ experiment when I did that.

**Comment by mleblanc321** [comment]
3.1 does not work when we Remove Tag and all its contents for <teiheader> tag;

here is text left dangling in the initial segment;  hmm, teiheader nests other tags within it, but if we set Remove Tag and all its contents, it is (somehow) not removing the "contents"

-------- top of segment one(1) of GenAB 1500 word cuts ---------
genab genab january kb citations dictionary of old english st george st rm university of toronto toronto ontario ms h canada a we ask that you not copy andor redistribute the corpus without the written consent of the dictionary of old english  the individual scholar must take responsibility for clearing copyright with the editors and publishers of the editions used in hisher own citations of the material   
  genesis krapp     the junius manuscript  aspr  new york    
   
cited by line no following ed   
     
   january  
  doe  staff   
updated the bibliographic information from the healeyvenezky list of texts

**Comment by scottkleinman** [comment]
Following the same procedure in 3.0 seems to delete everything. Is this likely to be the cause of the dendrogram topology problem? If so, we can close this and open another issue for Scrubber.

**Comment by mleblanc321** [comment]
ok, will make new scrubber issue (with latest knowledge based on some more testing)
