### ISSUE TITLE
Setting scrubbing 'Remove Element and All Its Contents' doesn't work

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#590]
testing with GenAB.sgml

trying to remove the entire
<teiheader> .... </teiheader> tags and *all* its contents is not working; at the point of scrub.py, the `session[xmlhandlingoptions][**teiheader**] ["action"]`
seems to be (always) set to "remove-tag"
(not the 'remove-element' option that i set in scrub options) ??

**Comment by scottkleinman** [comment]
Confirmed that `xmlhandlingoptions` are not being saved to the session. I'll look into why this is.

**Comment by mleblanc321** [comment]
ok, thanks;   ari found this bug while testing GenAB (phew);  hope it is not too bad ... (i'd like to learn)

**Comment by scottkleinman** [comment]
The short answer is that, after modifying the session, we needed to update the session with `session_manager.session.modified = True`. This is in the the [Flask documentation](http://flask.pocoo.org/docs/0.12/api/#sessions), but it is very understated. The guilty function was `utility.xml_handling_options()`.

There are a number of UI bugs which I need to fix on this, so it will take a couple of days to push a change. I'll close this issue then.

**Comment by mleblanc321** [comment]
session_manager.session.modified
ugh;  brilliant scott!  so glad;  dang, i tried to find that ... good job;

**Comment by scottkleinman** [comment]
I've encountered it in other projects, so I had a head start.

I've now pushed a fix in the `bugfix/taghandling` branch. This is for v.3.2 only, but it should possible to patch earlier versions easily. Please test.

**Comment by scottkleinman** [comment]
The fix has been merged into v3.1.1 and v3.2.
