### ISSUE TITLE
Error in calculation in a_word_line from rw_analyzer.py 

### ISSUE THREAD

**Issue by arialfie759** [WheatonCS/Lexos#591]
**File Used:** `rw_analyzer.py`
**Function Used:** `a_word_line(split_list, keyword, window_size)`
## Error Message: 
None (Logic Error)

## Bug: 
The initial window value in the returned list is calculated differently than the subsequent windows. It takes the number of keywords found and divides it by the number of words in the line, whereas the other lines are calculated by dividing the number of keywords found by the given window size (like the rest of the functions do). 

## Found: 
During unit testing, was able to do unit testing to all of the other functions in the file except this one.

## To reproduce: 
Conduct a small unit test on this function using the same line multiple times (3 at least). This can even be done over Lexos. It will be seen that the first rolling window number will be different than the others following.

## Function:
```python
window_start = 0
    window_end = window_start + window_size

    # Rolling count, to be divided for average
    count = 0

    window_word_length = 0  # window length (in # of words)

    lines = []

    # Split the lines into words for comparison and counting
    for i in range(len(split_list)):
        lines.append(split_list[i].split())

    # Count the initial window
    for i in range(window_start, window_end):
        window_word_length += len(lines[i])
        for word in lines[i]:
            if word == keyword:
                count += 1

    # Create list with initial value
    averages = [float(count) / window_word_length]

    while window_end < len(lines):
        # Adds one to count if a new match enters the window
        for word in lines[window_end]:
            if word == keyword:
                count += 1
        # Subtracts one from count if a match moves out of the window
        for word in lines[window_start]:
            if word == keyword:
                count -= 1

        # Adjust window size
        window_word_length += len(lines[window_end])
        window_word_length -= len(lines[window_start])

        # Compute average for window
        averages.append(float(count) / window_size)

        # Increment window indices
        window_end += 1
        window_start += 1

    return averages
```

**Comment by chantisnake** [comment]
fixed with #608
