### ISSUE TITLE
Random "could not select document" errors, occasionally causing 500 server error

### ISSUE THREAD

**Issue by EmmaGrace** [WheatonCS/Lexos#596]
500 server error was able to be reproduced on win-10 in firefox by showing all of 62 default scrubbed, 1000 word documents, clicking one to trigger the "can't select doc" pop-up, repeating selection-error process several times with other docs, then attempting to make a hierarchical clustering. This behavior was consistent on both the live lexos server and lexos3, but not local host.

On win-7 in firefox, the "could not select doc" error was reproducible using the same documents and methods, but attempting a hierarchical clustering resulted in a "must have two docs to make a dendrogram" pop-up instead. This behavior held on both live lexos and lexos3 as well.

The documents that were being processed at the time of the error are attached.
[files.zip](https://github.com/WheatonCS/Lexos/files/1195592/files.zip)

**Comment by chantisnake** [comment]
Can anyone reproduce this sometime?

**Comment by Myles-Trevino** [comment]
Document selection has been redone in 4.0, making this obsolete.
