### ISSUE TITLE
Misc tool tip problems

### ISSUE THREAD

**Issue by EmmaGrace** [WheatonCS/Lexos#611]
For "Statistics > Assign Temporary Labels", the tool tip icon does not show the tool tip.

In "Kmeans > K-Means Options > Method of Visualization", the tool tip disappears before the user can click on the links.

In "Kmeans > Culling Options", the drop down arrow does not turn.

In "Similarity > Select Comparison Document", the text formatting is inconsistent and the text box not correctly sized in the floating window.

In "Similarity > Culling Options", the drop down arrow does not turn.

In "Topword", the placement of "Assign Temporary Labels" is inconsistent.

J

**Comment by chantisnake** [comment]
Is this one fixed? I remember there is a pr about tooltips merged into master.

**Comment by EmmaGrace** [comment]
If you are referring to the pull request "bugfix/documentation_grammar" that Josh made using my account, that was merely grammar fixes. The above is everything we couldn't change during that pass because it requires actual code and not just string changes

**Comment by chantisnake** [comment]
I think this is a front end change. Do we have people to look at this right now?

**Comment by mathewleblanc** [comment]
On local host, the tool tip for "Statistics > Assign Temporary Labels" seems to be working. "Assign Temporary Labels" in Topword is still slightly misplaced compared to the other pages. I will try to fix this now as well as the culling options drop down arrow.

**Comment by jacksonjreed** [comment]
only the fourth issue is still present
