### ISSUE TITLE
we are naming zip file with `txt` extension.

### ISSUE THREAD

**Issue by Shi26** [WheatonCS/Lexos#615]
The download file from local hose page will produces encoding error within it.

It's probably related to this part of code:
```python
 # Make sure the filename has an extension
                fname = lFile.name
                if not fname.endswith('.txt'):
                    fname = fname + '.txt'
                zfile.write(lFile.savePath, arcname=fname, compress_type=zipfile.ZIP_STORED)
```

Which is in this commit a year ago:  e92ee7604ab11a60b79e6d987befee1716105301

**Comment by chantisnake** [comment]
I realize that this code is **not** the problem, we will investigate on this little more

**Comment by chantisnake** [comment]
This is another reminder that **do not use vague variable names** like file_name or fname
