### ISSUE TITLE
move stop words and keep words to the culling option

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#616]
keep words always hang when there is a large file, like mobi dick, and you only want to keep a few words (which is not unreasonable).

moving them to the matrix will speed stopwords and keepwords up a lot.

**Comment by scottkleinman** [comment]
I'm too tired to think this through, but would this disrupt the order of scrubbing functions, potentially leading to unexpected results? Just something to consider...

**Comment by chantisnake** [comment]
modulation would require each every functionality to work on its own.

If this interfere with the scrubbing functionality, I would think that is because our scrubbing functionality are implemented in the wrong way.

**Comment by mleblanc321** [comment]
well "wrong" may be alil' too strong;  you are right that stop-keep words *is* a culling functionality (as is lemmas and consolidations btw) ... however, the separation of these functionalities is beyond the scope of this summer;  that said, it is clear from the comments we are getting in Montreal that a standard set for scrubbing, culling, and tokenization is *much* needed

**Comment by scottkleinman** [comment]
Some of the issues involved in refactoring are addressed [here](https://github.com/WheatonCS/Lexos/wiki/Ribbon-Diagram) and [here](https://github.com/WheatonCS/Lexos/wiki/Ribbon-Diagrams-and-Document-Location-Mapping).

**Comment by cgnobrega** [comment]
Stop/keep words does not hang in v4.0
