### ISSUE TITLE
Both servers not encoding unicode in rolling window

### ISSUE THREAD

**Issue by Landaluce** [WheatonCS/Lexos#625]
After following the instructions for the Beowulf experiment and producing the graph, I clicked on the download CSV Matrix button, and got an internal server error.
The new server(Lexos3 running Lexos v3.1.1) logs say is a unicode encode error, and it happens when putting Unicode characters like þ or ð in the search pattern.
And I get the same error on the old server (Lexos v3.0)

**Comment by chantisnake** [comment]
@weiqi, test this on the new RWA (rwa_model branch). If the error no longer exists, close this.

**Comment by Weiqi97** [comment]
I just tested this and I believe #812 resolved this issue. I will close this once the PR is merged. Thank you guys.
