### ISSUE TITLE
Keep Word-Internal Apostrophes removes apos at the end of words

### ISSUE THREAD

**Issue by Landaluce** [WheatonCS/Lexos#626]
Keep Word-Internal Apostrophes removes apos at the end of words like [students']

**Comment by mleblanc321** [comment]
yup .... emma and i considered some possible changes to "fix" that ... but we're just not confident that such a change will work across other languages; that is, it is easy to "fix" for English ... but what about French, for example?  (we need more expertise here;  i think this is in the realm of work where one of us in the dev group just focuses on more sophisticated uses of (a) hyphens, (b) apostrophes, etc.

**Comment by EmmaGrace** [comment]
If the button said "keep possessive apostrophes" or something like that, I would agree it is misleading. However, the apostrophe in [students'] is external to the word, so it should already be doing exactly what people expect it to
