### ISSUE TITLE
Lexos 3.1.1 error in cutter functionality

### ISSUE THREAD

**Issue by Shi26** [WheatonCS/Lexos#627]
Applying huge value of last proportion will produces a weird last segment:
Here is one test case:

- **Text**: `"ABCDEFGHIJKL"`
- **Cutting Type**: Characters/Segment 
- **Segment Size**:5
- **Overlap**:0
- **Last Segment Size Threshold**:500%

It produces two segments:
```
"ABCDE", 
"FGHIJKL"
```

since the `overlap` is 500%, therefore the last segment should be 500% large, therefore all the text should be in one segment.

**Comment by Shi26** [comment]
current cutter rewrite fixes this issue.

**Comment by Weiqi97** [comment]
Should we close this since it is fixed?

**Comment by mleblanc321** [comment]
@Krissac and @ciaburri-ginger -- i think this Issue is now resolved? correct?  (if so, we can close this Issue)

**Comment by Krissac** [comment]
Yes it's all set.
