### ISSUE TITLE
Multicloud raises ValueError: View function did not return a response

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#631]
I can't tell what is generating this error. It applies only in Lexos 3.2.

**Comment by chantisnake** [comment]
yes, I seen this before, I think @XinruLiu encountered this.

I don't remember what is the problem

**Comment by chantisnake** [comment]
I think is a interface do not have a return

**Comment by scottkleinman** [comment]
It does have a return. I think the problem is somewhere in `utility.generate_mc_json_obj()` or one of its subroutines.

**Comment by chantisnake** [comment]
Returning a none can cause this problem too

Sent from my Windows 10 phone
