### ISSUE TITLE
Changes in handling and output regarding the cutter rewrite

### ISSUE THREAD

**Issue by Shi26** [WheatonCS/Lexos#633]
The new cutter contains less functions as before, clear the code structure while keeping the full functionality.

1. Rather than go through every token(including whitespace and newline characters), we now split the text using new definitions before actually cut the text list.

Here are the definitions of each cutting options element:
- For characters: 
```python
seg_list = re.findall("\S", text)
```
- For words: 
```python
seg_list = re.findall("\S+\s*", text)
```
- For lines: 
(just split by the newline character while keeping the newlines within the text)
```python
seg_list = text.splitlines(keepends=True)
```

- For milestone:
(just split text by the given milestone)
```python
final_seg_list = text.split(sep=milestone)
```

2. These definition changes will result in differences in output:
- The different whitespace characters will now return the same result, in other words, the whitespace and empty string or new lines will return empty string, even follows word characters:
(But we only keep the empty lines ("     \n") when cutting by line just in case users need it. If it produces empty segment, it will be removed by the get_matrix)

```python
assert cut_by_characters(text="", seg_size=10, overlap=5, last_prop=1) == [""]
assert cut_by_characters(text=" ", seg_size=100, overlap=0, last_prop=0.5) == [""]
assert cut_by_number(text="      <-There are six spaces here",num_segment=5) == [
                                     "<-There ", "are ", "six ", "spaces ", "here"]
assert cut_by_number(text="\n\n\n\n\nword\n\n\n\n\n", num_segment=11) == ["word\n\n\n\n\n"]
```
Example in cut by lines:
```python
assert cut_by_lines(text="   \n\ntest", seg_size=1, overlap=0, last_prop=1) == ["   \n", "\n", "test"]
```

- More importantly, the new cutter method follows more strictly by the value of segment size and last segment proportion, without repetition.

One example involving element repetition:
Before:
```python
assert cut_by_lines(text="test\r\ntest\ntest", chunk_size=2, overlap=1, last_prop=200) == [
                                "test\r\ntest\ntest\ntest"]
```
After:
```python
assert cut_by_lines(text="test\r\ntest\ntest", seg_size=2, overlap=1,last_prop=200) == [
                                "test\r\ntest\ntest"]
```

- When cutting by number of segment, the new method handles the text in the same as before. But if the number of segment exceeds the total number of words, the new method will produces several empty segment in the end.
Here is one example:
Before:
```python
assert cut_by_number(text="This text has too few words!",
                             num_segment=8) == \
            ["This ", "text ", "has ", "too ", "few ", "words!", '', '']
```

**Comment by chantisnake** [comment]
I think this issue is just for future reference.
