### ISSUE TITLE
Keep Word-Internal Apostrophes keeps apos if its the first char in the file and is followed by a space: "' ..."

### ISSUE THREAD

**Issue by Landaluce** [WheatonCS/Lexos#637]
Upload Lexos/test/test_suite/Scrubbing/Apos/apos.txt, in scrub select Keep Word-Internal Apostrophes and apply scrubbing
original text: ' Hello her 'na"me' is...
result text: ' hello her name is...
expected text: hello her name is...

**Comment by chantisnake** [comment]
@EmmaGrace will you look at this?

**Comment by chantisnake** [comment]
@Landaluce Please take some time to learn markdown, and format your issue properly.

**Comment by EmmaGrace** [comment]
This issue is already solved on the scrubber cleanup branch, but we may want to hotfix it on Lexos3

**Comment by chantisnake** [comment]
@EmmaGrace Please show me how complicated is your hotfix. (Maybe tomorrow)

**Comment by jacksonjreed** [comment]
@jlobes is this fixed with your update?

**Comment by jlobes** [comment]
#885
