### ISSUE TITLE
Improved Gutenberg detection

### ISSUE THREAD

**Issue by EmmaGrace** [WheatonCS/Lexos#639]
Right now, we are attempting to detect Project Gutenberg boilerplate on uploaded files, and place a very intrusive dialogue box on the scrubber page if we do so. The boilerplate detection is handled by the LexosFile class, and the derived boolean is then passed to scrub(), which will then automatically attempt to remove the boilerplate. However, LexosFile's check_for_gutenberg() method is a bit crude.

The only factor that determines whether that giant pop-up occurs is if the uploaded text contains the string "Project Gutenberg" exactly as typed, case sensitive. This means a text discussing Project Gutenberg will trigger that pop-up, and any Gutenberg boilerplate that has been scrubbed to lowercase in a different program will not. We easily simply make our check non-case sensitive, but a researcher who works regularly with Gutenberg texts could probably clue us in to a more significant pattern to look for.

**Comment by Landaluce** [comment]
This can be fixed by searching for "\*\*\* START OF THIS PROJECT GUTENBERG.*?\*\*\*" which is what scrubber is using to find gutenberg's front boiler plate

**Comment by chantisnake** [comment]
A PR is merged. I am gonna assume this is fixed.
