### ISSUE TITLE
Missing new lines after scrubbing on lexos3 server

### ISSUE THREAD

**Issue by Shi26** [WheatonCS/Lexos#643]
The original text file:

[scrubber_test_file_original.txt](https://github.com/WheatonCS/Lexos/files/1234742/scrubber_test_file_original.txt)

The file after simply scrubbed (deselect all the scrubbing options) will be like this:

[scrubber_test_file.txt](https://github.com/WheatonCS/Lexos/files/1234748/scrubber_test_file.txt)

It produces the same result even without all the empty lines.
Although it somewhat makes sense but I think it will produce a larger problem in scrubbing longer text. And if I then go to cutter, I cannot cut by line properly.

**Comment by jacksonjreed** [comment]
closed per #888 #884
