### ISSUE TITLE
Cannot use Chinese character as milestone for cutting on Lexos3 server

### ISSUE THREAD

**Issue by Shi26** [WheatonCS/Lexos#644]
When I try to cut by milestone using a Chinese character as milestone, on the web page it keep reporting error that cannot apply this cutting action. And afterwards, it keep popping warning with this syntax:

> Lexos seems to be taking a long time. This may be because you are cutting a large number of 
> documents. If not, we suggest that you cancel, reload the page, and try again.

I tried to use several different files but got same results.

Here are some test files:
[Chinese_short_sentences.txt](https://github.com/WheatonCS/Lexos/files/1234806/Chinese_short_sentences.txt)
[Chinese_long_sentences.txt](https://github.com/WheatonCS/Lexos/files/1234808/Chinese_long_sentences.txt)

**Comment by mleblanc321** [comment]
hmm, confirmed;  i could cut on English characters, e.g. "xx"

**Comment by mleblanc321** [comment]
hmmm, is Python v2.7.x not recognizing our utf-8 milestone?  (damn, i get this mixed up: encode() ?)

# split text by milestone string
final_seg_list = text.split(sep=milestone)
