### ISSUE TITLE
Cannot download BubbleViz from lexos3 server

### ISSUE THREAD

**Issue by Shi26** [WheatonCS/Lexos#645]
The "Save as PNG" doesn't work, it doesn't redirect to the new page where you can save the image.

**Comment by rcdemuth** [comment]
I am having this same problem.  It does not work if I'm running the software locally or on the wheaton college server.

**Comment by danny98m** [comment]
This still doesn't work as of 27 June 2018. However, save as png works fine in wordcloud (though svg does not) and bubbleviz and worldcloud share the same code for saving as png so this is particularly puzzling.

**Comment by danny98m** [comment]
Relevant pull request [#797](https://github.com/WheatonCS/Lexos/pull/797)
