### ISSUE TITLE
Error in Multicloud v3.1.1

### ISSUE THREAD

**Issue by arialfie759** [WheatonCS/Lexos#646]
When testing large files such as Moby_Dick.txt or Pride_and_Prejudice.txt, the multicloud function produces word clouds that say words such as 'had', 'an' or 'a' only appear 80 times in the novel when this cannot be true for such large novels since these words are so common. It appears 80 may be the highest word count that multiclouds can produce. 

It also appeared that some word counts were slightly off.I went through the scrubbed .txt files and would search for the word to check the counts by entering CTR+F, then typing a space, typing the word and then typing a space (since words should be counted separated by spaces). I am not sure if this is a good method to check, but numbers seemed not to match up whether the word count in the .txt appeared less (like the word 'wet' in Pride and Prejudice) than the multicloud said or more (like the word 'says' in Moby Dick) than the multicloud said. I tried this for War_and_Peace.txt and also with the Beowulf Mallet file and had similar results.

**Comment by scottkleinman** [comment]
I suspect that this is because `d3` is scaling the term counts, and we are getting the tooltips from that, but a good place to start is to check whether Python is returning accurate counts to the front end. Do the numbers match the counts shown by Tokenizer?

**Comment by arialfie759** [comment]
Using a default scrubbed version of Moby_Dick.txt I generated a couple of multiclouds, got the word counts of some words each time (in total I looked at about 20 words) and compared them to the raw counts found in the DTM. Every single word count I looked at from multicloud was off from the word count in the DTM. The words I found that supposedly had a word count of 80 in multicloud were much higher when I looked at their raw count. For example, 'one' actually had a count of 891 and 'so' had a count of 1042. It also appeared that a lot of the words counted only once in the DTM were said to have a count of 10 in the multicloud (e.g. 'rug', 'si', 'cart'). Every other word I tested with counts in between differed from their raw counts with no seen pattern in the size of the word in the multicloud contributing to the number the count was off by. The count in the multicloud also appeared to not only be lower, but higher in some cases as well than the raw count in the DTM.

**Comment by scottkleinman** [comment]
In `templates/multicloud.html`, find the line [`response = JSON.parse(response);`](https://github.com/WheatonCS/Lexos/blob/master/lexos/templates/multicloud.html#L122). Right above it add `console.log(response)`. This will allow you to see what data is being returned to the front end in your browser console. If this information is inaccurate, the problem can probably be traced to the code block starting [here](https://github.com/WheatonCS/Lexos/blob/master/lexos/interfaces/multi_cloud_interface.py#L112).

**Comment by arialfie759** [comment]
I tried to do this in the debugger in PyCharm, but because this is an html file it won't allow me to do this.

**Comment by scottkleinman** [comment]
I have confirmed that the back end is sending accurate counts, so the problem must be that the tooltip numbers are coming from scaled numbers on the front end.
