### ISSUE TITLE
Enhancement Proposal for Tokenizer

### ISSUE THREAD

**Issue by arialfie759** [WheatonCS/Lexos#647]
When testing large files such as Moby_Dick.txt or Pride_and_Prejudice.txt, some words show up in the DTM with a proportion of 0, indicating that they do not appear in the novel at all, which is not true since the word would not be in the table otherwise. The reason this happens is because the proportion of times the word appears in comparison to all the other words in the novel is so small, that it is rounded to 0. 

I propose possibly increasing the decimal place that these numbers are printed so that it can be seen how many times this word appears in the novel in proportion to all the other words in the novel. If this decimal would be too small, I also suggest possibly adding another column to this matrix for each novel that has the word count so that the user can have an alphabetized list of all the words in the novel and the number of their occurrences in the novel in a convenient table.

**Comment by scottkleinman** [comment]
I think that both these issues can be addressed by clicking `Raw Counts` in the `Normalize` options and regenerating the table. If that's right, the real issue is the default display and how best to display accurate information to the user. Should we display raw counts by default? The suggestion of adding an extra decimal place in the rounding may help when the user is examining proportions.

**Comment by arialfie759** [comment]
I apologize, I completely forgot about the Raw Counts option. It may be beneficial to the user to make the default display Raw Count as that might be what the user wants to see first. As for the extra decimal place, yes it would be helpful for examining proportions.

**Comment by chantisnake** [comment]
The extra decimal place will make the display not nice to look at.
If they want a precise number, they should probably download the csv (I think we will not round at all in csv)
