### ISSUE TITLE
 Explore Using Plotly for Dendrograms and Rolling Windows

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#650]
This is a summary of Slack discussion today about enhancing and optimising plotting for dendrograms and rolling windows.

## Dendrograms

There are a number of d3 examples:

- https://bl.ocks.org/mbostock/2429963
- http://bl.ocks.org/kueda/1036776

However, they do not produce exactly the kind of dendrogram we want and lack basic interactivity. There is no pure d3 solution that works out of the box.

We are already using Plotly for the PCA plots in K-Means. It might be worth experimenting with it for dendrograms. Plotly's dendrogram function will solve one of our long-running problems: overlapping labels in graphs with many leaves. It has pan and zoom tools, as well as an image download function. See [https://plot.ly/python/dendrogram/](https://plot.ly/python/dendrogram/).

Alvaro experimented with Plotly but failed to get the correct topology for DAZ. This may have been because the [plotly function](https://github.com/plotly/plotly.py/blob/75673a9e94f11c26e6986ecadd0cc750bc872999/plotly/figure_factory/_dendrogram.py) may not have implementated the Euclidean average metric and linkage by default. It now appears to have `distfun` and `linkagefun` hooks to set this, so it should be possible to implement the full range of Lexos options from scipy.

We are not absolutely certain where the Plotly function converts the scipy dendgrogram into a tree-like object. However, it can save the entire graph with interactive functions as a Javascript file, which can then be embedded in the Lexos template.

@xinru should be assigned to this with some help from @alvaro, who worked in the code for K-Means.

## Rolling Windows

Plotly might also form part of a solution for optimising performance for rolling windows. We've already implemented some skipping of points on the line, but it is still slow.

Useful links for implementing moving windows:

- Numpy: [https://gordoncluster.wordpress.com/2014/02/13/python-numpy-how-to-generate-moving-averages-efficiently-part-2/](https://gordoncluster.wordpress.com/2014/02/13/python-numpy-how-to-generate-moving-averages-efficiently-part-2/)
- Pandas: [http://pandas.pydata.org/pandas-docs/version/0.17.0/api.html#standard-moving-window-functions](http://pandas.pydata.org/pandas-docs/version/0.17.0/api.html#standard-moving-window-functions)

We should be able to use Plotly to plot the output of these. If they're still slow, we can perhaps use matplotlib and then convert to plotly.

An example might be the pandas time series one on on the Plotly website: [https://plot.ly/python/time-series/](https://plot.ly/python/time-series/). We may even be able to use the pandas built-in time series function if it is fast enough.

Most plotly examples have only about 50 data points, whereas we need thousands for rolling windows. It seems to be possible, to go by [this issue](https://github.com/ropensci/plotly/issues/297).

Also, [https://plot.ly/python/webgl-vs-svg/](https://plot.ly/python/webgl-vs-svg/) contains some wonderful example code for webgl.

**Comment by chantisnake** [comment]
nice job

**Comment by chantisnake** [comment]
Both are almost done. RWA are in progress for implementing milestone. We are counting on Weiqi.
