### ISSUE TITLE
Show tokenisation settings in Scrubber/Cutter

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#654]
Unless you go to Tokenizer first, Scrubber and Cutter use default tokenisation settings. It would be good to de-black box this by adding a "Show Tokenization Settings" button on those screens with the option to go to Tokenizer if the settings are not what the user wants.

**Comment by chantisnake** [comment]
makes sense.

**Comment by chantisnake** [comment]
But can you explain in detail, how should we behave if people chose to token by 2 grames?

What should stop words, lemma or consolidation do?

**Comment by scottkleinman** [comment]
Lemmatisation is probably meaningless for bi-grams, but you could, for instance, strip out "United States" but leave "united" and "states". Or you could consolidate "United States" and "United States of America".

**Comment by chantisnake** [comment]
but tokens are overlapping token:
`"The United States of America"` is tokenized to `"The United", "United States", "States of", "of America"`

How can we consolidate `"United States"` without interfering the words around it (`"The United", "State of"`)

**Comment by Myles-Trevino** [comment]
Tokenizer no longer affects other tools in 4.0.
