### ISSUE TITLE
In The Margins and tooltip changes required once scrubber_cleanup is merged

### ISSUE THREAD

**Issue by EmmaGrace** [WheatonCS/Lexos#657]
This issue is a list of tooltip and in the margins changes that will required once the scrubber cleanup branch is merged, as well as a few things that were always messed up and should be fixed. This document does not cover most tag-related issues, as our tag handling methods need a separate massive overhaul. The current changes are as follows:

**Tooltip changes**
_Stop/keep words text field_ -- "List format: a list of words separated by commas, spaces, or line breaks"
_Special characters text field_ -- "... The entity should be separated from its replacement glyph by a colon (e.g. &ae;: æ). ..."

**In the Margins changes**
_Misc_ -- Fix broken links in the keep hyphens and apostrophes sections
_Keep word-internal apostrophes_ -- "If this option is selected, apostrophes will be retained provided they are surrounded by non-whitespace characters on both sides (i.e. they do not follow or precede a newline, tab, etc). The beginning and end of the text counts as whitespace for these purposes. Note that if there are consecutive apostrophes, they will be treated as a single block, and removed or kept depending on what other characters surround the block."
_Keep ampersands_ -- "Selecting this option will change all variations of Unicode ampersands to a single type of ampersand ("&") and this will be left in the text. Note that HTML ..."
_Make Lowercase_ -- Somewhere in the paragraph it should be noted “This option applies to all characters with a lowercase equivalent supplied by the Unicode standard.”
_Stop words/keep words_ -- "... In both cases, words must be entered as comma-separated, space-separated, or line-separated lists like the following:
a, some, that, the, which
a some that the which ..."
_Stop words/keep words_ -- Fix broken bold tags around "Make Lowercase"
_New section_ -- At the end of the Additional Options section there should be a note along the lines of: "Lemmas, consolidations, and special characters with a user-defined list require exactly one colon per input line, at least one word or character to the left of said colon, and at most one word or character to the right of the colon. Deletions may be performed by leaving the right of the colon blank. Ex. typing "a, b, c:" in the consolidations field will delete all instances of the letters a, b, and c from the text."
_Special characters_ -- "... Note: Any special characters that appear inside tags _will_ be modified if they appear within the chosen rule set. ... The entity should be separated from its replacement glyph by a colon (e.g. &aelig;: æ ). ..."

**Comment by cgnobrega** [comment]
v4.0 fixes these issues
