### ISSUE TITLE
Convert existing jQuery Ajax calls to the Deferred Object API methods, or async functions

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#661]
See the deprecation notice on this page: http://api.jquery.com/jQuery.ajax/

> Basically, `.done()` replaces `.success()`, `.fail()` replaces `.error()`, and `.always()` replaces `.complete()`.
--- Scott Kleinman 

News flash, you can use `async` and `await` to handle jquery ajax.
 
I personally believe `async` `await` makes the code logic more linear, avoids the debugging issue of callbacks (sometime refers to as "callback hell"), and the code syntax more like regular sequential languages (python, C#, java, C++)

**Comment by scottkleinman** [comment]
Just some additional information : `.done()`, `.fail()`, and `.always()` are methods of the jQuery Deferred Object. There are a number of other methods, although they will probably be used only rarely in Lexos. The `.then()` method might be a useful one for multiple ajax calls. The API documentation is [here](http://api.jquery.com/category/deferred-object/).

**Comment by scottkleinman** [comment]
I have added a note in the Wiki about using the Deferred Object API in new code. This issue should remain until we convert existing code. I'll change the issue title to reflect this.

**Comment by chantisnake** [comment]
Related to https://github.com/WheatonCS/Lexos/issues/681

**Comment by Myles-Trevino** [comment]
The deprecated functions are not used in the 4.0 frontend rewrite.
