### ISSUE TITLE
RWA hangs when searching for strings, regex :(

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#667]
### which option did I check
RWA, "tatata", by character, in window of 100K chars

### which file did I use
DNA file

### what the bug looks like
server hangs (really hangs ... ugh)

### error message if applicable 
i haven't chased LOG files yet

**Comment by chantisnake** [comment]
window of 1000k... wow. I am surprised that python's poor memory management did not blow up...

**Comment by scottkleinman** [comment]
Does it work for smaller window sizes (i.e. is this just a memory management issue)? If so, we should probably just patch with a warning in v3.1 and address it more fully in v3.2.

For v3.2.+, I think that the d3 plotting in Rolling Window has to be re-written with plotly, anyway.

**Comment by mleblanc321** [comment]
right, string search works better (fine) for small window sizes ...

**Comment by scottkleinman** [comment]
OK. We should try to identify an upper limit on the server and for local installations, and I'll add a warning message as a patch to v3.1.

**Comment by chantisnake** [comment]
I am planning to rewrite rolling window to using panda, which should handle 100k pretty easily.
Also, our old algorithm is very inefficient.

inspired by this issue. I think we need to implement some kind of server timeout mechanism. When an `route` function has been executed for too long, just stops it.

**Comment by scottkleinman** [comment]
Yes, pandas has a [built-in rolling window method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rolling.html). The dataframe can be read directly into a [plotly line chart](https://plot.ly/pandas/line-charts/).
