### ISSUE TITLE
Allowed ES6 Feature

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#684]
- `let` and `const` (I recommend to always use `const`) documentation: [let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let), [const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)
- Destructuring assignment (mainly used as keyword parameter or named parameter) [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
- Template literal (for building string and html easily) [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

All the other ES6, ES7, ES8 features are not allowed in this project, including arrow functions. 
If you want more modern javascript features, please discuss in this issue,

@Weiqi97 This issue is just for future reference. You can close this issue when you see it.

reference:
![capture](https://user-images.githubusercontent.com/10100995/40140885-0164407c-5922-11e8-989e-28593f532358.PNG)

**Comment by scottkleinman** [comment]
I want to note that there are some incompatibilities with Microsoft Edge, but, since we don't officially support it, and Edge's ES6 support is likely to increase, these options sound to me like a reasonable deployment of ES6 features.

**Comment by chantisnake** [comment]
As far as I know Edge supports all the 3 features mentioned above, except for `Escape sequences allowed in tagged template literals` and `Rest in objects`, both features are experimental and we should not use it anyway.

**Comment by scottkleinman** [comment]
Yes, avoid experimental features, and we should be fine.

**Comment by chantisnake** [comment]
This issue has been open for long enough.
