### ISSUE TITLE
Migrate continuous integration to GitHub App and Checks

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#685]
Our Travis CI still uses GitHub Services API, which is deprecated: https://developer.github.com/changes/2018-04-25-github-services-deprecation/. 

I want migrate our Travis CI integration to GitHub Apps or Webhooks. In the mean time, I want to see if our integration service (Travis and Appveyor) are compatible with GitHub's new [check feature](https://help.github.com/articles/about-status-checks/#checks)

**Comment by chantisnake** [comment]
Turns out people need to be organization owner to add github app to an organization:  https://help.github.com/articles/permission-levels-for-an-organization/

@mleblanc321 want to do us a favor and promote someone (probably Weiqi should be in the mix, at least) to owner? The guide can be found here: https://help.github.com/articles/changing-a-person-s-role-to-owner/

**Comment by chantisnake** [comment]
@Weiqi97 @mleblanc321  if you guys have any problem feel free to comment on this issue. I am happy to help.

**Comment by Weiqi97** [comment]
@chantisnake Thanks, we will give it a try tomorrow.

**Comment by Weiqi97** [comment]
Sorry this has been a while. I just tried it and I think it worked. I will talk to Mark since I believe using his account to install will make more sense...

**Comment by Weiqi97** [comment]
The travis-ci is giving me a headache... I think it it not working because of [this](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org). I sent them an email already, I don't know how fast they gonna respond.

**Comment by Myles-Trevino** [comment]
This appears to have been solved.
