### ISSUE TITLE
Make presence of glyphicon-chevron-right more obvious to user.

### ISSUE THREAD

**Issue by danny98m** [WheatonCS/Lexos#696]
## Glyphicon Visibility
Talking to users, I have discovered that the little arrow on the right hand side of the page for each tool is very hidden. Most users seem to not even notice it is there until you point it out. The information provided by clicking the glyphicon is really helpful so I think it would be beneficial to make the tab move or something when a user initially goes to a page. Just to attract attention to it. This would be some pretty simple jQuery just not sure what people want the attracting action to be. 

### Proposed Enhancement:
* Add some sort of action to that pull out info tab so that its presence is more obvious to the user.

**Comment by jaronson13** [comment]
yes that would  look better i think for the ui pages, mainly for ease of use. Other things i noticed are the in the marghins pages can be hard to see where to close. The arrow is not always easy to see and notice

**Comment by mleblanc321** [comment]
_ok, who is spoofing on the jaronson13 account?  (cheng?)_

**Comment by mleblanc321** [comment]
phuntsho will show us a demo of one possibility ...

**Comment by chantisnake** [comment]
I am definitely not spoofing on @jaronson13's account. lol

**Comment by danny98m** [comment]
I have what I believe is a good solution to this. I'll work on it some more after some other tasks.

**Comment by danny98m** [comment]
I made it so the sidebar (In  the Margins) pops out for a little and then returns to the original space to make user aware of it. This only occurs on the upload page.

Here is the relevant pull request [#701](https://github.com/WheatonCS/Lexos/pull/701)

**Comment by jaronson13** [comment]
yes i think the concept is good, just hard to know how users would respond to it. I think it makes me aware of it but maybe non-technical user would prefer to have a tour like @scottkleinman  mentioned. definitely worth discussing further

**Comment by danny98m** [comment]
Okay, I can talk about it with the English students if that seems sufficient enough?

**Comment by chantisnake** [comment]
This issue is addressed in pull requests: https://github.com/WheatonCS/Lexos/pull/701

**Comment by danny98m** [comment]
I personally feel web storage is a better way to do this than using persistent cookies as it is more secure and you can fit more data. I have an alert popping up based on if a user has visited before or not. Its just displaying a test message as I'm not sure what we would want the alert to say or if an alert is even what we want.

**Comment by scottkleinman** [comment]
I would say, open a popover attached to the _In the Margins_ toggle tab with text like "View instructions for any screen in Lexos by clicking the _In the Margins Tab_. Add a "Got it!" button and then disable the trigger stored in web storage.

**Comment by danny98m** [comment]
Here is the relavant pull request [#730](https://github.com/WheatonCS/Lexos/pull/730).

**Comment by Weiqi97** [comment]
This issue is solved in pull requests: #730
