### ISSUE TITLE
clean up html template

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#704]
Maybe related to https://github.com/WheatonCS/Lexos/issues/539

On my phone, more soon.

**Comment by jacksonjreed** [comment]
I'm guessing this is no longer a problem but do you have more details @chantisnake ?

**Comment by chantisnake** [comment]
Uh, the HTML was old and haven't been refactored for years (when I was there).

I don't know whether it is fixed with the front end rewrite effort.
1. There are many submit, which is obsolete with Ajax.
2. Missing closing tag, or mismatched closing tag
3. Wrong tag, for example: use header tag for content, use br tag when should use p.

I think if there is no huge HTML rewrite in front end refactor, then definitely look over all the HTML.

**Comment by jacksonjreed** [comment]
The html for the new front end was pretty much redone from scratch and is very clean and readable for the most part, but I'm not 100% sure it meets your standards, e.g. I think there's frequently content in <h3> tags; so I'll leave this open for now for such discussions.
