### ISSUE TITLE
New Favicon

### ISSUE THREAD

**Issue by akuisara** [WheatonCS/Lexos#72]
I think we could have a better favicon for our new release, since personally I feel that the current favicon is hard to recognize. So here are some sample icons of letter "L" with different background colors and fonts I would like to show:
![icons](https://cloud.githubusercontent.com/assets/4997873/3126315/85844e00-e79e-11e3-9d87-1dd612f1ee83.png)
Do you have any comments or suggestions?

**Comment by chantisnake** [comment]
probably (d) or (e), 

the font is very classy and ancient look, and the color fit with the color of Lexos.

I prefer (e) a little better, because blue is already the main color of the Lexos webpage

**Comment by chantisnake** [comment]
Apparently no longer relevant
