### ISSUE TITLE
Latest version of d3 breaks word clouds

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#727]
There's a good chance that this issue discussed at [https://github.com/jasondavies/d3-cloud/issues/107](https://github.com/jasondavies/d3-cloud/issues/107) is causing the problem. If the solution provided there works for Word Cloud and Multicloud, we'll just need to check BubbleViz, since we should probably implement Rolling Windows in Plotly. Then we'll be able to use the latest version of d3 and we can close issue #464.

**Comment by scottkleinman** [comment]
Sadly, the issue is more complicated than indicated in the issue noted above. Our Word Cloud code contains many methods which were changed in v4 of d3.js. I went through and changed every method name that I could find, but I've got to a point where no word cloud is generated but the console does not show an error. I will continue to investigate, but I think we may have to stick with v3 for the moment.

**Comment by gustavz** [comment]
How did you solve this
