### ISSUE TITLE
BubbleViz number input resets after generating graph

### ISSUE THREAD

**Issue by ealitt** [WheatonCS/Lexos#731]
When changing the number inputs for "Graph Size", "Maximum Number of Terms", and "Minimum Term Length" for BubbleViz, the page reloads and the inputs revert back to their default values. Only the "Maximum Number of Terms" and "Minimum Term Length" options affect the graph, but the "Graph Size" never changes. Just to be clear, all three values go back to their defaults, but only two of the variables makes changes. It seems like the "Maximum Number of Terms" and "Minimum Term Length" are related to the backend in bubble_view.py whereas the "Graph Size" is related to scripts_viz.js. I think we'll need some ajax here so the values don't change back. Can someone take a look at that, since I'm not very familiar with ajax?

**Comment by Weiqi97** [comment]
I'll take a look next week. Thanks for reporting this issue.

**Comment by chantisnake** [comment]
It feels like you are not caching them in session
