### ISSUE TITLE
multicloud redesign

### ISSUE THREAD

**Issue by phuens** [WheatonCS/Lexos#739]
What do you think about this redesign of the options in multicloud @scottkleinman 

What we currently have is the following: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21346016/41111791-143609c6-6a4b-11e8-8891-d1a5dcdaa921.gif)

What do you think about redesigning it this way: 
I basically made the two options under the toggle button in the current version as two different options. This redesign makes the actual multicloud images fit in properly underneath the options since as of right now in the current version, when you generate the multicloud, it leaves a huge gap on the right side of the toggle button. 

![screenshot from 2018-06-07 11-52-32](https://user-images.githubusercontent.com/21346016/41111818-27f69f98-6a4b-11e8-934e-fd4fd674c345.png)

**Comment by scottkleinman** [comment]
I like the basic idea. My only suggestions would be for clarity. Why not make the layout three columns with an "Or" between the two options and change "Select Document(s)" to "Document Clouds"? (Alternatively, add "Document Clouds" about  "Select Document(s)" &mdash; I'm not sure which I prefer. That way the user can clearly see that they have two (parallel) alternative options.

**Comment by mleblanc321** [comment]
good to hear;  @phuens, please keep showing scott mock ups;  he and his collaborators (some heavy hitters) use this tool;  we'd like to make the UI more intuitive, but *not* mess anything up with functionality/intent ...
