### ISSUE TITLE
Multicloud tiles need to be natsorted

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#752]
In Multicloud, data for each cloud is not `natsorted` before it is passed to the layout algorithm, so the clouds are appearing as doc1, doc10, doc11...doc2 instead of doc1, doc2...doc10, doc11. I'm guessing that this should be fixed on the back end.

**Comment by jacksonjreed** [comment]
With merge of #879 I'm not sure this is still a problem, will investigate.

**Comment by jacksonjreed** [comment]
for files numbered internally (i.e. by cutter) this should no longer be a problem, but if you uploaded files already numbered without leading 0s it will be.
by implementing the leading 0s thing, should we now assume that it is the user's responsibility to follow this numbering scheme?

**Comment by scottkleinman** [comment]
I don't think we should ever assume the user's responsibility :-). Users may just upload a bunch of texts and go straight to Multicloud. If possible, the clouds should be sorted on the back end, but, if it is necessary to do it on the front end, there should be a javascript implementation of natsort lurking in the repo (we definitely used it at one point). If you need it and can't find it, let me know.

**Comment by Myles-Trevino** [comment]
This no longer appears to be a problem in the new multicloud implementation.
