### ISSUE TITLE
Results of Tokenizer are not passed to visualisation tools

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#763]
When re-tokenise your DTM in Tokenizer, for instance, by changing to bi-grams, the word cloud tools still give you 1-grams. It may be that we need to introduce the Advanced Options sidebar (in Hierarchical Clustering and other analysis tools) to the visualisation tools.

I'm not sure how we missed this before.

**Comment by chantisnake** [comment]
This is probably because word cloud is not a Analyser. And it does not use our matrix model. I noticed that couple years ago, and assumes that is a feature.

**Comment by scottkleinman** [comment]
Definitely not a feature--an oversight. I only noticed it when I tried to generate a "word" cloud in Chinese. You should definitely be able to generated clouds based on non-English or non-word tokenizations. There is one important implication to @chantisnake's observation. The functions under Analyze all allow you to tokenize separately from the Tokenizer tool. Should that be the case, or should they use the matrix produced by Tokenizer by default? What would be the easiest way to implement tokenisation in the Visualize tools?

**Comment by chantisnake** [comment]
This points out our design mistakes in our HTML. 

We currently uses a template hierarchy, we have templates for every set of tools, and put the panels in templates. now we realize some tools in different set (visualize and analyze) needs to share some panel (the tokenize panel).

I propose to make each panel a widget and include them into HTML, using the jinjia2 include syntax.

**Comment by scottkleinman** [comment]
This seems reasonable as an implementation strategy. I would just add the following:

1. We need to make clear on the Tokenizer screen that we are displaying statistics, not modifying the DTM in the way that Scrubber and Cutter do. This may mean that it is mis-categorised under the Prepare menu.
2. Topic clouds are based on pre-tokenised texts so it does not make sense to show the panel for this tool.
3. There are some serious screen real estate issues in adding the Advanced Options panel to many of the visualization tools. This will take some design ingenuity, and we may need to have a conversation about its appearance. It is possible that we will be forced to open up a dialog for the user to set these options.

**Comment by Myles-Trevino** [comment]
The tokenizer page no longer affects other tools to avoid confusion.
