### ISSUE TITLE
Word Cloud View Counts Table

### ISSUE THREAD

**Issue by Krissac** [WheatonCS/Lexos#768]
Word Cloud Get Graph works but when View Counts Table is clicked an empty Term Counts table appears...front end bug

**Comment by scottkleinman** [comment]
I noticed yesterday that the term counts table relies on a different `data` variable, which contains a list of lists passed from the back end. This takes the form of `[[b'term1': '200'], b'term2': '100'], etc.]`. The binary values in the list may be what is tripping up the DataTables script.

**Comment by mleblanc321** [comment]
>binary values in the list 
not sure what you mean here?

**Comment by scottkleinman** [comment]
Sorry, that should have been "bytes", not "binary". That is, the bytes literal `b'term'`, as opposed to the string `'term'`.

**Comment by chantisnake** [comment]
That might have been missed out during the python3 migration. In python3 string is automatically unicode therefore we don't need any more `u'stuff'` or `b'stuff'`.

**Comment by mleblanc321** [comment]
>I noticed yesterday that the term counts table relies on a different data variable, which contains a list of lists passed from the back end. This takes the form of [[b'term1': '200'], b'term2': '100'], etc.]. The binary values in the list may be what is tripping up the DataTables script.

@scottkleinman - where r u seeing this?

**Comment by mleblanc321** [comment]
hmm, i tried removing that ... but that didn't do it (?) ... oh well, tired boy;  sorry ... i'll leave this issue as is ...

**Comment by scottkleinman** [comment]
Hmmm... It worked for me, at least for the Modern English texts I had loaded. I'll pull from master next week and try again to test more thoroughly.
