### ISSUE TITLE
Upload Loading Spinner in Chrome Not Displaying

### ISSUE THREAD

**Issue by mathewleblanc** [WheatonCS/Lexos#794]
# Upload Loading Spinner in Chrome Not Displaying

Our loading icon svg is not displaying in Chrome. It works completely fine in Firefox; the icon appears when the user uploads a file and disappears when the file has finished uploading. It does its rotating animation as well. In upload on Chrome the icon does not display unless the visibility is hard coded in the HTML, and it does not do the rotating animation. I thought maybe certain syntax or attributes and properties were not supported in Chrome, but I checked them on W3Schools and they are all supported. If anyone has any idea why it is not working in Chrome and any creative solutions please try them on [this branch](https://github.com/WheatonCS/Lexos/tree/refactor/upload) by @phuens.

**Comment by scottkleinman** [comment]
@mathewleblanc I think I've solved this, but I'd like to know if it works at your end. In `scripts_upload.js`, find the `showProgress()` function and add `$('#status').css('z-index', 50000).show()` at the top. This should show the icon, even in Chrome.

Then, at the bottom of `FileSelectHandler()`, comment out `$('#status').hide()`. Right below `showProgress()` a few lines beneath it, add `$('#status').delay(1200).hide(0)`. This will hide the icon only after a short delay.

Let me know if this works for you.

**Comment by mleblanc321** [comment]
@mathewleblanc -- thoughts?

**Comment by mathewleblanc** [comment]
Yes, it worked! Thank you very much. I will make a PR on this soon.

**Comment by mathewleblanc** [comment]
I just made a PR #798. The spinner does appear in Chrome but it does not rotate. Any thoughts?

**Comment by scottkleinman** [comment]
That's a challenge. One solution is to do the following in `base.html`. Change

```html
<div id="status">
  <img src="{{ url_for('static', filename='images/loading_icon.svg') }}?ver={{version}}" alt="Loading...">
</div>
```
to
```html
<div id="status" style="display:block;">
  <i class="fa fa-spinner fa-spin fa-2x fa-fw" style="color: #0068AF;"></i>
  <span class="sr-only">Loading...</span>
</div>
```
This will use a Font Awesome icon instead of an animated SVG. (I've added `display: block` so that you can see it without uploading a file &mdash; remove that for production.) However, the Font Awesome icon looks different and will apply globally throughout Lexos, so it is a design decision whether we adopt this solution.

**Comment by mathewleblanc** [comment]
Thanks @scottkleinman, this new spinner works perfectly. I thought of using font awesome but I wasn't sure how much of a pain it might be. I'll make a PR on a branch so I think we can close this issue now.
