### ISSUE TITLE
Spinner icon not spinning in Chrome

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#800]
I just noticed this when generating a dendrogram, so I suspect it is global. The problem was first noted in Upload as described in issue #794. There is a proposal there to fix it with Font Awesome, but it involves a design decision. See the discussion there.

**Comment by mathewleblanc** [comment]
This was just fixed in issue #794 so I think we can close this issue too.

**Comment by scottkleinman** [comment]
I want to re-open this temporarily to make sure that we catch every example. Some screens use a different element&mdash;for instance, Dendrogram uses `<div id="status-analyze">` (this is a legacy of older code). We should probably make sure that all of these are changed in every tool before closing this issue.
