### ISSUE TITLE
Active documents icon triggers when you try to upload invalid file types

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#806]
If you try to upload an invalid file type (e.g. `.json`) in Upload, you, the upload is prevented, but the Active Documents icon appears, and the number of active documents shown increments if you try again.

**Comment by phuens** [comment]
@scottkleinman I will look into it.

**Comment by jacksonjreed** [comment]
working on this--
there seems to be a larger associated issue: if you navigate to the upload page and upload a new batch of documents, the active documents count updates to display only the number of docs you *just* uploaded

**Comment by jacksonjreed** [comment]
the code to initialize is accessing #counter from the html, which is set to 0 when loading the page...
the incrementation issue is fixed but waiting to push this until I figure out how to properly access active docs count

**Comment by jacksonjreed** [comment]
never mind, I'm pushing a branch to fix this specific issue...
BUT this code needs to be cleaned up more, the counter still definitely doesn't work as intended. I'll open another issue,
