### ISSUE TITLE
Javascript error in Content Analysis

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#820]
Content Analysis was loading `scripts_scrub.js`, and this was causing an error. I have commented out the code, assuming that this was a copy paste error. If I am correct that Content Analysis does not use this script, the line should be deleted. Otherwise, it can be uncommented, and we will have to figure out what the bug is.

**Comment by Landaluce** [comment]
I deleted this line [2f719e7](https://github.com/WheatonCS/Lexos/commit/2f719e7a867128e0cf547dc5b5ac409ec38ab551)
