### ISSUE TITLE
Tokenizer: convert to pandas dataframe?

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#837]
Tokenize. Perhaps experiment with assembling the data in a pandas dataframe, converting the head to html using `pandas.to_html()`, and sending that to the front end. It might be more efficient and actually make the Tokenizer table display work.

**Comment by jacksonjreed** [comment]
@Weiqi97 can this one be closed with the tokenizer rewrite?

**Comment by chantisnake** [comment]
It is better if you add the link to the pr you are referring to.
Thank you.

**Comment by jacksonjreed** [comment]
that would be #873

**Comment by Weiqi97** [comment]
I believe #873 resolves this issue.
