### ISSUE TITLE
Bootstrap Consensus without scikit-bio

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#845]
It would really be great if we could remove `scikit-bio` as a dependency for bootstrap consensus trees. Although I had it working on Windows, I recently upgraded to Python 3.7, and our Windows installation instructions no longer seem to work. I have heard others complaining about `scikit-bio` being unstable.

**Comment by mleblanc321** [comment]
unstable on Windows?  clearly scikit-bio as a whole is well received, no?

**Comment by scottkleinman** [comment]
The complaint I heard was from a Mac user, but my problems are on Windows. To go by the GitHub issues, the developers seem a little slow to support Windows. But I wonder if we could look at their code and transfer over to Lexos just the functions that we are using for BCT without all the overhead of another dependency (especially one that is still in beta).

**Comment by Weiqi97** [comment]
Yes, `scikit-bio` has to go. It is truly annoying and sorry I decided to include it at the first place. I'm now working on finding an alternative solution. In the meantime, I will see if I can get the circular tree mentioned in #826.

**Comment by scottkleinman** [comment]
For visualisation, it looks like we may want to use [biopython's Phylo module](http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc204). Here is [an example of how to visualise it with networkx](https://www.blopig.com/blog/2016/02/drawing-custom-unrooted-trees-from-sequence-alignments/). If we can do that, we should be able to draw it in plotly, as shown [here](https://plot.ly/python/network-graphs/). Just a thought.

Here are some other useful links that might get us there: [unrooted tree via Biopython-igraph-Plotly](https://plot.ly/~empet/14264/unrooted-tree-from-sequence-alignments/#/), [how to convert a graphviz layout to plotly](https://plot.ly/~empet/14007/graphviz-networks-plotted-with-plotly/#/).

But the first step is to calculate BCT without scikit-bio...

**Comment by Weiqi97** [comment]
We removed `scikit-bio` in #882.
