### ISSUE TITLE
make ITM scroll with the window

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#848]
when using a tool, then wanting to read the ITM directions, the directions/text from ITM is often displayed off the screen, out of sight from some of the tool options, so the user is forced to scroll up and down between ITM and the tool

can we make ITM scroll along with the main (tool) window?

**Comment by scottkleinman** [comment]
If I understand correctly, that might be hard to get right consistently. One option might be to put anchors in the ITM text and scroll to them when a user clicks on a link inside one of the optin tool tips.

A related error that I had forgotten about is that the titles in the ITM slideout link to the API's JSON response, not the actual ITM page. That should be an easy fix.
