### ISSUE TITLE
On tokenize panel, make N-gram button larger

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#852]
the N-gram button in tokenize has the more-fewer arrows very close together;

can we increase the size?

**Comment by jlobes** [comment]
Also present on:
Cut, BubbleViz, Rolling Window, Statistics, all Clustering pages, Similarity Query, & Topwords

**Comment by chantisnake** [comment]
I think all of them are in analyze template. Fixing one will fix all of them.

**Comment by jlobes** [comment]
Most of them are - but there are also a few stragglers in different page templates
