### ISSUE TITLE
Feedback and Support form (needs work)

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#853]
In the footer, our Feedback and Support button needs some love:

(a) we should give the user a chance to enter their email address (otherwise, we can't talk back to them)

(b) can we hook these to our GitHub Issues?

**Comment by WeaselPeasel** [comment]
(a) should we keep the Google form layout? If so, should we add an entry for email and perhaps change what is done with the form when it is submitted
(b) a GitHub account is required to open an issue, so we would need to work around that if we wanted to incorporate them into the Feedback and Support

**Comment by cgnobrega** [comment]
We have decided against the feedback and support form for v4.0
