### ISSUE TITLE
Scrubber Consolidation and Lemma: Improper formating

### ISSUE THREAD

**Issue by mlimoges** [WheatonCS/Lexos#854]
In the scrubber, consolidations and lemmas that are not formatted correctly (correct: "a:b" or "a,b:c") cause problems on the front end.

#### "a,b" and ":a"
In both of these cases, the page will attempt to load forever instead of giving an error.

#### "a:"
This will complete, but the end result is the removal of whatever "a" was. Although this makes sense, since scrubbing replaces the file on Lexos I think we should assume it is a typo and process it as an error.

These responses are consistent across Chrome, Firefox and local Lexos use.

"scrubber.py" in lexos/processors/prepare catches these errors, although this information isn't conveyed to the front end.

**Comment by scottkleinman** [comment]
In fixing this, we might want to consider adopting a more intuitive format.

**Comment by mlimoges** [comment]
resolved by pull request #961
