### ISSUE TITLE
feature: make some sample texts/corpora available from upload page

### ISSUE THREAD

**Issue by jacksonjreed** [WheatonCS/Lexos#857]
currently there are some example texts in our repo, but these could be available from the first page--a quick way for new users to test out the tools
these could be pre-scrubbed? or maybe have associated scrubbing settings tailored to that document that would load up when the scrubbing page is accessed, so the user could still change things.

if certain texts are intended to demonstrate certain features, perhaps selecting them here could direct the user immediately to the right tool page, again loading up associated settings

etc.--there are a variety of uses

**Comment by cgnobrega** [comment]
Our help section in v4.0 has links to the repo folders which have pre-scrubbed docs or scrubbing directions for the RWA tool and all analyze tools
