### ISSUE TITLE
active documents counter updates incorrectly on upload page

### ISSUE THREAD

**Issue by jacksonjreed** [WheatonCS/Lexos#862]
if a number of documents are already uploaded, and the user returns to the upload page to upload more documents, the active docs counter will update to display the number of documents _just uploaded_, rather than the total number of active docs including the new ones.
The code here accesses an html element that _should_ contain the number of active docs, but instead is always 0--need to find another way to access that info.

**Comment by chantisnake** [comment]
This is the method to get number of active document: https://github.com/WheatonCS/Lexos/blob/master/lexos/views/base_view.py#L34
