### ISSUE TITLE
Analyze and Tokenize: negative numbers are currently accepted input

### ISSUE THREAD

**Issue by mlimoges** [WheatonCS/Lexos#877]
I found this while attempting to activate error modals in similarity query
Most Analyze functions will complete even if given negative input in the Tokenize box
the html warns against this input but running the analysis usually will still generate results
* Similarity Query, Hierarchical Clustering:
    * negative n-grams runs
    * negative most frequent words (culling) runs
    * negative must be in x documents (culling) runs
    * must be in x documents where x > the number of active documents runs
* K-Means Clustering, Statistics, Bootstrap Consensus Tree, Topwords:
    * negative n-grams runs
    * negative most frequent words runs
    * negative must be in x documents runs
    * requiring a word to be in more documents than are active gives an error message; but Statistics still seems to generate new data anyway

**Comment by mleblanc321** [comment]
can we deactivate the "Submit" buttons if invalid input detected, to prevent any hit to back end?

also, @mlimoges -- i'm using Chrome (on lexos3) and i cannot enter (any) values from the keyboard, only the arrows up/down work for changing input; thus i can't seem to enter negative values on Chrome ... but (aha) Firefox let's me manually enter from keyboard;  e.g., -4 can be entered, the input field turns RED, but the -4 is sent to the back end :(

**Comment by chantisnake** [comment]
If you guys decided to check on the frontend, remember also check it on the relavent function on the backend for robustness.
