### ISSUE TITLE
scrubber regex wrecking whitespace in files

### ISSUE THREAD

**Issue by jacksonjreed** [WheatonCS/Lexos#884]
This line of regex at the end of the scrubber function is messing up a lot of files:
__finished_text = re.sub(r"[\s]+", " ", text, re.UNICODE | re.MULTILINE)__

It seems like the purpose is to take spans of whitespace and replace them with a single space; however it also catches tabs and newlines whether or not those options have been checked.
In addition, in some cases that we've tested, it only seems to catch the first few new lines, but not all of them.
__This could be a problem for anyone trying to Cut by line breaks.__

Because most of our tools aren't affected by spans of whitespace, we're considering just removing this line altogether--looking for a second opinion on this @scottkleinman. It seems to "solve" a nonexistent problem, at least from our standpoint.

As an example, try the consolidations file in test_suite/scrubber/consolidations using only the consolidation option and leaving everything else off--notice that the first three newlines are still replaced with spaces.

**Comment by mleblanc321** [comment]
gee, what were we doing here (or trying to do)?  i'm guessing:  if lots of empty lines at the end, we were "cleaning up" ?   @scottkleinman: do you recall?

**Comment by scottkleinman** [comment]
I'm not familiar with this line. I wonder if it was used for one of the specifc Remove Whitespace options. I would try testing those to see if there are any changes in behaviour if you remove the line.

**Comment by jacksonjreed** [comment]
Upon some further investigation we ended up just removing this line.
