### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by cgnobrega** [WheatonCS/Lexos#893]
### Overall 
- [x] sorry, but i (mdl) don't like the new icon;  it is kinda scary looking (in fact, it looks like a snake, not a dragon now); where is filled-in color icon?
- [x] Lexos (then space)  /Tool   we should be consistent, either space on both sides of slash(/) or not
- [x] "Help" should have a constant highlight color
- [x] Check boxes need check mark
- [x] Radio buttons need dot in center
- [x] Full footer (we want NEH logo; MIT License?)
- [x] Git hub test suite needs update to reflect directions for new UI
- [x] the buttons need more "pop" (hard to locate): standardize color/size/position
- [x] tool tips needs a better image, crisper
- [x] (perhaps only an issue on Firefox) numerical text fields can't be entirely selected
- [x] .lexos workspace files can be uploaded, but are unusable. attempting to load scrub gives a file not found error, other pages simply fail to properly load and show the error bar.
- [x] Tool names of each page should be in header bar
- [x] visualizations don't display single chars
- [x] walk-thru icon
- [x] manage files by clicking active docs (low priority)
- [x] Analyze tools- PNG and SVG downloads error "invalid resolution"

### Upload
- [x] hmm, i don't like that upload has lost the prime real estate;  sure, some (not many) like to enter URLs, but the space granted (one-half of opening screen) is *not* indicative of our users imho; the drag-files-here (marching ants) box should cover the entire screen, left to right;  (consider some other small area to upload URLs)
- [x] Upload list - document boxes are a bit big and bulky, looked better when narrow
- [x] Make marching-ants ---- border more pronounced
- [x] Save workspace.lexos works, downloads file; upload of .lexos works, 
- [x] When uploading multiple files, if one in the middle of the upload list is empty, the rest don't get uploaded
- [x] as of latest version "active documents" counter displays "NaN" upon uploading files, but changes to the correct number after loading another page
- [x] when uploading multiple documents (e.g. use the four apostrophes test suite files), only one appears in the uploads list (though they all appear on the manage page)

### Manage
- [x] I miss "click to toggle" the Select/Deselect feature;  that is, if on, click and it gets deselected; (is this problematic to keep?)
- [x] Text fields for “Edit Name” and “Edit Class” are very small and don’t save input if you were to edit again
- [x] inconsistent text in the "excerpt" section (sometimes a few words, sometimes 3 lines, sometimes only 1 line)
- [x] on right-click, the modals (e.g., to Edit names, Edit class, ...) are "off by four" (we are incorrectly indexing in the list of files names?)
- [x] in manage, when you right-click (e.g., to edit the class name) the menu need (some) border around the entire menu (so it doesn't blur into the text on the screen)
- [x] We should bring back the text that said to hold "d" when deselecting, or just let clicking a deactivated document activate it

### Scrubber 
- [x] On the original - special characters has predefined rule sets (http://lexos.wheatoncollege.edu/static/html/pre_defined_rules.html)
- [x] Cannot yet upload lists of Special Characters, Lemmas, Consolidation, or Keep/Stop Words
- [x] Scrub tags- “Replacement” text field should be disabled until “Replace” is selected
- [x] Upload buttons (lemmas, consolidations) might be more explicit?  e.g., "Upload Lemma List" (??)
- [x] make UI more explicit as to what you MUST do vs. OPTIONAL 
- [x] lemmas, consolidations, special chars take up too much real estate relative to their (potential) use
- [x] scrubber options should be bigger (ok to take up more real estate on page), with lemmas, consolidations, and special chars minimized in the middle column;  stop/keep words is important, so this should continue to get space;
- [x] no error produced for invalid input format (lemmas, consolidations, etc.)
- [x] scrub tags window needs work 
- [ ] download caching 

### Cutter
- [x] Cut is failing :(
- [x] I uploaded my webpage (cs.wheatoncollege.edu), and tried to CUT into 3 segments; FAILURE message at bottom?  (CUT also failed on regular text files) - cut by segments is broken
- [x] Error message with Overlap size 0 (this should not error)
- [x] The options in the second pane appear to reload every time the mode is changed, even if the options are the same.
- [x] Cut by milestone: empty tooltip
- [x] Cut by segment: "segment size" is a misleading label for # of segments option
- [x] Generally when cutter receives bad input it throws an error message specifying the problem; this is the case when overlap is greater than segment size, but when overlap is equal to segment size it instead throws a generic error and replaces the preview pane with "Loading Failed".
- [x] Should not fail the unit test :)

### Tokenizer
- [x]  GitHub > test_suite > tokenizer > tokens > bi-grams > loading indefinitely
- [x] Tokenizer > culling > Must be in [ ] documents > doesn’t give an error message if i enter a number greater than numActiveDocs, DTM just loads indefinitely
- [x] Documents as Rows, Terms as Columns isn't working (yes it is, see help section. the changes are only reflected in the downloaded data files due to the potential of hundreds of columns) -- ok, then we need the tool tip to be near the "doc as rows,terms as columns" choice; (see next item)
- [x] How about "doc as rows, terms as columns" (second option) does NOT appear in UI (since it will only apply on Download);  rather, only show "docs as columns, terms as rows" in the UI (and don't let them turn that off, keep radio button always on), *but* upon hitting download, give the user a choice (but only at this point);  
- [x] file names not displaying (they're #s) 

### Word Cloud
- [x] Font options
- [x] Number of Terms
- [x] Color options
- [x] Mouse-over word count
- [x] Download SVG and PNG (.png downloaded should have a white background; not gray? .svg is white, both on my Mac)
- [x] Do downloads work on both browsers (Firefox, Chrome) and both OSes (Windows, Mac)?

### Multi Cloud
- [x] As with Word Cloud, counts are not present yet
- [x] Exporting/Downloading ?

### BubbleViz
- [x]  Colors
- [x] Number of Terms
- [x] PNG Download
- [x] Mouse-over word count

### Rolling Window 
- [x] Ratio functionality
- [x] Rolling Windows downloads are all failing on Firefox
- [x] change positioning of "key" (list with all the terms under download buttons) interferes with plotly menu

### Statistics
- [x] Data table lacks sorting (see **Tokenize** for functional sorting table)
- [x] "Document Statistics" table download
- [x] table should sort on click (like Tokenizer) rather than clicking "Generate" to generate sorted table
- [x] failed to retrive doc stats when using larger files (e.g. dendrogram test  suite)
- [x] table won't sort by names
- [x] failing where anomalies are present (test_suite>catCaterpillar>cut by 10 tokens>stats>fail) and (test_suite>henryWP>but by 10 lines>stats>fail) index out of range console error

### Dendrogram
- [x] png svg broken [at least firefox]

### K-means clustering
- [x] Download document/cluster data?
- [x] png svg buttons not working [at least firefox]
- [x] if you select 2D or 3D scatter, an error will still get thrown on invalid # of clusters, even though these modes don't involve clustering
- [x] gridlines on 2D scatter

### Consensus Tree
- [x] Download?
- [x] Sample without replacement > loads indefinitely, no result obtained

### Similarity Query
- [X] Download data table

### Top words
- [x] Selecting to compare classes with no assigned classes did not produce an error message
- [x] Class divisions displaying improperly
- [x] failed to generate topwords (e.g. les mis & moby dick) same console error as when stats fails- index out of range

### Content Analysis
- [x] On the first results graph, the "score" column disappears when the help window is opened
- [x] The scaling of the individual boxes under "Documents" seems kind wonky; on these monitors with a full-screen window, each box has its own horizontal scroll bar, but dragging it to the right only reveals more empty space and the end of the word "Count"--all the data is already visible without any scrolling.
- [x] Overview and Corpus sections scrollbar issues
- [x] Overview table should sort
- [x] Calculator buttons should be darker or have an outline

### High priority
- [x] Add help pages to each page
- [x] Add tooltips to each page
    - [x] analyze page tooltips
- [x] Fix the unit test errors for test_kmeans_model.py and test_tokenizer_model.py
- [x] Make sure all user-input text is HTML-escaped before display
- [x] Add merge functionality to the manage page context menu
- [x] Add rolling ratio functionality to rolling window
- [x] Add color change options to the visualizations
- [x] Add save as PNG and SVG options to the visualizations
- [x] Add file upload buttons to the scrubber
- [x] Create the content analysis and scrubber pages

**Comment by jacksonjreed** [comment]
sorry I didn't realize checking the checkboxes actually changed anything publicly
I think I changed back anything I changed

**Comment by mlimoges** [comment]
Firefox has no vertical scrolling on some pages if you have a lot of documents: Manage, Sim Query, Stats, K-means, Consensus Tree, and Tokenize (can't see all the terms). I haven't encountered this issue on Chrome.

**Comment by cgnobrega** [comment]
On analyze pages, when you want a specific result (differing from the default) using lots of documents, you can't change the settings until the default loads (which can be a while) because the "Generate" button is deactivated.  Maybe we shouldn't render initial analyses since that's assuming what the user wants to do with their data.

**Comment by Myles-Trevino** [comment]
@mleblanc321 Please clarify the steps necessary to reproduce the Manage page issue of "Edit Name" and "Edit Class" being off by four.

**Comment by jacksonjreed** [comment]
Some minor Cutter issues:
- [ ] The options in the second pane appear to reload every time the mode is changed, even if the options are the same.
- [ ] Cut by milestone: empty tooltip
- [ ] Cut by segment: "segment size" is a misleading label for # of segments option

**Comment by jacksonjreed** [comment]
[ ] as of latest version "active documents" counter displays "NaN" upon uploading files, but changes to the correct number after loading another page

**Comment by mlimoges** [comment]
@Myles-Trevino i tested it this morning and there was no issue. the problem was that the title/class displayed in the popup would be the title/class of a document below it.

**Comment by maggieshafer** [comment]
- [ ] On the Manage page, the table should sort
