### ISSUE TITLE
Manage Page Sorting

### ISSUE THREAD

**Issue by maggieshafer** [WheatonCS/Lexos#960]
Currently, the manage page doesn't sort like on the old lexos. It's a bit tricky to implement though because it is not formatted like any of the other tables that are able to sort. Issues #507 and #470 include the need to sort the manage page.

**Comment by scottkleinman** [comment]
I have added a basic sort feature that doesn't require any changes to the way the Manage table is implemented. We may ultimately want to take a more consistent approach across the tools, but this should be sufficient for now.
