### ISSUE TITLE
Unit Test TLC

### ISSUE THREAD

**Issue by mlimoges** [WheatonCS/Lexos#995]
4 model unit tests are failing due to KeyError: 'id' (code snippets below)

https://github.com/WheatonCS/Lexos/blob/c4ca51f45433fb42bd57f0ebe225b9fae44b75d8/test/unit_test/test_bct_model.py#L33-L40

Line 37 is where the problems begin. 

https://github.com/WheatonCS/Lexos/blob/c4ca51f45433fb42bd57f0ebe225b9fae44b75d8/test/unit_test/test_kmeans_model.py#L45

https://github.com/WheatonCS/Lexos/blob/c4ca51f45433fb42bd57f0ebe225b9fae44b75d8/test/unit_test/test_stats_model.py#L25-L30

Line 26 causes the issue here. 

https://github.com/WheatonCS/Lexos/blob/c4ca51f45433fb42bd57f0ebe225b9fae44b75d8/test/unit_test/test_topword_model.py#L56-L57

The common issue is that further down the function calls, all these tests eventually try to access the session manager to see the uploaded files, which don't exist in the unit test context.

**Comment by chantisnake** [comment]
Access to session is impure, in the sense that session is a environmental variable provided by flask, our code have no way to create it.

Therefore don't store the uploaded file in session would solve this issue.
You get uploaded file from file manager, and then session are only used to keep user's option (radio button etc.)

**Comment by Myles-Trevino** [comment]
Unit tests are fixed in #1002.
